### ISSUE TITLE
Any way to pass conditions to bijectors in blockwise?

### ISSUE THREAD

**Issue by gitlabspy** [tensorflow/probability#1006]
```

class Bij(tfb.Bijector):
    def __init__(self,validate_args=False,name='bij'):
        super(Bij, self).__init__(...)
    def _forward(self, x, cond):
        return x + cond
     ....


blockwise = blockwise(
    bijectors=[tfb.Identity(), Bij()] 
)

flows = tfd.TransformedDistribution(
        distribution = tfd.Normal(0., 1.),
        bijector = blockwise,
        event_shape = (32,)
    )
cond = ...
argss = {'bijector_kwargs':{'cond':cond }}
print(flows.log_prob(tf.random.normal((3, 32)), **argss))
```
It throws `TypeError: _inverse() got an unexpected keyword argument 'cond'` error.
Should I write a kwargs getter in blockwise-like bijectors my self?? Or there's some decent way to achieve this ?

**Comment by SiegeLordEx** [comment]
It's not supported now, but it's easy enough to add (PR welcome, or we'll get to it one day too). We'd do it the same way this works in chain:

https://github.com/tensorflow/probability/blob/b8e03241fdbf23593b5bdecf4b23f8e9838373bf/tensorflow_probability/python/bijectors/chain.py#L242,L244

I.e. you'd give a name to your individual blockwise bijectors, and then pass kwargs to them like:

```python
argss = {'bijector_kwargs':{'bij': {'cond':cond }}}
print(flows.log_prob(tf.random.normal((3, 32)), **argss))
```

**Comment by gitlabspy** [comment]
@SiegeLordEx  Oh, There's one more thing. If I want to build a multi-layer architecture like glow, which is like a stack of blockwise. That makes the kwargs so long and a bit complicated to define... Any suggestions on this please? Thx!

**Comment by SiegeLordEx** [comment]
We're aware of this inelegance, but haven't seen a proposal about making it nicer. One approach I'd try as a user is perhaps iterate through the bijector graph and construct the corresponding nested dict, which can then be searched for a particular bijector.

**Comment by gitlabspy** [comment]
@SiegeLordEx Any built-in way to iterate a bijector graph? Graph it's a bit complicated due to the mixture of `chain` and `bloackwise`...

**Comment by SiegeLordEx** [comment]
No, but here's an example snippet (it does need blockwise to be fixed though to work with blockwise):

```python
def make_bijector_kwargs(bijector, name_to_kwargs):
  if hasattr(bijector, 'bijectors'):
    return {b.name: make_bijector_kwargs(b, name_to_kwargs) for b in bijector.bijectors}
  else:
    for name_regex, kwargs in name_to_kwargs.items():
      if re.match(name_regex, bijector.name):
        return kwargs
  return {}

def make_test_bijector(name):
  def forward_fn(x, arg=None):
    print(name, arg)
    return x
  
  return tfb.Inline(forward_fn=forward_fn, name=name, forward_min_event_ndims=0)

b1 = make_test_bijector('foo')
b2 = make_test_bijector('bar')
b3 = make_test_bijector('baz')

b = tfb.Chain([b2, tfb.Chain([b1, b3])])
kwargs = make_bijector_kwargs(b, {'foo': {'arg': 1}, 'bar': {'arg': 2}})
print(kwargs)

b.forward(0., **kwargs)
```

Also, let me reopen this so we don't forget to fix blockwise.
