### ISSUE TITLE
LinearGaussianStateSpaceModel doc error

### ISSUE THREAD

**Issue by wzy816** [tensorflow/probability#1027]
https://github.com/tensorflow/probability/blob/054a720ff9f221dd9660acd7ce7fb38a1dbb1290/tensorflow_probability/python/distributions/linear_gaussian_ssm.py#L980

Should we use the intermediate results, instead of x, as args for function `backward_smoothing_pass`?
Like
```
smoothed_means, smoothed_covs = model.backward_smoothing_pass(filtered_means, filtered_covs, predicted_means, predicted_covs)
```

**Comment by davmre** [comment]
Ah, you're absolutely right, thanks for catching this! Fix coming shortly.
