### ISSUE TITLE
SimpleStepSizeAdaption kernel not working when used within ReplicaExchangeMC kernel

### ISSUE THREAD

**Issue by simeoncarstens** [tensorflow/probability#1032]
It seems currently not possible to use the `SimpleStepSizeAdaption` kernel within a `ReplicaExchangeMC` kernel, because the former's `SimpleStepSizeAdaptionResults` is missing the `target_log_prob` field required by `ReplicaExchangeMC`. See a minimal-ish failing example in [this Colab notebook](https://colab.research.google.com/drive/1nRQqwbpYwZSUin0IIB5XcidyXMCH6A3U?usp=sharing).

Naively, it seems to me like it's an easy thing to fix by just adding the field to the results named tuple and propagating the `target_log_prob` from the inner kernel when returning the results `namedtuple` at the end of `one_step()` and in `bootstrap_results()`. If that's indeed the case, I'd be happy to fix this myself!

**Comment by axch** [comment]
Thanks for the report!  We've actually developed a style for this where we write helper functions that search for the required thing in each given `FooKernelResults`'s `inner_results` field.  You can see how `SimpleStepSizeAdaptation` itself looks for the `step_size` field in the potentially-nested `FooKernelResults` of its own inner kernel.  If that approach makes sense to you, we would certainly appreciate a PR.

**Comment by simeoncarstens** [comment]
Thanks for your answer & encouragement! Your approach with the helper functions sounds good; I'm already at it.
