### ISSUE TITLE
Undefined name 'tfe' in eight_schools_hmc.py

### ISSUE THREAD

**Issue by cclauss** [tensorflow/probability#104]
Undefined names can raise NameError at runtime.

flake8 testing of https://github.com/tensorflow/probability on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensorflow_probability/python/mcmc/eight_schools_hmc.py:88:18: F821 undefined name 'tfe'
  sample_chain = tfe.defun(tfp.mcmc.sample_chain)
                 ^
./tensorflow_probability/python/mcmc/eight_schools_hmc.py:134:29: F821 undefined name 'tfe'
    self._mode = 'eager' if tfe.executing_eagerly() else 'graph'
                            ^
2       F821 undefined name 'tfe'
2
```

**Comment by csuter** [comment]
Thanks for catching this! It's caused by an error in our automated transformations when we export code from our internal VCS to Github. I'm implementing the fix now.
