### ISSUE TITLE
BijectorCache.reset method throws an exception

### ISSUE THREAD

**Issue by leroidauphin** [tensorflow/probability#1058]
The `BijectorCache` class `reset` method throws the following exception:
`line 483, in reset`
`    type(self.forward), type(self.inverse))`
`TypeError: __init__() takes from 3 to 4 positional arguments but 5 were given`

This seems to be because the implementation of the `reset` method assumes that the `cache_type` function for the forward and inverse caches can be different, but the constructor uses the same function for both caches.

**Comment by emilyfertig** [comment]
As mentioned in the linked PR -- `BijectorCache.reset` has since been replaced with `BijectorCache.clear`, which doesn't have this bug.
