### ISSUE TITLE
Conditional RealNVP bijector

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#106]
It would be great if [RealNVP bijector](https://github.com/tensorflow/probability/blob/67a55b2ef5e94da203991ed102c9e41d085a840a/tensorflow_probability/python/bijectors/real_nvp.py) supported conditioning. The `shift_and_log_scale_fn` can be any non-invertible mapping, so the [ConditionalBijector's](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/distributions/python/ops/bijectors/conditional_bijector.py#L28) `condition_kwargs` could be fed directly to it and concatenated with the inputs at the beginning of the function.

I'm gonna go ahead and submit a PR for this. Happy to take any feedback on it.

**Comment by SiegeLordEx** [comment]
Should be fixed as the relevant PR is merged. Thanks for your contribution!
