### ISSUE TITLE
This version of TensorFlow Probability requires TensorFlow version >= 2.3

### ISSUE THREAD

**Issue by amaa11** [tensorflow/probability#1060]
Dear all,

I tried to run a model using TensorFlow Probability.
But when I run it I got the error below
**ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.3; Detected an installation of version 2.0.0-beta1. Please upgrade TensorFlow to proceed.**
I cannot install TensorFlow 2.3 because it says there is no match.
I have installed these libraries
**tensorflow (2.0.0b1)
tensorflow-estimator (1.14.0)
tensorflow-tensorboard (1.5.1)
tfp-nightly (0.12.0.dev20200817)**

Any suggestion how to fix it?

Thanks in advance

**Comment by csuter** [comment]
I think you just need to use `tf-nightly` pip package instead of `tensorflow`

**Comment by amaa11** [comment]
Thanks custer.
You mean I uninstall tensorflow and install tf-nightly?
Can I use it to build my model using keras?

**Comment by csuter** [comment]
Yes everything should "just work". Nightly is just released more frequently than the stable package. You can also always use the most recent pip package `tensorflow-probability` with the most recent stable `tensorflow` package.

**Comment by amaa11** [comment]
Thanks again csuter.
I uninstalled tensorflow.
I tried to install tf-nightly(**pip3 install tf-nightly**).
but it says 
**No matching distribution found for tf-nightly**
I use Python 3.6.9

**Comment by csuter** [comment]
Hm, that's odd. There are pip packages for 3.5 through 3.8, inclusive: https://pypi.org/project/tf-nightly/2.4.0.dev20200817/#files

**Comment by amaa11** [comment]
Thanks so much for your help csuter. I will try it

**Comment by csuter** [comment]
Oh, one thing you might try is upgrading pip itself (`pip install -U pip`). I recall some folks running into issues with older pips.

**Comment by csuter** [comment]
great, glad to hear it!
