### ISSUE TITLE
declare tensorflow as dependency

### ISSUE THREAD

**Issue by bsipocz** [tensorflow/probability#1073]
I wonder whether it would be possible to state the tensorflow dependency, including the minimum version in the packaging files here? Today I run into a situation that I could successfully install `tensorflow-probability` for a workshop, but then participants were unable to use it as the upstream versions were not recent enough. 
Ideally I should not be able to install the package from conda-forge when the dependencies are missing from there.

Ideally all these should be taken care of at the time of installation and then the checks in ``__init__.py`` would be just an additional safety layer.

**Comment by brianwa84** [comment]
There are a couple issues at play:
- tensorflow, tensorflow-cpu, tf-nightly, and tf-nightly-cpu are all valid
packages for installing tensorflow, depending on the TFP version; and we
want to allow users choice when installing as the CPU variants are much
smaller/faster to install. I often write `pip install tfp-nightly
tf-nightly-cpu`.
- We also support jax (`from tensorflow_probability.substrates import jax
as tfp`), in which case no TF install is required whatsoever.

For jax we added an extra `tfp-nightly[jax]`. Maybe we could do the same
for all relevant versions of tf, i.e. `tfp-nightly[tf]` => `tf-nightly`,
`tfp-nightly[tf-cpu]` => `tf-nightly-cpu`, `tensorflow-probability[tf]` =>
`tensorflow`, etc?

**Comment by bsipocz** [comment]
Oh, OK, no easy solution then.
