### ISSUE TITLE
Can you provide a differentiable quantile function for the gamma distribution?

### ISSUE THREAD

**Issue by kjmiller944** [tensorflow/probability#1075]
This is a new feature request for a differentiable quantile function for the gamma distribution. The current version of tfp does not support a quantile function for a number its distributions.

**Comment by srvasude** [comment]
Hi,
  I've recently added `tfp.math.igammainv` and `tfp.math.igammacinv` and should shortly be adding quantile functions to a number of Gamma based distributions.

**Comment by srvasude** [comment]
This is done here: https://github.com/tensorflow/probability/commit/c70101e220f3705d51b7d54326f3af9b3ad46bfc
