### ISSUE TITLE
Dropping a dimension in JointDistributionSequential distribution object and breaking matmul as a consequence

### ISSUE THREAD

**Issue by MichaelRGrant** [tensorflow/probability#1097]
I came across a strange issue with matrix multiplication within `JointDistributionSequential`. I created an example of this here:
```
def test_model(tensors):
    return tfd.JointDistributionSequential(
        [
            tfd.Sample(  # coefs
                tfd.Normal(loc=0.0, scale=1.0),
                sample_shape=tensors.features_tf.shape[0],
            ),
            tfd.HalfCauchy(loc=0.0, scale=1.0),  # sigma_response
            lambda sigma_response, coefs: tfd.Independent(
                tfd.Normal(  # mu_global
                    loc=coefs @ tensors.features_tf,
                    scale=sigma_response[..., tf.newaxis],
                ),
                reinterpreted_batch_ndims=1,
            ),
        ],
    )
```
`tensors` is a `NamedTuple` with tensors, and `tensors.features_df` is a matrix of shape `(8, N)` where `N` is the number of rows in my data. This code is just compressing a multivariate linear function where the sampled parameters (coefs) is multiplied by the covariates contained within the the `features_df` tensor. This is done with the matrix multiplication, `@`, in the above function. 

This produces the following error:
```
ValueError: Shape must be rank 2 but is rank 1 for '{{node mcmc_sample_chain/dual_averaging_step_size_adaptation___init__/_bootstrap_results/transformed_kernel_bootstrap_results/NoUTurnSampler/.bootstrap_results/process_args/maybe_call_fn_and_grads/value_and_gradients/matmul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](mcmc_sample_chain/dual_averaging_step_size_adaptation___init__/_bootstrap_results/transformed_kernel_bootstrap_results/NoUTurnSampler/.bootstrap_results/process_args/maybe_call_fn_and_grads/value_and_gradients/mcmc_sample_chain_dual_averaging_step_size_adaptation___init____bootstrap_results_transformed_kernel_bootstrap_results_NoUTurnSampler_bootstrap_results_process_args_maybe_call_fn_and_grads_value_and_gradients_Samplemcmc_sample_chain_dual_averaging_step_size_adaptation___init____bootstrap_results_transformed_kernel_bootstrap_results_NoUTurnSampler_bootstrap_results_process_args_maybe_call_fn_and_grads_value_and_gradients_Normal/sample/Reshape, mcmc_sample_chain/dual_averaging_step_size_adaptation___init__/_bootstrap_results/transformed_kernel_bootstrap_results/NoUTurnSampler/.bootstrap_results/process_args/maybe_call_fn_and_grads/value_and_gradients/matmul/b)' with input shapes: [8], [8,1995].
```
which is strange because the following code returns the shapes of all the distributions and the `coefs` shape is `(4, 8)`, not `(8)`. 
```
>>> [s.shape for s in test_model(tensors).sample(4)]

[TensorShape([4, 8]), TensorShape([4]), TensorShape([4, 1995])]
```

I also figured that the error is occuring in the `log_prob` part of the sampling run because if I just try and build a log_prob from the initial states as follows:
```
inits = test_model(tensors).sample(4)
test_model(tensors).log_prob(inits)
---
InvalidArgumentError: In[0] is not a matrix. Instead it has shape [8] [Op:MatMul]
```

I can't figure out why the log_prob is dropping the rank from 2 -> 1, but I was able to fix this problem by downgrading to `tensorflow-probability==0.8.0`. However I don't want to use this version because the `experimental_compile=True` parameter in the `tf.function` decorator was not implemented yet, and this parameter speeds up my run time ~10x. 

I'm hoping there is an easy solution since this worked in a previous installment and there must be something simple I am missing.

**Comment by ColCarroll** [comment]
It looks like however you are sampling, you are not running multiple chains (batches), so `coefs` ends up with shape `[8]` in an MCMC loop. You should be able to reproduce this by calling `test_model(tensors).sample()`, which I think will fail.

I think the most straightforward solution is to rewrite the matmul as an einsum: 
```python
loc=tf.einsum('...j,...jk->...k', coefs, features),
```

Let me know if that works out!

**Comment by MichaelRGrant** [comment]
Yes that works perfectly, thank you so much!
