### ISSUE TITLE
Negative Entropy for Truncated Normal Distribution

### ISSUE THREAD

**Issue by SomeshDaga** [tensorflow/probability#1100]
Hi

I seem to get negative entropy values for certain `loc` and `scale` values. As an example:

```
>>> m = tfp.distributions.TruncatedNormal(loc=0.693481624, scale=0.272697151, low=-1., high=1.)
>>> m.entropy()
<tf.Tensor: shape=(), dtype=float32, numpy=-0.15739295>
```
Unless I am misunderstanding the definition of the entropy or the parameters of the Truncated Normal distribution, I believe that the entropy should always be positive.

Curiously, I also get a negative entropy value from scipy's `truncnorm`, but it is a different value.

```
>>> from scipy.stats import truncnorm
>>> m = truncnorm(-1,1,loc=0.693481624,scale=0.272697151)
>>> m.entropy()
array(-0.6166075)
```

**Platforms**

- Ubuntu 18.04
- Tensorflow v2.3.1
- Tensorflow-Probability v0.11.1
- Scipy v1.5.2
- Scikit-learn v0.23.2

**Comment by SomeshDaga** [comment]
Comparing with a 3rd source, it does seem that the value produced by tensorflow-probability is consistent (not sure why scipy reports a different value). Also, it seems like I had a misunderstanding between differential entropy and the version of entropy with discrete rv's. So seems like all's good here.

**Comment by brianwa84** [comment]
AIUI Scipy, for entropy, will often fall back to a numerical estimation
algorithm.
The calculations in TFP, where they exist, are generally either analytic,
or have fairly well-tested bespoke numerical algorithms for the situations
where we deploy them.
