### ISSUE TITLE
Feature Request: Inverse auto-regressive flow

### ISSUE THREAD

**Issue by lxuechen** [tensorflow/probability#112]
Not sure if this is already done, but I skimmed over the bijectors directory and wasn't able to find IAF in there. 

If we don't have that already in tfp, would it make sense to make one specific class in bijectors just for it?

**Comment by dustinvtran** [comment]
```python
  iaf = tfd.TransformedDistribution(
      distribution=tfd.Normal(loc=0., scale=1.),
      bijector=tfb.Invert(tfb.MaskedAutoregressiveFlow(
          shift_and_log_scale_fn=tfb.masked_autoregressive_default_template(
              hidden_layers=[512, 512]))),
      event_shape=[dims])
```

We welcome any examples as well as extensions as you try it out.
