### ISSUE TITLE
sampling over tensorflow hub module

### ISSUE THREAD

**Issue by VMBoehm** [tensorflow/probability#1121]
Hi,
is it possible (and if so how?) to use a pretrained model, loaded as a hub module, in the the target_log_prob_fn of the mcmc sampler?
I'm running into issues that seem to suggest that it is creating several graphs:

> RuntimeError: Module must be applied in the graph it was instantiated for.

Simplified code:

> logp             = hub.Module(logp_path, trainable=False)
> 
> def log_prob:
>     return logp(x)
> 
> states = tfp.mcmc.sample_chain(
>  num_results=1000,
>  num_burnin_steps=500,
>  current_state=tf.zeros((params['batch_size'],params['latent_size']),tf.float32),
>  kernel=tfp.mcmc.HamiltonianMonteCarlo(
>  target_log_prob_fn=log_prob,
>  step_size=0.5,
>  num_leapfrog_steps=2),
>  trace_fn=None)

**Comment by brianwa84** [comment]
What if you decorate logp with @tf.function?

**Comment by brianwa84** [comment]
Decorate log_prob, that is.

**Comment by VMBoehm** [comment]
Thanks for the prompt reply! Unfortunately still get the same with:

```
model       = hub.Module(model_path, trainable=False)

@tf.function
def log_prob(z_):
    return tf.gather(model({'z':z_},as_dict=True)['x'],0)

states = tfp.mcmc.sample_chain(
    num_results=1000,
    num_burnin_steps=500,
    current_state=tf.zeros((params['batch_size'],params['latent_size']),tf.float32),
    kernel=tfp.mcmc.HamiltonianMonteCarlo(
      target_log_prob_fn=log_prob,
      step_size=0.5,
      num_leapfrog_steps=2),
    trace_fn=None)
```

I should maybe mention that I need to disable eager execution, otherwise it throws:

> RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.
on the line
`model       = hub.Module(model_path, trainable=False)`
 
Some version issue?

**Comment by brianwa84** [comment]
I'm not particularly familiar w/ TF Hub, so I'm just speculating here.
What if you put the mode = hub.Module(..) inside the tf.function?

**Comment by VMBoehm** [comment]
ha, yes, now it builds the graph, but with a suspicious warning:

> WARNING:absl:Using `hub.Module` while building a function: log_prob. This can lead to errors if the function is not pruned.
> WARNING:tensorflow:AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7fbfdd656d70>> and will run it as-is.
> Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
> Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
> To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

and then the initialization fails:

> ValueError: Fetch argument <tf.Operation 'init_1' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "init_1"
> op: "NoOp"
> input: "^AssignVariableOp_1"
> input: "^AssignVariableOp"
> input: "^AssignVariableOp_3"
> input: "^AssignVariableOp_2"
> input: "^AssignVariableOp_5"
> input: "^AssignVariableOp_4"
> input: "^AssignVariableOp_7"
> input: "^AssignVariableOp_6"
> input: "^AssignVariableOp_9"
> input: "^AssignVariableOp_8"
>  is not an element of this graph.)

**Comment by brianwa84** [comment]
@tensorflow/tfhub-maintainers any tips on this?

**Comment by akhorlin** [comment]
hub.Module is deprecated. It doesn't work well inside functions with @tf.function annotation. Instead of hub.Module, you can try using hub.load() (https://www.tensorflow.org/hub/api_docs/python/hub/load).

**Comment by VMBoehm** [comment]
thanks!
