### ISSUE TITLE
Broken link from documentation to source / v0.11.1 PyPI package without GitHub release

### ISSUE THREAD

**Issue by st--** [tensorflow/probability#1122]
For example, https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/Softplus has a "View source on GitHub" link that points to https://github.com/tensorflow/probability/blob/v0.11.1/tensorflow_probability/python/bijectors/softplus.py#L61-L173 which does not exist. This may be due to the fact that there isn't actually a tagged v0.11.1 release on GitHub (even though there is a 0.11.1 release on PyPI)?

**Comment by emilyfertig** [comment]
Thanks! I just added a v0.11.1 release on Github, and the links appear to be fixed.
