### ISSUE TITLE
No KL divergence functions for StudentT and MultivariateStudentTLinearOperator

### ISSUE THREAD

**Issue by Kevin-Chen0** [tensorflow/probability#1168]
Hi TFP,

Hi see that you have implemented the kl functions for Normal and MultivariateNormalLinearOperator:

```
@kullback_leibler.RegisterKL(Normal, Normal)
def _kl_normal_normal(a, b, name=None):
  ...
```
```
@kullback_leibler.RegisterKL(MultivariateNormalLinearOperator,
                             MultivariateNormalLinearOperator)
def _kl_brute_force(a, b, name=None):
  ...
```
Is it possible to do the same for StudentT and MultivariateStudentTLinearOperator in student_t.py and multivariate_student_t.py respectively?

Thanks,
~Kevin

**Comment by srvasude** [comment]
Hi,
  I'm going to close this issue since I believe https://github.com/tensorflow/probability/issues/1185 has an appropriate answer.
