### ISSUE TITLE
`JointDistributionCoroutineAutoBatched` sample doesn't work with values/kwargs

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#1170]
`tfd.JointDistributionCoroutine` seems to work very nicely if you specify values for some of the distributions:

``` python
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions

Root = tfd.JointDistributionCoroutine.Root


@tfd.JointDistributionCoroutine
def joint_dist():
    yield Root(tfd.Normal(loc=1.0, scale=1.0, name="a"))
    yield tfd.Normal(loc=2.0, scale=2.0, name="b")


joint_dist.sample(a=1.0)
# StructTuple(
#   a=<tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
#   b=<tf.Tensor: shape=(), dtype=float32, numpy=0.7329037>
# )
```

However if I try the same with the `AutoBatched` version I get:

``` python
@tfd.JointDistributionCoroutineAutoBatched
def auto_joint_dist():
    yield tfd.Normal(loc=1.0, scale=2.0, name="a")
    yield tfd.Normal(loc=2.0, scale=2.0, name="b")


auto_joint_dist.sample(a=1.0)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/jeff/workspace/talon/tests/core/test_fitting.py", line 213, in <module>
#     auto_joint_dist.sample(a=1.0)
#   File "/home/jeff/.virtualenvs/talon/lib/python3.6/site-packages/tensorflow_probability/python/distributions/distribution.py", line 1009, in sample
#     return self._call_sample_n(sample_shape, seed, name, **kwargs)
#   File "/home/jeff/.virtualenvs/talon/lib/python3.6/site-packages/tensorflow_probability/python/distributions/joint_distribution.py", line 548, in _call_sample_n
#     **kwargs)
# TypeError: _sample_n() got an unexpected keyword argument 'a'
```

As far as I can see the doc for both of these functions is the same so I am wondering if this is a bug?

``` python
>>> tf.__version__
'2.4.0-rc1'
>>> tfp.__version__
'0.12.0-rc1'
```

Thanks!

**Comment by davmre** [comment]
Yup, this is a bug. The autobatching mixin redefines `_sample_n`, so when keyword argument support was added to the main class, it didn't automatically percolate down to the autobatched variants.

I'm working on some changes that will dramatically simplify the autobatching class and remove most of its overrides, which should eventually fix this. These depend on some deeper technical changes in TF and TFP, so it's hard to give an exact timeline, but it will likely happen before the end of the year.

As a workaround, it should still work to pass a `value` arg to an autobatched JD:

```
auto_joint_dist.sample(value=(1.0, None))
```

**Comment by jeffpollock9** [comment]
Thanks for the reply, @davmre. Looking forward to seeing the changes.

**Comment by ColCarroll** [comment]
Hey @jeffpollock9 -- this got fixed in https://github.com/tensorflow/probability/commit/9aa5d76ae9845d32c5efd521f3b7bac23d43eadf . Thanks for calling it out!
