### ISSUE TITLE
Issue with cached sampling results

### ISSUE THREAD

**Issue by MaxGrtz** [tensorflow/probability#1171]
Hey,

First, thank you very much for this amazing library !

I am currently working on a study project and tried to build a thin wrapper around tfp for bayesian inference. 

It seems to be the case, that somehow sampling results are cached, even though the underlying distribution changes.

I really have no good explanation of the issue itself, so I created a simple example to illustrate it. 

In this colab everything is explained as best as I can: 

https://colab.research.google.com/drive/1MPALIeso4AKk5-JhAxRms9-vCXRyb9Tq?usp=sharing

I hope I did not make any stupid mistake myself to cause this, but I am stuck with this issue for some days now and can't figure it out. 

Thanks a lot!

**Comment by MaxGrtz** [comment]
Sorry, this is so awkward...

After two days, I just now realized this is caused by my misuse of @tf.function.

Sorry.

**Comment by brianwa84** [comment]
No problem! Glad you got it working!
