### ISSUE TITLE
Unsupported numpy type: NPY_INT

### ISSUE THREAD

**Issue by fkgruber** [tensorflow/probability#1175]
I was following the tutorial in 
https://blogs.rstudio.com/ai/posts/2019-05-06-tadpoles-on-tensorflow/
but I'm getting the error:

```
+ Error in py_call_impl(callable, dots$args, dots$keywords) :
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_INT).
```

right after calling:
```
+ res = hmc %>% mcmc_sample_chain(
+ num_results=n_steps,
+ num_burnin_steps=n_burnin,
+ current_state=initial_logits,
+ trace_fn=trace_fn
+ )
```
any idea what is causing it?`

**Comment by ColCarroll** [comment]
This sounds like it might be an outdated library, or something particular about the environment where you're running things: can you share the OS you're running this on, and the output of `sessionInfo()`?

**Comment by fkgruber** [comment]
I realized now that I posted this in the wrong github. I was using the tfprobability R package which is an interface to tensorflow probability. I will post in the appropriate github
