### ISSUE TITLE
Should we wrap trainable distributions by default in tfp.edward2?

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#118]
For the same reasons we wrap tfp.distributions for convenience.

**Comment by dustinvtran** [comment]
Issue was raised as suggested by @davmre.

From team discussions, we plan to redesign trainable distributions as tf.keras.Layer classes, as part of `tfp.layers`. This means we don't want to decorate trainable distributions (specifically, decorate their `call` with `@ed.interceptable`) unless we decorate all `tfp.layers`. I'm open to that if there's a grounding example or application.

**Comment by srvasude** [comment]
Closing this, as Edward2's repository is now located here: https://github.com/google/edward2
