### ISSUE TITLE
LinearGaussianStateSpaceModel silently fails to calculate prob(x) when stddev is small

### ISSUE THREAD

**Issue by jongmmm** [tensorflow/probability#1184]
The below code is copied from the code example of [LinearGaussianStateSpaceModel](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/LinearGaussianStateSpaceModel), but I changed three parameters (`ndims`, `step_std` and `noise_std`):

```python
import tensorflow as tf  # 2.5.0-dev20201120 / no GPU
import tensorflow_probability as tfp  # 0.12.0-dev20201120
tfd = tfp.distributions
tf.keras.backend.set_floatx('float64')  # does it help? 

ndims = 2  # changed this from 100 to 2
step_std = 0.1  # changed from 1.0 to 0.1
noise_std = 0.1  # changed from 1.0 to 0.1
model = tfd.LinearGaussianStateSpaceModel(
  num_timesteps=100,
  transition_matrix=tf.linalg.LinearOperatorIdentity(ndims),
  transition_noise=tfd.MultivariateNormalDiag(
   scale_diag=step_std**2 * tf.ones([ndims])),
  observation_matrix=tf.linalg.LinearOperatorIdentity(ndims),
  observation_noise=tfd.MultivariateNormalDiag(
   scale_diag=noise_std**2 * tf.ones([ndims])),
  initial_state_prior=tfd.MultivariateNormalDiag(
   scale_diag=tf.ones([ndims])))
```
Then I generate samples and calculate its likelihood:
```
xx = model.sample()
model.prob(xx)
```
, which returns:
```
<tf.Tensor: shape=(), dtype=float32, numpy=inf>
```
Also `model.log_prob(xx)` returns a positive number.

**Comment by davmre** [comment]
In most of TFP, `prob(x)` is just implemented as `tf.exp(log_prob(x))`. Assuming the `log_prob` is finite, you're probably just running into overflow.

You could try doing the exponentiation yourself at higher precision: `tf.exp(tf.cast(model.log_prob(xx), dtype=tf.float64))`. 

(I see you tried setting the Keras float type, but that unfortunately affects Keras only. TFP in general is dtype-agnostic---calculations are performed at the precision of whatever Tensors you pass in---so to do a fully `float64` calculation you'd probably need to construct the model with `float64` parameters. But that's not necessary if the overflow is just from the final exponentiation.)

**Comment by jongmmm** [comment]
Thanks for the clarification @davmre.
