### ISSUE TITLE
Why is there KL Divergence function for each distribution?

### ISSUE THREAD

**Issue by Kevin-Chen0** [tensorflow/probability#1185]
This might be a basic question, but why is there a separate implementation of KL divergence for each distribution? For example:

```
@kullback_leibler.RegisterKL(Normal, Normal)
def _kl_normal_normal(a, b, name=None):
  """Calculate the batched KL divergence KL(a || b) with a and b Normal.
  Args:
    a: instance of a Normal distribution object.
    b: instance of a Normal distribution object.
    name: Name to use for created operations.
      Default value: `None` (i.e., `'kl_normal_normal'`).
  Returns:
    kl_div: Batchwise KL(a || b)
  """
  with tf.name_scope(name or 'kl_normal_normal'):
    b_scale = tf.convert_to_tensor(b.scale)  # We'll read it thrice.
    diff_log_scale = tf.math.log(a.scale) - tf.math.log(b_scale)
    return (
        0.5 * tf.math.squared_difference(a.loc / b_scale, b.loc / b_scale) +
        0.5 * tf.math.expm1(2. * diff_log_scale) -
        diff_log_scale)
```

and

```
@kullback_leibler.RegisterKL(Gamma, Gamma)
def _kl_gamma_gamma(g0, g1, name=None):
  """Calculate the batched KL divergence KL(g0 || g1) with g0 and g1 Gamma.
  Args:
    g0: Instance of a `Gamma` distribution object.
    g1: Instance of a `Gamma` distribution object.
    name: Python `str` name to use for created operations.
      Default value: `None` (i.e., `'kl_gamma_gamma'`).
  Returns:
    kl_gamma_gamma: `Tensor`. The batchwise KL(g0 || g1).
  """
  with tf.name_scope(name or 'kl_gamma_gamma'):
    # Result from:
    #   http://www.fil.ion.ucl.ac.uk/~wpenny/publications/densities.ps
    # For derivation see:
    #   http://stats.stackexchange.com/questions/11646/kullback-leibler-divergence-between-two-gamma-distributions   pylint: disable=line-too-long
    g0_concentration = tf.convert_to_tensor(g0.concentration)
    g0_rate = tf.convert_to_tensor(g0.rate)
    g1_concentration = tf.convert_to_tensor(g1.concentration)
    g1_rate = tf.convert_to_tensor(g1.rate)
    return (((g0_concentration - g1_concentration) *
             tf.math.digamma(g0_concentration)) +
            tf.math.lgamma(g1_concentration) -
            tf.math.lgamma(g0_concentration) +
            g1_concentration * tf.math.log(g0_rate) -
            g1_concentration * tf.math.log(g1_rate) + g0_concentration *
            (g1_rate / g0_rate - 1.))
```

Should KL divergence be a general function that accepts any type of P and Q distributions, even when using tensors? For [example](https://towardsdatascience.com/kl-divergence-python-example-b87069e4b810) in Numpy:

```
def kl_divergence(p, q):
    return np.sum(np.where(p != 0, p * np.log(p / q), 0))
```

Thanks,
K

**Comment by csuter** [comment]
`KL(p, q)` for continuous p and q is actually an integral over the (common) support of p and q, of the integrand `p(x) log (p(x) / q(x))`. What you wrote would work for distributions of finite support, where p and q were vectors of probabilities associated with the elements of the support. For continuous distributions, there would be an (uncountably!) infinite number of these to sum up (and you'd need a differential "dx" scaling each term!).

You can get a monte carlo approximation of a KL between continuous distributions by sampling a bunch of points x_i from p and averaging `log (p(x_i) / q(x_i)`, but to get an exact value you need to do the integral. For many distribution pairs, this integral can be done analytically and computed numerically, which is what these registrations are representing. See the section on "relative entropy" [here](https://en.wikipedia.org/wiki/Relative_entropy#Properties) for more on the definitions.

**Comment by csuter** [comment]
in code, a monte carlo KL for continuous p, q might look like

```
def kl(p, q):   # p and q are distributions, not tensors!
  xs = p.sample(10000)
  return tf.reduce_mean(p.log_prob(xs) - q.log_prob(xs))   # note: log p(x) - log q(x) = log (p(x) / q(x))
```

**Comment by Kevin-Chen0** [comment]
So for `_kl_normal_normal` as an example, is that for continuous Normal distributions? If so, I do not see where in the code the integral is being used. Is continuity taken care of the `distribution.Distribution` class, where it inherently does the say Monte Carlo sampling? Or maybe you have broken it down somewhere in the `diff_log_scale`, `tf.math.squared_difference` and `tf.math.expm1` parts.

**Comment by csuter** [comment]
In tfp we generally don't implement approximate methods like Monte Carlo
KL. The methods you see don't include any integral because it's already
been computed analytically. You should read the Wikipedia article on kl
divergence and try computing some examples by hand for practice! Then the
formulas implemented in code should make more sense 😊

**Comment by Kevin-Chen0** [comment]
Yea, I have been looking at the Wiki back-and-forth with your code. I have run the kl_divergence functions a few times. However, I'm working on a research project that requires diving deep into the `distributions` code and understands what's happening underneath the hood of tfp.

Two weeks ago, I have made a separate [issue](https://github.com/tensorflow/probability/issues/1168) about StudentT and MultivariateStudentTLinearOperator not containing their own KL Divergence functions, with no response so far. Since the research project involves those functions as intermediary steps, I am wondering whether I can contribute to tfp by writing the StudentT and MultivariateStudentTLinearOperator KL Divergence functions. If you also think that this is meaningful and worth pursuing, I can submit a [PR](https://github.com/tensorflow/probability/blob/master/CONTRIBUTING.md) for this after dev and testing it.

**Comment by Kevin-Chen0** [comment]
Going back to the original question, I still don't quite understand why do you implement KL Divergence for each distribution. Should there be a general KL divergence that can work regardless of what the inputted Distributions are, i.e., whether normal or StudentT? For example, what happens if you input two StudentTs inside of `_kl_normal_normal` function. Would it not work because of how it is constructed using the `tf` and `tf.math` lib? If that is indeed the case, then why is the KL for StudentTs missing? Are StudentTs not commonly used?

**Comment by davmre** [comment]
The general contract of TFP Distributions is that they only implement properties that can be computed exactly, not by stochastic approximation. There is no general formula for KL divergences; exact solutions have to be worked out on a distribution-by-distribution basis.

For example, for the case of two StudentT distributions, we'd need an exact solution to the integral `\int p(x) log p(x)/q(x) dx` where `p` and `q` are StudentT densities. I'm not sure that this integral *can* be solved exactly; a quick Google search for the KL divergence of StudentT distributions doesn't turn up any leads.

The `_kl_normal_normal` method implements an exact solution to the [specific integral](https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians) that defines KL divergence for two Normal distributions. If you plug in any other type of distribution, you'll get wrong answers. You can check this by comparing against csuter@'s [general-purpose approximation](https://github.com/tensorflow/probability/issues/1185#issuecomment-736887732) above, which will work for any pair of distributions (but would require infinite `num_samples` to produce an exact answer).

**Comment by Kevin-Chen0** [comment]
Thanks for the clarity @davmre. Can I ask what is the reasoning for only implementing exact solutions and not approximates? Is it because of the risk of producing errors due to the non-determinism?

**Comment by davmre** [comment]
Sorry, this slipped past me! Of course the restriction to exact solutions is a design choice, and one could build a library that makes a different set of choices, but I think there are a few motivations for doing things the way the Distributions library does them:

- There needs to be a line somewhere, and 'exact solutions' is a relatively simple line to draw. It's an API contract that we can test and document, and it provides predictable behavior for users to reason about.
- Any given quantity has only one true value, but many possible approximations, and deciding what sort of approximation is appropriate for a given task is beyond the scope of a low-level distributions library.
- Exact solutions are (more or less) compositional: if we have an exact `prob`, for example, we can take its log to get the exact `log_prob` (up to floating-point precision). This is often not true for approximations. For example, the log of an unbiased estimate of `prob` is not an unbiased estimate of the `log_prob`.

Essentially, the Distributions library is meant to be used as a low-level foundation for other systems, and generally you'd rather have squishy stuff on top of a solid foundation than vice versa. For what it's worth, the higher-level parts of TFP (MCMC, VI, optimizers, etc) are all about approximate computation. I think we'd be happy to accept a utility function in `tfp.stats` to compute Monte Carlo KL estimates.

**Comment by davmre** [comment]
(closing this for now, feel free to reopen if there are additional issues).
