### ISSUE TITLE
Built-in interceptor for replacing values in program trace

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#119]
This is used so often it's possibly worth supporting a built-in one. See, e.g., [probabilistic PCA tutorial](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_PCA.ipynb).

A slightly abstract one might be

```python
def make_value_settings(trace):
  alignment = {"z1": "qz1", "z2": "qz2", "z3": "qz3",
               "W0": "qW0", "W1": "qW1", "W2": "qW2"}
  def set_values(f, *args, **kwargs):
    """Sets random variable values to the trace's aligned value."""
    name = kwargs.get("name")
    if name in alignment:
      kwargs["value"] = trace.get(alignment[name])
    return ed.interceptable(f)(*args, **kwargs)
  return set_values
```
(can make alignment be a function and/or part of the `make_value_settings`' arguments.

**Comment by brianwa84** [comment]
@davmre didn't you and Maria put this in?

**Comment by davmre** [comment]
Yup: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/edward2/program_transformations.py#L34
