### ISSUE TITLE
Asking shape of layer

### ISSUE THREAD

**Issue by cserpell** [tensorflow/probability#1200]
I am building models based on tensorflow probability layers, and in the newest version, they suddenly stopped providing layers shape. Usually, for any keras layer, you can ask their input and output shape, but at least for `MultivariateNormalTriL` and `KLDivergenceAddLoss`, it fails. I provided a minimum example in [this colab](https://colab.research.google.com/drive/1G7j2w98Pv5Bn06l8Cmv8cbNu_C3uaBv5?usp=sharing).

I copy the code here:

```python
x_data = np.array([[0.0], [1.0], [2.0], [3.0], [4.0]])
y_data = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0], [5.0, 6.0]])

print(x_data.shape)
print(y_data.shape)

input_layer = layers.Input(shape=x_data.shape[1:])
dense_layer = layers.Dense(tfp_layers.MultivariateNormalTriL.params_size(2))(
    input_layer)
# Define variational layer: prior a standard normal distribution, and
# the encoded is a normal distribution with parameters mean and variance
prior = distributions.Independent(distributions.Normal(tf.zeros(2), 1.0),
                                  reinterpreted_batch_ndims=1)
distr_layer = tfp_layers.MultivariateNormalTriL(2)(dense_layer)
div_layer = tfp_layers.KLDivergenceAddLoss(prior, weight=0.5)(distr_layer)
output_layer = layers.Dense(2)(div_layer)

model = models.Model(inputs=[input_layer], outputs=[output_layer])
model.compile(loss='MSE', optimizer='Adam')
print(model.summary())

print(input_layer.shape)
print(dense_layer.shape)

# Any of these fail
print(distr_layer.shape)
print(distr_layer.input_shape)
print(distr_layer.output_shape)
```

The error is `AttributeError: 'UserRegisteredTypeKerasTensor' object has no attribute 'input_shape'`.

**Comment by ColCarroll** [comment]
Thanks for reporting! An easy workaround is to use `tf.shape(distr_layer.shape)`, Let me know if that works.

**Comment by cserpell** [comment]
Thank you for replying so fast! No, it gives the same error:

```python
print(tf.shape(distr_layer.shape))
```

raises `AttributeError: 'UserRegisteredSpec' object has no attribute '_shape'`, while

```python
print(tf.shape(distr_layer.input_shape))
```

raises `AttributeError: 'UserRegisteredTypeKerasTensor' object has no attribute 'input_shape'`, same as when trying `output_shape`.

**Comment by cserpell** [comment]
I am sorry, actually using `tf.shape(distr_layer)`, it works, I replied too soon without noticing I had to remove the `.shape` part.

**Comment by ColCarroll** [comment]
Closing, but feel free to add to this thread/make a new one if something else comes up!

**Comment by cserpell** [comment]
Anyway, the call returns a `<KerasTensor: shape=(2,) dtype=int32 inferred_value=[None, 2] (created by layer 'tf.compat.v1.shape_2')>` object. I have no idea how to get the actual value "2", as this KerasTensor object has no numpy, value or eval methods. I am currently looking into it.

**Comment by cserpell** [comment]
Even trying to print the actual layer fails, because the `__repr__` method of the `KerasTensor` fails. It seems that moving to tensorflow 2.4.0 broke some things in tensorflow probability.

**Comment by ahoereth** [comment]
What is the solution here for getting a numpy array or python list of the actual shape? I am running into the same problem as @cserpell, so it does not appear resolved to me @ColCarroll? Previously the probability layers acted the same as core tensorflow layers.

**Comment by shifdz** [comment]
I am facing the same issue. How to get the actual shape of layers? @cserpell and @ahoereth, did you find a solution?

**Comment by ahoereth** [comment]
> I am facing the same issue. How to get the actual shape of layers? @cserpell and @ahoereth, did you find a solution?

I have an old commit referencing this issue here, but not sure if it actually solved the problem back then. You can give the following a try:

```python
tf.keras.backend.get_value(tf.shape(layer.output)
```

**Comment by shifdz** [comment]
> > I am facing the same issue. How to get the actual shape of layers? @cserpell and @ahoereth, did you find a solution?
> 
> I have an old commit referencing this issue here, but not sure if it actually solved the problem back then. You can give the following a try:
> 
> ```python
> tf.keras.backend.get_value(tf.shape(layer.output)
> ```

That didn't work. It gives an error:
`AttributeError: 'KerasTensor' object has no attribute 'numpy'`

**Comment by Diogenes4Sinope** [comment]
Can anyone let me know why the following code:

leads to the following error:

    model_mean_sd_1 = Model(inputs=inputs, outputs=dist)

AttributeError: 'UserRegisteredTypeKerasTensor' object has no attribute 'mean'

**Comment by anirban-mukherjee** [comment]
> Even trying to print the actual layer fails, because the `__repr__` method of the `KerasTensor` fails. It seems that moving to tensorflow 2.4.0 broke some things in tensorflow probability.

I think this issue is related. https://github.com/tensorflow/probability/issues/1500. I think the issue stems from the use of a temporary fix in the form of a user registered class while waiting for legacy code to migrate. https://github.com/tensorflow/tensorflow/blob/30b95925a42d0dcf6a387c51b1128012d8ae092c/tensorflow/python/keras/engine/keras_tensor.py#L475
