### ISSUE TITLE
Matrix Normal

### ISSUE THREAD

**Issue by gpantalos** [tensorflow/probability#1213]
Hi, I'm trying to implement a [matrix normal](https://en.wikipedia.org/wiki/Matrix_normal_distribution) by subclassing `tfd.Distribution`. I have found the single-sample implementation at [`scipy.stats.matrix_normal`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.matrix_normal.html) but can't figure out how to batch it.

Here is my code so far:
```python
import tensorflow as tf
import tensorflow_probability as tfp
from scipy.stats import matrix_normal

tfd = tfp.distributions


class MatrixNormal(tfd.Distribution):
    def __init__(self, mean, rowcov, colcov):
        super().__init__(dtype=None, reparameterization_type=tfd.FULLY_REPARAMETERIZED,
                         validate_args=False, allow_nan_stats=False, name='MatrixNormal')
        self.m = mean
        self.u = rowcov
        self.v = colcov

        self.distribution = matrix_normal(mean, rowcov, colcov)

    def _batch_shape(self):
        return self.m.shape[:-2]

    def _batch_shape_tensor(self):
        return self.batch_shape

    def _event_shape(self):
        return self.m.shape[-2:]

    def _event_shape_tensor(self):
        return self.event_shape

    def _sample_n(self, n, seed=None, **kwargs):
        return tf.convert_to_tensor(self.distribution.rvs(n))

    def _log_prob(self, x):
        return tf.convert_to_tensor(self.distribution.logpdf(x))

    def _log_survival_function(self, value, **kwargs):
        pass

    def _survival_function(self, value, **kwargs):
        pass

    def _entropy(self, **kwargs):
        pass

    def _mean(self, **kwargs):
        pass

    def _quantile(self, value, **kwargs):
        pass

    def _variance(self, **kwargs):
        pass

    def _stddev(self, **kwargs):
        pass

    def _covariance(self, **kwargs):
        pass

    def _mode(self, **kwargs):
        pass

    def _default_event_space_bijector(self):
        pass

    @staticmethod
    def _param_shapes(sample_shape):
        pass

    @classmethod
    def _params_event_ndims(cls):
        pass
```

Do you guys have any ideas on how to make it work for an arbitrary number of samples, that is, return samples of the same shape as the mean.

**Comment by brianwa84** [comment]
You could try using np.vectorize with self.distribution.rvs. If you wanted
to contribute this to TFP of course, it'd need to be using TF ops instead
of scipy. Also note that you won't get autodiff to parameters if you sample
using scipy, so s/FULLY_REPARAMETERIZED/NOT_REPARAMETERIZED/

**Comment by davmre** [comment]
I think you could get a proper TF implementation with not *too* much work by using [the fact](https://en.wikipedia.org/wiki/Matrix_normal_distribution#Definition) that flattened samples from a matrix normal are just samples from a MVN whose covariance matrix is the Kronecker product of the row and column covariances. So all we have to do is define that MVN, and then reshape its samples into a matrix.

```python
class MatrixNormal(tfd.TransformedDistribution):

  def __init__(self, loc, row_covariance, column_covariance):
    self._loc = loc
    # Flatten matrix 'loc' to a vector.
    flat_loc = tf.reshape(loc, tf.concat([tf.shape(loc)[:-2], [-1]], axis=0))

    self._covariance = tf.linalg.LinearOperatorKronecker(operators=[
        tf.linalg.LinearOperatorFullMatrix(
            row_covariance, is_self_adjoint=True, is_positive_definite=True),
        tf.linalg.LinearOperatorFullMatrix(
            column_covariance, is_self_adjoint=True, is_positive_definite=True)])
    super(MatrixNormal, self).__init__(
      distribution=tfd.MultivariateNormalLinearOperator(
        loc=flat_loc,
        scale=self._covariance.cholesky()),
      bijector=tfb.Reshape(event_shape_out=tf.shape(loc))
```

**Comment by gpantalos** [comment]
Works great thanks !

**Comment by brianwa84** [comment]
Would it make sense for us to put Dave's suggestion into `tfp.distributions`?

**Comment by srvasude** [comment]
I have an internal PR for this that I'll send out shortly.

Note that MatrixNormal / MatrixStudentT actually need some transposes in a few places. This is because if you want to use the `vec(.)` (which concatenates the columns) operation to compute Kronecker products matmuls, you will actually need a transpose.
