### ISSUE TITLE
NUTS Sampling: TypeError: Expected int32, got 0.0 of type 'float' instead

### ISSUE THREAD

**Issue by fonnesbeck** [tensorflow/probability#1218]
I am trying to use the NUTS sampling example from the **Modeling with JointDistribution** example notebook to sample from my own model. Recall that the key function that contains the sampler logic is as follows:

```python
@tf.function(autograph=False, experimental_compile=True)
def run_chain(init_state, step_size, target_log_prob_fn, unconstraining_bijectors,
              num_steps=500, burnin=50):

    def trace_fn(_, pkr):
        return (
            pkr.inner_results.inner_results.target_log_prob,
            pkr.inner_results.inner_results.leapfrogs_taken,
            pkr.inner_results.inner_results.has_divergence,
            pkr.inner_results.inner_results.energy,
            pkr.inner_results.inner_results.log_accept_ratio
            )

    kernel = tfp.mcmc.TransformedTransitionKernel(
        inner_kernel=tfp.mcmc.NoUTurnSampler(
        target_log_prob_fn,
        step_size=step_size),
        bijector=unconstraining_bijectors)

    hmc = tfp.mcmc.DualAveragingStepSizeAdaptation(
        inner_kernel=kernel,
        num_adaptation_steps=burnin,
        step_size_setter_fn=lambda pkr, new_step_size: pkr._replace(
            inner_results=pkr.inner_results._replace(step_size=new_step_size)),
        step_size_getter_fn=lambda pkr: pkr.inner_results.step_size,
        log_accept_prob_getter_fn=lambda pkr: pkr.inner_results.log_accept_ratio
    )

    # Sampling from the chain.
    chain_state, sampler_stat = tfp.mcmc.sample_chain(
        num_results=num_steps,
        num_burnin_steps=burnin,
        current_state=init_state,
        kernel=hmc,
        trace_fn=trace_fn)
    return chain_state, sampler_stat
```

In the case of my model, which is slightly larger than the one in the example, it is called with:

```python
chain, stat = run_chain(joint.sample(), 
                        step_size=0.1, 
                        target_log_prob_fn=target_log_prob_fn, 
                        unconstraining_bijectors=[tfb.Identity(), 
                            tfb.Exp(), tfb.Identity(), 
                            tfb.Exp(), tfb.Identity(), 
                            tfb.Exp(), tfb.Identity(),
                            tfb.Identity(), tfb.Identity(), 
                            tfb.Identity(), tfb.Identity()],
                        num_steps=1000, burnin=1000)
```

However, I run this and get a TypeError:

```
TypeError: in user code:

    <ipython-input-183-d29fde5c95cc>:30 run_chain  *
        chain_state, sampler_stat = tfp.mcmc.sample_chain(
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/sample.py:332 sample_chain  **
        previous_kernel_results = kernel.bootstrap_results(current_state)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/dual_averaging_step_size_adaptation.py:528 bootstrap_results
        inner_results = self.inner_kernel.bootstrap_results(init_state)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/transformed_kernel.py:496 bootstrap_results
        transformed_init_state))
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/nuts.py:476 bootstrap_results
        init_state)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/internal/leapfrog_integrator.py:386 process_args
        target_fn, state_parts)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/internal/util.py:267 maybe_call_fn_and_grads
        result, grads = _value_and_gradients(fn, fn_arg_list, result, grads)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/internal/util.py:227 _value_and_gradients
        result = fn(*fn_arg_list)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/transformed_kernel.py:130 transformed_log_prob_fn
        return tlp + ldj_fn(state_parts, event_ndims)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/transformed_kernel.py:64 fn
        for b, e, sp in zip(bijector, event_ndims, state_parts)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/transformed_kernel.py:64 <listcomp>
        for b, e, sp in zip(bijector, event_ndims, state_parts)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:1261 forward_log_det_jacobian
        return self._call_forward_log_det_jacobian(x, event_ndims, name, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:1216 _call_forward_log_det_jacobian
        ildj = attrs['ildj'] = -self._forward_log_det_jacobian(x, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/identity.py:87 _forward_log_det_jacobian
        return tf.constant(0., dtype=x.dtype)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:265 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:283 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:457 make_tensor_proto
        _AssertCompatible(values, dtype)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:337 _AssertCompatible
        (dtype.name, repr(mismatch), type(mismatch).__name__))

    TypeError: Expected int32, got 0.0 of type 'float' instead.
```

All the model parameters are Normal and HalfNormal, and all of the inputs are either integers or float32. Its not clear what is expecting int32 but getting a float. Looks like something to do with the Jacobian, but I have no idea beyond that based on this output. Has anyone seen this before?

**Comment by davmre** [comment]
It looks like the Identity bijector assumes that its log Jacobian determinant (0.0) should be converted to the same `dtype` as the values being passed through the bijector:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/bijectors/identity.py#L86
Trying to transform an integer-valued variable would raise an exception when it can't construct an integer tensor whose value is `0.0`.

It might help if you can you give some context for this code and what you're trying to accomplish. In general you wouldn't expect integer-valued random variables to work with NUTS or HMC, since they don't have gradients. You could work around this particular issue by casting your int-valued variables to floats, but if they're fundamentally categorical then the downstream inference code may or may not do something reasonable. Generally we recommend integrating out discrete variables when possible---is it feasible to frame your model in terms of continuous quantities?

**Comment by fonnesbeck** [comment]
This is a hierarchical mixed effects model, but the variables in question are only discrete in the sense that they are indicators for a random effect, such as:

```python
        b_scale = yield tfd.HalfNormal(scale=1.0, name="b_scale")
        b_prior = yield tfd.Normal(
            loc=tf.zeros(n_batters), scale=b_scale, name="b_prior"
        )
        b_effects = tf.gather(b_prior, batter_id, axis=-1)
```

or they are {0,1} indicator variables that are multiplied by a continuous beta. Neither seem to be variables you'd want to integrate out.

**Comment by ColCarroll** [comment]
Can you cast the coefficient indicators to `tf.float32`? If they aren't parameters, they will not add anything to the gradient.

You might also check `model.sample()` for parameters that are `int`s, which could help narrow down the problem.

**Comment by fonnesbeck** [comment]
Yeah, just tried that -- changing the inputs for my two indicator variables to float32 did not fix the problem. 

Looking at the types in sample, all are `tf.float32` except the last one, which is the likelihood, which is Bernoulli, so that will always be int, correct?

**Comment by ColCarroll** [comment]
That should be ok -- is `model.log_prob(model.sample())` doing ok? 

Looks like the original error is getting thrown the first time `tfp.math.value_and_gradient` is being called on `target_log_prob_fn`, so I am assuming 
```python
tfp.math.value_and_gradient(target_log_prob_fn(joint.sample()))
```
throws a similar exception (might be worth checking).

As an aside, thanks also for mentioning the colab you were following -- it could use some updating with new functions! I am also assuming `joint = model.experimental_pin(something=a_float_tensor)`, so you're already using some of them, but you can replace one of the kernels with this:

```python
    hmc = tfp.mcmc.DualAveragingStepSizeAdaptation(
        inner_kernel=kernel,
        num_adaptation_steps=burnin,
    )
```

**Comment by fonnesbeck** [comment]
The log prob of a prior sample runs without error.

The value_and_gradient check fails, but perhaps due to how my function is written:

```
def target_log_prob_fn(*args):
    return joint.log_prob(*args[:-1], likelihood=y)
```

which gives

```

ValueError: Joint distribution expected values for 11 components ['intercept', 'pitcher_scale', 'pitcher_prior', 'batter_scale', 'batter_prior', 'umpire_scale', 'umpire_prior', 'beta_pstrike', 'beta_2strike', 'beta_fullcount', 'likelihood']; saw 1 (from args () and kwargs {'likelihood': array([0., 1., 1., ..., 1., 0., 1.], dtype=float32), 'name': 'log_prob'}).
```

I have not been using pinning here, but I can certainly try it.

**Comment by davmre** [comment]
If you can reproduce the issues you're seeing in a Colab notebook, that would help us dig in further to figure out what concretely might be going wrong.

Generally the usual pattern is to start with a JD over latents and observations:

```python
@tfd.JointDistributionCoroutine
def model():
  x1 = yield LatentDist1(name='x1')
  x2 = yield LatentDist2(x1, name='x2')
  y = yield LikelihoodDist(x1, x2, name='y')
```

and then define a target_log_prob_fn that computes the unnormalized posterior density as a function of the latents:

```python
def target_log_prob_fn(x1, x2):
  return model.log_prob(x1, x2, observed_y)

# Equivalent
def target_log_prob_fn(*args):
  return model.log_prob(*args, y=observed_y)

# Equivalent
unnormalized_posterior = JointDistributionPinned(model, y=observed_y)
target_log_prob_fn = unnormalized_posterior.log_prob
```

The initial state passed to `sample_chain` should match the latents. Equivalently, it should be a valid list of arguments to `target_log_prob_fn`:

```python
latents = model.sample()[:-1]
latents = unnormalized_posterior.sample() # Equivalent if `unnormalized_posterior` is a JDPinned as above.

initial_state = [tf.random.normal(x.shape, dtype=x.dtype) for x in latents]

target_log_prob_fn(*initial_state)  # Should work.
```

In particular, if the only discrete variables in your model are in the likelihood, then those variables will/should never be part of the MCMC chain state, and your `target_log_prob_fn` shouldn't expect them as args (instead it should close over them, i.e., refer to their known, observed values).

**Comment by fonnesbeck** [comment]
I do have this as a Colab, however the data are proprietary so I will have to simulate some. The above looks pretty consistent with what I'm doing, and FWIW it all runs fine with HMC; its NUTS alone that breaks.

**Comment by fonnesbeck** [comment]
@davmre and @ColCarroll helped me solve this offline. I'm now using pinned values to specify the likelihood, rather than passing data to a joint log probability closure:

    target = joint.experimental_pin(likelihood=y)

the call to `run_chain` should then look like this:

```python
chain, stat = run_chain([x for x in target.sample_unpinned()], 
                        step_size=0.01, 
                        target_log_prob_fn=target.unnormalized_log_prob,
                        unconstraining_bijectors=[tfb.Identity(), 
                            tfb.Exp(), tfb.Identity(), 
                            tfb.Exp(), tfb.Identity(), 
                            tfb.Exp(), tfb.Identity(),
                            tfb.Identity(), tfb.Identity(), 
                            tfb.Identity()],
                        num_steps=1000, burnin=1000)
```

An upcoming PR will obviate the need for the list comprehension.
