### ISSUE TITLE
WishartLinearOperator not usable on JAX substrate because it requires tf.linalg.LinearOperator

### ISSUE THREAD

**Issue by dieterichlawson** [tensorflow/probability#1251]
The implementation of the Wishart distribution in `WishartLinearOperator` requires a scale supplied as a subclass of `tf.linalg.LinearOperator`. I'm using the JAX substrate and would rather not import Tensorflow and have to use its classes. Is it possible to use `WishartLinearOperator` without this class? Or is there a jax substrate equivalent?

**Comment by brianwa84** [comment]
You can write tf=tfp.tf2jax, then tf.linalg.LinearOperator* to access those
classes.

**Comment by dieterichlawson** [comment]
Gotcha, thanks Brian!
