### ISSUE TITLE
On the predictive distribution of a structural time-series model

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/probability#1252]
Hello,

This is not really an issue but a question. I am trying to understand the structure and, in particular, normality properties of the predictive distribution obtained by `tfp.sts.forecast`:

https://github.com/tensorflow/probability/blob/v0.12.1/tensorflow_probability/python/sts/forecast.py#L173-L375

My reasoning is as follows. The posterior distribution of model parameters is non-Gaussian in general. The inference via HMC yields posterior draws from this distribution, and variational inference yields posterior draws from a surrogate, which is a collection of independent Gaussians. For each draw regardless of the inference method used, the Kalman filter gives a multivariate Gaussian. The final posterior is a mixture of the multivariate Gaussians corresponding to the posterior draws of the model parameters. This implies that the predictive posterior is non-Gaussian; it is a mixture of Gaussians.

Does the above hold? If not, what is the correct explanation?

Thank you!

**Comment by krzysztofrusek** [comment]
Hi, I came to the same conclusions independently so we must be right.

**Comment by IvanUkhov** [comment]
@davmre, sorry for dragging you into the conversation like this. You might be the only one who is able to answer.

**Comment by davmre** [comment]
What you've said sounds correct to me. The predictive distribution over multiple timesteps is created explicitly in the code as a mixture of LinearGaussianStateSpaceModel distributions (each of which is multivariate Gaussian): 
https://github.com/tensorflow/probability/blob/v0.12.1/tensorflow_probability/python/sts/forecast.py#L372
so the marginal distribution at any given step is a mixture of Gaussians.

**Comment by IvanUkhov** [comment]
Thank you for the answer!
