### ISSUE TITLE
Port No-U-Turn Sampler into tfp.mcmc

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#126]
The current implementation is soon to be available in this repo's `experimental/`. It would be nice to abstract the code as part of the tfp.mcmc library.

The core implementation is already done. This involves, for example:

1. abstracting state information as, e.g., named tuples;
2. abstract the kernel function as a subclass of `TransitionKernel` (possibly inheriting from the HMC kernels);
3. unit tests with numerical checks.

**Comment by axch** [comment]
But, see also #8, and in particular https://github.com/tensorflow/probability/issues/8#issuecomment-387255619.  The batched implementation alluded to there (still WIP) may not necessarily share much code with the single-chain implementation coming to `experimental/` (or may yes share, TBD).

**Comment by axch** [comment]
For reference, pulled the batched implementation alluded to in https://github.com/tensorflow/probability/issues/8#issuecomment-387255619 to its own issue, #142.

**Comment by junpenglao** [comment]
Close by https://github.com/tensorflow/probability/commit/e57eba6c0ff15b2c94e0d802115641683206c38a
