### ISSUE TITLE
Errors in Bijector power

### ISSUE THREAD

**Issue by kasakh** [tensorflow/probability#1263]
I am exploring the bijector api `Power`. I have the following example in mind. Say, X ~ N(0,1) i.e. X is sampled from a standard normal distribution. What are the distributional properties of X^3. 

This is the minimum reproducible example. 

```
################################
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
tfd = tfp.distributions
tfb = tfp.bijectors

n = tfd.Normal(loc=0., scale=1.)
n_transformed = tfd.TransformedDistribution(n,bijector = tfb.Power(3))

print(n_transformed.quantile(0.10)) ## output -2.1047876 
print(n_transformed.quantile(0.90)) ## 2.1047876

print(n_transformed.cdf(-2.1047876)) ## Gives NaN as the output
print(n_transformed.cdf(2.104786)) ## 0.89999

print(n_transformed.prob(-2)) ## gives NaN
print(n_transformed.prob(2)) ## 0.037879337

#################################
```

Ideally, if the quantiles are correctly computed, we expect the corresponding the inverse i.e. cdfs also be computed correctly; however, it seems that specifically for negative numbers it gives NaN as the output. Similarly, for the density of computation, for positive inputs, the density is correctly computed; however, for negative inputs, it gives NaN as the output. 

Exploring further, I think it is due to the `tf.math.pow` function, which is used internally. Specifically, 
it is due to the fact that `tf.math.pow` gives NaN for all negative numbers raised to fractional numbers - e.g.  `tf.math.pow(-8.0, 1.0/ 3.0)` gives NaN.

I am not sure where to report this issue. Kindly let me know if there is a way to circumvent this issue to make my reproducible example work. 
Thanks in advance.

**Comment by srvasude** [comment]
Currently the `Power` bijector is only supported for positive arguments (and hence why this issue comes up), but we can easily extend it to negative inputs for power an odd integer.

**Comment by srvasude** [comment]
Fixed in https://github.com/tensorflow/probability/commit/4a9876f9046c0d81463cab3b80d23b080d18fe0e
