### ISSUE TITLE
Powerspherical distribution sampling giving nan values

### ISSUE THREAD

**Issue by Darkhunter9** [tensorflow/probability#1287]
When sampling using powerspherical distribution and the mean direction is [1,0,0], the sampling does not perform normally, giving nan values.
``` Python
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

m = tf.Variable([1., 0., 0.,])
m = tf.math.l2_normalize(m1, axis=-1)

a = tfd.PowerSpherical(mean_direction=m, concentration=10000)
b = a.sample((2,))
print(b)
print(tf.reduce_sum(b**2, axis=-1))
```
![image](https://user-images.githubusercontent.com/40048121/112926179-10dea480-90e1-11eb-9b02-9e6c6a09871c.png)

**Comment by ursk** [comment]
Thank you for bringing this to our attention. A fix will go out with out next nightly relese.
