### ISSUE TITLE
The documentation of tfp.TransformedDistribution is not readable

### ISSUE THREAD

**Issue by ramakrse** [tensorflow/probability#1288]
The documentation of tfp.TransformedDistribution is not readable in between. Please see the attachment
![Capture](https://user-images.githubusercontent.com/19791881/113089368-25b45880-9205-11eb-87a3-1810efc6bd20.PNG)

**Comment by ColCarroll** [comment]
It'll take a little time to percolate up to the docs site, but should be good -- thanks again for catching!
