### ISSUE TITLE
Overflow error in sample_chain() with jax backend

### ISSUE THREAD

**Issue by henrysky** [tensorflow/probability#1292]
I am experiencing an ``OverflowError: Python int too large to convert to C long`` in ``tfp.mcmc.sample_chain()`` with jax backend

Upon initial investigation, I realize in ``samplers.py`` under ``tensorflow_probability/python/internal/samplers.py`` (even true in master branch), the following line 

```python
salt = int(hashlib.sha512(str(salt).encode('utf-8')).hexdigest(), 16)
seed = fold_in(seed, salt)
```
which is basically this when I run ``sample_chain()`` so we can run it separately to demonstrate the issue

```python
import hashlib
import jax

key = jax.random.PRNGKey(0)

salt = int(hashlib.sha512(str("mcmc.sample_chain").encode('utf-8')).hexdigest(), 16)
seed = jax.random.fold_in(key, salt)
```

``salt`` is a very large integer that is causing the issue I am experiencing

**Comment by brianwa84** [comment]
Doesn't reproduce for me. I wrote:
from tensorflow_probability.substrates import jax as tfp
import jax
tfp.random.sanitize_seed(jax.random.PRNGKey(0), salt='mcmc.sample_chain')

Note that the "fold_in" called in your first block is immediately below in
samplers.py, and for JAX this will truncate the lower 32 bits:
if JAX_MODE
<https://source.corp.google.com/piper///depot/google3/third_party/py/tensorflow_probability/python/internal/samplers.py;l=50?q=samplers.py&ct=os&sq=-file:%5E%2F%2Fdepot%2Fgoogle3%2Fexperimental%20package:%5Epiper$%20file:%5E%2F%2Fdepot%2Fgoogle3%2F>:

from jax
<https://source.corp.google.com/search?q=file%3A%28%2F%7C%5E%29jax%28%5C.%28clif%7Cswig%7Cpy%7Cspt%29%24%7C%2F%28__init__%5C.%28clif%7Cswig%7Cpy%7Cspt%29%29%3F%24%29>
import random
<https://source.corp.google.com/search?q=file%3A%28%2F%7C%5E%29jax%2Frandom%28%5C.%28clif%7Cswig%7Cpy%7Cspt%29%24%7C%2F%28__init__%5C.%28clif%7Cswig%7Cpy%7Cspt%29%29%3F%24%29>
as jaxrand # pylint: disable=g-import-not-at-top
import jax.numpy
<https://source.corp.google.com/search?q=file%3A%28%2F%7C%5E%29jax%2Fnumpy%28%5C.%28clif%7Cswig%7Cpy%7Cspt%29%24%7C%2F%28__init__%5C.%28clif%7Cswig%7Cpy%7Cspt%29%29%3F%24%29>
as jnp # pylint: disable=g-import-not-at-top
return jaxrand.fold_in(seed
<https://source.corp.google.com/piper///depot/google3/third_party/py/tensorflow_probability/python/internal/samplers.py;bpv=1;bpt=1;l=148?q=samplers.py&ct=os&sq=-file:%5E%2F%2Fdepot%2Fgoogle3%2Fexperimental%20package:%5Epiper$%20file:%5E%2F%2Fdepot%2Fgoogle3%2F&gsn=seed&gs=kythe%3A%2F%2Fgoogle3%3Flang%3Dpython%3Fpath%3Dthird_party%2Fpy%2Ftensorflow_probability%2Fpython%2Finternal%2Fsamplers.py%23module.fold_in.seed>,

jnp.asarray(salt
<https://source.corp.google.com/piper///depot/google3/third_party/py/tensorflow_probability/python/internal/samplers.py;l=143?q=samplers.py&ct=os&sq=-file:%5E%2F%2Fdepot%2Fgoogle3%2Fexperimental%20package:%5Epiper$%20file:%5E%2F%2Fdepot%2Fgoogle3%2F>
& (2**32 - 1), dtype=SEED_DTYPE
<https://source.corp.google.com/piper///depot/google3/third_party/py/tensorflow_probability/python/internal/samplers.py;l=52?q=samplers.py&ct=os&sq=-file:%5E%2F%2Fdepot%2Fgoogle3%2Fexperimental%20package:%5Epiper$%20file:%5E%2F%2Fdepot%2Fgoogle3%2F>))


You would need to change your second block to:
salt = int(hashlib.sha512(str("mcmc.sample_chain").encode('utf-8')).hexdigest(),
16)
seed = jax.random.fold_in(key, salt & (2**32-1))

Brian Patton | Software Engineer | ***@***.***

**Comment by henrysky** [comment]
closing this issue as I (the issue author) cannot reproduce this issue anymore
