### ISSUE TITLE
Variational embedding layers

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#130]
References
+ Gaussian embeddings from Vilnis and McCallum (2015) (https://arxiv.org/abs/1412.6623)

**Comment by dustinvtran** [comment]
Am no longer developing tfp.layers. Will work on this idea elsewhere.

**Comment by pricel3ss** [comment]
Hey @dustinvtran , big fan of tensorflow_probabilities! 

Quick question : is there a plan to add embedding layers to tf_probabilities layers? If not, is there a reason why?

Thank you sir!

**Comment by dustinvtran** [comment]
Thanks for asking. I don't develop in TFP anymore due to various politics. We do have plans for Gaussian embedding layers in https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/bayes.py, building on Vilnus and McCallum (2015). (TFP is welcome to build on our implementation if they find it useful.)

**Comment by pricel3ss** [comment]
@dustinvtran thank you so much for the response. Again, big fans of your work here at CH Robinson (the company I work for). Especially the Flipout stuff.

We are attempting to integrate the denseflipout layers AND native embedding layers from normal tensorflow. Do you have any advice on how you would do that? Is that possible?
