### ISSUE TITLE
no attribute 'find_root_secant'

### ISSUE THREAD

**Issue by giandons** [tensorflow/probability#1313]
Importing tfp:
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'find_root_secant'

tensorflow.probability Version: 0.12.2
tensorflow Version: 2.4.0
tfp-nightly Version: 0.13.0.dev20210421

I am new with tfp,
Thank you in advance

**Comment by axch** [comment]
Generally we do not advise mixing stable and unstable versions of either
TFP or TensorFlow.  If you create an environment with only the stable
versions, or with only the nightly versions of both packages it should work.

**Comment by giandons** [comment]
I uninstalled both tfp and tfp-nightly, after installing again tfp 0.12.2, I get the same Attribute error.

Ps: I ended installing nightly because I got this before:
tensorflow 2.4.1 requires gast==0.3.3, but you have gast 0.4.0 which is incompatible.
tensorflow 2.4.1 requires grpcio~=1.32.0, but you have grpcio 1.37.0 which is incompatible.
tensorflow 2.4.1 requires h5py~=2.10.0, but you have h5py 3.1.0 which is incompatible.

**Comment by ColCarroll** [comment]
Sorry about the delay -- a few more troubleshooting steps:
- Chan you share the stack trace you get when importing `tensorflow_probability`?
- I'd make sure you are using the same Python to install as you are to run -- it is frustratingly easy to use a different `pip`: if you are using a python or ipython terminal, use `python -m pip freeze | grep tensorflow` to get the versions installed. If you are using jupyter, you can use 
```
import sys
!{sys.executable} -m pip freeze | grep tensorflow
```
which I _think_ should give you the kernel python.

**Comment by davmre** [comment]
It'd also help to see the output of `print(tf.__version__, tfp.__version__)`.

**Comment by giandons** [comment]
The problem was caused by the use of pip and conda to install some packages. With all packages installed on conda I succeed in importing tfp. 
Ps: this issue was making useless any try with virtual environments too.
Ty

**Comment by ColCarroll** [comment]
Thanks for following up, and glad you got it working!
