### ISSUE TITLE
Categorical distribution giving  Nan output for log_prob 

### ISSUE THREAD

**Issue by Pranav-India** [tensorflow/probability#1317]
Hi I am using tensoflow probability version 0.12.1 below is the code 

`prob = self.actor(obs)`
`dist = tfp.distributions.Categorical(probs = prob)`
`action = dist.sample()`
`log_prob = dist.log_prob(action)`

when I print my action and it's type following is the output I received.
`tf.Tensor([8], shape=(1,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>`

and for this or any other action I get log_prob as nan
`tf.Tensor([nan], shape=(1,), dtype=float32)`

am I doing something wrong?

**Comment by axch** [comment]
What's the value of `prob`?  If your probabilities are invalid, you may get
nans.  You can also ask `Categorical` (or any other TFP Distribution) to
check validity by passing `validate_args=True` to the constructor.  This is
off by default because the checks have a performance cost.

**Comment by Pranav-India** [comment]
Hi @axch  thanks for your response I just found that due to data bias neural network was getting converged to one side and a single probability was becoming '1.0' making all others as 0 which was causing this 'nan' output.
