### ISSUE TITLE
Cannot install from pip using git reference on case insensitive file systems

### ISSUE THREAD

**Issue by NeilGirdhar** [tensorflow/probability#1326]
```
pip install git+https://github.com/tensorflow/probability.git
Collecting git+https://github.com/tensorflow/probability.git
  Cloning https://github.com/tensorflow/probability.git to /private/var/folders/0r/cv_3zr0x2f140bsyf7g2lyv00000gn/T/pip-req-build-03_iq99_
  Running command git clone -q https://github.com/tensorflow/probability.git
...
  running bdist_wheel
  running build
  running build_py
  creating build
  error: could not create 'build': File exists
```
This is the same problem as this: https://github.com/pachyderm/python-pachyderm/issues/20, which was fixed by simply renaming the `BUILD` file: https://github.com/pachyderm/python-pachyderm/pull/25.

Unfortunately, installing `tfp-nightly` is not a solution because poetry cannot find it, and requires a dependency like this: `tfp-nightly = {git = "https://github.com/tensorflow/probability.git"}`.

**Comment by SiegeLordEx** [comment]
I guess we could rename `BUILD` to `BUILD.bazel` as is evidently supported by bazel https://docs.bazel.build/versions/master/build-ref.html#packages

**Comment by NeilGirdhar** [comment]
Awesome, that would be great

**Comment by SiegeLordEx** [comment]
Out of curiosity, what filesystems are actually case insensitive?

**Comment by NeilGirdhar** [comment]
Mac OS unfortunately

**Comment by SiegeLordEx** [comment]
So this is turning out to be quite complicated, since the pip package is built after generating a lot of files using `blaze`. Maybe it's worth trying to fix the original issue with poetry. What error were you getting with the `tfp-nightly` package? This appeared to work for me:

```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["blah blah"]

[tool.poetry.dependencies]
python = "^3.9"
tfp-nightly = "^0.13.0-alpha.20210506"
jax = "^0.2.13"
jaxlib = "^0.1.65"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by NeilGirdhar** [comment]
@SiegeLordEx That works!  Sorry for the bother then.
