### ISSUE TITLE
tfp.mcmc.sample_halton_sequence 

### ISSUE THREAD

**Issue by VA70** [tensorflow/probability#133]
Hello,

I'd like to use rqmc in a VAE and have encountered a problem with the tfp.mcmc.sample_halton_sequence function.  In building a graph which allows for variable sample sizes and a fixed dimension (say 64), I have created a tensor of size [None, 64]. I'd like to return a (random) uniform sample from the halton sequence which I can then transform into a normal distribution using an inverse cfd.  The problem I'm finding is that tfp.mcmc.sample_halton_sequence does not like using num_results=tf.shape(samples)[0] since it in effect parameterizing num_results with tensor, rather than an integer.

line 170 of the function catches the error here:
   if dim < 1 or dim > _MAX_DIMENSION:
      raise ValueError('Dimension must be between 1 and {}. Supplied {}'.format(_MAX_DIMENSION, dim))

raising the error:
  TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed etc....

Since dim is a tensor it's getting caught by using then if statement on it rather than, say, using tf.cond.

Is there a plan to allow tfp.mcmc.sample_halton_sequence to be parameterized by tensors?

Many thanks,

Vlad

**Comment by VA70** [comment]
Dear Ashish,

I was using tensors for both, but I can easily set the dimension parameters via a hardcoded value, the tricky part was dimensioning the sample size to reflect the batch size and the sampling rate for each element of the batch, so you change would be ideal!

Thank you for prompt reply.

Regards,

Vlad

**Comment by saxena-ashish-g** [comment]
You should now be able to supply tensorial values for the num_samples parameter (after [this commit](https://github.com/tensorflow/probability/commit/3b5bfba0657f13c5f5fbccd6ee5930d3efc97dde)).
