### ISSUE TITLE
Add a collapse interceptor

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#135]
The [current LDA example](https://github.com/tensorflow/probability/blob/064a66bb509fa030cfb799223dac3b7e9416952e/tensorflow_probability/examples/latent_dirichlet_allocation_edward2.py) is collapsed where it manually writes `tf.matmul` of `topics` of shape `[1, num_topics]` and `topics_words` of shape `[num_topics, num_words]`. It would be nice to write the vanilla LDA generative process, which has an explicit per-word topic assignment.

For inference, one can apply an interceptor that collapses the variable. For criticism, one can keep the explicit per-word topic assignment, which is necessary for PPCs like [Mimno et al. (2011)](https://mimno.infosci.cornell.edu/papers/mimno-ppcs-emnlp.pdf).

A collapsed mixture model might look like the following.

```python
def mixture_model(batch_size):
  probs = ed.Dirichlet(concentration=tf.ones(3), name="probs")
  cluster_means = ed.Normal(loc=tf.zeros([3, 2]),
                            scale=1.,
                            name="cluster_means")
  mixture_assignments = ed.OneHotCategorical(logits=prob,
                                             sample_shape=batch_size,
                                             name="mixture_assignments")
  datapoints = ed.Normal(loc=tf.matmul(mixture_assignments, cluster_means),
                         scale=1.,
                         name="datapoints")
  return datapoints

collapsed_mixture_model = ed.collapse(mixture_model, ["mixture_assignments"])
log_joint = ed.make_log_joint_fn(collapsed_mixture_model)

batch_size = 5
probs_value = tf.random_normal([3])
cluster_means_value = tf.random_normal([3, 2])
datapoints_value = tf.random_normal([batch_size, 2])
output = log_joint(batch_size,
                   probs=probs_value,
                   cluster_means=cluster_means_value,
                   datapoints=datapoints_value)
```

I think this would involve Autoconj magic. At the very least, it requires tracing the `tf.matmul` in Normal's location parameter.

**Comment by srvasude** [comment]
Closing this as Edward2's repository has moved here: Closing this, as Edward2's repository is now located here: https://github.com/google/edward2 (but this is still a cool interceptor to have :)).

**Comment by brianwa84** [comment]
Seems like this could apply just as well to jdcoroutine?

**Comment by davmre** [comment]
Yup, I think @dpiponi was/(is?) working on something along these lines.
