### ISSUE TITLE
Independent is hard to use in Edward2

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#136]
`tfd.Independent` takes a tfd Distribution as input, which implies the wrapped `ed.Independent` does too. It also requires hand-specifying the `value`, or otherwise it will sample from the overall distribution again.

This makes for ugly boilerplate. For example:

```python
def deep_exponential_family(data_size, feature_size, units, shape):
  """A multi-layered topic model over a documents-by-terms matrix."""
  batched_w2 = ed.Gamma(0.1, 0.3, sample_shape=[units[2], units[1]])
  w2 = ed.Independent(batched_w2.distribution,
                      value=batched_w2.value,
                      reinterpreted_batch_ndims=2,
                      name="w2")
  batched_w1 = ed.Gamma(0.1, 0.3, sample_shape=[units[1], units[0]])
  w1 = ed.Independent(batched_w1.distribution,
                      value=batched_w1.value,
                      reinterpreted_batch_ndims=2,
                      name="w1")
  batched_w0 = ed.Gamma(0.1, 0.3, sample_shape=[units[0], feature_size])
  w0 = ed.Independent(batched_w0.distribution,
                      value=batched_w0.value,
                      reinterpreted_batch_ndims=2,
                      name="w0")

  batched_z2 = ed.Gamma(0.1, 0.1, sample_shape=[data_size, units[2]])
  z2 = ed.Independent(batched_z2.distribution,
                      value=batched_z2.value,
                      name="z2")
  batched_z1 = ed.Gamma(shape, shape / tf.matmul(z2, w2))
  z1 = ed.Independent(batched_z1.distribution,
                      value=batched_z1.value,
                      name="z1")
  batched_z0 = ed.Gamma(shape, shape / tf.matmul(z1, w1))
  z0 = ed.Independent(batched_z0.distribution,
                      name="z0")
  batched_x = ed.Poisson(tf.matmul(z0, w0))
  x = ed.Independent(batched_x.distribution, value=batched_x.value, name="x")
  return x
```

Thoughts on how to improve usability are welcome.

**Comment by dustinvtran** [comment]
Yes that's a worthy potential solution. The potential con is that that requires custom logic for one distribution, which is more difficult to maintain. The ideal would be a more automatic solution, either within Edward2 or lower in the stack.

**Comment by brianwa84** [comment]
Does Edward2 handle TransformedDistribution? I would expect a similar issue
there.

**Comment by SiegeLordEx** [comment]
I don't think the code in OP is correctly written.

I think the correct way to write an Independent distribution in Edward2 is to do:

```
def model():
  n = tfp.distributions.Normal(loc=[1., 1.], scale=[1., 1.])
  q = tfp.edward2.Independent(distribution=n, reinterpreted_batch_ndims=1, name="q")
  return q
```
I.e. use a regular tfp distribution as an argument to the composed distribution.

If you instead do what the code in the OP does:

```
def model():
  n = tfp.edward2.Normal(loc=[1., 1.], scale=[1., 1.], name="n")
  q = tfp.edward2.Independent(distribution=n.distribution, value=n.value, reinterpreted_batch_ndims=1, name="q")
  return q
```

you'll actually be constructing a joint distribution with two perfectly correlated random variables and thus double counting the log probability associated with what you presumably meant to write.

This came up in this question https://groups.google.com/a/tensorflow.org/forum/#!topic/tfprobability/tFoHD_Ize20 in the context of `QuantizedDistribution`.

I think the general answer for these wrapper RandomVariables's is to use TFP distributions as arguments.
