### ISSUE TITLE
NaN constants returned by tfp.stats.quantiles interfere with numerical issue debugging

### ISSUE THREAD

**Issue by bberlo** [tensorflow/probability#1374]
## Problem
If the tfp.stats.quantiles() function is used in graph mode within a program, and the program is debugged with the function tf.debugging.experimental.enable_dump_debug_info(), the tfp.stats.quantiles() function creates NaN constant ops inside the graph that interfere with numerical issue debugging (i.e. when clicking in the 'alerts' tab, the first NaN recognized is a NaN constant op). This also interferes with the function tf.debugging.enable_check_numerics().

## TensorBoard Debugger V2 screen capture
![image](https://user-images.githubusercontent.com/81620791/124525332-2f9ab880-ddff-11eb-90bc-28807dd7e0ab.png)

**Comment by caisq** [comment]
To ignore the Const op, you can use the `op_regex` kwarg of `enable_dump_debug_info()`. The doc at https://www.tensorflow.org/api_docs/python/tf/debugging/experimental/enable_dump_debug_info provides an example. Specifically, you can do `op_regex=(?!^Const$)`

**Comment by bberlo** [comment]
Thank you for the elaboration. Will close this issue.
