### ISSUE TITLE
Markov Chain log_prob method is not working when using Markov chain state as part of features

### ISSUE THREAD

**Issue by xiaolongluo1979** [tensorflow/probability#1375]
Hi, I am trying to generate batch (with unique feature) Markov chains so that each transition probability dependents on its state as well. I can make the sample method work but the log_prob method fails. It is similar to one previous issue in terms of confused sample and batch shapes, but it seems more involved due to re-setting the transition distribution from each state.

Can someone help me to see how to fix it? Thanks a lot! Here are the short codes:

!pip install tfp-nightly
!pip install tf-nightly 

import tensorflow_probability as tfp
import tensorflow as tf
import numpy as np
import pandas as pd

tfd = tfp.distributions

batch_shape=10
features_num=5

### batch features
X=tf.random.normal([batch_shape,features_num], 0, 1, tf.float32, seed=1)

### get processes starting point and planned Jumpsteps
previous_state={'time':tf.zeros([batch_shape], tf.float32),
                'y':tf.zeros([batch_shape], tf.float32)
               }
Jump_steps=7   ### post starting position

### batch features and current state functions
jumptime_parameters=tf.keras.layers.Dense(1,activation='relu')
jump_parameters=tf.keras.layers.Dense(3,activation='softmax')

#### transition function of Markov chain
def transition_fn(_, previous_state):
    tfstate=tf.stack([previous_state[v] for v in previous_state.keys()],-1)
    if tf.rank(tfstate)==tf.rank(X):
        state_X=tf.concat([tfstate,X],axis=-1)
    if tf.rank(tfstate)>tf.rank(X):
        stackX=tf.stack(tf.shape(tfstate)[0].numpy()*[X],  axis=0)  ### broadcast X to all samples
        state_X=tf.concat([tfstate,stackX],-1)
    return tfd.JointDistributionNamedAutoBatched(
    batch_ndims=tf.rank(previous_state['time']),
    model=dict(
        time = tfd.TransformedDistribution(
          distribution=tfd.Gamma(concentration=1.0, 
                            rate=tf.math.softplus(jumptime_parameters(state_X)[:,0])),
              bijector=tfp.bijectors.Shift(previous_state['time'])),
        y = lambda time: tfd.Mixture(
          cat=tfd.Categorical(
              probs=jump_parameters(tf.concat([tf.expand_dims(time,axis=-1),state_X],-1))),
                          components=[
                            tfp.distributions.Deterministic(-1.0+tf.zeros_like(previous_state['y'])),
                            tfp.distributions.Deterministic(tf.zeros_like(previous_state['y'])),
                            tfp.distributions.Deterministic(1.0+tf.zeros_like(previous_state['y']))
                                    ])

    ))

### Batch Markov processes
process = tfd.MarkovChain(
                initial_state_prior=transition_fn(0, previous_state=previous_state),
                transition_fn=transition_fn,
                num_steps=Jump_steps)

print('batch shape \n',process.batch_shape, 'event shape \n',process.event_shape)
print('MC sample method is working \n', process.sample(2))
print('MC log_prob method is not working \n',process.log_prob(process.sample(2)))

**Comment by davmre** [comment]
A good way to check that your arguments to a MarkovChain will work correctly is to just run them yourself, for a single step:

```python
# Sample from the prior. To catch shape bugs, draw multiple samples.
prior_state = process.initial_state_prior.sample([3, 1, 4, 2])
prior_log_prob = process.initial_state_prior.log_prob(prior_state)
print("prior log prob ran and has batch shape:", prior_log_prob.shape)

# Create the transition distribution from our prior sample
transition_dist = process.transition_fn(0, prior_state)

# Sample from the distribution after one transition and compute its `log_prob`.
# Note that multiple prior samples induce *batch shape* in the transition distribution. 
next_state = transition_dist.sample()
transition_log_prob = transition_dist.log_prob(next_state)
print("transition log prob ran and has batch shape:", prior_log_prob.shape)
```

When I try this with your code, I get this error in `transition_fn`:

```python
InvalidArgumentError: ConcatOp : Ranks of all input tensors should match: shape[0] = [1,2,3,10,2] vs. shape[1] = [1,10,5]
```

which is coming from the third line of:

```python
if tf.rank(tfstate)>tf.rank(X):
  stackX=tf.stack(tf.shape(tfstate)[0].numpy()*[X], axis=0) ### broadcast X to all samples
  state_X=tf.concat([tfstate,stackX],-1)
```

It looks like you're trying to concat two things with different shapes. I suspect it's because the previous line that stacks `X` is assuming that `tfstate` will never have multiple batch dimensions, but this happens in `log_prob`. Would just `stackX = tf.broadcast_to(X, tf.shape(tfstate))` work there to broadcast the entire shape?

**Comment by xiaolongluo1979** [comment]
@davmre Hi Dave, thanks for the inspection idea. Indeed, multidimensional shape fail to broadcasting X with tf.stack. I tried stackX = tf.broadcast_to(X, tf.shape(tfstate)), but it was not compatible either (InvalidArgumentError: Incompatible shapes: [10,5] vs. [3,1,4,2,10,2] [Op:BroadcastTo] ). Ideally, i would need to broadcast "10" to "[3,1,4,2,10]" and keep the last dimension.

However, for this problem, i think it may be easier to add batch features to a state variable, keeping previous state in the transition. This does solve the tf.concat problem, but there is still shape compatibility issue with log_prob. See notes below.

**Comment by xiaolongluo1979** [comment]
@davmre As mentioned, adding features in MC state may have solved the  tf.concat problem. Would you help to see what log_prob method expect on shapes? 

There is problem from transition_dist.sample(): InvalidArgumentError: Incompatible shapes: [3,10,1] vs. [3,4,10] [Op:AddV2].


batch_shape=10
features_num=5

### batch features
X=tf.random.normal([batch_shape,features_num], 0, 1, tf.float32, seed=1)

### get processes starting point and planned Jumpsteps
previous_state={'X':X,
                'time':tf.zeros([batch_shape], tf.float32),
                'y':tf.zeros([batch_shape], tf.float32)
               }
Jump_steps=7   ### post starting position

### batch features and current state functions
jumptime_parameters=tf.keras.layers.Dense(1,activation='relu')
jump_parameters=tf.keras.layers.Dense(3,activation='softmax')

#### transition function of Markov chain
def transition_fn(_, previous_state):
    tfstate=tf.concat([tf.stack([previous_state[v] for v in previous_state.keys() if v !='X'],axis=-1),previous_state['X']],-1) 
    return tfd.JointDistributionNamedAutoBatched(
    batch_ndims=tf.rank(previous_state['time']),
    model=dict(
        X = tfp.distributions.Deterministic(previous_state['X']),
        time = tfd.TransformedDistribution(
          distribution=tfd.Gamma(concentration=1.0, 
                            rate=tf.math.softplus(jumptime_parameters(tfstate)[:,0])),
              bijector=tfp.bijectors.Shift(previous_state['time'])),
        y = lambda time: tfd.Mixture(
          cat=tfd.Categorical(
              probs=jump_parameters(tf.concat([tf.expand_dims(time,axis=-1),tfstate],-1))),
                          components=[
                            tfp.distributions.Deterministic(-1.0+tf.zeros_like(previous_state['y'])),
                            tfp.distributions.Deterministic(tf.zeros_like(previous_state['y'])),
                            tfp.distributions.Deterministic(1.0+tf.zeros_like(previous_state['y']))
                                    ])

    ))

### Batch Markov processes
process = tfd.MarkovChain(
                initial_state_prior=transition_fn(0, previous_state=previous_state),
                transition_fn=transition_fn,
                num_steps=Jump_steps)

print('batch shape \n',process.batch_shape, 'event shape \n',process.event_shape)

# Sample from the prior. To catch shape bugs, draw multiple samples.
prior_state = process.initial_state_prior.sample([3, 4])
prior_log_prob = process.initial_state_prior.log_prob(prior_state)
print("prior log prob ran and has batch shape:", prior_log_prob.shape)

# Create the transition distribution from our prior sample
transition_dist = process.transition_fn(0, prior_state)

# Sample from the distribution after one transition and compute its `log_prob`.
# Note that multiple prior samples induce *batch shape* in the transition distribution. 
next_state = transition_dist.sample()
transition_log_prob = transition_dist.log_prob(next_state)
print("transition log prob ran and has batch shape:", prior_log_prob.shape)


# print('MC sample method is working \n', process.sample(2))
# print('MC log_prob method is not working \n',process.log_prob(process.sample(2)))

**Comment by xiaolongluo1979** [comment]
Never mind. i think i found the bug. jumptime_parameters(tfstate)[:,0] should be jumptime_parameters(tfstate)[...,-1]. Thanks @davmre
