### ISSUE TITLE
Should Edward2 random variables defer constructing value tensor?

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#138]
For maximal performance in Eager mode, Edward2 may want to avoid extraneous sampling ops if the user doesn't actually use them. This can be done by moving any construction of the `value` Tensor from `__init__` to [`_tensor_conversion_function`](https://github.com/tensorflow/probability/blob/74037f90010c08e17a567c281ff3f70f4157364a/tensorflow_probability/python/edward2/random_variable.py#L312).

Note this breaks the API of querying `value` immediately after its construction: it will not exist until you apply, e.g., `tf.identity(rv)`. This delayed property seems undesirable. So we may want to unexpose the `value` property altogether.

**Comment by dustinvtran** [comment]
Random thought: TF Keras layers have delayed properties—several methods are not available until `self.built` is True, that is, one calls `build()`. So that might be okay for us too.

**Comment by axch** [comment]
Or `value` can be a method tagged with Python's standard `@property` decorator, which forces construction of the `value` Tensor if it hasn't been constructed yet.  That seems like the simplest solution to me.

**Comment by dustinvtran** [comment]
+1 to that solution

**Comment by brianwa84** [comment]
I thought @property methods were only called when accessed?

**Comment by axch** [comment]
Exactly.  The point is to avoid building that Tensor if it is not accessed.
