### ISSUE TITLE
Is there a plan to implement StudentTProcessRegressionModel similar to GuassianProcessRegressionModel? 

### ISSUE THREAD

**Issue by filpia** [tensorflow/probability#1383]
Title should be self-explanatory but just as `tfp.distributions.GaussianProcess` begets the `tfp.distributions.GaussianProcessRegressionModel` is there a plan to implement the `tfp.distributions.StudentTProcessRegressionModel` stemming from `tfp.distributions.StudentTProcess`?

**Comment by srvasude** [comment]
I plan on checking a version of this in O(weeks) (I was using this for an internal project).

**Comment by srvasude** [comment]
FWIW, the Student-T model doesn't have conjugacy, so you have to make other assumptions in order to write an analytic distribution. I am using ideas based off https://dl.acm.org/doi/abs/10.3233/978-1-61499-672-9-82

**Comment by filpia** [comment]
That's amazing, thank you @srvasude. 

re: conjugacy I may not be completely understanding the literature but I think [Shah et al](https://www.cs.cmu.edu/~andrewgw/tprocess.pdf) use an Inverse Wishart prior and its conjugacy with the multivariate normal to achieve Student-t behavior. They also mention that there's marginal equivalence by using the Inverse Gamma with analytical benefits over the Inverse Wishart

**Comment by srvasude** [comment]
Yes, I believe Shah et al. and the linked paper above are equivalent (the first paper gives an interpretation in terms of a noise model).

**Comment by srvasude** [comment]
Closing as a `StudentTProcessRegressionModel` distribution is in TFP.
