### ISSUE TITLE
Non-injective transformation -- dense layer

### ISSUE THREAD

**Issue by act65** [tensorflow/probability#139]
Hey,
I am trying to write a simple dense bijector that allows you to transform into higher/lower dim spaces.
I came across a trick for calculating the determinant of a rectangular transform (det(A) := sqrt(det(A.A^T)), which means we can cal the log_det_jacobian (it's not zero/inf). 
However I am having problems with `tfp.Bijector`/`tfd.TransformedDistribution` not liking the change in shape.

```
import tensorflow as tf
import tensorflow_probability as tfp
tfb = tfp.bijectors
tfd = tfp.distributions

def jacobian(y, x):
    """
    Code adapted from https://github.com/tensorflow/tensorflow/issues/675#issuecomment-319891923
    
    Args:
        y: A 2d tf.tensor [batch, n_outputs]
        x: A 2d tf.tensor [batch, n_inputs]
        
    Returns:
        [batch, n_outputs, n_inputs]
    """
    y_flat = tf.reshape(y, [-1])
    n = y_flat.get_shape()[0]

    loop_vars = [
        tf.constant(0, tf.int32),
        tf.TensorArray(tf.float32, size=n),
    ]
    _, jacobian = tf.while_loop(
        lambda j, _: j < n,
        lambda j, result: (j+1, result.write(j, tf.gradients(y_flat[j], x))),
        loop_vars)
    
    jacobian = jacobian.stack()

    dydx = tf.reshape(jacobian, y.shape.concatenate(x.shape))
    return tf.reduce_sum(dydx, axis=[2])

def non_square_det(x):
    """
    Idea taken from https://www.quora.com/How-do-we-calculate-the-determinant-of-a-non-square-matrix
    
    # for n != m
    A = tf.random_normal([n, m])
    det(A) := sqrt(det(A.A^T))
    
    Args:
        x (tf.tensor): shape in [..., a, b]
        
    Returns:
        [..., ]
    """
    squared_mat = tf.matmul(x, x, transpose_b=True)
    return tf.sqrt(tf.linalg.det(squared_mat))

class Dense(tfb.Bijector):
    """
    Want a hierarchical flow.
    Map some low dim distribution to a manifold in a higher dimensional space.
    """
    def __init__(self, n_inputs, n_outputs, validate_args=False, name='dense'):
        """
        Args:
            n_inputs (int): the number of features (last dim)
            n_outputs (int): the target num of feautres
        """
        super(self.__class__, self).__init__(
            validate_args=validate_args,
            forward_min_event_ndims=1,
            name=name)
        
        self.n_inputs = n_inputs
        self.n_outputs = n_outputs
        with tf.variable_scope(name, reuse=tf.AUTO_REUSE):
            self.weights = tf.get_variable(name='weights', 
                                           shape=[n_inputs,n_outputs], 
                                           dtype=tf.float32)
            self.bias = tf.get_variable(name='bias', 
                                        shape=[n_outputs], 
                                        dtype=tf.float32)
                
    def _forward_event_shape_tensor(self, shape):
        return tf.shape([shape[0], self.n_inputs])
    
    def _invserse_event_shape_tensor(self, shape):
        return tf.shape([shape[0], self.n_outputs])
                
    def _forward(self, x):
        return tf.matmul(x, self.weights) + self.bias
    
    def _inverse(self, y):
        # BUG this is only true if the weights are unitary
        # need to fix, maybe be use approx/learned inversion
        return tf.matmul(y - self.bias, self.weights, transpose_b=True)
    
    def _forward_log_det_jacobian(self, x):
        y = self.forward(x)
        J = jacobian(y, x)
        return tf.log(non_square_det(J))
    
    def _inverse_log_det_jacobian(self, y):
        return -self._forward_log_det_jacobian(self.inverse(y))
```

So, I thought `_forward_event_shape_tensor` would get called, but it doesnt seem to be. Instead get this error;

```
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py in merge_with(self, other)
    673         for i, dim in enumerate(self._dims):
--> 674           new_dims.append(dim.merge_with(other[i]))
    675         return TensorShape(new_dims)

~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py in merge_with(self, other)
    142     other = as_dimension(other)
--> 143     self.assert_is_compatible_with(other)
    144     if self._value is None:

~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
    115       raise ValueError("Dimensions %s and %s are not compatible" % (self,
--> 116                                                                     other))
    117 

ValueError: Dimensions 12 and 6 are not compatible

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-112-79593ca9043c> in <module>()
----> 1 density.sample(3)

~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/ops/distributions/distribution.py in sample(self, sample_shape, seed, name)
    713       samples: a `Tensor` with prepended dimensions `sample_shape`.
    714     """
--> 715     return self._call_sample_n(sample_shape, seed, name)
    716 
    717   def _log_prob(self, value):

~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/ops/distributions/transformed_distribution.py in _call_sample_n(self, sample_shape, seed, name, **kwargs)
    409       # returned result.
    410       y = self.bijector.forward(x, **kwargs)
--> 411       y = self._set_sample_static_shape(y, sample_shape)
    412 
    413       return y

~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/ops/distributions/distribution.py in _set_sample_static_shape(self, x, sample_shape)
   1198       shape = tensor_shape.TensorShape(
   1199           [None]*(ndims - event_ndims)).concatenate(self.event_shape)
-> 1200       x.set_shape(x.get_shape().merge_with(shape))
   1201 
   1202     # Infer batch shape.

~/anaconda3/envs/mri/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py in merge_with(self, other)
    675         return TensorShape(new_dims)
    676       except ValueError:
--> 677         raise ValueError("Shapes %s and %s are not compatible" % (self, other))
    678 
    679   def concatenate(self, other):

ValueError: Shapes (3, 12) and (?, 6) are not compatible
```

Might be not even be a bug... Im not sure.
Having trouble figuring it out for myself, cant find some of the fns in the repo...
Oh, version r0.3.

**Comment by act65** [comment]
Oh, I get that error when I call `Dense().sample(n)`

**Comment by shouldsee** [comment]
I had the same problem when trying to change the tensor_shape in a bijector. My experience is same with yours: _forward_tensor_shape() does not seems to be called anywhere.. Instead I had to hack around the TransformedDistribution(event_dims = output_dims, simple =True) to override the shape. See this gist [tfp_transformed_distribution.py](https://gist.github.com/shouldsee/1ba9a20a8cd3358c47c05544f54532dc)

This is a very dirty/brutal hack and bijector needs some expansion in the future.

**Comment by shouldsee** [comment]
@davmre:  Thank you for point me to the Reshape() bijector, but as far as my usage concerns, it would be impossible to do `log_prob()`/`sample()` and `reshape()` separately, since I am looking at non-injective transformation. 

It would be helpful if you can point me to an example where `_forward_event_shape` is called since I really struggle to find one.

**Comment by davmre** [comment]
@shouldsee What problem are you trying to solve? You'll need to be very careful with non-injective transformations to ensure that what you're doing is mathematically meaningful, but in terms of pure code you should just be able to write `forward` and `inverse` methods that return Tensors of the size you want, and `forward/inverse_event_shape` methods that return that size. Can you post the code snippet that's giving you an error?

**Comment by shouldsee** [comment]
@davmre

I was trying to project a Chi-Squared distribution to a multivariate Gaussian, and ended up hacking the event_shape overrider to make it working. Basically when I changed the shape in the _sample_n method, the actual call of sample() would throw an error saying unable to reshape. Say I have a chi square distrib of (1000,) where 1000 is the batch shape, and I want to project it into a Gaussian distribution in 3D, then the output shape should be (1000,3). My current solution sets event_shape = 3 in TransformedDistritbution() but this is pretty ugly...

I can post some code another day if the description above is not enough.

But speaking of non-bijective transformation, I don’t really see how it is harder than bijective ones.. (well it’s probably harder), given that people will have to write the _inverse_log_determinant() methods themselves anyway...

Sent from my iPhone

On 7 Sep 2018, at 21:09, Dave Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


@shouldsee<https://github.com/shouldsee> What problem are you trying to solve? You'll need to be very careful with non-injective transformations to ensure that what you're doing is mathematically meaningful, but in terms of pure code you should just be able to write forward and inverse methods that return Tensors of the size you want, and forward/inverse_event_shape methods that return that size. Can you post the code snippet that's giving you an error?

**Comment by davmre** [comment]
Does it not work to just return the appropriate `forward_event_shape` (which would be `[3]` in this case) from your Bijector? `TransformedDistribution` calls `forward_event_shape` to compute its event shape: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/distributions/transformed_distribution.py#L337

**Comment by shouldsee** [comment]
Ahh here it is! I was unable to spot this call for ages. Yeah I forgot to mention that I had absolutely no idea of an event_shape when I was writing that bijector. I will let you know once I tested the solution.

( I thought event_shape is just the shape of the transformed tensor and never thought to return a [3])

Sent from my iPhone

On 7 Sep 2018, at 22:15, Dave Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it not work to just return the appropriate forward_event_shape (which would be [3] in this case) from your Bijector? TransformedDistribution calls forward_event_shape to compute its event shape: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/distributions/transformed_distribution.py#L337

**Comment by shouldsee** [comment]
@davmre I have created a executable example of using `_forward_event_shape()` to specify the shape of the output. [radial_transform_minimal.py](https://gist.github.com/shouldsee/947f118e314b5cb39b4c3636c3b6d5dc) and I had to disable some caching to make the sampling work.
