### ISSUE TITLE
Accessing values of `current_state` inside target `log_prob` function

### ISSUE THREAD

**Issue by romanovzky** [tensorflow/probability#1390]
Hi there,

I'm trying to write my own `log_prob` target function which requires me to use non-tf functions in a `HamiltoneanMonteCarlo`. Since the only apparent requirement is for this function to return the `log_prob` of the state, I see no problem with this step.

However, when I try to get the values of the current state, I can't seem to invoque `.numpy()` method, even though `tf.executing_eagerly()` is returning `True`. What am I missing? How can I use the values of the `current_state`?

Cheers

**Comment by brianwa84** [comment]
The while loop body for MCMC is [effectively] a tf.function, within which
the tensors are symbolic, not eager. In the context of your log_prob,
tf.executing_eagerly() *should* return false.
If you want to use eager inside of it, you could use tf.py_function, but
note that you will lose autodiff if you use tensor.numpy() (actually, I'm
unsure whether py_function supports autodiff or not), and autodiff is
necessary for HMC.

**Comment by romanovzky** [comment]
Hi there @brianwa84 . You are right, I had oversight that HMC does indeed need gradients, something that escaped my mind at the time. I'll close the comment then, as I don't really have a case anymore. Thanks!
