### ISSUE TITLE
Is there a stable way to calculate functional of MarkovChain (or general joint distribution)?

### ISSUE THREAD

**Issue by xiaolongluo1979** [tensorflow/probability#1394]
Hi, is there a more general method to calculate functional of MarkovChain (or general joint distribution)? i understand there are some basic mean and some log_prob methods. 

For example, suppose we have a Markov chain W_n, n=0,1,2, ..., started from a fixed distribution. The state at a fixed step, e.g., n=5, should have a fixed distribution and so is f(W_5) for a fixed function f. How do we calculate its mean Ef(W_5)? We can try Monte Carlo method by using samples of the chains. However, it does not appear stable or reliable. See the simple example below:  

### construct a random walk with n(0,1) normal transition distribution
gaussian_walk = tfd.MarkovChain(
  initial_state_prior=tfd.Normal(loc=0., scale=1.),
  transition_fn=lambda _, x: tfd.Normal(loc=x, scale=1.),
  num_steps=10)

### get functional value of the state at a fixed step from simulation
def fun(walk,step, Nsim):
    walk_N=walk.sample(Nsim)
    val=0.5*walk_N[step]+1.8*tf.math.exp(-3.5*walk_N[step])
    return tf.math.reduce_mean(val).numpy()

print('Run 1: Difference between two simulated mean of the functional \n',
     fun(gaussian_walk,5, 10000),fun(gaussian_walk,5, 20000))

print('Run 2: Difference between two simulated mean of the functional \n',
     fun(gaussian_walk,5, 10000),fun(gaussian_walk,5, 20000))

**Comment by davmre** [comment]
I think the `[step]` indices in your line `0.5*walk_N[step] + +1.8*tf.math.exp(-3.5*walk_N[step])` should be `[:, step]`. Drawing `Nsim` iid samples will produce a tensor of shape `[Nsim, num_steps]`, and you want to index into the steps, not the samples. That would explain why you're seeing high variance.

Monte Carlo is the standard strategy for this kind of task in general, though there are cases where some problem-specific structure might let you do something analytical. (e.g., for a Gaussian random walk you could use `tfd.LinearGaussianStateSpaceModel`'s `.mean()` and `.stddev()`  to get the exact prior marginal distributions).

**Comment by xiaolongluo1979** [comment]
@davmre Got it. Thanks a lot. Sorry for the error of indexing.
