### ISSUE TITLE
Option for adding bias / intercept term to GLM 

### ISSUE THREAD

**Issue by nmarchio** [tensorflow/probability#1396]
I'm having trouble finding a method for adding a bias or intercept term to a [GLM regression](https://www.tensorflow.org/probability/examples/Generalized_Linear_Models). In most GLM regression packages such as [R's GLMnet](https://www.tensorflow.org/probability/examples/Generalized_Linear_Models) there is an option to add an intercept term. Is there a recommended approach for doing this with the GLM models or would it amount to a feature request? 

It appears the experimental Keras Linear Model in Tensorflow [offers a method](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/LinearModel) for adding in an intercept term. Thanks

**Comment by csuter** [comment]
It might be easiest to concatenate ones onto the design matrix. Not the
most elegant solution but should do the trick? It's probably what the
implementation of such an optional flag (a la glmnet) would do internally.

**Comment by nmarchio** [comment]
Oh thanks -- I think I found the issue is that I was using `tfp.glm.fit_sparse` which doesn't include an 'offset' argument, however `tfp.glm.fit` does include an 'offset' arg which I think appears to be tensorflow GLM terminology for an intercept?
