### ISSUE TITLE
Jittered HMC (i.e. HMC with a randomizable number of leapfrog steps)

### ISSUE THREAD

**Issue by anvvalade** [tensorflow/probability#1397]
I have been experiencing some frustration with the NUTS algorithm, and based on [this work](https://discourse.mc-stan.org/t/hmc-jittered-vs-nuts-on-1000-dimensional-standard-normal/8383/10) I would like to code a "jittered" HMC in tensorflow-probabilty as an alternative to it.

The idea of the jittered HMC is that the number of leapfrog steps L is not constant but drawn at random from the uniform law U(1, L) at each iteration.

Is there a simple way to properly implement that using the routines provided in tensorflow-probability?

**Comment by chrism0dwk** [comment]
Answering your question directly, I don't think there's a way to do this off the cuff.  

I played around with fixing the path length `T = epsilon * L` and adapting `L=floordiv(T, epsilon)` [here](https://github.com/chrism0dwk/probability/blob/ddc8c0f727d57ba273f940b13f844006bcd2c5c6/tensorflow_probability/python/mcmc/hmc.py#L755).  My motivation was to stablise the HMC and stop the total path length running to infinity for unwise choices of `epsilon` during adaptation. 

As pointed out by the TFP team at the time, making `L` stochastic does bad things to the scalability of running parallel MCMC chains in a SIMD fashion, but I do think there's a case for having an option for a stochastic number of steps (either with jitter as you suggest, or with a fixed total path length).

**Comment by anvvalade** [comment]
> As pointed out by the TFP team at the time, making L stochastic does bad things to the scalability of running parallel MCMC chains in a SIMD fashion, but I do think there's a case for having an option for a stochastic number of steps (either with jitter as you suggest, or with a fixed total path length).

Isn't it anyway what is happening when running NUTS? The length of each step may vary across chains! All the chains just have to wait for the longest. 

I am at the moment running NUTS with a low value of `max_tree_depth` as the U-Turn criterion seems to be never reached. From my understanding it is very close to running a "jittered" HMC, but I suppose with a computation overhead that I might not need.

**Comment by junpenglao** [comment]
I got a fairly simple jitter HMC:
```python
from tensorflow_probability.python.internal import unnest
from tensorflow_probability.python.internal import samplers

def hmc_like_num_leapfrog_setter_fn(kernel_results, new_num_leapfrog):
  """Setter for `new_num_leapfrog` so it can be randomized."""
  return unnest.replace_innermost(kernel_results,
                                  num_leapfrog_steps=new_num_leapfrog)


def hmc_like_num_leapfrog_getter_fn(kernel_results):
  """Getter for `num_leapfrog_steps` so it can be inspected."""
  return unnest.get_innermost(kernel_results, 'num_leapfrog_steps')


class JitterNumLeapfrog(tfp.mcmc.TransitionKernel):
  def __init__(self, hmc, jitter_dist):
    self._hmc = hmc
    self.jitter_dist = jitter_dist

  def one_step(self, current_state, previous_kernel_results, seed=None):
    seed = samplers.sanitize_seed(seed)
    leapfrog_seed, kernel_seed = samplers.split_seed(seed)
    perturbed_num_leapfrog = tf.cast(
        self.jitter_dist.sample(seed=leapfrog_seed), dtype=tf.int32)
    hmc_results = hmc_like_num_leapfrog_setter_fn(
        previous_kernel_results, perturbed_num_leapfrog)
    return self._hmc.one_step(
        current_state, hmc_results, kernel_seed)

  def bootstrap_results(self, state):
    return self._hmc.bootstrap_results(state)
  
  @property
  def is_calibrated(self):
    return self._hmc.is_calibrated
```

To use it:
```python
dist = tfd.Independent(
    tfd.Normal(np.arange(5,  dtype=np.float32), 1.), 1)
hmc = JitterNumLeapfrog(
    tfp.mcmc.HamiltonianMonteCarlo(
        dist.log_prob,
        step_size=.1,
        num_leapfrog_steps=5,
        store_parameters_in_results=True),
    jitter_dist=tfd.Uniform(low=10, high=20)
)
samples = tf.function(tfp.mcmc.sample_chain, jit_compile=True)(
    500, dist.sample(4), kernel=hmc, num_burnin_steps=500)

print(np.mean(samples.all_states, axis=0), np.std(samples.all_states, axis=0))

plt.plot(samples.trace.accepted_results.num_leapfrog_steps)
```

But as @chrism0dwk mentioned, due to the batching across chain, at each sample the number of leapfrog step is the same.

**Comment by anvvalade** [comment]
Thank you this work perfectly. I wanted to test if I could embed it in the `DualAveragingStepSizeAdaptation` wrapper. The convergence of the step size to the target depends on the relative difference between the `low` and `high` parameters, but in most of the cases it does converge. The final `log_accept_ratio` is then slightly superior to the target, as expected.
