### ISSUE TITLE
Proposing to reparameterize the Von Mises-Fisher distribution

### ISSUE THREAD

**Issue by nicola-decao** [tensorflow/probability#140]
Hello,

I am an author of [Hyperspherical Variational Auto-Encoders](https://arxiv.org/abs/1804.00891) where we proposed to reparameterize the Von Mises-Fisher distribution and sample from it. The implementation is in Tensorflow and available [here](https://github.com/nicola-decao/s-vae-tf).

I am opening this issues to propose to make the current Von Mises-Fisher distribution more numerically stable (current implementation works for dimensions <= 5) and reparameterizable.

I would like to be in touch with you and personally work on this.

Best,
Nicola

**Comment by brianwa84** [comment]
I'd love to see changes for better numerical stability!
I put up that first version since something is better than nothing (and the sampler works for arbitrary dims).

The obvious next thing needed (to me) was ive, which (for scipy) is a complicated legacy mess of fortran code. I have tried a TF port of cephes iv, but this seemed insufficiently precise.

Bottom line, we are happy to review your PRs and/or think through a process for getting things checked in.

**Comment by srvasude** [comment]
+1 to Brian. We'd be happy to accept PRs for this / keep in touch about this issue.

**Comment by brianwa84** [comment]
It has not (yet). Feel free to send a PR.

**Comment by mplanaslasa** [comment]
Hi @nicola-decao, do you know if anyone made progress on this issue?

**Comment by nicola-decao** [comment]
> Hi @nicola-decao, do you know if anyone made progress on this issue?

I am not aware of that.

**Comment by mplanaslasa** [comment]
> > Hi @nicola-decao, do you know if anyone made progress on this issue?
> 
> I am not aware of that.

Thanks for your answer. I have not found any publication focusing on this "problem".

**Comment by tgy** [comment]
@nicola-decao do you plan on opening a PR? It would be nice to be able to have high dimensional Von Mises-Fisher distributions (`n <= 5` is a huge limitation).

**Comment by nicola-decao** [comment]
I am. However, the impementation here is quite different than mine. 

Like `b` is not the one of Wood'94.
https://github.com/tensorflow/probability/blob/e7aee58d83505fe210520582b98069424961557d/tensorflow_probability/python/distributions/von_mises_fisher.py#L408
So also `x`: https://github.com/tensorflow/probability/blob/e7aee58d83505fe210520582b98069424961557d/tensorflow_probability/python/distributions/von_mises_fisher.py#L412
and `c` https://github.com/tensorflow/probability/blob/e7aee58d83505fe210520582b98069424961557d/tensorflow_probability/python/distributions/von_mises_fisher.py#L413
I need to work how this maps to my implementation to apply the same taylor expansion.

**Comment by arcrank** [comment]
Hi @nicola-decao , would there be any updates on this.  Having dim < 5 for vMF is not very useful.  Given the boom in representation learning I would think that there should be more support for getting this into tf.

**Comment by brianwa84** [comment]
It's been some time, but I thought I had worked out an equivalence between wood'94 and the set of equations used in here, but settled on these for numerics or some other reason.
If you wanted to send a PR to change the impl, I have no objections.
BTW we have a change coming imminently that drops the dim>5 restriction, now that bessels are implemented by @srvasude .

**Comment by nicola-decao** [comment]
> It's been some time, but I thought I had worked out an equivalence between wood'94 and the set of equations used in here, but settled on these for numerics or some other reason.
> If you wanted to send a PR to change the impl, I have no objections.
> BTW we have a change coming imminently that drops the dim>5 restriction, now that bessels are implemented by @srvasude .

That would be nice to have! But as you said maybe is useless if bessels are re-implemented.
