### ISSUE TITLE
Joint model with `tfd.Deterministic` and default bijector

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/probability#1403]
Hi all,

According to the [code](https://github.com/tensorflow/probability/blob/9e50fa39f37216dd084c24aa3dd14ab0d4dee926/tensorflow_probability/python/distributions/deterministic.py#L167), `tfd.Deterministic.experimental_default_event_space_bijector` maps to a zero-dimension Null tensor, which is presumably so that we can call `log_prob` and return a sensible value.  That said, I was expecting
```
import tensorflow_probability as tfp

X = tfp.distributions.Deterministic(1.0)
Y = X.experimental_default_event_space_bijector()(X)
Y.event_shape
```
to return `()`.  Instead, I get `IndexError: list index out of range`.

[Colab here](https://colab.research.google.com/drive/1_fVJlnjCveZbHPK0fzpAWrHjV8RnaZLV?usp=sharing)

**Comment by csuter** [comment]
The event space bijector maps from unconstrained space to constrained
space. I think you'd need to use Invert in your example for it to work.

**Comment by chrism0dwk** [comment]
Oh yeah, like this:
```
Y = tfp.bijectors.Invert(X.experimental_default_event_space_bijector())(X)
```
got it!   It's a subtle distinction cf `X.experimental_default_event_space_bijector().inverse(X)` which definitely doesn't work :)

Thanks @csuter !
