### ISSUE TITLE
[bug] Import failure in Bazel build (sts.internal import issues)

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/probability#141]
Hello,

I am building TFP from the Github repo with Bazel, and I'm getting an import error for the `sts` part.

What's weird is that the PyPI version also has the `sts` stuff but it installs and imports successfully (and it has an `__init__.py` file in `sts/internal`) whereas the Bazel build is failing to import. 

## Build command:
```
 cd /opt && git clone https://github.com/tensorflow/probability.git && \
	cd /opt/probability && \
    echo "" >> /opt/probability/tensorflow_probability/python/sts/internal/__init__.py && \
	bazel build \
    --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
    --copt=-mavx --copt=-msse2 --copt=-msse3 --copt=-msse4.1 --copt=-msse4.2 \
    --copt=-O3 --copt=-mfpmath=both \
    --copt="-DMKL_LP64" \
    --copt="-fPIC" \
    --linkopt="-lmkl_gf_lp64" \
    --linkopt="-lmkl_gnu_thread" \
    --linkopt="-dl" \
    --linkopt="-lpthread" \
    --linkopt="-lmkl_core" \
    --linkopt="-lm" \
    --linkopt="-lmkl_rt" \
    --linkopt="-lmkldnn" \
    :pip_pkg && \
	PKGDIR=$(mktemp -d) && \
	./bazel-bin/pip_pkg $PKGDIR && \
	pip install --no-deps $PKGDIR/*.whl && \
	cd /opt && rm -rf /opt/probability /tmp/* && \
    python -c "import tensorflow_probability"

```

## Error trace (when I try to import tensorflow_probability):
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 31, in <module>
    from tensorflow_probability.python import sts
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/sts/__init__.py", line 21, in <module>
    from tensorflow_probability.python.sts.local_linear_trend import LocalLinearTrend
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/sts/local_linear_trend.py", line 27, in <module>
    from tensorflow_probability.python.sts.internal import util as sts_util
ModuleNotFoundError: No module named 'tensorflow_probability.python.sts.internal'
```

**Comment by csuter** [comment]
Hi @sadatnfs, thanks for raising this. I believe this is a bug on our side. The reason the published pip package works is because (IIUC) until a few versions ago, bazel did some magic to generate the missing __init__ files. You're probably using a newer version that doesn't do this, whereas our pip package is built on some internal CI infra that happens to use a bazel binary that's a bit out of date. 

In the meantime, I believe the workaround will be to add a BUILD rule referencing the init file you're generating in the above snippet. This will ensure it's actually included in the pip package you're building.

Thanks for raising this; we'll fix it shortly. Stay tuned!

**Comment by sadatnfs** [comment]
Ah perfect, thanks @csuter ! Good to know that it's under you guys' radar! I tried to hack things by adding an empty **init** inside `sts/internal` but I don't know enough about bazel and so I didn't know that the BUILD rule was necessary.

I'll wait for you guys to push the latest fix, and then I'll restart my Jenkins build! Thanks!!

**Comment by csuter** [comment]
@sadatnfs I believe my last commit fixes this. I haven't tested building the package with newer bazel yet; if you get to it before me, let us know if you're unblocked. Thanks again for raising this!

**Comment by sadatnfs** [comment]
@csuter I can confirm that TFP builds and imports successfully now! Thanks SO much for the quick fix!!

**Comment by csuter** [comment]
Great! Thanks for confirming.

**Comment by sadatnfs** [comment]
Out of curiosity, are you guys considering maybe adding Travis support to the TFP repo? It would be nice to catch simple import errors right upon a commit-push.
