### ISSUE TITLE
Chain-parallel, graph-mode No U-Turn Sampler

### ISSUE THREAD

**Issue by axch** [tensorflow/probability#142]
The No U-Turn Sampler implementation in `experimental/` only works in Eager mode, and only runs one chain at a time.  As alluded to in https://github.com/tensorflow/probability/issues/8#issuecomment-387255619, this can be done.  However, the projected solution amounts to a multi-stage compiler from Python abstract syntax to TF graphs, and as such is considerable work.  This issue serves as a marker that this approach is being worked on internally.

**Comment by Joshuaalbert** [comment]
@axch Have you read the [source](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/seq2seq/python/ops/decoder.py#L163) for dynamic_decode? They dynamically decode different batch elements to different lengths with user defined termination conditions. I'd be able to help if desired.

**Comment by axch** [comment]
No, I haven't.  Thanks for the pointer!

**Comment by axch** [comment]
We now have an implementation checked in to tfp.experimental.mcmc.nuts.  The plan is to massage the API to look more like the HMC API, and promote it to tfp.mcmc.nuts, but it's available now.  Caveat: the performance characteristics may be, shall we say, surprising.

**Comment by Joshuaalbert** [comment]
In a good or bad way???

**Comment by adam-erickson** [comment]
@Joshuaalbert Are caveats or surprises ever good when it comes to code? ;) I would expect it to be much slower than STAN, as the Pyro implementation is reported to be.

**Comment by axch** [comment]
The full performance profile is pretty interesting, but the basic story (as of this writing) is that it scales up pretty well but down pretty badly.  In internal testing, we've seen going from 1 to 1,000 parallel chains take basically no extra time on a GPU; but where that breaks even vs Stan depends on the size of the problem.  Once you get to, say, 10,000 data points and 100 latent dimensions, I'm comfortable recommending this method over Stan, but we are still working on a precise and fair comparison.

**Comment by axch** [comment]
To be clear, here I'm talking about gradient evaluations per second, which is the rate at which the algorithm extracts information from the model.  Presumably nuts has a further advantage in how it uses those gradients, but we haven't carefully compared, e.g., effective samples per second yet.

**Comment by janosh** [comment]
@axch I'm particularly interested in the performance for very high-dimensionality (10^3 - 10^4) but relatively few data points (around 10^3). Did you take a look at that during testing by any chance?

Also, is there a reason to keep this in `experimental`? Seems like people could benefit if it's known to work well for complex problems. You could just add a disclaimer for the time being to prefer the `SimpleStepSizeAdaption` or `DualAveragingStepSizeAdaptation` over TFP's NUT sampler unless the dimensionality and data points exceed certain thresholds.

**Comment by axch** [comment]
@janosh We now have a no-u-turn sampler in tfp.mcmc.nuts, based on a different architecture, with more reasonable performance.  I haven't tested it on high-D low-N per se, but I encourage you to try it.

**Comment by janosh** [comment]
@axch Very cool! Just ran a bunch of tests and seems to work well. I'm using HMC to train BNNs. Training time with NUTS dropped anywhere from 10 to 55 % as compared to `SimpleStepSizeAdaptation` while test set performance remained the same or improved very slightly.

Do you know when the NUTS sampler will be added to the docs?

**Comment by axch** [comment]
IIRC, the docs are regenerated once per release.  Our release cadence follows TensorFlow, so whenever TF releases 2.0.  In the meantime, you can at least read the docstring :)

**Comment by davmre** [comment]
@janosh : glad NUTS is working for you! Just to make sure we're on the same page, `SimpleStepSizeAdaptation` and NUTS are mostly doing different things: NUTS automatically tunes the number of leapfrog steps, while step size adaptation tunes the size of those steps. In principle, you want both. (though I think there are still some technical issues in combining NUTS with our step size adaptation wrappers, so you might be stuck setting step sizes by hand for the moment).

**Comment by janosh** [comment]
Yeah, it was a little bit of a hassle to run experiments with NUTS multiple times to find a decent step size.

**Comment by junpenglao** [comment]
> (though I think there are still some technical issues in combining NUTS with our step size adaptation wrappers, so you might be stuck setting step sizes by hand for the moment)

NUTS is fully compatible with our stepsizeadaptation routine, however, you will need to specify the function to fetch the parameters from previous kernel result, see https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/mcmc/nuts_test.py#L395-L399 for an example.

The stepsizeadaptation in general, however, seems to have some problem right now as it can go negative (especially when your chain is stuck). The dualaverging in particular would likely need to set the scaling parameter as a function of number of chain, as our tuning works cross chain and very different from how it usually work in other package.

**Comment by janosh** [comment]
Ah, that might explain something. I was having trouble with `DualAveragingStepSizeAdaptation` in particular. It kept throwing the error
> TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type float64 of argument 'x'.

in the line

```py
retval_ = graph_hmc_scope.mark_return_value(ag__.converted_call(tfp.mcmc.sample_chain, graph_hmc_scope.callopts, () + tuple(args), dict(kwargs, **{}), graph_hmc_scope))
```

The only thing I could find in `locals` that had `dtype` `float64` was `prev_kernel_results.target_accept_prob`. Could this be related to having to set the scaling parameter as a function of the number of chains?

**Comment by junpenglao** [comment]
Hmm, that sounds like a bug in DualAveragingStepSizeAdaptation - could you open a bug with an example?

**Comment by janosh** [comment]
@junpenglao Sure thing. I opened #543.
