### ISSUE TITLE
tfp.bijectors.Softfloor properties documentation 

### ISSUE THREAD

**Issue by Kornel** [tensorflow/probability#1425]
The Softfloor [documentation for v0.13.0](https://github.com/tensorflow/probability/blob/v0.13.0/tensorflow_probability/python/bijectors/softfloor.py#L48-L51) states that 

>   This `Bijector` has the following properties:
>     * This `Bijector` is a map between `R` to `R`.
>     * For `t` close to `0`, this bijector mimics the identity function.
>     * For `t` approaching `infinity`, this bijector converges pointwise to `tf.math.floor` (except at integer points).

I'm not sure the 2nd and 3rd points are correct.

I believe it's the other way round: for `t->0` the bijector converges to `tf.math.floor`, and for `t->inf` this bijector mimics not quite the identity, but `f(x) = (x - 0.5)` (see [also here](https://www.wolframalpha.com/input/?i=lim+%281+%2F+%28sigmoid%280.5+%2F+t%29+-+sigmoid%28-0.5+%2F+t%29%29%29+*+sigmoid%28%28%28x-1%29%2Ft%29%29+%2B+%28-sigmoid%28-0.5+%2F+t%29+%2F+%28sigmoid%280.5+%2F+t%29+-+sigmoid%28-0.5+%2F+t%29%29%29+as+t+-%3E+infinity))

I'm happy to create a PR to fix these.

**Comment by csuter** [comment]
I think you're right. The behavior matches the terminology (higher temperature should increase smoothness), but the documentation is reversed. A PR to update the verbiage would be weclome. Thanks!

**Comment by srvasude** [comment]
Fixed by https://github.com/tensorflow/probability/commit/913085acf56c19436ed59f863eb2985d973d90a5
