### ISSUE TITLE
MCMC sample variance estimate

### ISSUE THREAD

**Issue by xiaolongluo1979** [tensorflow/probability#1426]
Can someone recommend any relevant method or example for estimating MCMC samples variance? It appears one could get a reasonable estimate from the MCMC samples and the asymptotic formula (see e.g. Page 132 ttps://www.stat.umn.edu/geyer/f05/8931/n1998.pdf ). I wonder if there is any implementation for similar MCMC samples variance in TFP. Thanks.

**Comment by SiegeLordEx** [comment]
The variance of the sample mean can be computed via the effective sample size quantity:

```
sigma_2 = tf.math.reduce_variance(chain, axis=[0, 1]) / tfp.mcmc.effective_sample_size(chain, cross_chain_dims=1)
```

This assumes that `chain` is an array with shape `[num_iterates, num_chains, ...]`

**Comment by xiaolongluo1979** [comment]
@SiegeLordEx Thanks! This is very helpful!
