### ISSUE TITLE
MixtureSameFamily sample() truncating positive results

### ISSUE THREAD

**Issue by lawortsmann** [tensorflow/probability#1467]
When sampling from a MixtureSameFamily distribution all of the samples are less than or equal to 0, seems like something is truncating or clipping samples greater than 0 and setting them equal to 0. Wondering if anyone else has ran into this issue? Or if its just an issue stemming from my environment...

```python
# the example from the MixtureSameFamily docstring
gm = tfd.MixtureSameFamily(
    mixture_distribution=tfd.Categorical(
        probs=[0.3, 0.7]),
    components_distribution=tfd.Normal(
      loc=[-1., 1],       # One for each component.
      scale=[0.1, 0.5]))  # And same here.

assert np.all(gm.sample(1000).numpy() <= 0)
```

Some additional info:
- numpy version: 1.19.5
- tensorflow version: 2.6.0
- tensorflow-probability version: 0.14.1
- macOS 12.1 (beta) on M1 chip
- tensorflow installed using [these instructions](https://developer.apple.com/metal/tensorflow-plugin/) and otherwise seems to be working fine

**Comment by csuter** [comment]
I'm not seeing this behavior. Is there some additional context we're
missing? Can you share a colab notebook or something reproducing it?

**Comment by lawortsmann** [comment]
Upon further investigation it seems to be stemming from an issue with `tf.reduce_sum`, can't replicate on a colab notebook so it must just be something weird with my environment. Apologies! will close the issue.
