### ISSUE TITLE
LinearGaussianStateSpaceModel has two different output types depending on the filtering method

### ISSUE THREAD

**Issue by lofriedman** [tensorflow/probability#1471]
Hello all, I noticed that the distribution was returning a `FilterResults` namedtuple if the experimental parallel Kalman filter is used and a regular tuple if we filter sequentially. I think a uniform return type would be great to be able to invoke the keys in the namedtuple object. 

The line is here:

`https://github.com/tensorflow/probability/blob/v0.15.0/tensorflow_probability/python/distributions/linear_gaussian_ssm.py#L1033`

Happy to help if needed :)

**Comment by davmre** [comment]
Thanks for pointing this out! https://github.com/tensorflow/probability/commit/f5541be80d2e118a3875ec795285927f5580465a should fix this in `tfp-nightly` and future releases.
