### ISSUE TITLE
Installed Tf and TFP on M1 Max with no problem through Conda as suggested in apple  however when running get errorImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.8; Detected an installation of version 2.7.0. Please upgrade TensorFlow to proceed. tf 2.7 and TFP 0.15

### ISSUE THREAD

**Issue by fbarfi** [tensorflow/probability#1479]

**Comment by jburnim** [comment]
The error:
> This version of TensorFlow Probability requires TensorFlow version >= 2.8; Detected an installation of version 2.7.0. Please upgrade TensorFlow to proceed

Indicates you are using a development/nightly version of TFP, not TFP 0.15.  This may be an issue in the particular conda package you are using.  The development/nightly version of TFP depends on tf-nightly (instead of the latest stable release of TensorFlow).

**Comment by fbarfi** [comment]
Thank you much for your response. The issue has been solved for some time now.


Badredine




From: Jacob Burnim ***@***.***>
Reply-To: tensorflow/probability ***@***.***>
Date: Friday, January 7, 2022 at 12:54 PM
To: tensorflow/probability ***@***.***>
Cc: Badredine Arfi ***@***.***>, Author ***@***.***>
Subject: Re: [tensorflow/probability] Installed Tf and TFP on M1 Max with no problem through Conda as suggested in apple however when running get errorImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.8; Detected an installat...

[External Email]

The error:

This version of TensorFlow Probability requires TensorFlow version >= 2.8; Detected an installation of version 2.7.0. Please upgrade TensorFlow to proceed

Indicates you are using a development/nightly version of TFP, not TFP 0.15. This may be an issue in the particular conda package you are using. The development/nightly version of TFP depends on tf-nightly (instead of the latest stable release of TensorFlow).

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tensorflow_probability_issues_1479-23issuecomment-2D1007609467&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=1XpXvO1g5MsaYxUCK4mC2A&m=XFlty5rfSrpDNtL-GjmeEnxJlAqHjdK5w3Ja8tdYfHRr51Zmb7zzLTWs12VZ3dzb&s=XupbAtx98VXW2UKvxyypYYL23Ptulnl04bnjMuzuMTo&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ARUHUPU7RCE3HPHY5LL5GXTUU4SERANCNFSM5KHUIULQ&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=1XpXvO1g5MsaYxUCK4mC2A&m=XFlty5rfSrpDNtL-GjmeEnxJlAqHjdK5w3Ja8tdYfHRr51Zmb7zzLTWs12VZ3dzb&s=cJty_LUvM63DsYR9-JGWEgLwiN3qBO12oq9JiwWjEMI&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=1XpXvO1g5MsaYxUCK4mC2A&m=XFlty5rfSrpDNtL-GjmeEnxJlAqHjdK5w3Ja8tdYfHRr51Zmb7zzLTWs12VZ3dzb&s=6Xo8PF-h6plCOWrNzaJ6B-dhMwqXAh_MRgOCKKfjEo8&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=1XpXvO1g5MsaYxUCK4mC2A&m=XFlty5rfSrpDNtL-GjmeEnxJlAqHjdK5w3Ja8tdYfHRr51Zmb7zzLTWs12VZ3dzb&s=9h2aA57RJv8l7DTy98wLV1_rfu1ZpzLZaEwzE3DmQ0Q&e=>.
