### ISSUE TITLE
    AttributeError: module 'tensorflow_probability.python.bijectors' has no attribute 'AffineScalar'

### ISSUE THREAD

**Issue by Diogenes4Sinope** [tensorflow/probability#1485]
Please can anyone let me know why the following code:

    import matplotlib.pyplot as plt
    import numpy as np
    import tensorflow_probability as tfp
    tfd = tfp.distributions
    tfb = tfp.bijectors
    from tensorflow.keras.models import Model
    from tensorflow.keras.layers import Dense
    print("TFP Version", tfp.__version__)
    print("TF  Version",tf.__version__)

    bits = 4
    logi = tfd.Logistic(loc=1, scale=0.25)
    logis = tfd.TransformedDistribution(distribution=tfd.Logistic(loc=1, scale=0.25),
                                    bijector=tfb.AffineScalar(shift=-0.5))
    discretized_logistic_dist = tfd.QuantizedDistribution(logis,low=0.,high=2**bits - 1.)
    vals = np.linspace(-10,10,1000) 
    plt.figure(figsize=(14,5))
    plt.subplot(1,2,1)
    plt.plot(vals, logi.prob(vals)) 
    plt.plot(vals, logis.prob(vals)) 
    #plt.plot(vals, discretized_logistic_dist.prob(vals)) 
    plt.stem(n_vals, discretized_logistic_dist.prob(n_vals), use_line_collection=True, markerfmt='C1o',linefmt='C1-.') 
    plt.legend(['Inner distribution','Shifted','Quantized version'], loc='upper right')
    plt.xlabel('x',fontsize=14)
    plt.ylabel('probability density function',fontsize=14)
    plt.subplot(1,2,2)
    plt.plot(vals, logi.cdf(vals)) 
    plt.plot(vals, logis.cdf(vals)) 
    plt.plot(vals, discretized_logistic_dist.cdf(vals)) 
    plt.legend(['Inner distribution','Shifted','Quantized version'], loc='lower right')
    plt.xlabel('x',fontsize=14)
    plt.ylabel('cumulative probability density function',fontsize=14)

gives the following error:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-12-06a719a78b92> in <module>()
    3 logi = tfd.Logistic(loc=1, scale=0.25)
    4 logis = tfd.TransformedDistribution(distribution=tfd.Logistic(loc=1, scale=0.25),
    ----> 5                                     bijector=tfb.AffineScalar(shift=-0.5))
    6 discretized_logistic_dist = tfd.QuantizedDistribution(logis,low=0.,high=2**bits - 1.)
    7 

    AttributeError: module 'tensorflow_probability.python.bijectors' has no attribute 'AffineScalar'

Any help will be greatly appreciated, thank you.

**Comment by europeanplaice** [comment]
Because `tfb.AffineScalar` is deprecated, you should use `tfb.Shift`.
```python
logis = tfd.TransformedDistribution(distribution=tfd.Logistic(loc=1, scale=0.25),
                                bijector=tfb.Shift(-0.5))
```

Please refer to https://github.com/tensorflow/probability/issues/839 .

**Comment by jburnim** [comment]
`tfb.AffineScalar` was removed in https://github.com/tensorflow/probability/commit/6ec52add318134875584108314e844163bc07f84 .

**Comment by Diogenes4Sinope** [comment]
@europeanplaice @jburnim Thanks. I will check it out.
