### ISSUE TITLE
Python 3.10 breaks collections.Sequence

### ISSUE THREAD

**Issue by alex-dixon** [tensorflow/probability#1488]
Sequence to have been moved to collections.abc in Python 3.10. This appears to be a breaking change.

Causes an error on this line:
https://github.com/tensorflow/probability/blob/bcdf53024ef9f35d81be063093ccfb3a762dab3f/tensorflow_probability/python/layers/distribution_layer.py#L167

I wasn't able to find a fix in userland so will probably need to downgrade to 3.9. :(

**Comment by SiegeLordEx** [comment]
You can replace it with `collections.abc.Sequence`. We'll fix it eventually (or you can send a pull request).

**Comment by jburnim** [comment]
Fixed by https://github.com/tensorflow/probability/commit/76ff71ba27a5a035fa6220e6132744ac89a56fdf .

With Python 3.10 and tfp-nightly==0.16.0.dev20220107, I no longer see this error when using `DistributionLambda`.

Thanks for the bug report!
