### ISSUE TITLE
Good first issue 

### ISSUE THREAD

**Issue by Rishabhbahuguna03** [tensorflow/probability#1493]
Hey I'm new to this good first issue. 
How can I get started ?

**Comment by kanishchugh** [comment]
HI Rishabh,
good first issues usually have a tag which you can search in the labels section and github also provides you with the option to select good first issues where you can select the issues where you want to contribute.

**Comment by ColCarroll** [comment]
It looks like there are some tagged (though this is a good reminder for us to tag more!) [Here's a link](https://github.com/tensorflow/probability/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
