### ISSUE TITLE
Implementation of LogGamma Distribution 

### ISSUE THREAD

**Issue by claCase** [tensorflow/probability#1502]
I would like to implement the LogGamma distribution. However from the test i've made there seem to be something wrong with the implementation. Is it just a visualization issue or is it something more foundamental? <br/> 
Following [this article](https://www.vosesoftware.com/riskwiki/LogGammadistribution.php), the exp of the samples from the Gamma random variable are distributed as a LogGamma random variable following the equation: <br/>
x ~ Gamma(alpha, beta) <br/>
y = exp(x) + (l-1) ~ LogGamma(alpha, beta,  l) <br/>
where l is a translation parameter such that the samples must be y>l.  It follows that samples distributed as a LogGamma(alpha, beta, l) can be transformed into a Gamma(alpha, beta) by the following transformation: <br/> 
y ~ LogGamma(alpha, beta, l) <br/> 
x = log( y - l + 1) ~ Gamma(alpha, beta) <br/> 
I've implemented the distribution as follows: <br/> 
```python
import tensorflow as tf
from tensorflow_probability import distributions as tfd
import matplotlib.pyplot as plt
import numpy as np

class LogGamma(tfd.Distribution):
    def __init__(self, alpha, beta, l=0.0, dtype=tf.float32):
        super(LogGamma, self).__init__(
            dtype=dtype,
            reparameterization_type=tfd.NOT_REPARAMETERIZED,
            validate_args=False,
            allow_nan_stats=False,
            parameters={"alpha": alpha, "beta": beta, "l": l},
        )
        self.l = l
        self.gamma = tfd.Gamma(alpha, beta)

    def _sample_n(self, n, seed):
        x = self.gamma.sample(n, seed=seed)
        y = tf.math.exp(x) + self.l - 1
        return y

    def _prob(self, x):
        x = tf.math.log(x - self.l + 1)
        return self.gamma.prob(x)

```
and made different tests: 
```python
plt.figure()
lg = LogGamma(1,20, 5)
samples = lg.sample(10000)
probs = lg.prob(samples)
probs = probs.numpy().flatten()
samples = samples.numpy().flatten()
plt.hist(samples, bins=100, density=True)
plt.scatter(samples, probs, s=1, color="orange", label="Alpha=1, Beta=20, l=5")
plt.legend()
```
and got the following figures: <br/>
![log_gamma_1_20_5](https://user-images.githubusercontent.com/36463823/150023320-37c2da72-4b09-4626-9947-c0ada052b089.png)
![log_gamma_20_20_5](https://user-images.githubusercontent.com/36463823/150023329-8becfde2-8e32-4655-ba54-a971c3d7a1bd.png)

As you can see in the second plot, with alpha being a high value, the pdf doesn't follow the frequency distribution. The first appears to be correct. Am i missing something?

**Comment by brianwa84** [comment]
Maybe you haven't accounted for the change of variables log-abs-det
correction?

You might compare against tfp.bijectors.Shift(l -
1)(tfp.bijectors.Log()(tfp.distributions.Gamma(alpha, beta)))

Also, for numerics, log(.. + 1) = log1p(..)

And you might prefer to implement log_prob instead of prob, again for
numerics.


Brian Patton | Software Engineer | ***@***.***

**Comment by csuter** [comment]
I think you want an exp bijector there

**Comment by claCase** [comment]
@brianwa84  Thank you so much for the quick response. Yes the change of variable correction was definitely the issue. <br/>
@csuter Thank you. Yes I was about to point that out as well. Here is the corrected implementation: 
```python
tfp.bijectors.Shift(l - 1)(tfp.bijectors.Exp()(tfp.distributions.Gamma(alpha, beta)))
```
