### ISSUE TITLE
TFP Matplotlib histogram on sample from 1d distribution

### ISSUE THREAD

**Issue by nipunbatra** [tensorflow/probability#1509]
Hi, I created some N samples from 1d distribution. The Matplotlib histogram called on `samples` does not work correctly but the histogram on `samples.numpy()` works as expected. This could be the expected behaviour and maybe it is best to use `.numpy()`.  I just wanted to check. The fact that `plt.plot(samples)` and `plt.plot(samples.numpy())` work identical perhaps caused this confusion.

MWE below to illustrate. 

```python
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import functools
import seaborn as sns
import tensorflow_probability as tfp
import pandas as pd

tfd = tfp.distributions


sns.reset_defaults()
sns.set_context(context="talk", font_scale=1)
%matplotlib inline
%config InlineBackend.figure_format='retina'
```

```python
dist = tfd.Normal(loc=0., scale=1.)
```

```python
samples = dist.sample(100)
print(samples.shape, samples.numpy().shape)
```

    (100,) (100,)

```python
# Works
plt.hist(samples.numpy())
```

    (array([ 6., 11., 13., 14., 21., 18., 10.,  4.,  2.,  1.]),
     array([-2.0196772 , -1.5321746 , -1.0446719 , -0.5571693 , -0.06966667,
             0.41783595,  0.9053386 ,  1.3928412 ,  1.8803438 ,  2.3678465 ,
             2.855349  ], dtype=float32),
     <BarContainer object of 10 artists>)

<img width="383" alt="output_3_1" src="https://user-images.githubusercontent.com/60985/152733283-72b5970f-9672-4789-b594-487ceda64261.png">

```python
# Works incorrectly
plt.hist(samples)
```

     array([-2.0196772 , -1.5321746 , -1.0446719 , -0.5571693 , -0.06966667,
             0.41783595,  0.9053386 ,  1.3928412 ,  1.8803438 ,  2.3678465 ,
             2.855349  ], dtype=float32),
     <a list of 100 BarContainer objects>)

<img width="390" alt="output_4_1" src="https://user-images.githubusercontent.com/60985/152733312-ea8bdd7e-4897-44c6-ae83-76e4894cfa17.png">

```python
# Both work here
plt.plot(samples, lw=2, alpha=0.6, label='TF Tensor')
plt.plot(samples.numpy(), linestyle='--', lw=2, label='Numpy')
plt.legend()
```

    <matplotlib.legend.Legend at 0x1e756bd00>

<img width="390" alt="output_5_1" src="https://user-images.githubusercontent.com/60985/152733342-01104d8c-1dd1-40a5-ac07-fe7864f82375.png">

**Comment by ColCarroll** [comment]
Hey! Can you check the versions of the libraries you're using, particularly (I'm guessing!) matplotlib? It looks like there is an active (and welcoming!) discussion over at https://github.com/matplotlib/matplotlib/issues/19574 , but running your MWE in colab today (with `tensorflow==2.7.0`, `matplotlib==3.2.2`, and `tensorflow-probability==0.15.0`), I get histograms just fine!

I poked around a little to see who fixed this, since it was an annoyance, but didn't find it quickly -- would welcome anyone who can point to the PR that took care of this!
