### ISSUE TITLE
KL between two Continuous Bernoulli distributions is sometimes negative

### ISSUE THREAD

**Issue by vsimkus** [tensorflow/probability#1511]
The KL divergence between two Continuous Bernoulli distributions returns negative values for some parameter settings. However, the KL should always be non-negative. This would then cause issues during optimisation in e.g. variational inference.

Here's a minimal example:

```python
import tensorflow_probability as tfp

q = tfp.distributions.continuous_bernoulli.ContinuousBernoulli(logits=-0.1343)
p = tfp.distributions.continuous_bernoulli.ContinuousBernoulli(logits=-0.0340)
tfp.distributions.continuous_bernoulli._kl_bernoulli_bernoulli(q, p)
# <tf.Tensor: shape=(), dtype=float32, numpy=-0.00083708763>
```

**Comment by ColCarroll** [comment]
thank you! i'll watch for the CLA, then get to reviewing!
