### ISSUE TITLE
[BUG] batch_interp_regular_nd_grid broken with unknown sample shape (tfp>=0.14)

### ISSUE THREAD

**Issue by jonas-eschle** [tensorflow/probability#1516]
When the sample shape of `x` (the values that we want to interpolate to) is unknown (e.g. (None, 1), the whole shape is rendered unknown and the function fails. This used to work in TensorFlow<2.7 and TFP < 0.14 (correspondingly)

Tracking the issue down, it seems that the shape information is lost here: https://github.com/tensorflow/probability/blob/main/tensorflow_probability/python/math/interpolation.py#L653

But I am not fully sure, why.

Example to reproduce (colab notebook: https://colab.research.google.com/drive/14F-HqpiGZ9OW6Lu3nPBizIx7wF_VIUcU?usp=sharing) :
```
import tensorflow as tf
import tensorflow_probability as tfp

y_ref = tf.exp(tf.linspace(start=0., stop=10., num=20))

x = tf.random.uniform(shape=[300, 1], minval=0.0, maxval=10.0)


@tf.function
def func(x, y_ref):
    x = x[x[:, 0] > 0.1]  # make the shape unknown -> [None, 1]
    print(x.shape)
    return tfp.math.batch_interp_regular_nd_grid(
        x=x, x_ref_min=[0.], x_ref_max=[10.], y_ref=y_ref,
        axis=0)


func(x, y_ref)
```

**Comment by SiegeLordEx** [comment]
We have an internal fix for this in progress, it's a bit of a doozy. Thanks for reporting this.

**Comment by jonas-eschle** [comment]
Glad that you managed to fix it already! Is that to be expected for 0.16?

**Comment by SiegeLordEx** [comment]
Probably. It'll also show up in the nightly packages today or tomorrow (https://pypi.org/project/tfp-nightly/)

**Comment by jonas-eschle** [comment]
Great, many thanks!

**Comment by csuter** [comment]
I think 0.16 has already been cut and (mostly?) released, FYI
