### ISSUE TITLE
How to disable warnings

### ISSUE THREAD

**Issue by pipme** [tensorflow/probability#1523]
When running the following code, a bunch of warning messages **WARNING:root:The use of `check_types` is deprecated and does not have any effect.** are raised. How to disable this behaviour? `warnings.filterwarnings("ignore")` doesn't work. My tfp verison is 0.15.0.
```python
import tensorflow_probability.substrates.jax.distributions as tfd
import jax.numpy as jnp

L = jnp.ones((2,2))
rv = tfd.MultivariateNormalTriL(0, L)
```

**Comment by AlexanderGri** [comment]
I have the same issue, didn't manage to fix

**Comment by hriebl** [comment]
The warning comes from [dm-tree](https://github.com/deepmind/tree) and could probably be fixed by uncommenting line 195 in 7acdfb510a928214c768be49a4de95f153a80a1b. Meanwhile, here is a workaround that disables the warning:

``` python
import logging

import tensorflow_probability.substrates.numpy as tfp

# this prints a WARNING

tfp.distributions.TransformedDistribution(
    tfp.distributions.Normal(0.0, 1.0), tfp.bijectors.Identity()
)

logger = logging.getLogger("root")


class CheckTypesFilter(logging.Filter):
    def filter(self, record):
        return "check_types" not in record.getMessage()


logger.addFilter(CheckTypesFilter())

# this does not print a WARNING

tfp.distributions.TransformedDistribution(
    tfp.distributions.Normal(0.0, 1.0), tfp.bijectors.Identity()
)
```

**Comment by pipme** [comment]
Thx for pointing out the source and the workaround! @hriebl

**Comment by mvsoom** [comment]
For me, the solution required `logger = logging.getLogger()` instead of `logger = logging.getLogger("root")`.
