### ISSUE TITLE
STS Multivariate 

### ISSUE THREAD

**Issue by cscid01** [tensorflow/probability#1531]
Does STS support multivariate time series. Is there any way to include exogenous variables into the model ?

**Comment by junpenglao** [comment]
`tf.sts` does not support multivariate observation (but it support batches of single variate time series, which might work for most use case)
To include exogenous variables you can try one of the below: `tfp.sts.DynamicLinearRegression`, `tfp.sts. LinearRegression`, or `tfp.sts.SparseLinearRegression`,

**Comment by cscid01** [comment]
Thanks.
