### ISSUE TITLE
tfd.Independent: is this really the right name?

### ISSUE THREAD

**Issue by naji-s** [tensorflow/probability#1535]
I am trying to learn TFP from scratch, and have been very impressed by going through the particular helpful documentations on understanding the pillar concepts of shape semantics in probabilistic programming [here](https://ericmjl.github.io/blog/2019/5/29/reasoning-about-shapes-and-probability-distributions/) and [here](https://www.tensorflow.org/probability/examples/Understanding_TensorFlow_Distributions_Shapes).

And it was all good and nice, until I came to learn about `tfd.Indepedent` and I really cannot wrap my head around it. Let's consider an example:

```
d = tfd.Normal(loc=[0., 0., 0.], scale=[1., 1., .1])
``` 

should naturally turn ```d``` into a multivariate normal distribution. As such, calling 
```
s = d.sample()
d.log_prob(s)
```
should return the log-probability of observing `s` as an outcome of it being a sample of `d`.  Yet when running it this yields --at least to me-- this  unexpected result!
```
>>> from tensorflow_probability import distributions as tfd
>>> d = tfd.Normal(loc=[0., 0., 0.], scale=[1., 1., .1])
>>> s = d.sample()
>>> d.log_prob(s)
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-2.402578 , -1.4037428,  1.2033085], dtype=float32)>
```

In fact it seems I need to apply tfd.independent to make an instance from a 3d Gaussian distribution to be treated as really an instance instead of a batch. I am not able to understand why the default behavior of tfd.Normal should be to return a batch sample while its definition, i.e. its mean and covariance are passed in a form that they define a 3 dimensional Gaussian distribution. Can somebody please clarify if I am misunderstanding a concept or this is a feature rather than a bug, and with the right interpretation one can understand why tfd.Normal.sample should return  a batch sample from 3 distinct Normal distributions as opposed to a single sample from a 3d distribution?

**Comment by naji-s** [comment]
Thanks so much! I did not know about that at all.  But in any case I don't think that justifies the naming `tfd.Idependent`. Even based on your comment, a more proper name to me seems to be tfd.Joint, **so that the given a batch sample from a joint distribution,  it converts it back to a joint distribution out of batch probabilities.** Am I missing something here?

**Comment by csuter** [comment]
I think your intuition is probably right. I don't recall the discussion
that led to the name. If I had to guess it might have started with dropping
the middle I from "IID". But I'm just speculating on the history. Joint
would be accurate but perhaps over general. In the intervening years we've
added actual joint distribution support, where the constituent
distributions need not be independent or even of the same family. In any
case, renaming now would be tough 😊. Thanks for taking the time to learn
about TFP! Keep the good questions coming.

**Comment by naji-s** [comment]
Thanks for giving some historical remarks about the naming process. Granted dropping I from IID reminds me of what[ batch_shape is about](https://www.tensorflow.org/probability/examples/Understanding_TensorFlow_Distributions_Shapes#basics):
> "Batch shape describes independent, not identically distributed draws, aka a "batch" of distributions."

Anyway, thanks again for taking the time for explaining the details. However do you mind elaborating on this: " In the intervening years we've
added actual joint distribution support, where the constituent
distributions need not be independent or even of the same family." I am very unfamiliar with the joint distribution implementation you just mentioned. Do you mind pointing me in that direction please? Is it tfp.distributions.JointDistribution*?

P.S. For context I am specifically interested in implementing probabilistic logistic regression from scratch in a fully probabilistic setting; that is where I use multi-variate normal distribution for the  weight in the logistic function which itself is inside a Bernoulli function.

**Comment by csuter** [comment]
Thanks for the discussion; I'm going to close this as it is not particularly actionable.

**Comment by naji-s** [comment]
Hey @ColCarroll, just wanted to stop by and thanks for your useful references!
