### ISSUE TITLE
No module named 'tensorflow_probabilty'

### ISSUE THREAD

**Issue by Cipy0** [tensorflow/probability#1539]
Hello I am using google colab and wanted to import tensorflow_probability but I got this error.

`4 import tensorflow_probabilty as tfp

ModuleNotFoundError: No module named 'tensorflow_probabilty'
`
But tensorflow_probability is shown installed when using !pip list (tensorflow-probability        0.16.0)  so I don't understand the problem. I've tried solutions found online but none worked for me. Help is welcome thanks!

**Comment by csuter** [comment]
You have a typo in your import statement 😊
