### ISSUE TITLE
Convolution variational layers do not work with "channels_first"

### ISSUE THREAD

**Issue by jmzeng** [tensorflow/probability#154]
I'm having some trouble with using the data_format="channels_first" functionality for Conv2DFlip. The exact same network compiles with "channels_last", but fails when I switch to "channels_first" with the following error:

> ValueError: Dimensions must be equal, but are 26 and 32 for 'conv2d_flipout/mul_1' (op: 'Mul') with input shapes: [?,32,26,26], [?,?,?,32].

Please see the example below. This setup works in the deterministic case with Conv2D from keras. Is there something else I need to change for probabilistic layers? 

```
import tensorflow as tf
import tensorflow_probability as tfp

data_format = "channels_first"

num_classes = 10
img_rows, img_cols = 28, 28

if data_format == "channels_first":
    input_shape = [1, img_rows, img_cols]
    images = tf.placeholder(tf.float32, (None, 1, img_rows, img_cols))
else:
    input_shape = [img_rows, img_cols, 1]
    images = tf.placeholder(tf.float32, (None, img_rows, img_cols, 1))

model = tf.contrib.keras.models.Sequential()
model.add(tfp.layers.Convolution2DFlipout(32, kernel_size=(3, 3),
                                          activation='relu',
                                          data_format=data_format,
                                          input_shape=input_shape))
model.add(tfp.layers.Convolution2DFlipout(64, kernel_size=(3, 3),
                                          activation='relu',
                                          data_format=data_format))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tfp.layers.DenseFlipout(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

logits = model(images)
```

**Comment by srvasude** [comment]
@dustinvtran Adding Dustin

**Comment by dustinvtran** [comment]
Yeah I recommended @jmzeng raise an issue about this. The solution is not obvious to me from a glance.

**Comment by jcreinhold** [comment]
I am also running into this same issue with tfp v0.5.0. Is there any plan to make headway with this issue? At the very least, should there be a `NotImplementedError` raised if the user sets the `data_format` to `channels_first`?

**Comment by SiegeLordEx** [comment]
I'm working on a fix, should be in by the end of next week.
