### ISSUE TITLE
[TFP] Potential Joint Distribution Bug

### ISSUE THREAD

**Issue by robpmcadam** [tensorflow/probability#1544]
I think I've stumbled upon a bug with defining joint distributions inside a layer call. If I run this:
```
import tensorflow_probability as tfp
from tensorflow.keras import Model
from tensorflow.keras.layers import(
    Input,
    Layer
)
tfd = tfp.distributions

class JointDistLayer(Layer):
    def call(self, inputs):
        self.dist = tfd.JointDistributionNamedAutoBatched(
            {
                's_0': tfd.Logistic(0,1)}) 
        return self.dist.log_prob(self.dist.sample())
    
    
inp = Input(1)
h = JointDistLayer()(inp)
model = Model(inp, h)
model.compile()
```
I get this (rather cryptic) error when compiling the model:

```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: joint_dist_layer/Logistic/scale:0
```

This seems to be only a problem with `JointDistributions` _and_ the assignment of the distribution to the layer object. I.e., if you change `self.dist` -> `dist`, no problem—I can do all the computation I want. I can also just change `self.dist = tfd.JointDistributionNamedAutoBatched(...)` -> `self.dist = tfd.Logistic(...)`, and things are fine. Disabling eager execution also resolves the issue.

Using `tensorflow.2.6.0` and `tensorflow-probability.0.14.1`.

**Comment by csuter** [comment]
I can get the code to run by doing the assignment in `build` instead of `call`:

```
import tensorflow_probability as tfp
from tensorflow.keras import Model
from tensorflow.keras.layers import(
    Input,
    Layer
)
tfd = tfp.distributions

class JointDistLayer(Layer):
    def build(self, input):
        self.dist = tfd.JointDistributionNamedAutoBatched(
            {
                's_0': tfd.Logistic(0,1)}) 
    def call(self, inputs):
        return self.dist.log_prob(self.dist.sample())
    
    
inp = Input(1)
h = JointDistLayer()(inp)
model = Model(inp, h)
model.compile()
```

In general I'd advise not putting side-effects (like writing to `self`) in call. Do all construction/preparation work in `__init__` and `build`, and keep `call` "[pure](https://en.wikipedia.org/wiki/Pure_function)".

Closing the issue for now, but feel free to reopen if you continue to have trouble.

**Comment by csuter** [comment]
Thanks Rob, I certainly empathize with the challenge of debugging these things. To clarify, the error/traceback here is coming from the Keras framework, and pertains to the manner in which it does internal graph building and how that interacts with the custom Layer code you've written. I think strictly speaking this usage is "off-label" from Keras's perspective (but I'm no Keras expert). I don't think we can solve this at the TFP level. I suspect something about the way that JointDistribution entails some deferred computation interacts badly with Keras's attempt to precompile its graph.

Within TFP we have a small library of Keras Layers that are designed to produce distributions as prediction outputs, which isn't quite what you're doing, but possibly related. I haven't tried returning a JointDistribution from a tfp.layers.DistribtuionLayer, but it might work. Historically these things are pretty finicky, partly for the same reason you're having trouble (correct Keras interop is hard).

There's also some experimental work in [tfp.experimental.joint_distribution_layers](https://www.tensorflow.org/probability/api_docs/python/tfp/experimental/joint_distribution_layers) which is not Keras-based but is an interesting take on combining nn-style layers with (joint) distributions.
