### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'event_shape'

### ISSUE THREAD

**Issue by skr3178** [tensorflow/probability#1552]
`normal= tfd.Normal(loc=0, scale=1.)

cubed_normal= tfd.TransformedDistribution(normal, cubic, event_shape=[2])`

![image](https://user-images.githubusercontent.com/79299617/164528253-0d901eb5-9de2-4bc1-b87e-d6c2b789d54a.png)

**Comment by csuter** [comment]
Hi, can you say a bit more about what you were hoping to do here?

TransformedDistribution does not have such an `event_shape` argument (see [API docs](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/TransformedDistribution)).

If you want a cubically transformed 2-dimensional normal you can do something like

```
cubed_normal = tfb.Power(3)(tfd.MultivariateNormalDiag([0, 0], [1, 1]))
```

This (calling a bijector on a distribution) is equivalent to

```
cubed_normal = tfd.TransformedDistribution(tfd.MultivariateNormalDiag([0, 0], [1, 1]), tfb.Power(3))
```

**Comment by CyberPlayerOne** [comment]
I'm watching the same video.
I found if I define as this:
`cubed_normal = tfd.TransformedDistribution(normal, cubic, )`
I can sample from it with this shape:
```
n =(1000,2)
g = cubed_normal.sample(n)
```
It will achieve the same result as in the video tutorial.
However, `.sample()` method's param should be `sample_shape` only, but `n =(1000,2)` also includes 2 as the event_shape. This is semantically wrong, I guess?

**Comment by CyberPlayerOne** [comment]
> Hi, can you say a bit more about what you were hoping to do here?
> 
> TransformedDistribution does not have such an `event_shape` argument (see [API docs](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/TransformedDistribution)).
> 
> If you want a cubically transformed 2-dimensional normal you can do something like
> 
> ```
> cubed_normal = tfb.Power(3)(tfd.MultivariateNormalDiag([0, 0], [1, 1]))
> ```
> 
> This (calling a bijector on a distribution) is equivalent to
> 
> ```
> cubed_normal = tfd.TransformedDistribution(tfd.MultivariateNormalDiag([0, 0], [1, 1]), tfb.Power(3))
> ```

Thsi is the `Cubic` Bijector class and the `cubic` bijector object:
```
# Define a new bijector: Cubic
class Cubic(tfb.Bijector):

    def __init__(self, a, b, validate_args=False, name='Cubic'):
        self.a = tf.cast(a, tf.float32)
        self.b = tf.cast(b, tf.float32)
        if validate_args:
            assert tf.reduce_mean(tf.cast(tf.math.greater_equal(tf.abs(self.a), 1e-5), tf.float32)) == 1.0
            assert tf.reduce_mean(tf.cast(tf.math.greater_equal(tf.abs(self.b), 1e-5), tf.float32)) == 1.0
        super(Cubic, self).__init__(validate_args=validate_args, forward_min_event_ndims=0, name=name)

    def _forward(self, x):
        x = tf.cast(x, tf.float32)
        return tf.squeeze(tf.pow(self.a * x + self.b, 3))

    def _inverse(self, y):
        y = tf.cast(y, tf.float32)
        return (tf.math.sign(y) * tf.pow(tf.abs(y), 1/3) - self.b) / self.a

    def _forward_log_det_jacobian(self, x):
        x = tf.cast(x, tf.float32)
        return tf.math.log(3. * tf.abs(self.a)) + 2. * tf.math.log(tf.abs(self.a * x + self.b))
```

```
# Cubic bijector
cubic = Cubic([1.0, -2.0], [-1.0, 0.4], validate_args=True)
```

**Comment by skr3178** [comment]
Hi,
Unfortunately, I found it easier to just return to the previous version of tensorflow probability which solved the issue. 

Thanks for helping!
