### ISSUE TITLE
Should Flipout use Rademacher or Uniform Distribution?

### ISSUE THREAD

**Issue by a76yyyy** [tensorflow/probability#1554]
In this paper, The original content is "r and s are random vectors whose entries are sampled uniformly from ±1"

I think this should refer to uniform distribution rather than [Rademacher distribution](https://github.com/tensorflow/probability/blob/main/tensorflow_probability/python/layers/conv_variational.py#L1084).

Is it my understanding errors, or which article explains the effectiveness of the Rademacher Distribution?

**Comment by a76yyyy** [comment]
Who can answer my questions?

**Comment by SiegeLordEx** [comment]
The flipout paper uses the rademacher distribution, that is core to the derivation of the algorithm. E.g. in Observation 1: 

> Let E be a random sign matrix that is independent of ∆dW. Then ∆W = ∆dW ◦ E is identically distributed to ∆dW.

This would not work with a uniform distribution.
