### ISSUE TITLE
How to specify a batch_shape to a custom bijector?

### ISSUE THREAD

**Issue by CyberPlayerOne** [tensorflow/probability#1555]
I have defined a Cubic bijector. This is the `Cubic` Bijector class and the `cubic` bijector object. It's basically $y = (ax+b)^3$.
```python
# Define a new bijector: Cubic
class Cubic(tfb.Bijector):

    def __init__(self, a, b, validate_args=False, name='Cubic'):
        self.a = tf.cast(a, tf.float32)
        self.b = tf.cast(b, tf.float32)
        if validate_args:
            assert tf.reduce_mean(tf.cast(tf.math.greater_equal(tf.abs(self.a), 1e-5), tf.float32)) == 1.0
            assert tf.reduce_mean(tf.cast(tf.math.greater_equal(tf.abs(self.b), 1e-5), tf.float32)) == 1.0
        super(Cubic, self).__init__(validate_args=validate_args, forward_min_event_ndims=0, name=name)

    def _forward(self, x):
        x = tf.cast(x, tf.float32)
        return tf.squeeze(tf.pow(self.a * x + self.b, 3))

    def _inverse(self, y):
        y = tf.cast(y, tf.float32)
        return (tf.math.sign(y) * tf.pow(tf.abs(y), 1/3) - self.b) / self.a

    def _forward_log_det_jacobian(self, x):
        x = tf.cast(x, tf.float32)
        return tf.math.log(3. * tf.abs(self.a)) + 2. * tf.math.log(tf.abs(self.a * x + self.b))
```

```python
# Cubic bijector
cubic = Cubic([1.0, -2.0], [-1.0, 0.4], validate_args=True)
```
Then I defined a distribution with it:
```python
normal = tfd.Normal(loc=0., scale=1.)
cubed_normal = tfd.TransformedDistribution(normal, cubic, )
```

However when I sample from it
```python
g = cubed_normal.sample(10)
```
Error occurs:

> InvalidArgumentError: required broadcastable shapes [Op:Mul]

According to the [API doc](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/TransformedDistribution) of `tfp.distributions.TransformedDistribution`, the `sample` function here should work with the scalar `sample_shape`. **Why it doesn't work in my case? Is it because my definition of `Cubic` bijector lacks the definition of its `batch_shape`?**

**Comment by csuter** [comment]
Yes you need to define the batch_shape. These days, there's some plumbing in Bijector to automatically determine batch shape, with the right incantations. You need to 1) pass a parameters dict to super().__init__ and 2) define _parameter_properties classmethod:

```python
# Define a new bijector: Cubic
class Cubic(tfb.Bijector):

    def __init__(self, a, b, validate_args=False, name='Cubic'):
        parameters = dict(locals())
        self._a = tf.convert_to_tensor(a, dtype_hint=tf.float32, name='a')
        self._b = tf.convert_to_tensor(b, dtype_hint=tf.float32, name='b')
        if validate_args:
            assert tf.reduce_mean(tf.cast(tf.math.greater_equal(tf.abs(self._a), 1e-5), tf.float32)) == 1.0
            assert tf.reduce_mean(tf.cast(tf.math.greater_equal(tf.abs(self._b), 1e-5), tf.float32)) == 1.0
        super(Cubic, self).__init__(
            validate_args=validate_args,
             forward_min_event_ndims=0,
             parameters=parameters,
             name=name)

    @classmethod
    def _parameter_properties(cls, dtype):
      return dict(a=parameter_properties.ParameterProperties(),
                  b=parameter_properties.ParameterProperties())

    def _forward(self, x):
        x = tf.cast(x, tf.float32)
        return tf.pow(self._a * x + self._b, 3)

    def _inverse(self, y):
        y = tf.cast(y, tf.float32)
        return (tf.math.sign(y) * tf.pow(tf.abs(y), 1/3) - self._b) / self._a

    def _forward_log_det_jacobian(self, x):
        x = tf.cast(x, tf.float32)
        return tf.math.log(3. * tf.abs(self._a)) + 2. * tf.math.log(tf.abs(self._a * x + self._b))
```

The above worked for me. I also changed the casts to convert_to_tensor and got rid of the tf.squeeze -- squeeze is almost always a code smell, at least in library code (like a custom bijector). With the above, the sample op on the TD works as expected.

**Comment by CyberPlayerOne** [comment]
@csuter Thanks a lot! It works!
The first two lines of the newly added code segments seem to be easy to understand. Could you please give a bit explanation to the third new segment? What does this function actually do to the `Cubic` bijector class?
```python
    @classmethod
    def _parameter_properties(cls, dtype):   # <-- new
      return dict(a=parameter_properties.ParameterProperties(),
                  b=parameter_properties.ParameterProperties())
```
I have found two links: [parameter_properties](https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/Bijector#parameter_properties) and [tfp.util.ParameterProperties](https://www.tensorflow.org/probability/api_docs/python/tfp/util/ParameterProperties). It seems they only explained how this should be done, but they didn't tell the purpose of these or the internal mechanism...

**Comment by csuter** [comment]
Sorry for the slow reply. Parameter properties serve a few purposes, like automating batch shape inference (as in this example) but also things like automatically constructing trainable instances of a bijector (or distribution). In this case they're pretty minimal, since there are no constraints on valid parameter values for this bijector. Others might require, say, non-negative values, etc. Peeking at the commits that touched this feature might be informative ([link](https://github.com/tensorflow/probability/search?q=parameterproperties&type=commits)). Also, peeking at what some distributions and bijectors have for their param props, eg [Normal](https://github.com/tensorflow/probability/blob/main/tensorflow_probability/python/distributions/normal.py#L149), which has no constraints on `loc` but a positivity constraint on `scale`.
