### ISSUE TITLE
Posterior sampling and randomizing fixed effects?

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/probability#156]
Is there a way to do posterior sampling from all the parameters after running a model, using the `Linear_Mixed_Effects_Models` example? I'm guessing to raw from the fixed effects, I'd have to put some distributions over them to make them 'random' first eh?

**Comment by dustinvtran** [comment]
To get more posterior samples from the random effects, you can just run the E-step (MCMC) for longer while fixing the model parameters (fixed effects). As you note, the fixed effects are harder—not so much because they're model parameters, but because they're reified as `tf.Variables`.

The easiest suggestion is to just make them random. An alternative suggestion—if you want to keep fixed effects as `tf.Variables`—is to first define them outside the `linear_mixed_effects_model` function, and pass them in as arguments to the function. Then for `target_log_prob_fn`, write something like

```python
def target_log_prob_fn(effect_students, effect_instructors, effect_departments, fixed_effects):
  """Unnormalized target density as a function of states."""
  assign_op = your_variables.assign(fixed_effects) ....
  with tf.control_dependencies([assign_op]):
    return log_joint(  # fix `features` and `ratings` to the training data
      features=features_train,
      fixed_effects=fixed_effects,
      effect_students=effect_students,
      effect_instructors=effect_instructors,
      effect_departments=effect_departments,
      ratings=labels_train)
```

This will ensure the variables are assigned to their MCMC state during inference. MCMC will run on the unnormalized target density where the model implicitly has an improper uniform prior over the model parameters.

**Comment by sadatnfs** [comment]
Thanks @dustinvtran ! I'm trying the first suggestion (transform into random), like such: 
``` effect_ln_pop = ed.RandomVariable(ed.Normal(0., 1., name="effect_ln_pop"))```
where `effect_ln_pop` is a fixed effect I'm trying to 'randomize'.

If I run that assignment just outside the model function I get this error:
```
AttributeError: 'RandomVariable' object has no attribute 'name'
``` 
while setting up the EM steps give me this error:
```
ValueError: Incompatible shape for initialization argument 'value'. Expected (), got (1,).
```


For broad context, this is what my linear mixed effect model looks like (used the example and edited in my dataset's information). As you can see, I have tried a bunch of things to make `effect_ln_pop` random. The whole chunk where I set it as `ed.Normal` with a premade loc and scale was definitely NOT the right option, because I think it wasn't the simple random transformation that you were referring to and it might have been trying to fit distributions per data point (the MCMC was taking forever for a single iteration).

```python

def linear_mixed_effects_model(features):
        
    # Set up fixed effects and other parameters.
    intercept = tf.get_variable("intercept", [])  # alpha in eq
    effect_ln_TFR = tf.get_variable("effect_ln_TFR", [],
                                    constraint=lambda x: tf.clip_by_value(x, -np.infty, 0))  # beta in eq
#     effect_ln_pop = tf.get_variable("effect_ln_pop", [])  # gamma in eq
    stddev_iso3 = tf.exp(tf.get_variable("stddev_raw_iso3", []))
    model_stddev = tf.exp(tf.get_variable("model_stddev", []))

  # Set up random effects on country.
    effect_iso3 = ed.MultivariateNormalDiag( 
      loc=tf.zeros(n_res),
      scale_identity_multiplier=stddev_iso3,
      name="effect_iso3")  

#    The following allows us to define priors over params..?
#     stddev_pop = tf.exp(tf.get_variable("stddev_pop", [1]) )
#     loc_pop = tf.get_variable("loc_pop", [1]) 
#     effect_ln_pop = ed.Normal(loc =  loc_pop, 
#                               scale = stddev_pop,
#                               name="effect_ln_pop")
        
    effect_ln_pop = ed.RandomVariable(ed.Normal(0., 1., name="effect_ln_pop"))
#     effect_ln_pop = ed.as_random_variable(tfd.Normal(0., 1., name="effect_ln_pop"))
    

  # Set up likelihood given fixed and random effects.
    ln_gdppc = ed.Normal(
      loc=((intercept * features['intercept']) +
           (effect_ln_TFR * features["ln_TFR"]) +
           (effect_ln_pop * features["ln_pop"]) +
           tf.gather(effect_iso3, features["iso3"])),
      scale=model_stddev, name="ln_gdppc")
    return ln_gdppc

def target_log_prob_fn(effect_iso3, effect_ln_pop):
    return log_joint(
            features=features_train,
            effect_iso3=effect_iso3,
            effect_ln_pop=effect_ln_pop,
            ln_gdppc=labels_train)
```


and the EM setup is as follows :
```python
# Wrap model in a template. All calls to the model template will use the same
# TensorFlow variables.
tf.reset_default_graph()
model_template = tf.make_template("model", linear_mixed_effects_model)

## Make joint LL
log_joint = ed.make_log_joint_fn(model_template)

# draw_graph(linear_mixed_effects_model, features_train)
## Set up E-step (MCMC) for RE vars
effect_iso3 = tf.get_variable("effect_iso3", [n_res], trainable=False)
# effect_ln_TFR = tf.get_variable("effect_ln_TFR", [1], trainable=False)
effect_ln_pop = tf.get_variable("effect_ln_pop", [1], trainable=False)

## Global step
global_step = tf.Variable(0, trainable=False, name="global_step")

## RE state to update
# current_state = [effect_iso3]
current_state = [effect_iso3, effect_ln_pop]

## Set up MCMC object
hmc = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=0.02,
    num_leapfrog_steps=2)

## Update state
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    next_state, kernel_results = hmc.one_step(
      current_state=current_state,
      previous_kernel_results=hmc.bootstrap_results(current_state))
```


The ValueError is coming from the `hmc.bootstrap_results` call. Any tips would be greatly appreciated!! Thanks again Dustin!

**Comment by dustinvtran** [comment]
Similar to the existing random effects, you only need to specify `ed.Normal` as the prior on global variables (fixed effects). It inherits from `ed.RandomVariable` as a subclass. Have you tried that?

**Comment by sadatnfs** [comment]
@dustinvtran Thanks again!

Having something like what you suggested is returning me this ValueError (trying a prior on ln_TFR):
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-1f0d07067c30> in <module>()
     31     warnings.simplefilter("ignore")
     32     next_state, kernel_results = hmc.one_step(current_state=current_state,
---> 33       previous_kernel_results=hmc.bootstrap_results(current_state))
     34 
     35 ## Update Expectation

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/hmc.py in bootstrap_results(self, init_state)
    506   def bootstrap_results(self, init_state):
    507     """Creates initial `previous_kernel_results` using a supplied `state`."""
--> 508     kernel_results = self._impl.bootstrap_results(init_state)
    509     if self.step_size_update_fn is not None:
    510       step_size_assign = self.step_size_update_fn(self.step_size, None)  # pylint: disable=not-callable

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py in bootstrap_results(self, init_state)
    261         name=mcmc_util.make_name(self.name, 'mh', 'bootstrap_results'),
    262         values=[init_state]):
--> 263       pkr = self.inner_kernel.bootstrap_results(init_state)
    264       if not has_target_log_prob(pkr):
    265         raise ValueError(

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/hmc.py in bootstrap_results(self, init_state)
    672           init_target_log_prob,
    673           init_grads_target_log_prob,
--> 674       ] = mcmc_util.maybe_call_fn_and_grads(self.target_log_prob_fn, init_state)
    675       return UncalibratedHamiltonianMonteCarloKernelResults(
    676           log_acceptance_correction=tf.zeros_like(init_target_log_prob),

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/util.py in maybe_call_fn_and_grads(fn, fn_arg_list, result, grads, check_non_none_grads, name)
    226     fn_arg_list = (list(fn_arg_list) if is_list_like(fn_arg_list)
    227                    else [fn_arg_list])
--> 228     result, grads = _value_and_gradients(fn, fn_arg_list, result, grads)
    229     if not all(r.dtype.is_floating
    230                for r in (result if is_list_like(result) else [result])):  # pylint: disable=superfluous-parens

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/util.py in _value_and_gradients(fn, fn_arg_list, result, grads, name)
    181 
    182     if result is None:
--> 183       result = fn(*fn_arg_list)
    184     result = _convert_to_tensor(result, 'fn_result')
    185 

<ipython-input-7-700033a65e8f> in target_log_prob_fn(effect_iso3, effect_ln_TFR)
     50     effect_iso3=effect_iso3,
     51     effect_ln_TFR=effect_ln_TFR,
---> 52     ln_gdppc=labels_train)

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/edward2/program_transformations.py in log_joint_fn(*args, **kwargs)
    107     model_kwargs = _get_function_inputs(model, **kwargs)
    108     with interception(interceptor):
--> 109       model(*args, **model_kwargs)
    110     log_prob = sum(log_probs)
    111     return log_prob

/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/template.py in __call__(self, *args, **kwargs)
    366           custom_getter=self._custom_getter) as vs:
    367         self._variable_scope = vs
--> 368         return self._call_func(args, kwargs)
    369 
    370   @property

/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/template.py in _call_func(self, args, kwargs)
    309         # Checkpointable).
    310         with checkpointable_util.capture_dependencies(template=self):
--> 311           result = self._func(*args, **kwargs)
    312 
    313       if self._variables_created:

<ipython-input-7-700033a65e8f> in linear_mixed_effects_model(features)
     14 #                               scale=stddev_raw_tfr,
     15 #                               name = 'effect_ln_TFR')
---> 16     effect_ln_TFR = ed.Normal(loc =1., scale =1., name = "effect_ln_TFR")
     17 
     18     # gamma in eq

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/edward2/interceptor.py in func_wrapped(*args, **kwargs)
    191   def func_wrapped(*args, **kwargs):
    192     with get_next_interceptor() as interceptor:
--> 193       return interceptor(func, *args, **kwargs)
    194 
    195   return func_wrapped

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/edward2/program_transformations.py in interceptor(rv_constructor, *rv_args, **rv_kwargs)
    100       rv_kwargs["value"] = value
    101 
--> 102       rv = rv_constructor(*rv_args, **rv_kwargs)
    103       log_prob = tf.reduce_sum(rv.distribution.log_prob(rv.value))
    104       log_probs.append(log_prob)

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/edward2/generated_random_variables.py in func(*args, **kwargs)
    211     return RandomVariable(distribution=distribution_cls(*args, **kwargs),
    212                           sample_shape=sample_shape,
--> 213                           value=value)
    214   return func
    215 

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/edward2/random_variable.py in __init__(self, distribution, sample_shape, value)
    118         raise ValueError(
    119             "Incompatible shape for initialization argument 'value'. "
--> 120             "Expected %s, got %s." % (expected_value_shape, value_shape))
    121     self._value = value
    122 

ValueError: Incompatible shape for initialization argument 'value'. Expected (), got (1,).

originally defined at:
  File "<ipython-input-8-1f0d07067c30>", line 5, in <module>
    model_template = tf.make_template("model", linear_mixed_effects_model)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)
```

**Comment by sadatnfs** [comment]
However, if I go `effect_ln_TFR = ed.Normal(loc = tf.ones(1), scale =1., name = "effect_ln_TFR")`, then the each iteration takes impossibly long to run. I'm trying with a simple linear regression of type `y=a + bX + error` where I did a simple prior on the intercept with `effect_intercept = ed.Normal(loc=tf.zeros(1), scale=1., name = 'effect_intercept')`, and it also gets forever stuck on the first iterations..

**Comment by sadatnfs** [comment]
@dustinvtran I'm willing to say that: when I randomize the fixed effects in the way above, the reason why it might take so long to run a single iteration is because it's evaluating the coefficient distribution for every data point as opposed to doing what we want? That makes me wonder that maybe we might have to change `effect_ln_TFR * features["ln_TFR"]` into something else when adding to `yhat` (where `effect_ln_TFR = ed.Normal(loc = tf.ones(1), scale =1., name = "effect_ln_TFR")`). Thoughts?

**Comment by dustinvtran** [comment]
I'm having a bit of trouble understanding the revised model. Can you write that code snippet? Also, full Bayes will naturally take longer. How much longer are you seeing?

**Comment by sadatnfs** [comment]
@dustinvtran apologies for all the blank references. I pushed my code in this gist here with outputs:
https://gist.github.com/sadatnfs/83453d5cd6831fabdadea9969582332b

I basically have two chunks: one where I keep the parameter in question (`effect_ln_TFR`) fixed, and the other where I attempt to randomize it with a simple N(0,1) prior. Both the models have a multivariate normal random effect to denote country-specific intercepts (`effect_iso3`). 

As you can see, running 100 iterations took ~12s, where as the one where I randomized the extra variable took ~2 minutes for just 10 iterations (breezed through warmup, but I guess we're not running the session for all the variables there).

**Comment by dustinvtran** [comment]
It looks like this notebook is being run out-of-order. So it's a little hard to diagnose—particularly for a nuanced issue like this. (FYI as good practice, this is one reason why [Jupyter notebooks are bad for development](https://twitter.com/dustinvtran/status/1033495895642320897)). 

In particular, it looks like the target log prob fns are defined without making the log joint function, and it seems to depend on the same function in both. Can you update the cells to work in sequence?

**Comment by sadatnfs** [comment]
I was just about to separate them and then I realized exactly why my iterations were running so slowly..

So when I doing my `sess.run(...)` and was recording the coefficient samples, I was passing the parameter as `sess.run(effect_ln_TFR[0])` instead of `sess.run(effect_ln_TFR)`, because I wanted to pull the scalar values to record in the numpy array later on. Little did I know that should have left that variable in there as is, and done the slicing later on when recording into the array... Now it breezes through!

The new properly sequenced notebooks are [here for fixed](https://gist.github.com/sadatnfs/15c596272e480676842a4d8d7964a4d0) and [here for random](https://gist.github.com/sadatnfs/927727c66f9dad45731353343601f93c).

Thanks again @dustinvtran ! I do have one last question: if I wanted to run a model where I did not have any random effects at all (in both the above models I have a multivariate normal on an int variable), can I still pass them through MCMC? I tried to leave `current_state` blank along with passing no arguments to `target_log_prob_fn` but the EM setup borked out on me...

Thanks again!!!

**Comment by dustinvtran** [comment]
No problem. Thanks for all the updates @sadatnfs.

> I do have one last question: if I wanted to run a model where I did not have any random effects at all (in both the above models I have a multivariate normal on an int variable), can I still pass them through MCMC?

I would recommend writing down what you want this to mean mathematically. Given that mathematical definition, you can then look into various ways to codify it. In this case, I'm not totally sure I understand what it means to do MCMC or EM without any random effects.

**Comment by sadatnfs** [comment]
Perfect, will look into that. Thanks Dustin, closing this now!
