### ISSUE TITLE
RandomVariable error on setting name?

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/probability#158]
Hi everyone,

I've been trying to tinker with a model in another issue but I realized that maybe this is error worthy.

As far as I know, whenever we define a distribution inside a model, we'd have to have it named. However, one of the things I've been trying to do recently is to take a fixed/global effect parameter and trying to 'randomize' it by giving it a distribution (let's say a Normal). Dustin suggested using the `ed.RandomVariable` call but I'm getting this weird error :

```python
test_case = ed.RandomVariable(ed.Normal(loc=1., scale=1., name = 'test_case'))
test_case
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/conda/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

/opt/conda/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/edward2/random_variable.py in __repr__(self)
    183   def __repr__(self):
    184     string = "ed.RandomVariable '%s' shape=%s dtype=%s" % (
--> 185         self.distribution.name, self.shape, self.dtype.name)
    186     if hasattr(self.value, "numpy"):
    187       string += " numpy=%s" % _numpy_text(self.value, is_repr=True)

AttributeError: 'RandomVariable' object has no attribute 'name'

```

Further down in the model, it gives a different shape error, but that's something @dustinvtran and I are discussing in #156, but for now, is this something we should be worried about?

**Comment by davmre** [comment]
`ed.Normal` is already a random variable: it's a convenience wrapper around `ed.interceptable(ed.RandomVariable(distribution=tfd.Normal(...), name=name))`. So you don't need to wrap it further; just 

```python
test_case = ed.Normal(loc=1., scale=1., name = 'test_case')
```

should be enough.

In general it's very rare that user code needs to explicitly construct `RandomVariable` instances. If you're using a built-in distribution like a Normal, the `ed.Normal` call is all you need. For user-defined distributions, the convenience method `ed.as_random_variable(distribution_instance)` will handle building an interceptable random variable with the given distribution.

**Comment by sadatnfs** [comment]
Perfect thanks for the info Dave! I'll close this and focus on the other issue now.
