### ISSUE TITLE
Calling distributions module causes out of memeory error for jax

### ISSUE THREAD

**Issue by MichelangeloConserva** [tensorflow/probability#1582]
Hello,
I have found a weird behavior of the tfp.distributions module.

When I run the following code,
```
import jax.numpy as jnp
from tensorflow_probability.substrates import jax as tfp

tfp.distributions

mix = 0.2
means=((2.0, 2), (-2.0, -2.0))
covs = ([[2.5, 0.1], [0.1, 2.5]], [[2.0, -0.3], [-0.3, 2.0]])
covs = [jnp.linalg.cholesky(cov) for cov in covs]
```
I get the following error,
`jaxlib.xla_extension.XlaRuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda/cusolver_kernels.cc:79: operation cudaMemcpyAsync(buffers[1], buffers[0], SizeOfCusolverType(d.type) * d.batch * d.n * d.n, cudaMemcpyDeviceToDevice, stream) failed: out of memory`

However, if I comment out tfp.distributions then it runs normally.
```
import jax.numpy as jnp
from tensorflow_probability.substrates import jax as tfp

#tfp.distributions

mix = 0.2
means=((2.0, 2), (-2.0, -2.0))
covs = ([[2.5, 0.1], [0.1, 2.5]], [[2.0, -0.3], [-0.3, 2.0]])
covs = [jnp.linalg.cholesky(cov) for cov in covs]
```

My jax version is '0.3.14' and my tfp version is '0.17.0-dev20220629'.

Thanks.

**Comment by brianwa84** [comment]
Do you have tensorflow installed? It will eagerly allocate all GPU RAM, and
we might import tf in a try catch block.

**Comment by MichelangeloConserva** [comment]
I confirm that it is tensorflow's fault. The code runs without errors once I uninstall tensorflow. Thanks.
