### ISSUE TITLE
a bug when using KLDivergenceRegularizer for Triangular distribution

### ISSUE THREAD

**Issue by yang24feifei** [tensorflow/probability#1584]
Hi, there is a bug when I using KLDivergenceRegularizer for constructing Triangular distribution layer. I know there has not have registed KL for Triangular distribution, what I want to know is should it work when 'use_exact_kl=False' ? 
Recently, when I using KLDivergenceRegularizer with 'use_exact_kl=False', the bug shows: 
AttributeError:'Triangular' object has no attribute '_log_prob'

the code:
test=np.eye(9)
prior =tfd.Triangular (low=0, high=1, peak=0.5)
outputs=tfpl.DistributionLambda(  make_distribution_fn=lambda t: tfd.Triangular(low=0, high=1,peak=0.5), 
        activity_regularizer=tfpl.KLDivergenceRegularizer(prior , use_exact_kl=False, weight=1.0),
                                convert_to_tensor_fn=tfd.Distribution.sample 
                               )(test)

**Comment by SiegeLordEx** [comment]
Interesting bug. I don't have a fix for you, but here's a workaround:

```python
class TriangularLogProb(tfd.Triangular):

  def _log_prob(self, x):
    return tfd.Triangular(**self.parameters).log_prob(x)


test = np.eye(9)
prior = TriangularLogProb(low=0, high=1, peak=0.5)
outputs = tfpl.DistributionLambda(
    make_distribution_fn=lambda t: TriangularLogProb(low=tf.zeros_like(t), high=1, peak=0.5),
    activity_regularizer=tfpl.KLDivergenceRegularizer(
        prior, use_exact_kl=False, weight=1.0),
    convert_to_tensor_fn=tfd.Distribution.sample)(
        test)
```
