### ISSUE TITLE
Potential argument name collision for 'make_log_joint_fn'

### ISSUE THREAD

**Issue by jereliu** [tensorflow/probability#160]
In the function `_get_function_inputs` (under `edward2.program_transformations.py`), the arg name for the function to check argument against is `f`. 

Consequently, whenever user try to call `make_log_joint_fn` with a model function whose kwargs contains the name `f`, the function `_get_function_inputs` will receive two arguments with the same name `f`, and a seemingly cryptic error will arise:

```
Traceback (most recent call last):
  File "<ipython-input-100-247a5b0bcb2c>", line 1, in <module>
    target_log_prob_fn(f, sigma, y)
  File "<ipython-input-98-bfb9baac0cc3>", line 3, in target_log_prob_fn
    return log_joint(X=X_train, f=f, sigma=sigma, y=y)
  File "/tensorflow_probability/python/edward2/program_transformations.py", line 107, in log_joint_fn
    model_kwargs = _get_function_inputs(model, **kwargs)
TypeError: _get_function_inputs() got multiple values for argument 'f'
```
I can see this happen often with GP regression, for example, see how the model is defined in the [GP classification tutorial](http://edwardlib.org/tutorials/supervised-classification) in Edward.

I think a quick fix will be to check for potential argument name collision somewhere in `make_log_joint_fn`, or in `_get_function_inputs` change of the name of the argument from `f` to a more descriptive name such as `function_to_check`

**Comment by dustinvtran** [comment]
Thanks for the report—sounds like an easy fix as you mention. Contribution welcome!

**Comment by jereliu** [comment]
ok will make a pull request soon
