### ISSUE TITLE
quantile is not implemented: Beta

### ISSUE THREAD

**Issue by jedisom** [tensorflow/probability#1635]
Similar to Issues [20208](https://github.com/tensorflow/tensorflow/issues/20208) and [51948](https://github.com/tensorflow/tensorflow/issues/51948) in the tensorflow repo, as well as issue [1259](https://github.com/tensorflow/probability/issues/1259) in this repo, the Beta distribution does not have its `quantile` method implemented.  Calling that method gives the following error:  
"quantile is not implemented: Beta"

I'm using python==3.8.11, tensorflow==2.10.0, tensorflow-probability==0.18.0

- Can we get this added?  
- Is there a work around until it gets added?
- Also, I noticed the same issue with the `GeneralizedExtremeValue` distribution.  Should I open another ticket for that distribution separate from this one?

**Comment by leandrolcampos** [comment]
Hi @jedisom,

I hope this message finds you well.

The quantile of Beta distribution was added last month. Try to install the nightly build of TensorFlow Probability, just like in [this](https://gist.github.com/leandrolcampos/65ea8069f6cdc54933dd4d93a84984a7) Colab notebook.

All the best,

**Comment by jedisom** [comment]
@leandrolcampos, that's great news!  When should I expect this to get into a stable build revision?

**Comment by jedisom** [comment]
@leandrolcampos: Also, I tested the nightly build and it works as you said.  Should I close this issue and reopen one for the `quantile` method missing in `GeneralizedExtremeValue`?

**Comment by leandrolcampos** [comment]
> @leandrolcampos, that's great news! When should I expect this to get into a stable build revision?

About this, I think [this](https://github.com/tensorflow/probability/issues/991#issuecomment-700232834) comment from a TFP member answers your question.
