### ISSUE TITLE
How is sampling from a Categorical implemented?

### ISSUE THREAD

**Issue by dieterichlawson** [tensorflow/probability#1638]
I am wondering how sampling from a Categorical distribution is implemented. Specifically, I am interested in the complexity of the sampling algorithm as a function of the number of classes and number of samples. Is the [alias method](https://en.wikipedia.org/wiki/Alias_method#:~:text=In%20computing%2C%20the%20alias%20method,arbitrary%20probability%20distribution%20pi.) used? 

I tried to read the code but lost the thread at some auto-generated code.

I am also specifically interested in the implementation for the JAX backend, if it is different at all.

**Comment by SiegeLordEx** [comment]
Under JAX, we use the Gumbel-Max technique. The code is here: https://github.com/tensorflow/probability/blob/e84cd82b901b2ee58514052df119b726d2c34065/tensorflow_probability/python/internal/backend/numpy/random_generators.py#L105
