### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by somum** [tensorflow/probability#167]
My goal is to train my dataset but after all the process when i began the train it showed me this error. is there any solution? 
![t2](https://user-images.githubusercontent.com/38000910/46062594-1d8a8680-c18c-11e8-8865-3cc983f868f9.JPG)

**Comment by brianwa84** [comment]
take a look at https://github.com/tensorflow/probability/issues/46

**Comment by brianwa84** [comment]
Please reopen if that issue doesn't clarify/resolve things for you.
