### ISSUE TITLE
JAX distributions source code? 

### ISSUE THREAD

**Issue by saraelshawa** [tensorflow/probability#1680]
Hi, 

I'm looking for the source code linked [here](https://www.tensorflow.org/probability/api_docs/python/tfp/substrates/jax/distributions/WishartTriL), but that doesn't seem to exist in this repo (should be under ./substrates/jax/distributions). 
Can you please let me know where I can find it? 

Thanks!

**Comment by ColCarroll** [comment]
Hi! The JAX substrate is dynamically generated by changing some imports. One way to see the source is to run 

```python
import tensorflow_probability.substrates.jax as tfp
import inspect
tfd = tfp.distributions


with open(inspect.getabsfile(tfd.WishartTriL), 'r') as buff:
  print(buff.read())
  ```

note that this will show you the line

```
from tensorflow_probability.python.internal.backend.jax.compat import v2 as tf
```
along with most of the source that you see anyways [here](https://github.com/tensorflow/probability/blob/v0.19.0/tensorflow_probability/python/distributions/wishart.py#L417-L558). If you keep chasing the symbols, most of the actual implementations will be somewhere in [here](https://github.com/tensorflow/probability/tree/v0.19.0/tensorflow_probability/python/internal/backend/numpy).

(closing to be tidy, but feel free to follow up here!)
