### ISSUE TITLE
Request of making tfp.stats.quantiles accepts float instead of int for the quantile argument

### ISSUE THREAD

**Issue by Daniel4078** [tensorflow/probability#1700]
I was trying to port some code that uses numpy to use tensorflow instead and I met this problem from try to replace numpy.quantile with tfp.stats.quantiles: As np.quantile accept float ranged 0-1 for its second argument quantile, the tfp.stats.quantiles accepts int for its second argument num_quantiles. This make the result from tfp.stats.quantiles not as accurate as the numpy version as if the value passed into the secomd quantile has more trailing digits like 0.34523, the only way to make tfp.stats.quantiles work is to convert that into 34, which makes the result potentially much less accurate.

So can someone change the behavior of tfp.stats.quantiles to make it accept floats instead for the second argument to make it more compatile to other ML frameworks? Thank you!

**Comment by leandrolcampos** [comment]
Hi @Daniel4078,

Take a look at `tfp.stats.percentile`. This function is comparable to `numpy.percentile`. Try replacing `numpy.quantile` with it by multiplying the original quantile to compute by 100 (following your example, use 34.523 instead of 0.34523).

All the best,

**Comment by Daniel4078** [comment]
> Hi @Daniel4078,
> 
> Take a look at `tfp.stats.percentile`. This function is comparable to `numpy.percentile`. Try replacing `numpy.quantile` with it by multiplying the original quantile to compute by 100 (following your example, use 34.523 instead of 0.34523).
> 
> All the best,

But acccording to this doc(https://www.tensorflow.org/probability/api_docs/python/tfp/stats/quantiles), the quantile can only be a int tensor, not a float like 34.523.

**Comment by leandrolcampos** [comment]
See this notebook: https://gist.github.com/leandrolcampos/4b7974d91964f80b2626514c799186d8

**Comment by Daniel4078** [comment]
Thank you!
