### ISSUE TITLE
tfp.stats.histogram weights argument bug when using multiple axes

### ISSUE THREAD

**Issue by joaozenobio** [tensorflow/probability#1712]
> Issue at Tensorflow GitHub:  https://github.com/tensorflow/tensorflow/issues/60287

# Current Behaviour

Tensorflow throws a ValueError when using weights and multiple axes at the same time, saying that the input and weights arguments should have the same shape, even though they already have.

Hint: Does not happen when using only one axis.

# Standalone code to reproduce the issue

```
import tensorflow_probability as tfp
import tensorflow as tf
x = tf.constant([[1, 2, 3], [1, 2, 3.]])
w = tf.constant([[1, 1, 1], [1, 1, 1.]])
e = tf.constant([0, 2.5, 10])
axis = tf.constant([0, 1])
tfp.stats.histogram(x=x, edges=e, axis=axis, weights=w)
```

# Relevant log output

Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/stats/quantiles.py", line 393, in histogram
    raise ValueError('Number of dimensions of `x` and `weights` must '
ValueError: Number of dimensions of `x` and `weights` must coincide. Found: x has 2, weights has 1

# Configs

* OS Platform and Distribution: Linux Ubuntu 22.04
* Python version: 3.8.10
* Tensorflow Version: 2.9.1

**Comment by ColCarroll** [comment]
Thanks! Looks like this is a quick fix from a typo. I can send a fix shortly.

**Comment by ColCarroll** [comment]
Fixed in https://github.com/tensorflow/probability/commit/bcca631f01c855425710fe3b8947192b71e310dd

Thanks again @joaozenobio

**Comment by joaozenobio** [comment]
Thank you for your support @ColCarroll ! :)
