### ISSUE TITLE
Deprecation Warning calculating log_prob() of JointDistribution containing a Beta-Distribution

### ISSUE THREAD

**Issue by tobnie** [tensorflow/probability#1721]
Hello,
whenever I am creating a JointDistribution (can be either Named or Sequential), I get the following warning:

> WARNING:tensorflow:From C:\Users\tobia\miniconda3\envs\idm\lib\site-packages\tensorflow_probability\python\internal\batched_rejection_sampler.py:102: calling while_loop_v2 (from tensorflow.python.ops.control_flow_ops) with back_prop=False is deprecated and will be removed in a future version.
> Instructions for updating:
> back_prop=False is deprecated. Consider using tf.stop_gradient instead.
> Instead of:
> results = tf.while_loop(c, b, vars, back_prop=False)
> Use:
> results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))

Since this is an issue within the tensorflow_probability-package, I thought I'd let you know. The warning can be reproduced with the following code (I just plugged in arbitrary numbers since they don't seem to matter):

```python
import tensorflow_probability as tfp
tfd = tfp.distributions
test_jd = tfd.JointDistributionSequential([tfd.Beta(concentration1=5, concentration0=1)])
test_jd.log_prob([2])
``` 

I am using `tensorflow==2.12.0` with `python==3.8.16` in the environment.

**Comment by ColCarroll** [comment]
thanks @tobnie -- for others visiting, @brianwa84 fixed this, and upgrading to `tfp-nightly` and `tf-nightly` will remove the warnings, until TFP 0.21 is released and this will be in the stable PyPI package.
