### ISSUE TITLE
Lack of requires-python causes tfp v0.20.0 to break all Python 3.7 and older 

### ISSUE THREAD

**Issue by matthewfeickert** [tensorflow/probability#1723]
Hi. As TensorFlow Probability doesn't have `requires-python` metadata (c.f. https://peps.python.org/pep-0621/#requires-python) the recent [`v0.20.0` release](https://github.com/tensorflow/probability/releases/tag/v0.20.0) has broken installation for Python 3.7 and older for everyone (c.f. https://github.com/tensorflow/probability/commit/e81e7e8af77280aabb0db4e9f5826673fe756346). This is because [TensorFlow `v2.12.0`](https://pypi.org/project/tensorflow/2.12.0/) is the first TensorFlow release to require Python 3.8+. So requiring 

https://github.com/tensorflow/probability/blob/e81e7e8af77280aabb0db4e9f5826673fe756346/tensorflow_probability/python/__init__.py#L54

without properly communicating that Python 3.8+ is now explicitly required by TensorFlow probability means that any Python 3.7 (or older) that was able to install and use TensorFlow `v2.11.0` and previous versions of TensorFlow Probability now gets a **broken** install of `tensorflow` `v2.11.0` and `tensorflow-probability` `v0.20.0` which produce a runtime `ImportError`

```
This version of TensorFlow Probability requires TensorFlow version >= 2.12; Detected an installation of version 2.11.0. Please upgrade TensorFlow to proceed.
```

(Example: https://github.com/scikit-hep/pyhf/pull/2202)

Including `requires-python` metadata would have properly guarded against this behavior. TensorFlow Probability `v0.20.0` should be yanked from PyPI and a `v0.20.1` should be cut that includes PR #1725 (backport of PR #1724).

These patterns have been discussed in many places previously and in great detail in @henryiii's blog post "[Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/)" (c.f. https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special for somewhat similar ideas).

cc @jburnim who made the release.

**Comment by matthewfeickert** [comment]
Thanks for the fast merge of PR #1724. :+1: Though for this Issue to be fully closed out the following still needs to happen:

* PR #1725 needs to get merged.
* [TensorFlow Probability `v0.20.0`](https://pypi.org/project/tensorflow-probability/0.20.0/) needs to get yanked from PyPI (this is crucial as its presence will continue to cause broken installs).
* TensorFlow Probability `v0.20.1` needs to be released.

**Comment by matthewfeickert** [comment]
@jburnim thanks for releasing [`tensorflow-probability` `v0.20.1`](https://pypi.org/project/tensorflow-probability/0.20.1/) quickly. :+1: It is still important that `v0.20.0` is [yanked from PyPI](https://pypi.org/help/#yanked) as without that all installs on  Python 3.7 and older will continue to be broken.

**Comment by henryiii** [comment]
FYI, if it helps, yanking is a safe procedure; anyone who has pinned v0.20.0 will still be able to get it; it will only no longer participate in open solves (which is what you want here).

**Comment by matthewfeickert** [comment]
> FYI, if it helps, yanking is a safe procedure;

Agreed, though I think the team already knows this as they have previously yanked https://pypi.org/project/tensorflow-probability/0.16.0.dev20220214/

**Comment by jburnim** [comment]
The 0.20.0 release has been yanked.

**Comment by matthewfeickert** [comment]
Excellent. Thank you @jburnim!
