### ISSUE TITLE
The equivalent of LinearOperator in JAX

### ISSUE THREAD

**Issue by pawel-czyz** [tensorflow/probability#1733]
This issue is related to [TensorFlow Probability on JAX](https://www.tensorflow.org/probability/examples/TensorFlow_Probability_on_JAX).

The tutorials of [multivariate Student](https://www.tensorflow.org/probability/api_docs/python/tfp/substrates/jax/distributions/MultivariateStudentTLinearOperator) and [multivariate normal](https://www.tensorflow.org/probability/api_docs/python/tfp/substrates/jax/distributions/MultivariateNormalLinearOperator) use `tf.linalg.LinearOperatorLowerTriangular`.

However, this object does not exist in JAX. I wonder what is the correct way to build these distributions?
Passing a JAX array leads to an error:
```
TypeError: Expected argument `scale` to be instance of `LinearOperator`. Found: `[[ 0.6  0.   0. ]
 [ 0.2  0.5  0. ]
 [ 0.1 -0.3  0.4]]`.
```

Any help would be much appreciated!

## Additional notes
  - Issue #1595 may be related with this one.

**Comment by brianwa84** [comment]
If you've done `import tensorflow_probability.substrates.jax as tfp`, then you can find linear operators in: `jtf = tfp.tf2jax; dir(jtf.linalg)`

**Comment by pawel-czyz** [comment]
It resolved the issue, thank you very much! :slightly_smiling_face:
