### ISSUE TITLE
Use intricate variables with JointDistributionSequential

### ISSUE THREAD

**Issue by pl992** [tensorflow/probability#1739]
I would like to build evaluate the posterior of a model where one parameter is completely defined by another one:
Let's say I want to sample a normal distribution with parameters mu and q.
mu ~ U([0,1])
while q is given by f(mu,k) with 0<k<1
the way I'm trying to write this is as follow:

```
def model(k,shape):
    q = lambda mu: (tf.cast(k,dtype) * (1-mu)/mu)
    return tfd.JointDistributionSequential([
        # mu
        tfd.Uniform(low=tf.cast(0,dtype),high=tf.cast(1,dtype)),
        lambda mu: tfd.Independent(tfd.Normal(mu[...,tf.newaxis]*sigma(mu[...,tf.newaxis]),
                                             tf.sqrt(mu[...,tf.newaxis]
                                                     * q(mu[...,tf.newaxis])
                                                     * (1 - mu[...,tf.newaxis]))),
                                  reinterpreted_batch_ndims=1)])
```
`shape` is simply the shape of the data I have.
Now this script works but provides completely wrong results with no fluctuations from the initial state of the MCMC. 
If I explicitly wrote the `q` in the JointDistribution as follow:
```
def model(k,shape):
    return tfd.JointDistributionSequential([
        # mu
        tfd.Uniform(low=tf.cast(0,dtype),high=tf.cast(1,dtype)),
        lambda mu: tfd.Independent(tfd.Normal(mu[...,tf.newaxis]*(tf.cast(k,dtype) * (1-mu)/mu)[...,tf.newaxis],
                                             tf.sqrt(mu[...,tf.newaxis]
                                                     * (tf.cast(k,dtype) * (1-mu)/mu)[...,tf.newaxis]
                                                     * (1 - mu[...,tf.newaxis]))),
                                  reinterpreted_batch_ndims=1)])
```
then everything appears to work fine.
It would be much more convenient to have a way of writing this script in a similar way to the first example since for more complicated functions the syntax might become really heavy. Is there a way to do that?

**Comment by ColCarroll** [comment]
Can you show the code you ran that indicates this is wrong? It looks fine to me -- could the problem be with how MCMC is being run?

**Comment by ColCarroll** [comment]
I think this is just a difficult problem, because the model is written somewhat strangely: You draw `trjs ~ N(mu, get_std)`, but that is nothing like what your joint distribution says. When I try this out, I see that the sampler tries to make the parameter `mu` as small as possible, but it is constrained by the `Uniform(0, 1)` prior. If you change the model to be `tfd.Normal(mu, q(mu))`, or the prior to be `tfd.Normal(0, 10)` (or both!) you might have more success.

For debugging, note that this is just a 1d problem, so you can always use gridsearch pretty nicely.

```
t = np.linspace(0, 1, 1000)
plt.plot(t, mdl.log_prob(t, trjs))
```

**Comment by pl992** [comment]
I'm really sorry about that! I think after many tests I've copied the wrong one. I really hoped though I made that stupid mistake so I knew what was wrong. 
Here's the code with trj~N(mu,get_std(mu,k)) and the model based as well on N(mu,get_std(mu,k)).
Even in this case I get a completely wrong sample.
Here's the right code:
```import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd
from tensorflow_probability import bijectors as tfb

if tf.test.gpu_device_name() != '/device:GPU:0':
    print('WARNING: GPU device not found.')
else:
    print('SUCCESS: Found GPU: {}'.format(tf.test.gpu_device_name()))

dtype = tf.dtypes.float32
@tf.function(autograph=False, experimental_compile=True)
def run_chain(init_state, step_size, target_log_prob_fn, unconstraining_bijectors,
              num_steps=500, burnin=500):

    def trace_fn(_, pkr):
        return (
            pkr.inner_results.inner_results.step_size,
            pkr.inner_results.inner_results.target_log_prob,
            pkr.inner_results.inner_results.leapfrogs_taken,
            pkr.inner_results.inner_results.has_divergence,
            pkr.inner_results.inner_results.energy,
            pkr.inner_results.inner_results.log_accept_ratio
               )

    kernel = tfp.mcmc.TransformedTransitionKernel(
    inner_kernel=tfp.mcmc.NoUTurnSampler(
      target_log_prob_fn,
      step_size=step_size),
    bijector=unconstraining_bijectors)

    hmc = tfp.mcmc.DualAveragingStepSizeAdaptation(
    inner_kernel=kernel,
    num_adaptation_steps=burnin,
    step_size_setter_fn=lambda pkr, new_step_size: pkr._replace(
        inner_results=pkr.inner_results._replace(step_size=new_step_size)),
    step_size_getter_fn=lambda pkr: pkr.inner_results.step_size,
    log_accept_prob_getter_fn=lambda pkr: pkr.inner_results.log_accept_ratio
    )

    # Sampling from the chain.
    chain_state, sampler_stat = tfp.mcmc.sample_chain(
      num_results=num_steps,
      num_burnin_steps=burnin,
      current_state=init_state,
      kernel=hmc,
      trace_fn=trace_fn)
    return chain_state, sampler_stat
def get_std(mu,k):
    return k * (1-mu)/mu
def model(k):
    return tfd.JointDistributionSequential([
        # mu
        tfd.Uniform(low=tf.cast(0,dtype),high=tf.cast(1,dtype)),
        lambda mu: tfd.Independent(tfd.Normal(mu[...,tf.newaxis],
                                              get_std(mu,k)[...,tf.newaxis]),
                                   reinterpreted_batch_ndims=1)])

k = 232

NSTEPS = 100000
mu = .344
nchains = 6

trjs = np.random.normal(mu,get_std(mu,k),NSTEPS)

mdl = model(k,)
unnormalized_posterior_log_prob = lambda *x: mdl.log_prob(x + (trjs, ))

*initial_state,sim = mdl.sample(nchains)
unconstraint_bijector = [tfb.Sigmoid()]
step_size = [.1]

samples,sampler_stat = run_chain(initial_state,step_size,
                                 unnormalized_posterior_log_prob,
```
The `run_chain` function is taken from one of the [tutorial](https://www.tensorflow.org/probability/examples/Modeling_with_JointDistribution) which should work in this case as well.
Take into account I'm entirely sure this works (with mu~U([0,1])) since I've built the same script using pymc and everything works fine. (I'm attaching the code just in case it is needed for comparison)
```
with pymc.Model() as model:
    mu = pymc.Uniform('mu',0,1)
    std = pymc.Deterministic('std',get_std(mu,k))
    sim = pymc.Normal('sim',mu,std,observed=trjs)
    trace = pymc.sample()
```

**Comment by pl992** [comment]
I'm sorry that was my really bad everything works fine now, I guess I felt overwhelmed by overflow's syntax (which appeared to me more convoluted than pymc). I would like to thank you a lot since you moved me to the right direction just saying 'it looks fine to me!'
