### ISSUE TITLE
Running tests does not require "--config=opt"

### ISSUE THREAD

**Issue by kdexd** [tensorflow/probability#176]
The [CONTRIBUTING.md](https://github.com/tensorflow/probability/blob/master/CONTRIBUTING.md) file states this command for running tests:

```
bazel test --config=opt --copt=-O3 --copt=-march=native \
  //tensorflow_probability/...
```

While executing this command, I get this error:
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'test' from /home/kd/Documents/probability/tools/bazel.rc:
  Inherited 'common' options: --color=yes
INFO: Reading rc options for 'test' from /home/kd/Documents/probability/tools/bazel.rc:
  'test' options: --test_output=errors
ERROR: Config value opt is not defined in any .rc file
```

On the contrary, executing `bazel test` without `--config=opt` runs the tests.

**Comment by csuter** [comment]
Thanks for pointing this out. Thought we'd removed all the instances of this erroneous flag, but looks like we missed a couple. Will fix momentarily.

**Comment by kdexd** [comment]
Thanks for the response @csuter :)

**Comment by kdexd** [comment]
@csuter: I just went ahead and opened a small PR quickly.

**Comment by csuter** [comment]
Thanks @kdexd -- I had already started making the change internally earlier today, but got sidetracked and just now submitted. Should be fixed. Thanks for prepping the PR though!
