### ISSUE TITLE
New release for TF 2.18?

### ISSUE THREAD

**Issue by jonas-eschle** [tensorflow/probability#1851]
Hi all,

thanks again for this library and maintaining it!

Is there a release planned soon for TF 2.18?

As mentioned here (https://github.com/tensorflow/probability/issues/1832), and I think a no-brainer, regular releases together with a TF version are _crucial_ for any library depending on TensorFlow-Probability as well as the distribution via `conda-forge`, which is currently [stuck as well](https://github.com/conda-forge/tensorflow-probability-feedstock)

**Comment by jonas-eschle** [comment]
Ping @csuter @jburnim 

Is there any holding item for the releases for TF 2.17 or, more importantly, for the current release 2.18? We're currently stuck on [conda-forge with the current version](https://github.com/conda-forge/tensorflow-probability-feedstock) and aren't delivering TFP anymore, not to mention any downstream package that relies on regular versioning alone. Isn't there supposed to be regular releases? That's what packages rely on. Is there any help needed to do releases?

I think this should really get unstuck, it's becoming a bit of a dependency nightmare otherwise as libraries cannot upgrade to newer TensorFlow versions (or is TFP ment to be fully compatible? If so, the dependencies should be changed)

**Comment by csuter** [comment]
Hi Jonas, 0.25 is up as of a few moments ago, targeting tf 2.18. Please give it a try. Thanks for the nudge, and sorry for the recent lapse in releases.

**Comment by jonas-eschle** [comment]
Thanks a lot for the release! It's working and I am preparing the conda-forge release: https://github.com/conda-forge/tensorflow-probability-feedstock/pull/54

FYI, if this is of relevance: As TF has been removed as a strict dependency, it has been requested to do so in conda-forge as well (https://github.com/conda-forge/tensorflow-probability-feedstock/issues/53). While conda-forge is usually "batteries included", TF is a heavy dependency and I planned to drop both TF and JAX as a dep there (to be explicitly requested by a user). If you have any concerns or disagree, just let us know in the [PR](https://github.com/conda-forge/tensorflow-probability-feedstock/pull/54)
