### ISSUE TITLE
[(LIVE.FREE™!)] UFC 309 Live Streams Free to Watch? Streaming Details 16 November, 2024

### ISSUE THREAD

**Issue by mondien** [tensorflow/probability#1868]
The heavyweight championship is on the line on Saturday night when champion Jon Jones takes on two-time former champion Stipe Miocic in the main event of UFC 309. The action goes down from the legendary Madison Square Garden in New York.

[🔴WATCH📺📱👉 UFC 309 LIVE STREAM](https://ufc.procast.live/?refd_by=clicktvnew)
[🔴WATCH📺📱👉 UFC 309 LIVE STREAM](https://ufc.procast.live/?refd_by=clicktvnew)
[🔴WATCH📺📱👉 UFC 309 LIVE STREAM](https://ufc.procast.live/?refd_by=clicktvnew)

Jones is considered by many to be the sport's greatest fighter of all time. His record in the light heavyweight division speaks for itself with title wins over some of the top fighters of the early era of UFC. However, long periods of inactivity continue to haunt him in the public eye as Jones has just one fight in the last three years.

Elsewhere on the card, a lightweight rematch between top contenders is set when former champion Charles Oliveira takes on former Bellator king Michael Chandler. The two previously met in 2021 for the vacant strap at 155 pounds with Oliveira overcoming an early barrage from Chandler to score a second-round knockout for the championship. It capped off an incredible career resurgence for the Brazilian as it was his ninth straight win. Oliveira went on to defend the title twice before finally meeting his match in current titleholder Islam Makhachev in October 2022. Chandler, meanwhile, hasn't seen the Octagon much since 2022 as he waited for Conor McGregor to join him. After spurts of expecting the fight to materialize, including for International Fight Week this year, Chandler finally moved on in an effort to stay active.

Below is all the information you need to catch UFC 309 on Saturday night.

Where to watch UFC 309 prelims
Date: Nov. 16 | Location: Madison Square Garden -- New York
Time: 8 p.m. ET (6 p.m. ET for early prelims)
Channel: ESPNews/FX

Where to watch UFC 309 main card
Date: Nov. 16 | Location: Madison Square Garden -- New York
Time: 10 p.m. ET
Stream: ESPN+ PPV | Price: $79.99

Now, here's a look at the UFC 308 main fight card and betting odds.

UFC 309 main card, odds
Favorite Underdog Weightclass
Jon Jones (c) -625 Stipe Miocic +450 Heavyweight title
Charles Oliveira -265 Michael Chandler +215 Lightweights
Bo Nickal -1200 Paul Craig +750 Middleweights
Karine Silva -265 Viviane Araujo +215 Women's flyweights
Mauricio Ruffy -900 James Llontop +625
Lightweights

**Comment by rafinfazal65** [comment]
cx vxf d
