### ISSUE TITLE
Visualization and checking for sample results

### ISSUE THREAD

**Issue by yaochitc** [tensorflow/probability#188]
After finishing the sample process, it is usual to visualize and check the result. I think it is useful to implement some methods like pm.traceplot and pm.summary as in pymc3 instead of having to write codes.

**Comment by brianwa84** [comment]
Agreed, we were just discussing the option of adding a from_tfp to arviz.
PR to arviz and tfp as necessary would be welcome!

https://colcarroll.github.io/arviz_pydata_nyc/#/

**Comment by yaochitc** [comment]
Ok, I'll check the option.

**Comment by brianwa84** [comment]
Just noticed https://github.com/arviz-devs/arviz/pull/376 is moving forward, thanks!

**Comment by yaochitc** [comment]
In fact I just added the state that contains the posterior currently, thinking about adding the information in the sample result to it.

**Comment by yaochitc** [comment]
I've implemented most of the work, seems no need to change the tfp right now, just close the issus.
