### ISSUE TITLE
Feature request: PERT distribution

### ISSUE THREAD

**Issue by srhoades10** [tensorflow/probability#209]
I'd like to test out a beta-PERT distribution for my particular problem. However, I would also look for a way to use a Beta distribution and omit (a, b) < 1 to  avoid an arcsine-type of distribution (I'm modeling reaction activities, so I essentially want something more flexible than a Normal but on bounded support). As the calculations are very similar to a Beta, I wrote up a PERT distribution script, however I'm struggling to integrate it into my tf import (I get errors regarding input dtypes and tf.math.xlogy errors).

I'm happy to make a request for what I have made thus far, although I believe the the calculations for entropy and KL_div are only identical in the event of a lower bound of 0. Thanks!

**Comment by axch** [comment]
It would probably be easier to get PERT as a scale+shift transformation of a standard Beta than coding the computations directly.  Something like this:
```
alpha = 6 * (mean - min) / (max - min)
beta = 6 * (max - mean) / (max - min)
std_beta = tfp.distributions.Beta(concentration1=alpha, concentration0=beta)
pert = tfp.distributions.TransformedDistribution(
  distribution=std_beta,
  bijector=tfp.bijectors.AffineScalar(shift=min, scale=(max - min)))
```

If you would like to contribute a PERT implementation along those lines (which we would definitely appreciate!), you can take a look at the multivariate Gaussian as an example: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/mvn_linear_operator.py#L169-L193.  That's coded as a class that inherits from TransformedDistribution; it gets a nontrivial covariance by transforming an isotropic Gaussian with a linear operator bijector.

**Comment by srhoades10** [comment]
Thanks for the suggestion, I've since gone through the tfp's paper detailing the utility of bijectors, and I think this is a much simpler and concise approach. If I tidy up the PERT implementation then I can move forward to contribute, but I'll see if this Beta transformation suits my objectives too

**Comment by srvasude** [comment]
Closing this as PERT was added as a distribution.
