### ISSUE TITLE
Conda-forge

### ISSUE THREAD

**Issue by dirmeier** [tensorflow/probability#211]
Hello, 
are there any plans to add `probability` to `conda-forge`? Otherwise I could add the recipe there...
Best,
Simon

**Comment by brianwa84** [comment]
I don't think this is currently on our roadmap, but it seems there are a
number of users who might benefit from sharing this.

**Comment by flyaflya** [comment]
Yes, please add this.  This would greatly simplify life for my students.  Thanks.

**Comment by rongou** [comment]
+1

**Comment by dirmeier** [comment]
I'll close this issue. TFP is on conda-forge now thanks to @sodre: https://github.com/conda-forge/tensorflow-probability-feedstock
