### ISSUE TITLE
`mean_fn` in Gaussian Process not behaving as expected.

### ISSUE THREAD

**Issue by peterroelants** [tensorflow/probability#224]
I'm building a Gaussian process model where I'm setting a mean function `mean_fn`. However, after getting posterior predictions this mean doesn't seem to be accounted for in the posterior mean or any samples. I'm not sure if I'm using the API wrong or if this is an actual bug.

I adapted a Colab example to illustrate the issue: https://colab.research.google.com/gist/peterroelants/2d6702bce37aca447c6594b4c34479d2/gaussian-process-regression-in-tensorflow-probability.ipynb 

In the example I'm using a simple mean which is just the mean of my observations:
```
observations_mean = tf.constant([np.mean(observations_)], dtype=np.float64)
mean_fn = lambda _: observations_mean
```
Next I'm using this `mean_fn` in two places. The first one is during optimization of the model parameters:
```
gp = tfd.GaussianProcess(
    mean_fn=mean_fn,
    kernel=kernel,
    index_points=observation_index_points_,
    observation_noise_variance=observation_noise_variance)
```
And after tuning the parameters to make posterior predictions.
```
gprm = tfd.GaussianProcessRegressionModel(
    mean_fn=mean_fn,
    kernel=kernel,  # Reuse the same kernel instance, with the same params
    index_points=predictive_index_points_,
    observation_index_points=observation_index_points_,
    observations=observations_,
    observation_noise_variance=observation_noise_variance,
    predictive_noise_variance=0.)
```
However, the postior doesn't seem to take this mean into account when getting the postior mean `gprm.mean()` or samples `gprm.sample(num_samples)`. There is a difference of `observations_mean` between what values I'm getting and what values I'm expecting to get. I've added an example in the following figure:

![mean_off](https://user-images.githubusercontent.com/951093/48311272-3eb90200-e595-11e8-8f6b-fdd3cac5b4c5.png)

**Comment by axch** [comment]
Looks like a bug.  The posterior predictive location should probably depend on `self._mean_fn(self.index_points)`, but code inspection suggests it does not.  Thank you for catching it!  @csuter, take a look?

**Comment by csuter** [comment]
Thanks for raising this! Fix is on the way.
