### ISSUE TITLE
build from source with option --gpu not recognized

### ISSUE THREAD

**Issue by jcsh4326** [tensorflow/probability#227]
I try to use tensorflow_probability on google colab with GPU.

Since googel colab use CUDA 9.2, so I have to build tfp from source.

I builded it with that code `!./bazel-bin/pip_pkg $PKGDIR --gpu --release` as the comments mentioned in `./bazel-bin/pip_pkg`.

But I got an error as 
```
++ uname -s
++ tr A-Z a-z
+ PLATFORM=linux
+ [[ 3 -lt 1 ]]
+ mkdir -p 60
++ dirname 60/does_not_exist
+ DEST=60
++ cd 60
++ pwd
+ DEST=/content/probability/60
+ cd bazel-bin/pip_pkg.runfiles/tensorflow_probability
+ python setup.py bdist_wheel --universal --gpu --release --dist-dir=/content/probability/60
/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.6.0-dev' to '0.6.0.dev0'
  normalized_version,
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --gpu not recognized
```
What can I do for solving it ?
BTW. I have successfully builded it without gpu,

**Comment by jcsh4326** [comment]
I just see the Latest commit of  setup.py, it eliminate GPU build. So I can just build `tfp-nightly` instead of `tfp-nightly-gpu` and use tensorflow with GPU.

**Comment by csuter** [comment]
Hi, are you still having trouble with this? We recently got rid of gpu-specific packaging and build; just install the appropriate tensorflow underneath, instead. When building our pip package, just omit the --gpu flag.

**Comment by csuter** [comment]
Feel free to reopen if you're still having trouble

**Comment by Pindar777** [comment]
@csuter 
Please have a look at this issue
https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/issues/430
I encountered that GPU is not used by TFP.

**Comment by Pindar777** [comment]
@jcsh4326 Could you finally use tf-probability with GPU. 
@csuter I'm still struggling with that. Even after updating to tf 1.13.1, CUDA 10, cuDNN 7.5 and tfp 0.6
