### ISSUE TITLE
Getting nan as a probability in high-dimensional spaces

### ISSUE THREAD

**Issue by fortuin** [tensorflow/probability#233]
Hi everyone!
I am trying to implement a VAE-like architecture in TFP and get a `nan` loss. I found out that this is due to the probability becoming `nan` in high-dimensional spaces (i.e., with a large latent space), since the untrained encoder will embed the data into places of the latent space that are usually not too close to the origin.
The error can be reproduced with this toy example:

```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tf.reset_default_graph()

for target_shape in [1, 10, 100, 1000]:
    mean_vec = np.tile([0.0], target_shape)
    std_vec = np.tile([0.1], target_shape)
    dist_test = tfp.distributions.MultivariateNormalDiag(loc = mean_vec,
                                                         scale_diag = std_vec,
                                                         allow_nan_stats=False)

    with tf.Session() as sess:
        print(dist_test.prob(np.tile([1.0], target_shape)).eval())
        
# Output:
# 7.694598626706408e-22
# 7.275447423157728e-212
# 0.0
# nan
```

I am using `numpy 1.15.2`, `tensorflow-gpu 1.12.0` and `tensorflow-probability 0.5.0` in `Python 3.6.6`.
Can anyone explain why the probability in this case would become `nan` and not just stay at 0.0? Is there a fix for this kind of behavior?
Thanks for your help!

**Comment by junpenglao** [comment]
The probability in high dimension could be too small - so small that it is below numerical precision. You should work in log space instead, something like: 
```
print(dist_test.log_prob(np.tile([1.0], target_shape)).eval())
```

**Comment by axch** [comment]
The OP is right, however, that underflow shouldn't cause the direct-space probability to become nan.  Working in log space is certainly a good practical solution, but maybe we should look into causing the direct-space probability to be 0 instead.

**Comment by csuter** [comment]
Not an answer, but a note: rewriting with Independent(Normal(...)) works:

```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp


for target_shape in [1, 10, 100, 1000]:
    tf.reset_default_graph()
    mean_vec = np.tile([0.0], target_shape)
    std_vec = np.tile([0.1], target_shape)
    dist_test = tfp.distributions.Independent(
        tfp.distributions.Normal(loc = mean_vec, scale = std_vec),
        reinterpreted_batch_ndims=1)

    with tf.Session() as sess:
        print(dist_test.prob(np.tile([1.0], target_shape)).eval())
# Output
# 7.69459862671e-22
# 7.27544742316e-212
# 0.0
# 0.0
```

Also, using log_prob instead of prob does prevent `NaN`, although I agree we should not be getting the `NaN` at all.

**Comment by axch** [comment]
Looking at that code, why don't we just delete it and rely on the default implementation of prob as exp(log_prob)?  I do not at first glance see any advantage to implementing the computation in direct space.

**Comment by csuter** [comment]
(Just raised that exact question internally; likely answer, I suspect, is "no reason -- that's what we should be doing)

**Comment by fortuin** [comment]
Thanks a lot for your replies! I'm working in log-space now and that works well. I agree that `tf.exp(dist.log_prob(.))` seems to be a generally good solution for the problem, but I am obviously not acquainted so deeply with the internals of TFP as to be able to fully assess the implications of such a change...
