### ISSUE TITLE
Should not call `warnings.simplefilter` in a library

### ISSUE THREAD

**Issue by ywkim** [tensorflow/probability#237]
### Description
Importing `tensorflow_probability` changes the current warnings filter, making it very difficult to control warnings using standard Python syntax, e.g `-W` command flag.

### Steps/Code to Reproduce
The function `inspect.getargspec` is deprecated since version Python 3.0 and using it results in a warning. See also https://github.com/tensorflow/tensorflow/issues/16152.

```python
import tensorflow_probability
from inspect import getargspec

def foo(x):
    pass

getargspec(foo)
```

```
$ python3 example.py
example.py:7: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  getargspec(foo)
```

I'm surprised to see a `DeprecationWarning` — that's not supposed to happen in Python unless I ask to see it. Let me try to ignore the warning.

```
$ python3 -W ignore example.py
example.py:7: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  getargspec(foo)
```

It is not possible to change the warnings filter, because it is hardcoded in the `tensorflow_probability`!

### Expected Results
- Don't configure the warnings filter. This behavior should be controlled by an application or an end user, not a library.
- If you feel like you really must do this, please use [append=True](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings)

**Comment by davmre** [comment]
Good catch! (and thanks for making a PR!) I'm guessing this is vestigial code. Let's discuss on the PR (#236).
