### ISSUE TITLE
NaN Entropy for Categorical Distribution

### ISSUE THREAD

**Issue by harrismirza** [tensorflow/probability#241]
If you have a Categorical Distribution with any of the probabilities equal to 0, the returned Entropy is NaN. This should not be the case, when the probability is 0, it should be ignored.

e.g: If the probabilities of your distribution = [0,0.5,0.5] then entropy should be ~0.69 and when probabilities = [0,0,1] then entropy should be 0.

**Comment by harrismirza** [comment]
I added a pull request:

https://github.com/tensorflow/probability/pull/242

**Comment by srvasude** [comment]
Fixed by https://github.com/tensorflow/probability/pull/242. Thanks!
