### ISSUE TITLE
Mistake in KL divergence computation of bayesian neural network

### ISSUE THREAD

**Issue by ImranRolo** [tensorflow/probability#246]
In the file [probability/tensorflow_probability/examples/bayesian_neural_network.py](https://github.com/tensorflow/probability/blob/e00ab7df4b3865054a39f8af64e85e31123aba5c/tensorflow_probability/examples/bayesian_neural_network.py#L260) , on line 263, the KL divergence is computed as the sum of the losses of each layer: `kl = sum(neural_net.losses) / mnist_data.train.num_examples`.

However the KL divergence **does not equal to** the sum of the losses of the weights. Elsewhere in the TensorFlow_probability documentation the KL divergence is implemented with the KL divergence inbuilt function: 
[tf.distributions.kl_divergence](https://www.tensorflow.org/api_docs/python/tf/distributions/kl_divergence) for example in [here](
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/edward2/Upgrading_From_Edward_To_Edward2.md#variational-inference) so the [probability/tensorflow_probability/examples/bayesian_neural_network.py](https://github.com/tensorflow/probability/blob/e00ab7df4b3865054a39f8af64e85e31123aba5c/tensorflow_probability/examples/bayesian_neural_network.py) file should be updates with the _tf probability distributions_ function of the KL divergence as well.

**Comment by SiegeLordEx** [comment]
That example is written using TFP's variational Bayesian layers, and for those layers (by default) the losses are in fact computed using `tfp.distributions.kl_divergence`:
https://github.com/tensorflow/probability/blob/50f38f3b0184c1a441921fb7826d9c76672ca44f/tensorflow_probability/python/layers/dense_variational.py#L297-L308

And here's where the default is set:

https://github.com/tensorflow/probability/blob/50f38f3b0184c1a441921fb7826d9c76672ca44f/tensorflow_probability/python/layers/dense_variational.py#L101

**Comment by ImranRolo** [comment]
Thanks! Perhaps it should be more explicit about this in the documentation. I assumed [losses](https://www.tensorflow.org/api_docs/python/tf/keras/models/Sequential#losses) referred to the difference in the norms of the weights before and after the updates of the network rather than the KL divergence between the weight distributions before and after the networks.
