### ISSUE TITLE
Automatically differentiation via MCMC

### ISSUE THREAD

**Issue by JiahaoYao** [tensorflow/probability#250]
```python
samples, _ = tfp.mcmc.sample_chain(
            num_results=1000,
            current_state=dtype(1),
            kernel=tfp.mcmc.RandomWalkMetropolis(
               target_log_prob_fn,
               seed=42),
            num_burnin_steps=500,
            parallel_iterations=1)
```

If there is a trainable variable in the `target_log_prob_fn`, then we can get the samples from this way. So does the differentiation go through the sample to the trainable variables in the  `target_log_prob_fn`?

**Comment by junpenglao** [comment]
In `RandomWalkMetropolis` there is no gradient operation so you are safe, but if you are using eg HMC, you should set `state_gradients_are_stopped=True`, see: https://github.com/tensorflow/probability/blob/0806024d91784685ae7b0e32c0af5e5eec31f151/tensorflow_probability/python/mcmc/hmc.py#L413-L416

**Comment by JiahaoYao** [comment]
Thanks @junpenglao. So, this issue is closed now.
