### ISSUE TITLE
tfp does not play nice with ipython terminal tab autocomplete

### ISSUE THREAD

**Issue by henrysky** [tensorflow/probability#251]
It seems like tfp has issue with ipython terminal tab autocomplete, showing a bunch of error message when tab completing tfp. But it is fine when using jupyter notebook/lab. I am currently using `ipython 7.2.0` but the issue can still be reproduced with something like `ipython 6.5.0` on Windows, MacOS and Ubuntu

Some of the many ways to reproduce this is
```python
from tensorflow_probability import <tab>
```

```python
from tensorflow_probability.<tab>
```

```python
from tensorflow_probability.layers import <tab>
```

![untitled](https://user-images.githubusercontent.com/28623434/50126909-e08ad900-023c-11e9-91a7-8b97266575c1.png)

**Comment by davmre** [comment]
This might be related to https://github.com/tensorflow/probability/issues/237.

**Comment by brianwa84** [comment]
Is this resolved by the commit mentioned above?

**Comment by henrysky** [comment]
> Is this resolved by the commit mentioned above?

Yes it is fixed thanks
