### ISSUE TITLE
Optimizing the log prob of HMC MC gives error on variable initialization

### ISSUE THREAD

**Issue by Joshuaalbert** [tensorflow/probability#256]
## Context
I came across this error while writing a maximum likelihood optimization of the average log probability of an MCMC (SAEM).
Basically, I was able to narrow it down to the below MVCE.
When not optimizing the average chain log prob, the MCMC runs fine.
## Error
Running the below MVCE fails at `sess.run(init_op)` giving,
``` bash
InvalidArgumentError: Input 1 of node gradients/mcmc_sample_chain/scan/while/smart_for_loop/while/mh_one_step/hmc_kernel_one_step/while/Switch_3_grad/b_switch was passed float from NextIteration:0 incompatible with expected double.
```
## MVCE

```python
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

class TargetDistribution(object):
    def __init__(self, m, var):
        #num_chains, N
        self.m = m
        self.var = var

        
    def logp(self, z_t):
        #N, N
        L = self.var*tf.ones((10,10),dtype=tf.float64)
        P = tfp.distributions.MultivariateNormalTriL(loc=self.m, scale_tril=L[None,:,:])
        #num_chains
        log_prob = P.log_prob(z_t)

        return log_prob
    
    def chain_logp(self):
        
        step_size = tf.get_variable(
                name='step_size',
                initializer=lambda: tf.constant(1.,dtype=tf.float64),
                use_resource=True,
                dtype=tf.float64,
                trainable=False)
        
        hmc = tfp.mcmc.HamiltonianMonteCarlo(
                        target_log_prob_fn=self.logp,
                        num_leapfrog_steps=2,
                        step_size=step_size,
                        step_size_update_fn=tfp.mcmc.make_simple_step_size_update_policy(target_rate=0.75))

        #num_chains, N
        q0 = tf.zeros_like(self.m)

        _, kernel_results = tfp.mcmc.sample_chain(
            num_results=1,
            num_burnin_steps=0,
            current_state=q0,
            kernel=hmc)
        
        posterior_log_prob = tf.reduce_sum(kernel_results.accepted_results.target_log_prob,name='marginal_log_likelihood')

        return posterior_log_prob

with tf.Session(graph=tf.Graph()) as sess:   
    
    var = tf.get_variable('A',shape=(),trainable=True,dtype=tf.float64)
    # works with:
    # m = tf.placeholder(tf.float64,shape=(1, 10))
    # m = tf.placeholder(tf.float64,shape=(1, None))
    # doesn't work with
    m = tf.placeholder(tf.float64,shape=(None, 10))
    
    P = TargetDistribution(m, var)
    logp = P.chain_logp()
    
    opt = tf.train.AdamOptimizer(1e-1).minimize(-logp,var_list=[var])

    init_op = tf.variables_initializer(tf.global_variables())    
    sess.run(init_op)
```

**Comment by Joshuaalbert** [comment]
I have been testing different ways to cause this error. The simplest way is to set the independent chain dimension to None, of the returned tensor of the target distribution function.

**Comment by matthewdhoffman** [comment]
In general backprop _through_ HMC is dangerous, because the accept-reject step is a discontinuous function.

However, using HMC in SAEM should work fine as long as you use `stop_gradient()` on the output of the chain. If you don't do that, you'll get gradients that are some combination of more expensive, biased, and unsupported. Unfortunately that may be a little wasteful compared to what you're doing (using the log-probs returned in `kernel_results`), but it's the correct thing to do. (We should look into supporting SAEM using the log-probs returned in `kernel_results`.)

All that being said, a quick glance suggests that the cause of this specific error message may be that HMC expects `tf.float32`s, and you're giving it `tf.float64`s without an explicit cast.

**Comment by Joshuaalbert** [comment]
@matthewdhoffman Thank you, I discovered that it was due to too strict shape invariants. The problem generally seems to be solved when I set the`TensorShape` of the output of the target distribution to the number of chains. When it it becomes inferred, due to the dynamic input, or some operation in the target distribution, then one should proceed to set the tensor shape as such.

With regards to supporting SAEM using `kernel_results`, the docstring itself contains an [example](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/mcmc/hmc.py#L334) where they do just that. I see your point that the proper way would be to first stop_gradients of the samples and recalculate the target_distribution. How easy would this be to build in? What would be the lost support in doing so?

**Comment by Joshuaalbert** [comment]
@matthewdhoffman , @brianwa84 The issue is solved by the above comment (i.e. you must ensure the `num_chains` dimension of the returned target distribution is inferable, i.e. set). Furthermore, with regards to SAEM, this can be safely accomplished by setting ```state_gradients_are_stopped=True``` in the constructor of ```HamiltonianMonteCarlo```.
