### ISSUE TITLE
DenseFlipout posterior distribution stdvs not apparent

### ISSUE THREAD

**Issue by ImranRolo** [tensorflow/probability#258]
In the documentation for [tfp.layers.DenseReparameterization](https://www.tensorflow.org/probability/api_docs/python/tfp/layers/Reparameterization), I can only appear to output the posterior means but not the posterior standard deviations. In the snippet below:

```
model = tf.keras.Sequential([
    tfp.layers.DenseReparameterization(512, activation=tf.nn.relu),
    tfp.layers.DenseReparameterization(10),
])
```
If I get the layers now:
`tf.trainable_variables()`

which gives:

```
[<tf.Variable 'sequential_1/dense_flipout_2/kernel_posterior_loc:0' shape=(5, 512) dtype=float32>,
 <tf.Variable 'sequential_1/dense_flipout_2/kernel_posterior_untransformed_scale:0' shape=(5, 512) dtype=float32>,
 <tf.Variable 'sequential_1/dense_flipout_2/bias_posterior_loc:0' shape=(512,) dtype=float32>,
 <tf.Variable 'sequential_1/dense_flipout_3/kernel_posterior_loc:0' shape=(512, 10) dtype=float32>,
 <tf.Variable 'sequential_1/dense_flipout_3/kernel_posterior_untransformed_scale:0' shape=(512, 10) dtype=float32>,
 <tf.Variable 'sequential_1/dense_flipout_3/bias_posterior_loc:0' shape=(10,) dtype=float32>]

```

At first I thought `kernel_posterior_untransformed_scale` was the standard deviation however it outputs values with negative numbers. It is possible that these are values `rho` such that `stdv = soft plus(rho)`. I cannot see this in the documentation however.

**Comment by SiegeLordEx** [comment]
Yes, `scale = tf.math.softplus(kernel_posterior_untransformed_scale)` is the correct reverse transformation.

One way to get at these qualities in an "official" way is to do:

```python
layer = tfp.layers.DenseReparameterization(10)
kernel_posterior_mean = layer.kernel_posterior.mean()
kernel_posterior_std = layer.kernel_posterior.stddev()
```

We definitely need to boost the documentation around this, however.
