### ISSUE TITLE
Bayesian Neural Network example - module not found error

### ISSUE THREAD

**Issue by Raj-DIAL** [tensorflow/probability#265]

**Comment by Raj-DIAL** [comment]
from tensorflow_probability.examples.models.bayesian_vgg import bayesian_vgg

statement gives module not found error. The path is not correctly set?

**Comment by brianwa84** [comment]
maybe `from tensorflow_probability.examples.models import bayesian_vgg`? reopen if that doesn't work

**Comment by brianwa84** [comment]
Never mind, I see the issue - we are removing the `examples` module from `__init__.py`

**Comment by brianwa84** [comment]
I guess that's probably intended, and the examples directory is targeted at copy-paste type usage. @csuter wdyt?

**Comment by Raj-DIAL** [comment]
I had to change it to from models import bayesian_vgg, perhaps it is meant to be run from a different location by copy pasting.

**Comment by csuter** [comment]
IIRC we made a call to only support running such examples via "bazel run". @Raj-DIAL can you give that a try (or confirm that that's what you're doing and it still doesn't work)?

**Comment by csuter** [comment]
(admittedly this was not ideal but we couldn't come up with a simpler solution)

**Comment by brianwa84** [comment]
We could add 'examples' to `tfp/__init__.py`

**Comment by csuter** [comment]
> We could add 'examples' to `tfp/__init__.py`

This is intentionally not done. The core library shouldn't depend on or include example code directly. We could perhaps consider a canned 'models' module (or separate package?), with appropriate unit tests, documentation, etc.

**Comment by Raj-DIAL** [comment]
@csuter I was just running it as python cifar10-bnn.py in the examples directory (~/probability/tensorflow_probability/examples). So perhaps that explains. However, I cant run the suggested "bazel run tensorflow_probability/examples:cifar10_bnn" from that same directory. I had to run it from ~/probability. Sorry, I am new to this environment. Why some examples run with basic command run python and some needs bazel?

**Comment by Raj-DIAL** [comment]
Thanks @csuter. I confirm all your suggestions on bazel works. Perhaps this can be added in file for others! I completely missed that part!

**Comment by csuter** [comment]
Ah here's where I was remembering that we had written this out at some point: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/cifar10_bnn.py#L22

We should pull that out to a more general README or HOWTO.
