### ISSUE TITLE
NotImplementedError: Caching devices are not yet supported when eager execution is enabled (for bijector.forward())

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#273]
Hi, I am getting the above error 

```
NotImplementedError: 
Caching devices are not yet supported when eager execution is enabled.
```

with this code snippet (simplified from https://github.com/ericjang/normalizing-flows-tutorial/blob/master/nf_part2_modern.ipynb and modified to use eager execution).

Could you please take a look?
Thank you!

```
import tensorflow as tf
tf.enable_eager_execution()

import tensorflow_probability as tfp
tfd = tfp.distributions
tfb = tfp.bijectors

base_dist = tfd.MultivariateNormalDiag(loc = tf.zeros([2], tf.float32))
x = base_dist.sample(8000)

test_b = tfb.MaskedAutoregressiveFlow(
  shift_and_log_scale_fn = tfb.masked_autoregressive_default_template(
    hidden_layers = [512, 512]))
    
test_b.forward(x)
```

**Comment by skeydan** [comment]
Just tested with a new build of TF master and TFP master, - I still get the same error.

@axch were you able to take a look? Thanks!

cc @jvdillon @jburnim

**Comment by axch** [comment]
I reproduced the problem; working on a fix.

**Comment by jburnim** [comment]
We have committed a fix.  Please let us know if you are still seeing the error.  And thanks for reporting this issue!

**Comment by skeydan** [comment]
Works great, thank you!!
