### ISSUE TITLE
hmc with adaptive step size in `mcmc.sample`

### ISSUE THREAD

**Issue by adder** [tensorflow/probability#28]
I adopted the adaptive stepsize code provided in the example in the help of `mcmc.hmc`.
The hmc stepsize is adapted during warmup and the final warmup stepsize is used to sample from the posteriors.

I was wondering if its possible to somehow do adaptive stepsizes with `mcmc.sample` to run (multiple) hmc chains? 
Or should I resort to implementing the adaptive stepsize low level as done in the `mcmc.hmc` help and  copy the final `step_size` and `current_state` to a new hmc kernel to use with 'mcmc.sample'?

**Comment by jvdillon** [comment]
Yep! We're currently exploring how to add this feature. We'll update this thread once we have a plan in O(days).

**Comment by brianwa84** [comment]
Our current preferred way to do this (currently only in tfp-nightly) is using tfp.mcmc.SimpleStepSizeAdaptation. There is also a less performance approach using variables in our released versions.
