### ISSUE TITLE
InverseGamma distribution rate versus scale parametrization

### ISSUE THREAD

**Issue by nowozin** [tensorflow/probability#283]
The `InverseGamma` distribution class claims ot use a `rate` parametrization throughout the code, such as [in its initializer method](https://github.com/tensorflow/probability/blob/86ec046cca80c277a31c2fea99cb99e50aa78b0c/tensorflow_probability/python/distributions/inverse_gamma.py#L132)

However, [checking against other sources](https://www.rdocumentation.org/packages/nimble/versions/0.6-12/topics/Inverse-Gamma), I believe the current code actually uses a scale parametrization and incorrectly calls the scale parameter `rate`.

### Rate Parametrization

For a given density _f(x;a,b)_ a parameter _b_ is said to be a _rate parameter_ if the density satisfies f(x;a,b) = b f(b x;a,1).

The simplest example where this can be immediately seen is the [_exponential distribution_](https://en.wikipedia.org/wiki/Exponential_distribution), which is most often parametrized using rate.

### `InverseGamma` example

The following code demonstrates that the `rate` argument to `InverseGamma` is not a rate parameter.

```python
import numpy as np
import tensorflow as tf
from tensorflow_probability.python.distributions import inverse_gamma
import matplotlib.pyplot as plt

dist1 = inverse_gamma.InverseGamma(concentration=1.0, rate=2.0)  # here "rate" means scale
dist2 = inverse_gamma.InverseGamma(concentration=1.0, rate=1.0)  # here "rate" means scale
xs = tf.linspace(0.0, 10.0, 1024)

fig, axes = plt.subplots(figsize=(8.0,2.5))
axes.plot(xs.numpy(), np.exp(dist1.log_prob(xs).numpy()), "k-", label="pdf conc 1, rate 2")
axes.plot(xs.numpy(), 2.0*np.exp(dist2.log_prob(2.0*xs).numpy()), "r--", label="pdf conc 1, rate 2")
axes.legend()
fig.tight_layout()
```

### Implications to Users

To the user, the use of the word rate to denote a scale parameter is confusing and can lead to problems when porting code from other libraries (e.g. from scipy).  If users are familiar with scale versus rate parameterizations they may also be used to converting between the two (scale = 1/rate), leading to errors.

### Proposed Fix

Drop the `rate` argument entirely from the constructor and instead add a `scale` argument.

(I believe the incorrect use of `rate` may originate from using the `Gamma` distribution in `sample` to construct inverse Gamma variates; the `Gamma` object is correctly using the term `rate` and indeed parametrizes its operations using the rate.  However, if X is distributed according to Gamma(shape=a, rate=b) then Y=1/X is distributed according to InverseGamma(shape=a,scale=b), not according to InverseGamma(shape=a,rate=b).)

**Comment by SiegeLordEx** [comment]
Thanks for your detailed analysis, I believe you're correct. We'll get this fixed.
