### ISSUE TITLE
convert_to_tensor TypeError

### ISSUE THREAD

**Issue by bkazi** [tensorflow/probability#290]
Using tfp-nightly (0.7.0.dev20190214) with tf-nightly-gpu-2.0-preview (2.0.0.dev20190213)

Get the following error when sampling from a TransformedDistribution that contains a BatchNormalization bijector

```
TypeError: convert_to_tensor_v2() got an unexpected keyword argument 'preferred_dtype'
```

It seems like the issue arises [at this line](https://github.com/tensorflow/probability/blob/a91ff8e91c1817fde78ac53ad07799ddc6025df5/tensorflow_probability/python/internal/distribution_util.py#L1298)  
judging by the [docs](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/convert_to_tensor) for `convert_to_tensor` it seems that `dtype_hint` should be used instead of `preferred_dtype`  
I could be wrong

**Comment by brianwa84** [comment]
You are correct. We have a fix coming.
