### ISSUE TITLE
sample not returning numpy

### ISSUE THREAD

**Issue by truittll** [tensorflow/probability#296]
I am starting off very basic. When I sample from any distribution, no numpy is returned. The shape is accurate, but numpy is simply not listed as an output. I'm sure I'm missing something obvious, but can't figure it out.

**Comment by csuter** [comment]
Are you using TensorFlow in graph mode or eager mode? In graph mode you need to create a Session object and call `sess.run(samples)` where `samples` is the Tensor object returned by the `Distribution.sample` method. In eager mode (put `tf.enable_eager_execution()` at the beginning of the program), you will get an `EagerTensor` instance which has a `numpy` accessor yielding the numpy array.

**Comment by truittll** [comment]
Yes, I was not in eager mode although I thought I was. Thanks for your help!
