### ISSUE TITLE
Replica Exchange Monte Carlo

### ISSUE THREAD

**Issue by YoshikawaMasashi** [tensorflow/probability#3]
Hi.

I implemented Replica Exchange Monte Carlo method for `edward`, recently.
(https://github.com/blei-lab/edward/pull/865)
I also want to implement this method for this repository.

Can I contribute for this project if I implement it?

Thanks.

**Comment by jvdillon** [comment]
Hi YoshikawaMasashi. We'd love to have your contribution!

Ideally it'd be possible to implement the low-level MCMC algorithm as a tfp.mcmc.TransitionKernel. Then, working with Dustin, you could consider using this low-level code in Edward2.

In a matter of days we'll be adding RandomWalkMetropolis so this may serve as a nice example in addition to HMC. (But feel free to begin your implementation whenever you like.)

**Comment by junpenglao** [comment]
BTW this can be close now.
