### ISSUE TITLE
Encoder mean and variance have shared parameters in the VAE example

### ISSUE THREAD

**Issue by May4m** [tensorflow/probability#315]
I noticed that the mean and variance of the encoder share the same parameters in line [213](https://github.com/tensorflow/probability/blob/225a735277af5a772240537915e4d2d03af9a253/tensorflow_probability/examples/vae.py#L213) and [220](https://github.com/tensorflow/probability/blob/225a735277af5a772240537915e4d2d03af9a253/tensorflow_probability/examples/vae.py#L220). In most implementations the encoder has a 2 head output for mean and variance

**Comment by jvdillon** [comment]
It still has 2 heads, we just kept things concatenated for vectorization purposes. It is true that prior to this last layer, the mean and variance share the same embedding space. However, to my knowledge, this is a standard architecture. (Please reopen if that explanation doesn't make sense and we can deep-dive.)
