### ISSUE TITLE
Tanh bijector inverse log det jacobian numerically unstable

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#318]
Hey,

The [Tanh bijector](https://github.com/tensorflow/probability/blob/ef6bb176e0ebd1cf6e25c6b5cecdd2428c22963f/tensorflow_probability/python/bijectors/tanh.py)'s forward log det jacobian computation was [recently made more numerically stable](https://github.com/tensorflow/probability/commit/ef6bb176e0ebd1cf6e25c6b5cecdd2428c22963f). This was good news, since we've been using our custom made [SquashBijector](https://github.com/rail-berkeley/softlearning/blob/d3d37b81668ee47bf43e799b3510f4e98e9640dc/softlearning/distributions/squash_bijector.py) in our [softlearning project](https://github.com/rail-berkeley/softlearning).

Unofortunately, however, the inverse computation is still numerically unstable. If I increase the tanh test data range to `np.linspace(-20., 20., 100).astype(np.float64)` instead of the current `np.linspace(-10., 10., 100).astype(np.float64)` in

https://github.com/tensorflow/probability/blob/4884692b925b7eeed57f6692b70841e333b5f110/tensorflow_probability/python/bijectors/tanh_test.py#L59

and run the tests from current master (https://github.com/tensorflow/probability/commit/76549303bd55e85ff650e009c8a15c858f983ea5), I get the following error:
```bash
2019-03-07 17:26:36.212884: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
[  FAILED  ] TanhBijectorTest.testBijectiveAndFinite
[ RUN      ] TanhBijectorTest.testBijector
[       OK ] TanhBijectorTest.testBijector
[ RUN      ] TanhBijectorTest.testMatchWithAffineTransform
[       OK ] TanhBijectorTest.testMatchWithAffineTransform
[ RUN      ] TanhBijectorTest.testScalarCongruency
[       OK ] TanhBijectorTest.testScalarCongruency
[ RUN      ] TanhBijectorTest.test_session
[  SKIPPED ] TanhBijectorTest.test_session
======================================================================
FAIL: testBijectiveAndFinite (__main__.TanhBijectorTest)
testBijectiveAndFinite (__main__.TanhBijectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kristian/conda/envs/softlearning/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 971, in decorated
    f(self, *args, **kwargs)
  File "./tensorflow_probability/python/bijectors/tanh_test.py", line 64, in testBijectiveAndFinite
    rtol=1e-4)
  File "/home/kristian/github/hartikainen/probability/tensorflow_probability/python/bijectors/bijector_test_util.py", line 222, in assert_bijective_and_finite
    assert_finite(ildj_f_x)
  File "/home/kristian/github/hartikainen/probability/tensorflow_probability/python/bijectors/bijector_test_util.py", line 30, in assert_finite
    raise AssertionError("array was not all finite. %s" % array[:15])
AssertionError: array was not all finite. [        inf         inf         inf 36.04365339 35.35050621 34.65735903
 33.7410683  32.95261094 32.15183309 31.34317302 30.53426505 29.72468528
 28.91676258 28.10878182 27.30060034]

----------------------------------------------------------------------
Ran 5 tests in 0.305s

FAILED (failures=1, skipped=1)
```

**Comment by jvdillon** [comment]
Thats for finding this. I will fix it ASAP.

**Comment by jvdillon** [comment]
Fix should be in by COB, Mar 11.

**Comment by jvdillon** [comment]
FIx in. Please re-open if you still see issues.
