### ISSUE TITLE
Support for Tensorflow 2 and TFP 0.7.0-dev

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [tensorflow/probability#323]
Hi all,

Sorry but TFP does not work at all with TF .2.0.0ao in my PC.
I tried to run [this cloab](https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb#scrollTo=_0HRI91zHWrh) file in my PC; however, the version of TF utilized in the colab is 
`print(tf.__version__, tfp.__version__)`

> 1.14.1-dev20190309 0.7.0-dev

Then I tried to check some cases in my PC:

`a= tfd.Bernoulli(probs=0.7)`
raise an error
>    ValueError: if neither `probs` nor `logits` were passed in, or both were.
TypeError: __init__() got an unexpected keyword argument 'values'

`a = tfd.Normal(0, 1);
 a.sample()`
will raise an error
> TypeError: __init__() takes 2 positional arguments but 4 were given

My TF version:
`tf.__version__`
> '2.0.0-alpha0'

My TFP version:
`tfp.__version__`
> '0.7.0-dev'

Hence `TF 2.0.0a0 `is not compatible with `TFP 0.7.0-dev`

**Comment by lc0** [comment]
![image](https://user-images.githubusercontent.com/775466/54081092-846fa800-42b3-11e9-87a2-a24b1e1d2b3a.png)
I just tested it with nightly versions of TF2 and TFP and it works for me

**Comment by ErmiaAzarkhalili** [comment]
> ![image](https://user-images.githubusercontent.com/775466/54081092-846fa800-42b3-11e9-87a2-a24b1e1d2b3a.png)
> I just tested it with nightly versions of TF2 and TFP and it works for me

Could you please let me know how to install TF2 nightly?

**Comment by jvdillon** [comment]
`pip install --upgrade {tf,tfp}-nightly`

Then in python,

```python
import tensorflow.compat.v2 as tf
import tensorflow_probability as tfp
tf.enable_v2_behavior()
```

[Here's a TF2 + TFP example.](https://colab.sandbox.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_VAE.ipynb)

**Comment by jvdillon** [comment]
Please reopen if the above procedure didnt work for you. In the coming days we'll also update the GH home page.
