### ISSUE TITLE
InvalidArgumentError: data[0].shape = [2] does not start with indices[0].shape = [3]

### ISSUE THREAD

**Issue by kalradivyanshu** [tensorflow/probability#327]
I am following the tutorial: https://medium.com/tensorflow/regression-with-probabilistic-layers-in-tensorflow-probability-e46ff5d37baf

But am getting the following error:

InvalidArgumentError: data[0].shape = [2] does not start with indices[0].shape = [3] [[{{node training/Adam/gradients/loss/output_1_loss/negloglik/weighted_loss/Mean_grad/DynamicStitch}}]] [Op:__inference_keras_scratch_graph_622]

Code:

`import tensorflow as tf
print("tf imported")
import tensorflow_probability as tfp
print("tfp imported")
tfd = tfp.distributions
tfk = tf.keras
tfkl = tfk.layers
import numpy as np

def get_prior():
    model1 = tfk.Sequential([
        tfkl.Dense(2),
        tfp.layers.DistributionLambda(lambda t: tfd.Gamma(t[..., :1], t[..., :1]), convert_to_tensor_fn=lambda s: s.sample(1))
    ])
    def negloglik(y, p_y):
        return -p_y.log_prob(y)
    model1.compile(tf.optimizers.Adam(learning_rate=0.05), loss = negloglik)
    return model1

model1 = get_prior()
inp = np.array([1., 2.], dtype = np.float32).reshape(1,2)

output = model1(inp)
print(output.sample())

model1.fit(x = inp, y = np.array([1]).reshape(1,1))`

Error:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-12-fa960fecd13a> in <module>
    2         return -p_y.log_prob(y)
    3 #model1.compile(tf.train.AdamOptimizer(learning_rate=0.05), loss = negloglik)
----> 4 model1.fit(x = inp, y = np.array([1]).reshape(1,1))

~/Desktop/MyCPU/P/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    872           validation_steps=validation_steps,
    873           validation_freq=validation_freq,
--> 874           steps_name='steps_per_epoch')
    875 
    876   def evaluate(self,

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    350 
    351         # Get outputs.
--> 352         batch_outs = f(ins_batch)
    353         if not isinstance(batch_outs, list):
    354           batch_outs = [batch_outs]

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
3220         value = math_ops.cast(value, tensor.dtype)
3221       converted_inputs.append(value)
-> 3222     outputs = self._graph_fn(*converted_inputs)
3223     return nest.pack_sequence_as(self._outputs_structure,
3224                                  [x.numpy() for x in outputs])

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
    538       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
    539           list(kwargs.keys()), list(self._arg_keywords)))
--> 540     return self._call_flat(args)
    541 
    542   def _filtered_call(self, args, kwargs):

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args)
    607     # Only need to override the gradient in graph mode and when we have outputs.
    608     if context.executing_eagerly() or not self.outputs:
--> 609       outputs = self._inference_function.call(ctx, args)
    610     else:
    611       self._register_gradient()

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args)
    414             attrs=("executor_type", executor_type,
    415                    "config_proto", config),
--> 416             ctx=ctx)
    417       # Replace empty list with None
    418       outputs = outputs or None

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
    64     else:
    65       message = e.message
---> 66     six.raise_from(core._status_to_exception(e.code, message), None)
    67   except TypeError as e:
    68     if any(ops._is_keras_symbolic_tensor(x) for x in inputs):

~/Desktop/MyCPU/P/myProject/tf2/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: data[0].shape = [2] does not start with indices[0].shape = [3]
    [[{{node training/Adam/gradients/loss/output_1_loss/negloglik/weighted_loss/Mean_grad/DynamicStitch}}]] [Op:__inference_keras_scratch_graph_622]

**Comment by kalradivyanshu** [comment]
The problem was I was passing in convert_to_tensor_fn, when I removed it, it worked as expected.

**Comment by edmondja** [comment]
Hi, what is the TF bug ?

**Comment by kiflowb777** [comment]
@kalradivyanshu How to remove convert_to_tensor_fn?
