### ISSUE TITLE
More flexible MAF/IAF bijectors

### ISSUE THREAD

**Issue by Skydes** [tensorflow/probability#330]
Thank you for this great repos, it's such an amazing toolbox!

I am wondering whether you plan to add more flexible MAF/IAF bijectors, for example replacing the shift+scale operation by the DSF or DDSF introduced in [Neural Autoregressive Flows (Huang et al., ICML18)](http://proceedings.mlr.press/v80/huang18d/huang18d.pdf). Although these are not strictly bijectors, as non invertible, they allow much more expressive models.

**Comment by brianwa84** [comment]
I kind of like the idea. It doesn't exactly fit the bijector mold, but maybe that's OK?
The NAF paper reminded me of Input Convex NNs: https://arxiv.org/abs/1609.07152
There is also Neural ODE and Augmented NODE, where the augmented bit could perhaps use this trick.

**Comment by SiegeLordEx** [comment]
NAFs are invertible, it's just that they don't have an analytic inverse (which is fine for API purposes, we can either not implement the inverse or do the numerical approximation). We definitely have internal research interest in NAF's, so they'll likely get implemented sooner rather than later.

**Comment by brianwa84** [comment]
I just committed `tfb.RationalQuadraticSpline`, which you should be able to use with `tfb.RealNVP` or `tfb.MaskedAutoRegressive`. Hopefully this lets you try some new and interesting stuff!
https://github.com/tensorflow/probability/commit/9c80b99d66b4f98d0b3cbf161c11b517b72842ee

**Comment by Skydes** [comment]
@brianwa84 That's great, thank you for letting me know! That should help quite a lot.
