### ISSUE TITLE
TensorFlow Probability: Learning with confidence (TF Dev Summit '19)

### ISSUE THREAD

**Issue by JimAva** [tensorflow/probability#332]
Where can I find documentation on the example code from the TF Summit 2019presentation?  For example, the DenseVariational layer.  I'd like to learn more about the parameters and see if I can use this layer for the multivariate dataset that I have.

**Comment by janithwanni** [comment]
I hope this might be helpful to you. 
[Link](https://www.tensorflow.org/probability/api_docs/python/tfp/layers/DenseLocalReparameterization) 
According to the documentation, 

Class DenseLocalReparameterization

Densely-connected layer class with local reparameterization estimator.

This layer implements the Bayesian variational inference analogue to a dense layer by assuming the kernel and/or the bias are drawn from distributions. By default, the layer implements a stochastic forward pass via sampling from the kernel and bias posteriors,

This is what you were looking for I believe.

**Comment by csuter** [comment]
The demo in the presentation was based on code that hasn't yet made it into a stable build (pip package "tensorflow-probability"). We hope to have one out as soon as possible (this might require a new stable TF release first, though).

In the mean time, the code is available in the pip package "tfp-nightly", which is updated automatically each night.

The demo from the presentation is available as a Colab notebook (source [here](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb), runnable Colab link [here](https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb). There, you can configure (and the default is set to) nightly builds for TFP and TF2.0.

The documentation we host at https://tensorflow.org/probability is reflective of the latest *stable* release (which is currently 0.6); we don't have nicely rendered API docs for the nightly at this time, sadly. However, all the docs are auto-generated from the python docstrings, so everything you need to know is there in the source code. We are happy to assist with specific issues here on the issue tracker or in the [discussion forum](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfprobability).

Hope this helps!

**Comment by csuter** [comment]
(please reopen if you have more questions!)
