### ISSUE TITLE
release timeline?

### ISSUE THREAD

**Issue by goldingn** [tensorflow/probability#34]
This is absolutely amazing work! I'm really excited to see where this goes and contribute if I can.

I'm switching to using probability as the sampler backend for [greta](https://greta-dev.github.io/greta/). The technical implementation is all done on the dev branch of greta, and works like a charm. But I can't release this version of greta until there's a stable release of probability that I can point users to install.

Do you have a rough timeline for when the first version might be released, so I can plan ahead?

**Comment by dustinvtran** [comment]
Hey @goldingn. Thanks for asking. We haven't decided on a rough timeline just yet. There are a few factors at play.

One hard restriction is depending on a compatible TF stable version. This can be difficult as the team often pushes code to both locations.

Another restriction is figuring out when we're mostly happy with the API and want to support backwards compatibility. Things are very likely not going to change, but we're not confident we can quite make that promise.

Do you have a particular timeline in which you'd like to release the new greta version? We're very open to taking suggestions!

**Comment by goldingn** [comment]
Great, thanks for letting me know!

I was hoping to release greta 0.3 with all the TFP stuff in mid-June, about 4 weeks from now. No worries if that's too soon for you, I can either push that back or explore other ways of making sure greta users get the right development version of TFP.

**Comment by goldingn** [comment]
Oh that sounds great, thanks Dave!

**Comment by dustinvtran** [comment]
Marking fixed.
