### ISSUE TITLE
Hierarchical bayes modeling with tfd.JointDistributionSequential

### ISSUE THREAD

**Issue by hellocybernetics** [tensorflow/probability#344]
I am a new user of TFP. 

` tfd.JointDistributionSequential` is a new class I hope it is very useful for probabilistic modeling. However I have some questions related hierarchical bayes modeling with that class.

First, below code represented this joint distribution.

p(X, mu) = N(mu | 0, 1) \prod_n N(x_n | mu, 1)

```python
model = tfd.JointDistributionSequential([
    # prior
    tfd.Normal(loc=0., scale=1.),
    # likelihood
    lambda mu: tfd.Independent(
        tfd.Normal(loc=mu, scale=1.),
        reinterpreted_batch_ndims=1,
    ),
])
```

This is ease of case. If we make hierarchical bayes modeling with joint distribution, for example,

p(X, a, b, c, d) = p(a)p(b)p(c | a)p(d |a, b, c) \prod_n p(x_n | d, b)

how to implement this model with `tfd.JointDistributionSequential`? 

My main question is how to inform relations of random variables using `lambda` function. Note that this model is DAG which has some jumping connection. We have to give list of distributions to `tfd.JointDistributionSequential`, and each distributions does not have name.

Second, when we implement regression model p(Y | b0 + b1*X )p(b0)p(b1), i think below code is a snipet.

```python
X_data, Y_data = load_data()

model = tfd.JointDistributionSequential([
    # prior of b0
    tfd.Normal(loc=0., scale=1.),
    # prior of b1
    tfd.Normal(loc=0., scale=1.),
    # likelihood
    lambda b1, b0: tfd.Independent(
        tfd.Normal(loc=b0+b1*X_data, scale=1.),
        reinterpreted_batch_ndims=1,
    ),
])
```

`X_data` is a global variable, but if we use mini-batch training with this model, inputs of regression model `X_data` should be inputed lazyly. 

This two questions are solved if using edward2 module.

Thank you for your seeing.

**Comment by brianwa84** [comment]
I think you will like some code I have under review right now, another take called `tfd.JointDistributionNamed`.

Your `p(X, a, b, c, d) = p(a)p(b)p(c | a)p(d |a, b, c) \prod_n p(x_n | d, b)` will become
```python
d=tfd.JointDistributionNamed((
    'a', SomeDist(),
    'b', SomeDist(),
    'c', lambda m: SomeDist(m.a),
    'd', lambda m: SomeDist(m.a, m.b, m.c),
    'x', lambda m: tfd.Sample(SomeDist(m.d, m.b), n)  # also new!
))
d.log_prob(d.namedtuple_type(a=a, b=b, c=c, d=d, x=data))
```

**Comment by brianwa84** [comment]
Also possible that you actually wanted x_i in which case you could do something like:
```python
d=tfd.JointDistributionNamed((
    'a', SomeDist(),
    'b', SomeDist(),
    'c', lambda m: SomeDist(m.a),
    'd', lambda m: SomeDist(m.a, m.b, m.c)) + tuple(
      zip(('x_{}'.format(i) for i in range(n)), 
          (lambda m: SomeDist(m.d, m.b) for i in range(n))
))
```

**Comment by jvdillon** [comment]
Just to add to Brian's answer:

```python
# p(X, mu) = N(mu | 0, 1) \prod_n N(x_n | mu, 1)
model = tfd.JointDistributionSequential([
    tfd.Normal(loc=0., scale=1.),
    lambda mu: tfd.Sample(tfd.Normal(loc=mu, scale=1.), n),
])


```python
# p(X, a, b, c, d) = p(a) p(c | a) p(b) p(d |a, b, c) \prod_n p(x_n | d, b)
model = tfd.JointDistributionSequential([
    A(),                                   # a
    lambda a: C(a),                        # c
    B(),                                   # b
    lambda b, c, a: D(a, b, c),            # d
    lambda d, b: tfd.Sample(X(d, b), n),   # x
])
```

(I'll now work on the third case.)

**Comment by hellocybernetics** [comment]
Thank you for your prompt reply.

@brianwa84 
I did not know the classes of  `tfd.JointDistributionNamed` and `tfd.Sample` which are so useful. When `tfd.JointDistributionNamed` will be added to repository ( or doc ) ?

@jvdillon 
Thank you for some ideas. 

#### question 1
I have same idea of Localize dependencies. This is readable code from the point of dependencies between rv as you say, so in many case, I will use this idea.

However, for example, in case that my interest may be what is the global rv or what is the local rv, I wanna put the global rv into place of top. In this case I will use dummy args strategy (or using `tfd.JointDistributionNamed`).



#### question 2
You recognize correctly my question. I had misunderstanding about `tfd.JointDistributionSequential` (I thought this class is used like `tf.keras.Sequential`). I should create an instance `JointDistributionsSequential` each time I change data `X_data`.




Is there sample code with `tfd.JointDistributionSequential` for example, representative probabilistic models such as PCA and LDA? It may helps me (and other beginners) for understanding `tfd,JointDistributionSequential` deeply.

**Comment by csuter** [comment]
Our friend and colleague @junpenglao has written some nice examples in https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb

I don't think PCA and LDA are covered, but hopefully you find it helpful in any case. Maybe you can write the PCA and/or LDA examples and send a PR! 😄

Glad you are enjoying this (very!) new feature!

**Comment by junpenglao** [comment]
re Question 2, in graph mode you can build the JointDistribution once, and use `feed_dict=` during training. I am not sure the equivalent in TF2 tho.

**Comment by jvdillon** [comment]
Note: `feed_dict` is deprecated in TF2. A more sustainable solution would be to use a factory as I indicated or a `tf.Variable` (although in this case that seem ill-advised).

**Comment by jvdillon** [comment]
One of our colleagues is putting together an HLM example using `JointDistributionSequential`. Here's the essential snippet we cooked up (which is very close to what you originally had too):

```python
@tf.function(autograph=False)
def affine(x, kernel_diag, bias):
  """`diag(kernel_diag) @ x + bias` with broadcasting."""
  kernel_diag = kernel_diag[..., tf.newaxis]
  x = tf.ones_like(kernel_diag) * x
  return tf.linalg.matmul(kernel_diag, x)[..., 0, :] + bias

def model(floor):
  """Creates a joint distribution representing our generative process."""
  return tfd.JointDistributionSequential([
      tfd.Normal(loc=0., scale=1e5),                  # beta0
      tfd.Normal(loc=0., scale=1e5),                  # beta1
      tfd.HalfCauchy(loc=0., scale=5),                # sigma
      lambda s, b1, b0 : tfd.MultivariateNormalDiag(  # y
          loc=affine(floor[tf.newaxis],
                     b1[..., tf.newaxis],
                     b0[..., tf.newaxis]),
          scale_identity_multiplier=s
    )
  ])

@tf.function(autograph=False)
def unnormalized_posterior_log_prob(beta0, beta1, sigma):
  """Computes `joint_log_prob` pinned at `log_radon`."""
  return model(floor).log_prob([beta0, beta1, sigma, log_radon])

assert [] == unnormalized_posterior_log_prob(0., 0., 1.).shape
assert [2] == unnormalized_posterior_log_prob([0.,0], [0., 0], [1., 1]).shape
```

What's nice about this implementation is that it automatically handles batches (of chains), as evident from the assertions at the bottom.

**Comment by jvdillon** [comment]
Anudhyan has now checked in the above example.
https://colab.sandbox.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Multilevel_Modeling_Primer.ipynb

**Comment by hellocybernetics** [comment]
Thank you for this discussion. I will continue to learn TFP.

**Comment by jvdillon** [comment]
The dictionary version has landed.
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/joint_distribution_named.py#L29

**Comment by jvdillon** [comment]
The coroutine version has landed.
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/joint_distribution_coroutine.py#L34
