### ISSUE TITLE
"no gradients provided" for simple affine flow with tf.variables and eager execution

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#345]
I apologize for cross-posting here a question I asked on the mailing list (there is a bit of time pressure...)

From Eric Jang's tutorial https://github.com/ericjang/normalizing-flows-tutorial/blob/master/nf_part1_intro.ipynb, I would assume I could train a simple affine bijector as follows:

```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
tfb = tfp.bijectors
tf.enable_eager_execution()

DTYPE=tf.float32
NP_DTYPE=np.float32

x = tf.constant(np.arange(20), shape = (10,2), dtype= tf.float32)
base_dist = tfd.MultivariateNormalDiag(loc=tf.zeros([2], DTYPE))

V = tf.get_variable('V', [2,2], dtype=DTYPE)
shift = tf.get_variable('shift', [2], dtype=DTYPE) 
L = tf.get_variable('L', [2 * (2 + 1) / 2], dtype=DTYPE)
bijector = tfb.Affine(
            scale_tril=tfb.FillTriangular().forward(L),
            scale_perturb_factor=V,
            shift=shift)
dist = tfd.TransformedDistribution(base_dist, bijector)
           
def loss(): return -tf.reduce_mean(dist.log_prob(x))
# ValueError: No gradients provided for any variable
tf.train.AdamOptimizer(1e-3).minimize(loss)           
# []
tf.trainable_variables()
```

This for me results in "no gradients", and no trainable variables found. The only difference I see to Eric Jang's code (apart from my totally simplifying stuff) is that I'm using eager execution.
Also, the same eager setup works fine if I use MaskedAutoregressiveFlow instead of AffineScalar (and thus, don't define variables myself).

Any help would be greatly appreciated!

**Comment by SiegeLordEx** [comment]
The solution is to move the distribution construction inside `loss`:

```python
def loss():
  bijector = tfb.Affine(
            scale_tril=tfb.FillTriangular().forward(L),
            scale_perturb_factor=V,
            shift=shift)
  
  return -tf.reduce_mean(tfd.TransformedDistribution(base_dist, bijector).log_prob(x))
```

The reason why it fails is that `tfb.Affine` wil pass the inputs through `tf.identity` inside the constructor, so when it is used inside `loss()`, there'll be no evidence that variables were ever used. In Eager mode, `loss()` must actually use the variables you want to optimize with respect to for the gradients to be computed.

**Comment by skeydan** [comment]
Thank you so much for the prompt answer!!! 

Then probably, even in the working version we expect an empty list from `tf.trainable_variables`, right? (which is what I get).

BTW I also see 

```
W0403 20:54:43.506436 140593784997952 backprop.py:965] 
The dtype of the source tensor must be floating (e.g. tf.float32) 
when calling GradientTape.gradient, got tf.resource
```

with every training batch, perhaps that is of interest to you? (working with the nightly build of TF and TFP)

**Comment by SiegeLordEx** [comment]
Yeah, `tf.trainable_variables` is a Graph concept, so it doesn't work in Eager.

**Comment by skeydan** [comment]
But I do see the `Variables` - even in Eager - when using a `MaskedAutoregressiveFlow` instead...
