### ISSUE TITLE
Multiple Regressions Use-Case Question

### ISSUE THREAD

**Issue by phynweb** [tensorflow/probability#346]
Hello...

I've been following the Tensorflow Probability project for some time now with a lot of interest. I am excited at the idea of being able to measure model uncertainty, however, i'm not quite sure i'm properly grasping the TFP concept, especially since i haven't seen an example that uses TFP the way i have in mind.

My use cases will primarily be multiple regressions, so my question is - how do i take an example like this - https://www.tensorflow.org/tutorials/keras/basic_regression - and apply TFP in a way that produces a prediction, and an uncertainty measure? Is there an example out there that i'm missing, or do I have the wrong idea on TFP's application?

Thanks!

**Comment by brianwa84** [comment]
Can you take a look at https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb and see if that helps?
