### ISSUE TITLE
exact tf and tfp versions

### ISSUE THREAD

**Issue by guyko81** [tensorflow/probability#347]
Can you provide the exact tf and tfp versions for structural time series modelling so anyone can reproduce the results? I mean with tf-2.0 the standard is eager; with tf-1.41 the variable_scope is different, etc.

https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Structural_Time_Series_Modeling_Case_Studies_Atmospheric_CO2_and_Electricity_Demand.ipynb

**Comment by junpenglao** [comment]
I think the notebook should run fine under TF2 preview and TFP nightly. The best way to try is running it in colab, where it has a code block to update the environment.

**Comment by noirmist** [comment]
This version is currently working.

```
!pip3 install -q --upgrade tf-nightly-gpu-2.0-preview
!pip3 install -q tfp-nightly

import tensorflow as tf
import tensorflow_probability as tfp

print("tf version:", tf.__version__)
print("tfp version:", tfp.__version__)
```

```
tf version: 2.0.0-dev20190408
tfp version: 0.7.0-dev
```
