### ISSUE TITLE
multiple regressors

### ISSUE THREAD

**Issue by JimAva** [tensorflow/probability#349]
In the example for sts.LinearRegression, temperature is the only external data.  In my case, I have 8 (or more) potential series.  In the documentation, it refers to the get_batch_of_inputs() routine for the design_matrix.  I've searched for sample code on this batch routine but haven't been able to find one.  Any suggestion would be greatly appreciated.     

design_matrix = get_batch_of_inputs()

**Comment by davmre** [comment]
Hi Jim, sorry the docs are unclear! Constructing the design matrix is up to
you (that routine is just a placeholder, intended as illustration). The
design matrix just needs to be a Tensor of shape `[..., num_timesteps,
num_features]`. If you have 8 covariate series, you'd just stack them along
the last axis to build a matrix with `num_features=8`.

Dave

**Comment by JimAva** [comment]
Thanks Dave - apologize for my ignorance, but I saw this example and wanted to confirm.  So, in my case I'd have 1D arrays named series1 thru series 8?

regression = tfp.sts.LinearRegression(
  design_matrix=tf.stack([series1, series2], axis=-1),
  weights_prior=tfd.Normal(loc=0., scale=1.))

**Comment by davmre** [comment]
Yup.

**Comment by axch** [comment]
Looks like this problem has been resolved?  Please reopen if anything remains unclear or needs fixing.
