### ISSUE TITLE
LinearRegression component using latent variables instead of parameters

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#357]
If I understand the current code correctly, then the [LinearRegression](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/sts/regression.py#L32) class implements a component of the form:

```
observed_time_series[t] = design_matrix[t] @ weights
```

with `weights` being a parameter/hyperparameter to be estimated on some fixed dataset using e.g. HMC.

I was wondering if there is any interest in adding a component which instead treats the weights as latent variables i.e.:

```
observed_time_series[t] = design_matrix[t] @ weights[t]
```

where `weights` has an initial Gaussian prior and Gaussian transition noise so that it always has a Gaussian distribution.

I guess this is similar to [LinearGaussianStateSpaceModel](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/linear_gaussian_ssm.py#L160) but I think the component would be very useful as it enables the user to build up a `LinearGaussianStateSpaceModel` from smaller easier to manage components.

Anyway, if my understanding is correct, that is, this is not currently implemented and might be useful, then please let me know and I will devote a few days work to adding this and sending a PR.

Thanks!

**Comment by davmre** [comment]
Hi Jeff!  If I understand correctly, the component you're thinking about is what's sometimes called a dynamic regression:
https://rdrr.io/cran/bsts/man/add.dynamic.regression.html

You're right that this is not currently implemented, but it'd be great to have it. If you have a chance to take a stab, that'd be great! I'm happy to review a PR, and/or to chat more about implementation details if you like.

**Comment by jeffpollock9** [comment]
@davmre that all sounds spot on, thanks! I'll have a go and if I get anywhere I'll send over a PR, if not I'll report back here.
