### ISSUE TITLE
dynamic programming layers

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#36]
From https://arxiv.org/abs/1802.03676
https://twitter.com/arthurmensch/status/994976710071373824
> __Differentiable Dynamic Programming for Structured Prediction and Attention__
> Arthur Mensch, Mathieu Blondel
> (Submitted on 11 Feb 2018 (v1), last revised 20 Feb 2018 (this version, v2))
>
> Dynamic programming (DP) solves a variety of structured combinatorial problems by iteratively breaking them down into smaller subproblems. In spite of their versatility, DP algorithms are usually non-differentiable, which hampers their use as a layer in neural networks trained by backpropagation. To address this issue, we propose to smooth the max operator in the dynamic programming recursion, using a strongly convex regularizer. This allows to relax both the optimal value and solution of the original combinatorial problem, and turns a broad class of DP algorithms into differentiable operators. Theoretically, we provide a new probabilistic perspective on backpropagating through these DP operators, and relate them to inference in graphical models. We derive two particular instantiations of our framework, a smoothed Viterbi algorithm for sequence prediction and a smoothed DTW algorithm for time-series alignment. We showcase these instantiations on two structured prediction tasks and on structured and sparse attention for neural machine translation.

A useful start could be the linear-chain CRF layer. @fchollet also mentioned this would be useful to have ported into TF(P) as implementations already exist.

**Comment by dustinvtran** [comment]
References
+ https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/layers/crf.py
+ https://github.com/tensorflow/tensorflow/tree/r1.10/tensorflow/contrib/crf

**Comment by dustinvtran** [comment]
Am no longer developing tfp.layers. Will work on this idea elsewhere.

**Comment by z687wang** [comment]
Hello there, are you working on this idea elsewhere?

**Comment by DesmondYuan** [comment]
Feature request! Plzzzz
