### ISSUE TITLE
ed.SGHMC in Edward2

### ISSUE THREAD

**Issue by chan-y-park** [tensorflow/probability#361]
Is ed.SGHMC of Edward implemented in Edward2? 

If not, 1) is there a plan to implement it in Edward2, and 2) if there is no such plan, can anyone give me some pointers how to translate ed.SGHMC into the framework of tf.probability? 

Thanks!

**Comment by davmre** [comment]
To clarify terminology somewhat: unlike Edward, Edward2 is 'just' a very lightweight framework for specifying probability models. It doesn't implement inference directly. The idea is that you can specify your model however you want (E2, manually-written log joint fn, other tools yet to be written, etc.) and then apply any of the inference tools from the surrounding TFP framework: tfp.mcmc, tfp.vi, tfp.optimizer, etc.

I don't know of anyone working on this currently, but it might be possible to adapt our SGLD implementation to SGHMC:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/optimizer/sgld.py

**Comment by chan-y-park** [comment]
Thanks for the pointer! Seems that a decent amount of work is needed to be done to implement SGHMC sampling, considering the SGLD implementation is focused on optimization, but it's definitely a good starting point, I presume. 

And also a huge gratitude for the clarification of the ideas behind Edward and Edward2. I hope that is declared more clearly in the overview documentation of ```tfp``` or ```tfp.edward2```, or maybe it is already there and I just missed it.

Let me close this issue then.
