### ISSUE TITLE
Why is eager execution of tensorflow probability much faster than non-eager execution?

### ISSUE THREAD

**Issue by mostafa-mahmoud** [tensorflow/probability#367]
Hello everyone,

I am trying to create a lot of probability distributions and sample from them big amounts of data, each distribution I create has different parameters (for simplicity I use the same parameters in the example below). I find that the eager execution is increadbly faster, however I can't sadly use it in the middle of the code because I get this error.

`tf.enable_eager_execution must be called at program startup.`

A small snippet of code that shows how eager execution is increadbly faster:  
```
#!/usr/bin/env python3
import os
import sys

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
import tensorflow_probability as tfp
from tqdm import tqdm


INTERACTIVE, EAGER, SESSION = 'interactive', 'eager', 'session'


interactive_session = None
session = None

def run(mean, std, sample_size, ex):
    if ex == EAGER:
        tf.enable_eager_execution()
    elif ex == INTERACTIVE:
        global interactive_session
        if interactive_session is None:
            interactive_session = tf.InteractiveSession()
    elif ex == SESSION:
        global session
        if session is None:
            session = tf.Session()
    else:
        assert ex in [INTERACTIVE, EAGER, SESSION]

    distribution = tfp.distributions.TruncatedNormal(mean, std, 0., 1.)
    data = distribution.sample([3, sample_size])

    if ex == EAGER:
        return data.numpy()
    elif ex == INTERACTIVE:
        return data.eval()
    elif ex == SESSION:
        return session.run(data)
    return


if __name__ == "__main__":
    mean, std, execution, inner_sample_size, outer_sample_size = sys.argv[1: 6]
    mean = float(mean)
    std = float(std)
    inner_sample_size = int(inner_sample_size)
    outer_sample_size = int(outer_sample_size)
    gen = (run(mean, std, inner_sample_size, execution)
           for _ in range(outer_sample_size))
    for dataset in tqdm(gen, total=outer_sample_size):
        pass
    print("")
```

Here, I call the function `run` 300 times, and orders of magnitude better than using a Session/InteractiveSession.
```
$ ./tensorflow_prob_slow.py 4 5 eager 5 300
100%|██████████████████████████████████████| 300/300 [00:00<00:00, 1041.28it/s]

$ ./tensorflow_prob_slow.py 4 5 session 5 300
100%|████████████████████████████████████████| 300/300 [00:54<00:00,  3.11it/s]

$ ./tensorflow_prob_slow.py 4 5 interactive 5 300
100%|████████████████████████████████████████| 300/300 [00:39<00:00,  4.21it/s]
```

Here, I call the function `run` 5 times only with bigger datasets,  it is still faster but not as much as in the first example.
```
$ ./tensorflow_prob_slow.py 4 5 eager 300 5
100%|███████████████████████████████████████████| 5/5 [00:00<00:00, 617.30it/s]

$ ./tensorflow_prob_slow.py 4 5 session 300 5
100%|████████████████████████████████████████████| 5/5 [00:00<00:00, 27.59it/s]

$ ./tensorflow_prob_slow.py 4 5 interactive 300 5
100%|████████████████████████████████████████████| 5/5 [00:00<00:00, 31.69it/s]

```

Additionally, there are more with bigger dataset sizes.
```
$ ./tensorflow_prob_slow.py 4 5 eager 3000 5
100%|███████████████████████████████| 5/5 [00:00<00:00, 134.08it/s]

$ ./tensorflow_prob_slow.py 4 5 session 3000 5
100%|████████████████████████████████| 5/5 [00:00<00:00, 22.92it/s]

$ ./tensorflow_prob_slow.py 4 5 interactive 3000 5
100%|████████████████████████████████| 5/5 [00:00<00:00, 38.12it/s]

$ ./tensorflow_prob_slow.py 4 5 eager 300000 5
100%|████████████████████████████████| 5/5 [00:00<00:00, 47.34it/s]

$ ./tensorflow_prob_slow.py 4 5 session 300000 5
100%|████████████████████████████████| 5/5 [00:00<00:00, 21.01it/s]

$ ./tensorflow_prob_slow.py 4 5 interactive 300000 5
100%|████████████████████████████████| 5/5 [00:00<00:00, 23.66it/s]
```

I am not sure if this is particularly a `tensorflow_probability` issue or just `tensorflow` generally. I didn't try to recreate such an example with a regular tensorflow operation.

I ultimately would like to run a function like `run` (a more complicated one) with many calls and with relatively big sampled datasets (tensor of 1,000,000 elements), either by figuring out a way to use eager in the middle of the code, or without eager but without losing the efficiency. I also hope to know why it is like this.

- tensorflow version: 1.12.0
- tensorflow_probability version: 0.5.0
- numpy version: 1.15.4
- Python version 3.6.5
- macOS 10.14.4 (Mojave)
- CPU only, no GPU

**Comment by mayou36** [comment]
No, that is correct. But you don't measure the execution time here, you measure the graph building and execution time. Like timing a C++ script and including the compilation time.

What happens is this: `run` does not just run the function (in eager mode is does) but it **constructs the graph** and then runs it. So to time the graph mode, you first have to (one time only) build the tensor `data` outside of the function and then `run` only calls `sess.run` (you should also move the creation of the session outside of the function).

so move
```
    distribution = tfp.distributions.TruncatedNormal(mean, std, 0., 1.)
    data = distribution.sample([3, sample_size])
```
outside of the function.

Why is that: TensorFlow builds a graph first (which is comparably time consuming) using all the information available and "optimizing" it. Then it get's finally executed. Consequent executions are way faster because the graph building is already done. But for a single run of a simple calculation, TF will always be slower in graph mode (because it is not designed for it). Compare a car vs bicycle. A bike may accelerates faster, but a car can reach way higher speeds. If you measure the completed distance in the first second, the bicycle wins. And it does not change if you repeat this experiment 300 times. It only changes once you measure 300 seconds of one acceleration.

**Comment by brianwa84** [comment]
You should reset the graph (`tf.compat.v1.reset_default_graph()`)if you will be rebuilding it every iteration. But really, you should just reuse the node in multiple calls to `session.run`.

TF graph mode runs a graph optimizer ("grappler") on the graph every time it changes between session runs. And in this case the graph has 1x, then 2x, then 3x, etc all the way up to 300x the original number of nodes, so you are paying (300)(300+1)/2 graph optimizations total.

**Comment by mostafa-mahmoud** [comment]
Thanks all for the reply! reusing the node fixed the issue, it's even faster now! (The code is shown below, with a short explanation of what I changed)

@mayou36 I wasn't fully aware of the overhead of creating the graph 300 times, additionally, I made a wrong assumption that the parameters to TruncatedNormal can't be tensors. Replacing them with placeholders, and reusing the same one graph 300 times was the solution. However, the session is global anyway, so it doesn't matter, I think.

$ ./tensorflow_prob_slow.py 4 5 session 5 300
100%|██████████████████████████| 300/300 [00:00<00:00, 3038.37it/s]

@brianwa84 I'm still curious how resetting the graph might work, I tried to add the reset statement at the end of the function `run`, but it didn't make an improvement. Placing it anywhere earlier raised exceptions that the tensors are not found. Is it necessary that resetting the graph would have made an improvement or was it just an attempt?

The run with resetting the graph:
$ ./tensorflow_prob_slow.py 4 5 session 5 300
100%|████████████████████████████| 300/300 [00:52<00:00,  3.22it/s]

```
def run(mean, std, sample_size, ex):
    if ex == EAGER:
        tf.enable_eager_execution()
    elif ex == INTERACTIVE:
        global interactive_session
        if interactive_session is None:
            interactive_session = tf.InteractiveSession()
    elif ex == SESSION:
        global session
        if session is None:
            session = tf.Session()
    else:
        assert ex in [INTERACTIVE, EAGER, SESSION]

    distribution = tfp.distributions.TruncatedNormal(mean, std, 0., 1.)
    data = distribution.sample([3, sample_size])

    if ex == EAGER:
        return data.numpy()
    elif ex == INTERACTIVE:
        return data.eval()
    elif ex == SESSION:
        return session.run(data)
    tf.reset_default_graph()
    return
```
_________________________________

The code that finally worked, building one graph with placeholders arguments, and feeding them 300 times instead of constructing 300 graphs.
```
#!/usr/bin/env python3
import os
import sys

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
import tensorflow_probability as tfp
from tqdm import tqdm


INTERACTIVE, EAGER, SESSION = 'interactive', 'eager', 'session'


interactive_session = None
session = None

def run(mean, std, sample_size, ex):
    if ex == EAGER:
        tf.enable_eager_execution()
    elif ex == INTERACTIVE:
        global interactive_session
        if interactive_session is None:
            interactive_session = tf.InteractiveSession()
    elif ex == SESSION:
        global session
        if session is None:
            session = tf.Session()
    else:
        assert ex in [INTERACTIVE, EAGER, SESSION]

    distribution = tfp.distributions.TruncatedNormal(mean, std, 0., 1.)
    data = distribution.sample([3, sample_size])

    if ex == EAGER:
        return data.numpy()
    elif ex == INTERACTIVE:
        return data.eval()
    elif ex == SESSION:
        return session.run(data)
    return


def construct_graph():
    mean_tensor = tf.placeholder(tf.float32)
    std_tensor = tf.placeholder(tf.float32)
    sample_size_tensor = tf.placeholder(tf.int32)

    distribution = tfp.distributions.TruncatedNormal(mean_tensor, std_tensor, 0., 1.)
    data = distribution.sample([3, sample_size_tensor])
    return data, [mean_tensor, std_tensor, sample_size_tensor]


def run_graph(graph, placeholders, mean, std, sample_size):
    global session
    if session is None:
        session = tf.Session()

    return session.run(graph, feed_dict=dict(zip(placeholders, [mean, std, sample_size])))


if __name__ == "__main__":
    mean, std, execution, inner_sample_size, outer_sample_size = sys.argv[1: 6]
    mean = float(mean)
    std = float(std)
    inner_sample_size = int(inner_sample_size)
    outer_sample_size = int(outer_sample_size)

    if execution == SESSION:
        graph, placeholders = construct_graph()
        gen = (run_graph(graph, placeholders, mean, std, inner_sample_size)
               for _ in range(outer_sample_size))
    else:
        gen = (run(mean, std, inner_sample_size, execution)
               for _ in range(outer_sample_size))
    for dataset in tqdm(gen, total=outer_sample_size):
        pass
    print("")
```

**Comment by mayou36** [comment]
Glad that you managed to make it work. This looks more realistic to me now. As parameters, you can use also tf.Variables or Constants, whatever you like basically ("anything" that `tf.convert_to_tensor` likes if I am right).

On the resetting: You should do this in the beginning _before_ creating a session (or otherwise close it). Something like

```python
def run():
	tf.reset_default_graph()
	with tf.Session() as sess:
		# create your graph here like:
		dist = tfd.TruncatedNormal(...)
		sample = ...
		sess.run(sample)
```

**Comment by brianwa84** [comment]
One last time to mention is that the "TF2 way" to do a graph with placeholders is to `@tf.function` decorate a python function. There the args become your placeholders and you can call the function in eager mode while getting graph performance. Be careful to call it with `Tensor` args to avoid re-tracing, as the internal graph representation is cache keyed on the dtypes+shape of Tensor args and the id of non Tensor args.

**Comment by axch** [comment]
I'm assuming this issue is resolved now.  Feel free to reopen (or start a new one) if there's anything else.
