### ISSUE TITLE
Tutorial request: BNN using Estimator

### ISSUE THREAD

**Issue by dave-fernandes** [tensorflow/probability#371]
The current bnn and cifar10 examples use old-style tf.Session. It would be helpful to have a simple example of a BNN that uses Estimator and Dataset. The VAE example is much more complicated and difficult to follow.

**Comment by janosh** [comment]
I was about to suggest the same thing. The [BNN example](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py) is a decent starting point, but as @dave-fernandes said, I think it would be much more insightful when ported to idiomatic TF 2.0.

**Comment by srvasude** [comment]
I'm going to close this since I believe the example is ported to TF2.
