### ISSUE TITLE
Bug in annealed importance sampling (AIS) example

### ISSUE THREAD

**Issue by travelbureau** [tensorflow/probability#376]
In:
tensorflow_probability/g3doc/api_docs/python/tfp/mcmc/sample_annealed_importance_chain.md

Line 93:
```
proposal = tfd.MultivatiateNormalDiag(
   loc=tf.zeros([dims], dtype=dtype))
```

Should be:

```
proposal = tfd.MultivariateNormalDiag(
   loc=tf.zeros([dims], dtype=dtype))
```

**Comment by axch** [comment]
The updated from #377 has propagated to https://github.com/tensorflow/probability/blob/master/tensorflow_probability/g3doc/api_docs/python/tfp/mcmc/sample_annealed_importance_chain.md.  It will propagate to the "more official" docs at https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/sample_annealed_importance_chain when we do a release.
