### ISSUE TITLE
error when using tfd.Deterministic() with   tfp.vi.monte_carlo_csiszar_f_divergence()

### ISSUE THREAD

**Issue by adder** [tensorflow/probability#378]
Hi,

> When using `tfd.JointDistributionNamed` for the surrogate posterior in    `tfp.vi.monte_carlo_csiszar_f_divergence` in latest tfp-nightly, I get the error below.
> 
> I narrowed down the error a bit further.
> `tfp.vi.monte_carlo_csiszar_f_divergence` calls `tfp.monte_carlo.expectation` wich calls   `tf.stop_gradient` on a sample from the surrogate posterior.
> However  `tf.stop_gradient` can't handle a `dict` of tensor as produced by  `tfd.JointDistributionNamed`

**EDIT:**
I was wrong this error has nothing to do with  `tfd.JointDistributionNamed`.
The error is because I had a `tfd.Deterministic()` distribution in the posterior constructed with  `tfd.JointDistributionNamed`.  (I'm trying to get MAP estimates)
Everything works fine when I use `tfd.Emperical()` instead.
Not sure if this is the supposed behavior?

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Attempt to convert a value ({'sigma': <tf.Tensor: id=574, shape=(5, 4587), dtype=float32, numpy=
array([[1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994]], dtype=float32)>, 'ridge_beta': <tf.Tensor: id=593, shape=(5, 4587), dtype=float32, numpy=
array([[1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.        , ..., 0.99999994, 0.99999994,
        0.99999994],
       [1.        , 1.        , 1.    

```

**Comment by axch** [comment]
Do you have a complete (ideally minimal) reproducing example?  I could take a look, but I don't have enough context as posted.

**Comment by srvasude** [comment]
Going to close this issue. If you still see this issue, please reopen.
