### ISSUE TITLE
ADVI results in negative 'mu' which may only be non-negative real number

### ISSUE THREAD

**Issue by WongyuChoi** [tensorflow/probability#389]
My apologies for almost zero knowledge in Variational Inference and ADVI. 

It seems one of variational inference example notebooks, **Modeling_with_JointDistribution.ipynb**, results in negative values in inference parameters ('mu' and 'sd'). 

For example, sigma_y, which is originally modeled as:
`tfd.HalfCauchy(loc=mu0, scale=5.)`, and used in the following likelihood:
```
tfd.Normal(
            # parameter transformation (linear equation), this is a long one
            loc=(tf.transpose((gamma[..., 0]
                             + gamma[..., 1]*u.values[:, None]
                             + gamma[..., 2]*xbar[county][:, None]))
                 + tf.gather(eps_a, county, axis=1)
                 + b[..., None]*floor_measure),
            scale=sigma_y[:, None]
        )
```

should have supposedly non-zero real value if I understand correctly. Resulting approximated parameters from ADVI is:

>'sigma_y': {'mu': -0.25675468712606553, 'sd': 0.07413891079361569}}

Having negative 'mu' makes sense at least within VI context because things are Normal in the meanfield ADVI, but using the above values to simulate **sigma_y** that is positive real and then using the original regression(likelihood) are not well understood to me. Maybe I am missing another step to use it for the original regression equation (the likelihood).

**Comment by junpenglao** [comment]
There are currently two ways to do it when it comes to ADVI, what I am doing in Modeling_with_JointDistribution.ipynb is the same as in the original paper - I transform the domains of a free parameter into Real if they are bounded, and approximated the posterior in the transformed (unbounded) space with a Gaussian distribution. This is the same approach as in PyMC3 and Stan.
So when you see `'sigma_y': {'mu': -0.25675468712606553, 'sd': 0.07413891079361569}}`, it is actually the approximation of `sigma_y` _after_ transformation.
Alternatively, you can transform the approximation to bounded space like in sts https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/sts/fitting.py#L89
The two approach should be identical.

**Comment by WongyuChoi** [comment]
@junpenglao It is great to hear from the author of the notebook.

Based on what you explained, it seems that the forward function of the bijector brings the space back to bounded space.

```
# after training is finished in ADVI
num_sample = 200000
advi = build_meanfield_advi(free_param)
simulated = _forward_transform(advi.sample(num_sample))
```

Now I can sample sigma_y as well. Thanks for this wonderful tool!
