### ISSUE TITLE
Triangular distribution has density of 1 at low point

### ISSUE THREAD

**Issue by cchan** [tensorflow/probability#391]
Repro below. There's a definite mismatch with both written spec and scipy behavior.

```
import tensorflow as tf
import tensorflow_probability as tfp

with tf.Session() as sess:
    ph = tf.placeholder(dtype=tf.float32)
    print(sess.run(tfp.distributions.Triangular(low=2.0, peak=4.0, high=6.0).prob(ph), {ph: 2}))
```

Output:

```
1.0
```

Expected output:
```
0.0
```

**Comment by cchan** [comment]
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/triangular.py#L237

should have `broadcast_x_to_high >= self.low`

**Comment by jvdillon** [comment]
Hi @cchan thanks for finding this bug. Would you be interested in making a PR to fix this problem?

**Comment by brianwa84** [comment]
I guess you missed #391, @jvdillon ?
