### ISSUE TITLE
Skew-Normal distribution

### ISSUE THREAD

**Issue by brianwa84** [tensorflow/probability#399]
PyMC folks would like a skew-normal (ideally multivariate) distribution. A start was made here: https://github.com/pymc-devs/pymc4/pull/85

**Comment by brianwa84** [comment]
Also see https://github.com/pymc-devs/pymc4/issues/44

**Comment by mihailyanchev** [comment]
Hi, would you know if there is a univariate version of the skewed normal distribution already implemented anywhere?

**Comment by leandrolcampos** [comment]
Hi @brianwa84,

Can I try to solve this issue implementing the univariate and multivariate skew-normal and skew-t distributions? I'd like to use the method proposed in [1] to construct a skew density from a symmetric one. For the univariate cases, the closed-form expressions for mean, variance, PDF, CDF, and inverse CDF are shown in [2] (see the distributions SN2 and ST3). A multivariate extension is outlined in [3], which also describes a general method for sampling from these distributions.

[1] Fernández, C., & Steel, M. F. (1998). On Bayesian modeling of fat tails and skewness. Journal of the American Statistical Association, 93(441), 359-371.

[2] Rigby, R. A., Stasinopoulos, M. D., Heller, G. Z., & De Bastiani, F. (2019). Distributions for modeling location, scale, and shape: Using GAMLSS in R. Chapman and Hall/CRC.

[3] Bauwens, L., & Laurent, S. (2005). A new class of multivariate skew densities, with application to generalized autoregressive conditional heteroscedasticity models. Journal of Business & Economic Statistics, 23(3), 346-354.

**Comment by brianwa84** [comment]
I think the closest thing we have right now is this:
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/GeneralizedNormal

As a general rule we'd welcome contributions of new distributions w/
tractable sampling & pdf. All the other methods are icing on the cake. It's
worth noting as you start that we have a bit higher of a bar than
many opensource projects in terms of testing, code style, etc. (probably
comparable to TensorFlow or Numpy)
https://github.com/tensorflow/probability/blob/main/CONTRIBUTING.md and
https://github.com/tensorflow/probability/blob/main/discussion/tfp_distributions_contract.md
would be good to browse.

Brian Patton | Software Engineer | ***@***.***

**Comment by leandrolcampos** [comment]
Hi @brianwa84,

I created a pull request, [#1524](https://github.com/tensorflow/probability/pull/1524), that provides an implementation for the Skew Normal distribution.

Any feedback is appreciated.
