### ISSUE TITLE
Feature request: intuitive replacement for pymc.Normal(tau=foo, observed=True, value=bar)

### ISSUE THREAD

**Issue by matthew-mcateer** [tensorflow/probability#40]
I've been searching both the Tensorflow probability documentation and the pymc/pymc3 documentation for a good way to convert between something like this from pymc:

```python
obs = pymc.Normal(name="obs", mu=mean, tau=prec, value=Y, observed=True)
```

and something like this?

```python
import tensorflow_probability.distributions as tfd

obs = tfd.Normal(name="obs", loc=mean, scale=std, data=Y, observed=True)
```

Does something like this already exist, or am I missing something here?

**Comment by dustinvtran** [comment]
Have you looked at Edward2? We don't have semantics for declaring a random variable as "observed" (I think this confuses modeling/inference semantics). But we do have a notion of binding random variables to specific values:

```python
from tensorflow_probability import edward2 as ed

obs = ed.Normal(name="obs", loc=mean, scale=std, value=Y)
```

**Comment by matthew-mcateer** [comment]
Hi Dustin,

I had seen that. I actually had previously used edward2, but I was attempting to use something within the larger tf.distributions or tf.contrib.distributions. I didn't know if there was something along the lies of `tfd.normal_conjugates_known_scale_predictive()` or `tfd.normal_conjugates_known_scale_posterior()` that could have acted as a substitute.

**Comment by dustinvtran** [comment]
Got it. No, it doesn't exist in TF distributions. It's Edward2's job.
