### ISSUE TITLE
How to compute tfd.Normal(0,1) * x + tfd.Normal(0,1)

### ISSUE THREAD

**Issue by stokhos** [tensorflow/probability#408]
Hi guys:

I'm trying to build Bayesian neural network.
with following structure:
y1 = w11 x11 w12 x12 + b1,
y2 = w2 y1 + b2,

where w11, w12, b1,  w2, b2 ~ N(0,1)
x11, x12 are variables of type tf.float32

w11 = tfd.Norma(0,1)
w12 = tfd.Norma(0,1)
b1 = tfd.Normal(0,1)
y1 = w11 x11 + w12 x12 + b1
How can get random variable y1?

**W** = tf.cast(np.random.rand(3,2), dtype=tf.float32)
**X** = tfp.distributions.Normal([[1,2,3],[2,2,3]],[[3,4,5],[5,6,7]])
**b** = tfp.distributions.Normal([[1,2],[2,2]],[[3,4],[5,6]])
**y** = tf.add(tf.matmul(**W**,**X**) + **b**)

I got this
TypeError: Failed to convert object of type <class 'tensorflow_probability.python.distributions.normal.Normal'> to Tensor. Contents: tfp.distributions.Normal("Normal_6/", batch_shape=(2, 3), event_shape=(), dtype=float32). Consider casting elements to a supported type.

I have tried edward2, but some part of the function I need can't not find in edward2 now.

**Comment by brianwa84** [comment]
You should call .sample() to get a sample from each distribution.
