### ISSUE TITLE
Muldimensional Uniform Distributions

### ISSUE THREAD

**Issue by matthew-mcateer** [tensorflow/probability#41]
I have been trying to create a 2-dimensional Uniform distribution, something that might take the following form: 
`tf.distributions.Uniform("halo_position_4/", batch_shape=(), event_shape=(2,), dtype=float32)`.
However My attempts have nearly always resulted in a form that resembles this: `tf.distributions.Uniform("halo_position_4/", batch_shape=(2,), event_shape=(), dtype=float32)`.

Largely I've been trying to make use of multiple uniform distributions
```python
two_d_uniform = tfd.Uniform(name="two_d_uniform", low=[0.0, 0.0], high=100.0, 100.0)
```
as well as trying to make use of an independent distribution 

```python
two_d_uniform = tfd.Independent(tfd.Uniform(name="two_d_uniform", 
                                    low=0.0, 
                                    high=100.0), reinterpreted_batch_ndims=1) 
```
but the output for that last one resembles the following:
```
ValueErrorTraceback (most recent call last)
<ipython-input-14-9c97b2535035> in <module>()
     31     two_d_uniform = tfd.Independent(tfd.Uniform(name="two_d_uniform", 
     32                                     low=0.0,
---> 33                                     high=100.0), reinterpreted_batch_ndims=1)    
     34     print(halo_position)
     35 

/content/.local/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/independent.pyc in __init__(self, distribution, reinterpreted_batch_ndims, validate_args, name)
    144           name=name)
    145       self._runtime_assertions = self._make_runtime_assertions(
--> 146           distribution, reinterpreted_batch_ndims, validate_args)
    147 
    148   @property

/content/.local/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/independent.pyc in _make_runtime_assertions(self, distribution, reinterpreted_batch_ndims, validate_args)
    227         raise ValueError("reinterpreted_batch_ndims({}) cannot exceed "
    228                          "distribution.batch_ndims({})".format(
--> 229                              static_reinterpreted_batch_ndims, batch_ndims))
    230     elif validate_args:
    231       batch_shape = distribution.batch_shape_tensor()

ValueError: reinterpreted_batch_ndims(1) cannot exceed distribution.batch_ndims(0)
```

Is there a simple way to make multi-dimensional uniform distributions like the litany of methods for multivariate normal can? If not, could this be added as a feature?

Mainly what I've been trying to do is find a substitute for the following:
```python
two_d_uniform = pymc.Uniform("two_d_uniform", 0, 100, size=(1, 2))
```
and modifying the event_shape` (as opposed to the batch_shape) appears to be the way to go with

**Comment by matthew-mcateer** [comment]
I have found a workaround: 
```python
two_d_uniform = tf.random_uniform(shape=[2], minval=0.0, maxval=100.0, dtype=tf.float32)
```
It would be nice if something like this could be referenced directly from tensorflow_probability, though.

**Comment by davmre** [comment]
Hi Matthew! You were actually very close with the Independent distribution. The Independent distribution converts batch dimensions (representing independent random variables) to event dimensions (representing a single multidimensional random variable). In this case you want to first create two independent uniform distributions, i.e., a `Uniform` object with `batch_shape==[2]`, and then use `Independent` to combine them into a 2D uniform. This code should work:
```python
two_d_uniform = tfd.Independent(tfd.Uniform(name="two_d_uniform", 
                                    low=[0., 0.], 
                                    high=[100., 100.]), reinterpreted_batch_ndims=1) 
```
