### ISSUE TITLE
Consider adding tf.enable_eager_execution() to main website example

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/probability#412]
In the main website:
https://www.tensorflow.org/probability
, there is an example.  On TensorFlow 1.13, it does not output the evaluation of coeffs because eager execution is not on by default.  The colab notebook does include the call:
https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/g3doc/_index.ipynb

Consider enabling eager_execution in that sample as is done in colab:

```
import tensorflow as tf
import tensorflow_probability as tfp

tf.enable_eager_execution()

print(tf.__version__)
```

**Comment by srvasude** [comment]
Since TF2.X is used by default, and most examples are migrated to using TF2.X, closing this issue. Once we clean up the remaining examples, everything will be eager mode by default.
