### ISSUE TITLE
Error When Building From Source

### ISSUE THREAD

**Issue by vastsoun** [tensorflow/probability#419]
Hi,

I tried to build from source but experienced the following error:
```
/home/vassilios/git/tensorflow/probability/tools/bazel.rc
ERROR: /home/vassilios/git/tensorflow/probability/tensorflow_probability/python/distributions/internal/BUILD:100:1: //tensorflow_probability/python/distributions/internal:correlation_matrix_volumes: no such attribute 'python_version' in 'py_binary' rule
ERROR: /home/vassilios/git/tensorflow/probability/tensorflow_probability/python/distributions/internal/BUILD:129:1: Target '//tensorflow_probability/python/distributions/internal:init' contains an error and its package is in error and referenced by '//tensorflow_probability/python/distributions/internal:slicing'
ERROR: /home/vassilios/git/tensorflow/probability/tensorflow_probability/python/distributions/internal/BUILD:129:1: Target '//tensorflow_probability/python/distributions/internal:slicing.py' contains an error and its package is in error and referenced by '//tensorflow_probability/python/distributions/internal:slicing'
ERROR: /home/vassilios/git/tensorflow/probability/tensorflow_probability/python/distributions/BUILD:303:1: Target '//tensorflow_probability/python/distributions/internal:slicing' contains an error and its package is in error and referenced by '//tensorflow_probability/python/distributions:distribution'
ERROR: Analysis of target '//:pip_pkg' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.124s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//src/tools/launcher/util
```

System Description:
* Lenovo ThinkPad P50 (NVIDIA M2000M GPU)
* Ubuntu 18.04 LTS
* Python 3.6 (default python3 on 18.04)
* Bazel 0.19.2 (the one required to build tensorflow 1.13.1 from source)

Moreover, I have the following question: TFP seems to build a **python** library using bazel (sorry I'm not a frequent user thereof), and yet, -copt and -mtune flags are passed to the build command. I did not identify any C/C++ header or source files in the repo nor any cc library targets in the BUILD files. Am I missing something? Is TFP purely python or does it actually build a C/C++ library as well?

Sincerely,

Vassilios

**Comment by csuter** [comment]
Hm, sorry about this. We (TFP) always test our build on the latest bazel release; I guess these python version annotations were added more recently than 0.19. The tags were added due to some large-scale internal refactors in preparation for the py2 deprecation at end of year.

I'd recommend using a newer bazel; should be safe with TF, too. If you find any incompatibility please do bring it to our attention!

**Comment by vastsoun** [comment]
Hi @csuter,

Thanks for your response. I updated bazel to 0.25.2 and I can confirm that building the pip package worked. 

Also, could you please comment on my question regarding TFP and C/C++?

Cheers,
Vassilios

**Comment by csuter** [comment]
Ah, yes, sorry. We have no c/c++ in TFP. I believe you can ignore those flags.
