### ISSUE TITLE
Using an array of step-sizes for mcmc

### ISSUE THREAD

**Issue by rzu512** [tensorflow/probability#431]
While `tfp.mcmc.HamiltonianMonteCarlo` supports updating multiple chains, can it update each chain with different step-size?

When I try to provide a step-size array, all the step-sizes become exactly the same in the end. So I doubt if  `tfp.mcmc.HamiltonianMonteCarlo` supports an array of step-sizes. If it doesn't, then it has to pick one step-size for all chains when some chains can use a larger step-size.

The alternative is to set up one instance `tfp.mcmc.HamiltonianMonteCarlo` for each chain and then run all instance simultaneously.

I vaguely remember the doc says using adaptive step-size during the sampling phase would break time-reversibility. How would that affect NUTS and HMC?

Result:
```
[[ 0.8595034  -2.2379014 ]
 [ 0.89156437 -2.2505744 ]
 [ 0.89156437 -2.2505744 ]
 ...
 [ 0.88753796 -2.2419243 ]
 [ 0.8917903  -2.2378962 ]
 [ 0.90693414 -2.2428718 ]]
mean:-0.6857  stddev:1.5561  acceptance:0.7246
mean: [0.7047516  0.09612619]
step_sizes [array([0.04036212, 0.04036212], dtype=float32)]
```
The step_sizes are exactly the same.

Test:
```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions
from functools import partial


def logp_func(observations, p):
    b = tfd.Bernoulli(logits=p)
    return tf.reduce_sum(b.log_prob(observations), axis=0)


def main():
    n_obs = 10000
    obs = [np.random.choice(2, p=[0.3, 0.7], size=n_obs),
           np.random.choice(2, p=[0.9, 0.1], size=n_obs)]
    obs = np.vstack(obs).astype(np.float32).T
    observations = tf.constant(np.array(obs))
    logp = partial(logp_func, observations)

    step_size = tf.get_variable(
        name='step_size',
        initializer=np.array([0.9, 0.9]).astype(np.float32),
        use_resource=True,  # For TFE compatibility.
        trainable=False)

    num_results = int(1e4)
    num_burnin_steps = int(1e3)
    num_adaptation_steps = int(num_burnin_steps * 0.8)
    hmc = tfp.mcmc.HamiltonianMonteCarlo(
        target_log_prob_fn=logp,
        num_leapfrog_steps=3,
        step_size=step_size,
        step_size_update_fn=tfp.mcmc.make_simple_step_size_update_policy(
            num_adaptation_steps=None))

    samples, kernel_results = tfp.mcmc.sample_chain(
        num_results=num_results,
        num_burnin_steps=num_burnin_steps,
        current_state=np.array([1e-6, 1e-6], dtype=np.float32),
        kernel=hmc)

    # Initialize all constructed variables.
    init_op = tf.global_variables_initializer()

    with tf.Session() as sess:
        init_op.run()
        samples_, kernel_results_ = sess.run(
            [samples, kernel_results])
        step_size_ = sess.run([step_size])
        print(samples_)

        print('mean:{:.4f}  stddev:{:.4f}  acceptance:{:.4f}'.format(
            samples_.mean(), samples_.std(),
            kernel_results_.is_accepted.mean()))
        mapped_sample = 1 / (1 + np.exp(-samples_))
        print("mean:", np.mean(mapped_sample, axis=0))
        print("step_sizes", step_size_)


main()
```

**Comment by SiegeLordEx** [comment]
The old style step size adaptation (the one you're using) doesn't support per-chain adaptation. The yet unreleased version of TFP (which you can get from the tfp-nightly package) has a new way of doing step size adaptation that does support it, here is an example:

```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions
from functools import partial


def logp_func(observations, p):
    b = tfd.Bernoulli(logits=p)
    return tf.reduce_sum(b.log_prob(observations), axis=0)


def main():
    tf.reset_default_graph()
    n_obs = 10000
    obs = [np.random.choice(2, p=[0.3, 0.7], size=n_obs),
           np.random.choice(2, p=[0.9, 0.1], size=n_obs)]
    obs = np.vstack(obs).astype(np.float32).T
    observations = tf.constant(np.array(obs))
    logp = partial(logp_func, observations)

    num_results = int(1e4)
    num_burnin_steps = int(1e3)
    num_adaptation_steps = int(num_burnin_steps * 0.8)
    kernel = tfp.mcmc.HamiltonianMonteCarlo(
        target_log_prob_fn=logp,
        num_leapfrog_steps=3,
        step_size=np.array([0.9, 0.9]).astype(np.float32))
    kernel = tfp.mcmc.SimpleStepSizeAdaptation(kernel, num_adaptation_steps=num_adaptation_steps)

    samples, (is_accepted, step_size) = tfp.mcmc.sample_chain(
        num_results=num_results,
        num_burnin_steps=num_burnin_steps,
        current_state=np.array([1e-6, 1e-6], dtype=np.float32),
        kernel=kernel,
        trace_fn=lambda _, pkr: (pkr.inner_results.is_accepted,
                                 pkr.inner_results.accepted_results.step_size))

    with tf.Session() as sess:
        samples_, is_accepted_, step_size_ = sess.run(
            [samples, is_accepted, step_size])
        step_size_ = step_size_[-1]
        print(samples_)

        print('mean:{:.4f}  stddev:{:.4f}  acceptance:{:.4f}'.format(
            samples_.mean(), samples_.std(),
            is_accepted_.mean()))
        mapped_sample = 1 / (1 + np.exp(-samples_))
        print("mean:", np.mean(mapped_sample, axis=0))
        print("step_sizes", step_size_)

main()
```

> I vaguely remember the doc says using adaptive step-size during the sampling phase would break time-reversibility.

That is correct, that's why we recommend doing adaptation during burnin (and stopping adaptation before burnin ends, so that the chain can burnin after the adaptation ends). NUTS does not do step size adaptation on the fly, but rather trajectory adaptation. It has a clever way of preserving reversibility to compensate.

**Comment by rzu512** [comment]
Do we have an example for using NUTS?

**Comment by SiegeLordEx** [comment]
There'll be a NUTS implementation added soon, a caveat is that NUTS by construction is not very efficient on accelerator hardware (it's mostly fine on CPU though).

It does not do mass matrix adaptation, we're still adding that. Today you can fit a variational gaussian or do a laplace approximation and then use `tfp.mcmc.TransformedTransitionKernel` to pre-condition your problem. Those aren't quite the same thing as what people usually mean when they say `mass matrix adaptation`, but it can get you pretty far.

**Comment by rzu512** [comment]
Does replica exchange support also using an array of step-sizes and an array of log-likelihood?

**Comment by SiegeLordEx** [comment]
Yes, what might not work is adaptation in that context because of the way it's implemented right now. We'd need to try it and see.

**Comment by srvasude** [comment]
https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/SimpleStepSizeAdaptation
SimpleStepSizeAdaptation is in TFP and supports per-chain, per-state-part step sizes. Closing this.
