### ISSUE TITLE
Overfitting in Atmospheric CO2 and Electricity Demand (Jupyter notebook)

### ISSUE THREAD

**Issue by pjo256** [tensorflow/probability#432]
While reading through the notebook, I noticed there might be some overfitting. 

In the forecast of atmospheric CO2, `build_model` takes training data as input.

```
def build_model(observed_time_series):
    ...

co2_model = build_model(co2_by_month_training_data)
```
`build_model` in the electricity demand section takes no argument, and passes `observed_time_series=demand` to the underlying components.

```
def build_model():
  hour_of_day_effect = sts.Seasonal(num_seasons=24,
                                    observed_time_series=demand,
                                    name='hour_of_day_effect')
```

`demand` in this context is defined as the entire dataset, whereas `demand_training_data = demand[:-num_forecast_steps]`, so the model is trained on both the training and test sets.

**Comment by davmre** [comment]
You're totally right. In fairness, the effect isn't dramatic -- the series passed into the model definition is used just to set priors based on the empirical mean and stddev, which don't differ much between the two series, and the primary fitting (defined in the call to `build_factored_variational_loss`) does correctly use just the training data. But the correct thing to do is to use the training data in both cases (as we do for the CO2 model example, so I think this was just an oversight). Fix coming soon; thanks for pointing this out!
