### ISSUE TITLE
ed.as_random_variable(dist) causes problem in ed.tape()

### ISSUE THREAD

**Issue by stokhos** [tensorflow/probability#437]
```python
import tensorflow_probability.edward2 as ed
```

ed.as_random_variable changes the random variable name from "W_0" to "W" in the following code
```python
with ed.tape() as model_tape:
    W_0 = as_random_variable(tfp.distributions.Normal(loc=tf.zeros([1, 2]), scale=tf.ones([1, 2]), name="W_0"))
    W_1 = as_random_variable(tfp.distributions.Normal(loc=tf.zeros([2, 2]), scale=tf.ones([2, 2]), name="W_1"))
```
model_tape will be 
```python
OrderedDict([('W', <ed.RandomVariable 'W_1/' shape=(2, 1) dtype=float32>)])
```
The problem is caused by 
https://github.com/tensorflow/probability/blob/8857b94f6f4e049d8d3dbf824495b037f88cc4d1/tensorflow_probability/python/edward2/generated_random_variables.py#L74-L79
which trys to do the following:
```python
  d1 = tfd.Normal(0., 1., name='x') # d1.name = 'x/'
  d2 = tfd.Normal(0., 1., name='x') # d2.name = 'x_2/'
  _simple_name(d2) # returns 'x'
```

**Comment by csuter** [comment]
Reopening until we confirm the fix (this was auto-closed based on change description that said it *possibly* fixed this issue #)

**Comment by srvasude** [comment]
Closing this as Edward2 has moved to https://github.com/google/edward2. Feel free to reopen this issue there (if it is still an issue).
