### ISSUE TITLE
Use different distributions for each replica in replica exchange

### ISSUE THREAD

**Issue by rzu512** [tensorflow/probability#440]
Can I use different logp for each replica in replica exchange?

For example, 
- 1st replica is an exponential distribution with rate = 2
- 2nd replica is an exponential distribution with rate = 1

**Comment by csuter** [comment]
Hi @rzu512! Thanks for test driving TFP on your problem 😊

Would you mind raising this on the [tfprobability@tensorflow.org TFP user forum](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfprobability)?

We'd like to keep the issue tracker confined to bugs and feature requests as much as possible, and use the forum for discussions of methods, and applications of tools to problems.
