### ISSUE TITLE
RelaxedOneHotCategorical has no probs attribute

### ISSUE THREAD

**Issue by rzu512** [tensorflow/probability#441]
While both `OneHotCategorical` and `ExpRelaxedOneHotCategorical` have a `probs` attribute, `tfp.distributions.RelaxedOneHotCategorical` does not have a `probs` attribute.

I am using tfp-nightly and tf-nightly.

**Comment by brianwa84** [comment]
Since `RelaxedOneHotCategorical` is a `TransformedDistribution`, you can instead do `dist.distribution.probs`. PR welcome, to pass these through.
