### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compat.v2'

### ISSUE THREAD

**Issue by miguelmorin** [tensorflow/probability#446]
I install the master branch with 

```bash
cd ~/code
git clone git@github.com:tensorflow/probability.git
export PYTHONPATH=":$HOME/code/probability"
pip install tensorflow
```

and I run the `vae.py` example, which gives the error `ModuleNotFoundError: No module named 'tensorflow.compat.v2'`:

```
 python3 ../probability/tensorflow_probability/examples/vae.py
Traceback (most recent call last):
  File "../probability/tensorflow_probability/examples/vae.py", line 123, in <module>
    import tensorflow_probability as tfp
  File "/Users/mmorin/code/probability/tensorflow_probability/__init__.py", line 75, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/Users/mmorin/code/probability/tensorflow_probability/python/__init__.py", line 21, in <module>
    from tensorflow_probability.python import bijectors
  File "/Users/mmorin/code/probability/tensorflow_probability/python/bijectors/__init__.py", line 23, in <module>
    from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
  File "/Users/mmorin/code/probability/tensorflow_probability/python/bijectors/absolute_value.py", line 21, in <module>
    import tensorflow.compat.v2 as tf
ModuleNotFoundError: No module named 'tensorflow.compat.v2'
```

I found this problem from the fix to #255.

[This TensorFlow issue](https://github.com/tensorflow/tensorflow/issues/26546) suggests it's a typo and proposes changing from `compat.v2` to `compat.v1`.

What do you think?

**Comment by csuter** [comment]
You'll need to install tf-nightly to work with TFP at HEAD.

**Comment by miguelmorin** [comment]
Yes, that was the solution. Sorry for overlooking the link.

**Comment by sehargul-123** [comment]
have installed tensorflow==1.8.0, i have to run a file in order to star my training. but I am getting this error.
ModuleNotFoundError: No module named 'tensorflow.compat'
then i wrote this command "pip install tensorflow.compat" i got following error
ERROR: Could not find a version that satisfies the requirement tensorflow.compat (from versions: none)
ERROR: No matching distribution found for tensorflow.compat
