### ISSUE TITLE
TensorBoard logdir error

### ISSUE THREAD

**Issue by oke-aditya** [tensorflow/probability#449]
Hello I am using tensorflow 1.13.1 version.
I am getting an error with the TensorBoard

`tensorboard = TensorBoard(logdir = 'logs/{}'.format(name))`
```
TypeError                                 Traceback (most recent call last)
<ipython-input-17-a1ad9ae26dd8> in <module>
      1 name = "Cats-vs-dogs-cnn-{}".format(int(time.time())) # Name of the model with timestamp
----> 2 tensorboard = TensorBoard(logdir = 'logs/{}'.format(name))

TypeError: __init__() got an unexpected keyword argument 'logdir'
```
Can you please help me with this?

**Comment by oke-aditya** [comment]
It was just a typo it is log_dir  I am sorry.

**Comment by csuter** [comment]
:)

(also -- note this is the tensorflow/probability issue tracker, so we're not the best ones to ask about TensorBoard)

**Comment by oke-aditya** [comment]
I'm sorry, I am new here, trying to use Tensorflow, thank you for :) and spending your time viewing a closed issue, I appreciate your promptness 👍  💯
