### ISSUE TITLE
"No variables to optimize." for tfp.sts.fit_with_hmc in eager mode

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#452]
Using `tfp.sts.fit_with_hmc` in eager mode, with `@tf.function`, throws "No variables to optimize." for this code (basically taken from `decomposition_test.py`):

```
import numpy as np
import tensorflow as tf
tf.enable_v2_behavior()
import tensorflow_probability as tfp


observed_time_series = tf.convert_to_tensor(np.random.randn(2,1,12))

@tf.function()
def fit(observed_time_series):
  day_of_week = tfp.sts.Seasonal(
        num_seasons=7,
        observed_time_series=observed_time_series,
        name='day_of_week')
  local_linear_trend = tfp.sts.LocalLinearTrend(
        observed_time_series=observed_time_series,
        name='local_linear_trend')
  model = tfp.sts.Sum(components=[day_of_week, local_linear_trend],
                        observed_time_series=observed_time_series)
  samples, kernel_results = tfp.sts.fit_with_hmc(model, observed_time_series)
  return samples

samples = fit(observed_time_series)

```

For similar cases, the workaround seems to be putting code where variables are defined in a function, but I'm already doing that - is there another workaround for this? 
Many thanks!

**Comment by jeffpollock9** [comment]
Hi @skeydan - I think this is the same problem as https://github.com/tensorflow/probability/issues/348

If so, I'm not aware of any way to make this work other than dropping `tf.function` (which is very slow) or running in graph mode with TF 1

**Comment by skeydan** [comment]
Thanks @jeffpollock9, yes, this looks like it's the same!

Given that in other areas than `sts` (see e.g. https://github.com/tensorflow/probability/issues/450#issuecomment-499447991, cc @brianwa84 ) there are efforts to make Eager (with `tf.function`) work in similar cases (how similar I honestly can't say :-)), it would be helpful to know if/when we could expect a fix?
Thanks!

Also, I think that in eager mode (without `tf.function`) it takes so long that it doesn't seem right (even with a toy dataset and 10 sampling steps, I never so far managed to _not_ kill the process ;-)).
At first I thought this was due to my calling this from R, but it's the same when using only Python...
(Also @axch was implying this might be a bug in #348...)

**Comment by davmre** [comment]
We just committed a rewrite of STS fitting to better support eager idioms: https://github.com/tensorflow/probability/commit/e823f4b1510b1ff4b2c000a45965ec432a19bec5
https://github.com/tensorflow/probability/commit/1cb9d0ae0fa4473eb8ff1160a5d8d1c736a0f796

In particular, changes to the underlying VI semantics should eliminate the error you're seeing, and `tfp.sts.fit_with_hmc` now automatically wraps the sampler with `tf.function`, so you don't need to do it explicitly anymore.

I'm going to go ahead and close this issue; feel free to reopen if you're still seeing problems.
