### ISSUE TITLE
Error reporting for "ValueError: Encountered `None` gradient." for Hamiltonian Monte Carlo kernel

### ISSUE THREAD

**Issue by arunpatro** [tensorflow/probability#454]
This is related to https://github.com/tensorflow/probability/issues/47. As I am unable to reopen the issue, I'm starting another. I was unable to get help on SO. See this [question](https://stackoverflow.com/questions/56498469/no-support-for-multivariate-normal-in-edward2-tensorflow-probability). 

```python
import tensorflow as tf
tf.enable_eager_execution()
import tensorflow_probability as tfp
from tensorflow_probability import edward2 as ed
import numpy as np
from scipy.stats import multivariate_normal


tfd = tfp.distributions

x_true = multivariate_normal.rvs(cov=np.eye(4), size = 500)

def mvnmodel(data_size=1, dimension=4):
    nu = ed.Uniform(name="nu", low=tf.constant(0.), high=tf.constant(4.))
    corr_mat = ed.LKJ(name="corr", dimension=4, concentration=nu)
    sigma = ed.LogNormal(name='sigma', loc=tf.zeros([dimension]), scale=tf.ones([dimension]))
    sigma_mat = tf.diag(name="sigma_mat", diagonal=sigma)
    cov_mat = sigma_mat @ corr_mat @ sigma_mat 
    L_tril = tf.cholesky(cov_mat)
    mu = ed.MultivariateNormalTriL(name="mu", loc=tf.zeros([4]), scale_tril = L_tril)
    x = ed.MultivariateNormalTriL(name="x", loc=mu, scale_tril = L_tril, sample_shape=[data_size])
    return x

log_joint = ed.make_log_joint_fn(mvnmodel)

nu0 = np.random.uniform(0, 4)
with tf.Session() as sess:
    corr_tmp = ed.LKJ(name="corr0", dimension=4, concentration=nu0, validate_args=True)
    l_tril = tf.cholesky(corr_tmp)
    corr0, l_tril0 = sess.run([corr_tmp, l_tril])
sigma0 = np.random.lognormal(np.zeros(4), np.ones(4))
mu0 = np.random.multivariate_normal(np.zeros(4), np.eye(4))

qnu = tf.convert_to_tensor(nu0, name='qnu')
qcorr = tf.convert_to_tensor(corr0, name='qcorr')
qsigma = tf.convert_to_tensor(sigma0, name='qsigma')
qmu = tf.convert_to_tensor(mu0, name='qmu')

q_list = [qnu, qcorr, qsigma, qmu]

print('Printing\n', [qnu, qcorr, qsigma, qmu])

def target_log_prob_fn(nu, corr, sigma, mu):
    return log_joint(data_size=x_true.shape[0], 
                     dimension=x_true.shape[1], 
                     nu=qnu, 
                     corr=qcorr, 
                     sigma=qsigma, 
                     mu=qmu, 
                     x=x_true)

print(target_log_prob_fn(qnu, qcorr, qsigma, qmu)) #works

hmc_kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=0.01,
    num_leapfrog_steps=5)

states, kernels_results = tfp.mcmc.sample_chain(
    num_results=1000,
    current_state=[qnu, qcorr, qsigma, qmu],
    kernel=hmc_kernel,
    num_burnin_steps=0)
```
This throws an error regarding none gradients. 

```python
Printing
 [<tf.Tensor: id=353, shape=(), dtype=float32, numpy=3.3430696>, <tf.Tensor: id=354, shape=(4, 4), dtype=float32, numpy=
array([[ 1.        ,  0.57910216,  0.18112545, -0.2228805 ],
       [ 0.57910216,  1.        , -0.44517764, -0.42296514],
       [ 0.18112545, -0.44517764,  1.        ,  0.4743349 ],
       [-0.2228805 , -0.42296514,  0.4743349 ,  1.        ]],
      dtype=float32)>, <tf.Tensor: id=355, shape=(4,), dtype=float64, numpy=array([5.05385036, 0.36153196, 8.35021843, 3.05508949])>, <tf.Tensor: id=356, shape=(4,), dtype=float64, numpy=array([-0.17279591,  0.68791932, -1.70513022,  1.3289289 ])>]
tf.Tensor(-12322.489, shape=(), dtype=float32)
Traceback (most recent call last):
  File "tfp-edward.py", line 70, in <module>
    num_burnin_steps=0)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/sample.py", line 235, in sample_chain
    previous_kernel_results = kernel.bootstrap_results(current_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 518, in bootstrap_results
    kernel_results = self._impl.bootstrap_results(init_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py", line 264, in bootstrap_results
    pkr = self.inner_kernel.bootstrap_results(init_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 687, in bootstrap_results
    ] = mcmc_util.maybe_call_fn_and_grads(self.target_log_prob_fn, init_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/util.py", line 248, in maybe_call_fn_and_grads
    '  grads: {}'.format(fn_arg_list, grads))
ValueError: Encountered `None` gradient.
  fn_arg_list: [<tf.Tensor: id=353, shape=(), dtype=float32, numpy=3.3430696>, <tf.Tensor: id=354, shape=(4, 4), dtype=float32, numpy=
array([[ 1.        ,  0.57910216,  0.18112545, -0.2228805 ],
       [ 0.57910216,  1.        , -0.44517764, -0.42296514],
       [ 0.18112545, -0.44517764,  1.        ,  0.4743349 ],
       [-0.2228805 , -0.42296514,  0.4743349 ,  1.        ]],
      dtype=float32)>, <tf.Tensor: id=355, shape=(4,), dtype=float64, numpy=array([5.05385036, 0.36153196, 8.35021843, 3.05508949])>, <tf.Tensor: id=356, shape=(4,), dtype=float64, numpy=array([-0.17279591,  0.68791932, -1.70513022,  1.3289289 ])>]
  grads: [None, None, None, None]
```

I have alternatively tried the following kernels too, out of which only `tfp.mcmc.RandomWalkMetropolis` works. Setting `state_gradients_are_stopped=True` for HMC also gives same none gradient error. 

```python
hmc_kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=0.01,
    num_leapfrog_steps=5,
    state_gradients_are_stopped=True)

rwm_kernel = tfp.mcmc.RandomWalkMetropolis(
    target_log_prob_fn=target_log_prob_fn)

umc_kernel = tfp.mcmc.UncalibratedHamiltonianMonteCarlo(
        target_log_prob_fn=target_log_prob_fn,
        step_size=0.01,
        num_leapfrog_steps=3)

mh_kernel = tfp.mcmc.MetropolisHastings(umc_kernel)
```

**Comment by csuter** [comment]
The main problem is that your target log joint doesn't depend on its inputs:

```
                                       # vvv----where are these used?
def target_log_prob_fn(nu, corr, sigma, mu):
    return log_joint(data_size=x_true.shape[0], 
                     dimension=x_true.shape[1], 
                     nu=qnu, 
                     corr=qcorr, 
                     sigma=qsigma, 
                     mu=qmu, 
                     x=x_true)
```

I don't think you need any such q terms -- it looks like you might be mixing in code from a variational inference example.

Also -- notice that you have enabled eager execution but are still writing graph mode code (tf.Session should be unnecessary in eager mode).

**Comment by arunpatro** [comment]
@csuter Thanks. I did borrow the initializing tensor names from Variational Inference. I just needed to pass the correct arguments in the target_log_prob_fn.

**Comment by DhruvVPatel** [comment]
@arunpatro @csuter This might be a naive question, but I'm not able to figure out an answer either on SO or here so posting it here.
Is it possible to use TFP for already trained model? I'm trying to sample from the posterior of a trained generative model (GAN for example) using MCMC. Specifically, for a problem of interest, I would like to find a conditional posterior distribution of latent vector z. Now, the output of my target_log_prob_fn has two term: prior which is on z and likelihood which is some function of z defined by my already trained generator of GAN. So, in order to compute target_log_prob_fn, I will have to pass z through the trained GAN model and compute my likelihood and I'm facing difficulties with it. Here, z is the placeholder of my model and so I'm running a session and feeding value of z as the current state of chain to produce some function of output of generator to compute log(likelihood), which is then added to log(prior) (which is just a standard normal distribution on z) to produce posterior and that is the output of target_log_prob_fn.

However, when I run this chain with (HMC kernel, even tried RandomWalkMetropolis and MH) I realized that it is not considering the likelihood term and every time it just produces samples from prior. So, I removed the prior contribution from posterior calculation just to verify this and it breaks down throwing ValueError: Encountered 'None' gradient. Not sure if there is something obvious that I'm missing or something else?

         def joint_log_prob(self, z):              
                like_stddev = 1.0
                
                [dummy_out, matA_] = self.session.run([self.model.dummy.initializer, self.model.matA],
                    feed_dict=self.model.get_feed_dict(batch_chunk, np.tile(tf.Session().run(z), [self.batch_size, 1])))
                
                prior = tfd.MultivariateNormalDiag(loc=np.zeros(self.n_z, dtype=np.float32), scale_diag=np.ones(self.n_z, dtype=np.float32))
                                                  
                like = tfd.MultivariateNormalDiag(loc=np.zeros(900, dtype=np.float32),
                                                  scale_diag=like_stddev*np.ones(900, dtype=np.float32))
                
                #matA_col1 = tf.slice(self.model.matA, [0,0], [self.model.matA.get_shape()[0],1])
                return (like.log_prob(matA_[:,0]))#+prior.log_prob(z)
             
                                                  
          
            def unnormalized_posterior(z):
                return joint_log_prob(self, z) 
            adaptive_hmc = tfp.mcmc.HamiltonianMonteCarlo(target_log_prob_fn=unnormalized_posterior, step_size=np.float32(1.2), num_leapfrog_steps=3)
            

            initial_state = tf.zeros(self.n_z, dtype=tf.float32)
            [samples, kernel_results] =  tfp.mcmc.sample_chain(
                num_results=N,
                num_burnin_steps=burn,
                current_state=initial_state,
                kernel=adaptive_hmc)
              
            [dummy_out, samples_, kernel_results_, accept_rate] = self.session.run([self.model.dummy.initializer, samples, kernel_results, 
            tf.reduce_mean(tf.cast(kernel_results.is_accepted, dtype=tf.float32))]
            ,feed_dict=self.model.get_feed_dict(batch_chunk, z_))
            
            map_ind = np.argmax(kernel_results_[4][1])`

This throws...
`Traceback (most recent call last):
  File "hmc.py", line 418, in <module>
    main()
  File "hmc.py", line 415, in main
    evaler.eval_run()
  File "hmc.py", line 227, in eval_run
    coord.join(threads, stop_grace_period_secs=3)
  File "/home/pogo/v_envs/tflow/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/pogo/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "hmc.py", line 163, in eval_run
    kernel=adaptive_hmc)
  File "/home/pogo/v_envs/tflow/lib/python3.5/site-packages/tensorflow_probability/python/mcmc/sample.py", line 235, in sample_chain
    previous_kernel_results = kernel.bootstrap_results(current_state)
  File "/home/pogo/v_envs/tflow/lib/python3.5/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 513, in bootstrap_results
    kernel_results = self._impl.bootstrap_results(init_state)
  File "/home/pogo/v_envs/tflow/lib/python3.5/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py", line 263, in bootstrap_results
    pkr = self.inner_kernel.bootstrap_results(init_state)
  File "/home/pogo/v_envs/tflow/lib/python3.5/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 682, in bootstrap_results
    ] = mcmc_util.maybe_call_fn_and_grads(self.target_log_prob_fn, init_state)
  File "/home/pogo/v_envs/tflow/lib/python3.5/site-packages/tensorflow_probability/python/mcmc/util.py", line 247, in maybe_call_fn_and_grads
    '  grads: {}'.format(fn_arg_list, grads))
ValueError: Encountered 'None' gradient.
  fn_arg_list: [<tf.Tensor 'zeros:0' shape=(8,) dtype=float32>]
  grads: [None]`

**Comment by brianwa84** [comment]
The session.run call you have in there breaks the gradients from
`z` -> `matA_` [is a np.ndarray, not a tf.Tensor] -> `log_prob(matA_)`.

You could try using eager mode if you like to see intermediate values
immediately.
`tf.enable_v2_behavior()` or `tf.enable_eager_execution()`  at process
startup.


Brian Patton | Software Engineer | bjp@google.com

**Comment by DhruvVPatel** [comment]
Thanks @brianwa84 for your quick response! Actually, I don't want to see the intermediate values. The reason why I'm calling session.run is because z is the placeholder of my model and I would like to feed the current value of MCMC to z to compute my posterior.

To be precise, I've already trained my GAN model (which has z - latent vector of GAN - as a placeholder). Now, my posterior(target_log_prob_fn) has two components: prior and likelihood; out of which calculation for prior is straightforward. Whereas likelihood is some function of output of the generator f(g(z)), where g is the _already trained_ generator and f is some fixed analytical function of g(z) (square loss for example). f(g(z)) is self.model.matA in joint_log_prob function above.

So, now in order to compute the posterior of latent vector z, I'll have to feed the current value of MCMC to my placeholder z  and pass it through the _already trained_ generator to compute log(likelihood) and then add it to easy-to-compute log(prior) and that is why I think I need to call the session. Please let me know if there is any other way this can be done or if my understanding of how TFP MCMC sampler works is wrong.

**Comment by dionman** [comment]
@arunpatro which was the correction for your code?

**Comment by arunpatro** [comment]
change these lines
```
nu=qnu, 
corr=qcorr, 
sigma=qsigma, 
mu=qmu,
```
to
```
nu=nu, 
corr=corr, 
sigma=sigma, 
mu=mu,
```

> @arunpatro which was the correction for your code?

**Comment by nikhilmahar** [comment]
I am also getting similar error for following code:

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions

class AdaptiveHMC:
    def __init__(
        self,
        target_log_prob_fn,
        init_state,
        num_results=1000,
        num_burnin=1000,
        num_leapfrog_steps=30,
        step_size=0.1,
    ):
        self.target_log_prob_fn = target_log_prob_fn
        self.init_state = init_state
        self.kernel = tfp.mcmc.SimpleStepSizeAdaptation(
            inner_kernel=tfp.mcmc.HamiltonianMonteCarlo(
                target_log_prob_fn=self.target_log_prob_fn,
                num_leapfrog_steps=num_leapfrog_steps,
                step_size=step_size,
            ),
            num_adaptation_steps=int(0.8 * num_burnin),
            target_accept_prob=0.75,
        )
        self.num_results = num_results
        self.num_burnin = num_burnin

    @tf.function
    def run_chain(self):
        samples, results = tfp.mcmc.sample_chain(
            num_results=self.num_results,
            num_burnin_steps=self.num_burnin,
            current_state=self.init_state,
            kernel=self.kernel,
        )
        return samples, results
    


# Rest of the code remains the same until the target_log_prob function.
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sc
import torch
import torch.nn as nn
import pandas as pd

df = pd.read_excel("./time-5.xlsx")
t=df.to_numpy()
df = pd.read_excel("./disp-5.xlsx")
disp=df.to_numpy()


sigma = 0.01


# obtain response and add noise
#y = a*x+b
points=200
noise = (np.random.randn(len(t[0:points]))*sigma).reshape(len(t[0:points]),1)
x=t[0:points]
y=(disp[0:points]+noise)

noise = np.random.randn(200)*sigma
x=np.linspace(0,3,200)
y=np.cos(7*x)+noise


# create a matrix containing the predictor in the first column
# and the response in the second
data = np.vstack((x,y)).T 
data = tf.constant(data, dtype=tf.float32)
# create a matrix containing the predictor in the first column
# and the response in the second
#data = np.hstack((x,y)).T 
#data=np.concatenate((x,y),axis=1)

# plot data 
plt.figure()
plt.scatter(data[:,0], data[:,1])
plt.xlabel("x")
plt.ylabel("y")
plt.show()



def init_params(n,N1,N2,M):
    W1 = np.random.rand(N1, n) 
    b1 = np.random.rand(N1, 1)
    W2 = np.random.rand(N2, N1) 
    b2 = np.random.rand(N2, 1) 
    W3 = np.random.rand(N2, M) 
    b3 = np.random.rand(M, 1) 
    return W1, b1, W2, b2, W3, b3


np.random.seed(50)
# input nodes
input_nodes=1;
#hidden nodes
N1=5
N2=5
M=1   #total number of output neurons
W1_in, b1_in, W2_in, b2_in, W3_in, b3_in = init_params(input_nodes,N1,N2,M)
SIGMA=np.random.rand(1).reshape(1,-1)
#SIGMA=np.array([0.1])

thetas=np.concatenate((W1_in.flatten(),b1_in.flatten(),W2_in.flatten(),b2_in.flatten(),W3_in.flatten(),b3_in.flatten()))
n=len(thetas)
thetas=thetas.reshape(len(thetas),1)
width = 0.8
accepted = 0
rejected = 0
samples = 100000

data = tf.constant(data, dtype=tf.float32)

# Convert the initial state to TensorFlow tensors with float32 data type
thetas = tf.constant(thetas, dtype=tf.float32)



def forward_prop(X, theta):
    X = tf.reshape(X, [-1, 1])
    W1 = tf.reshape(theta[:N1], [1, N1])
    b1 = tf.reshape(theta[N1:2 * N1], [1, N1])
    W2 = tf.reshape(theta[2 * N2:7 * N2], [N1, N2])
    b2 = tf.reshape(theta[7 * N2:8 * N2], [1, N2])
    W3 = tf.reshape(theta[8 * N2:9 * N2], [N2, M])
    b3 = tf.reshape(theta[9 * N2], [1, M])

    Z1 = tf.matmul(X, W1) + b1
    A1 = tf.nn.sigmoid(Z1)
    Z2 = tf.matmul(A1, W2) + b2
    A2 = tf.nn.sigmoid(Z2)
    Z3 = tf.matmul(A2, W3) + b3
    A3 = Z3
    return A3



def lhd(x, theta):
    xs = x[:, 0]
    ys = x[:, 1]
    print("lhd")
    _fn1 = lambda x: forward_prop(x, theta) 
    #mean=forward_prop(xs, theta)
    mean=_fn1(xs)
    print("mean",mean.shape)
    #lhd_out = sc.norm.logpdf(ys, loc=mean, scale=theta[:, -1] * 1.0)
    u_likeli1 = tfd.Normal(loc=ys, scale=0.1 * tf.ones_like(ys))
    log_likeli = (
        tf.reduce_sum(u_likeli1.log_prob(mean))
       
    )
    print("lhd",log_likeli)
    #lhd_out = tf.reduce_sum(lhd_out)
    return log_likeli


def prior(theta):
    theta_prior = tfd.MultivariateNormalDiag(loc=tf.zeros(n - 1), scale_diag=tf.ones(n - 1))
    sigma_prior = tfd.Gamma(concentration=100.0, rate=0.01)
    prior_out = theta_prior.log_prob(theta[:-1]) + sigma_prior.log_prob(theta[-1])
    return prior_out

# Correct the length of theta
n = len(thetas[1])

# Define the target log probability function (1D Gaussian) using TensorFlow.
def target_log_prob(x):
    #theta_prior = prior(thetas[-1,:])
    log_lik_theta = lhd(data, thetas[:,-1])
    log_lik =  log_lik_theta
    return log_lik


# Create an instance of AdaptiveHMC with desired parameters.
num_results = 1000
num_burnin = 1000
num_leapfrog_steps = 30
step_size = 0.1
#ahmc = AdaptiveHMC(target_log_prob, thetas, num_results, num_burnin, num_leapfrog_steps, step_size)
# ... (previous code remains the same)
ahmc = AdaptiveHMC(target_log_prob, thetas, num_results, num_burnin, num_leapfrog_steps, step_size)
# ... (rest of the code remains the same)


# Run the sampling chain and get the samples and results.
samples, results = ahmc.run_chain()

# The samples variable contains the generated samples after burn-in.
print("Generated Samples:")
print(samples)

# Compute some statistics of the generated samples.
mean_sample = tf.reduce_mean(samples, axis=0)
variance_sample = tf.reduce_mean((samples - mean_sample)**2, axis=0)
print("\nMean of Samples:", mean_sample.numpy())
print("Variance of Samples:", variance_sample.numpy())

error is:

ValueError: Encountered `None` gradient.
  fn_arg_list: [<tf.Tensor 'mcmc_sample_chain/trace_scan/while/smart_for_loop/while/simple_step_size_adaptation___init__/_one_step/mh_one_step/hmc_kernel_one_step/leapfrog_integrate/while/leapfrog_integrate_one_step/add:0' shape=(46, 1) dtype=float32>]
  grads: [None]
