### ISSUE TITLE
Optimization does not seem to work with build_factored_variational_loss in eager mode

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#457]
Hi,

the below example, where the fitting code is basically taken from 

https://github.com/tensorflow/probability/blob/3a1fe2043f4cce66a35fcfaa89b47b16acfcf55b/tensorflow_probability/python/sts/fitting_test.py#L58

shows decreasing loss in static graph mode, but no progress in eager mode.
The test only checks for correct shapes, not loss decrease, so I'm wondering if somehow in eager mode, variable state is lost here?

```
import tensorflow as tf
#tf.enable_v2_behavior()
import tensorflow_probability as tfp
import numpy as np


observed_time_series = (np.arange(1, 101) + np.random.randn(100)).astype(np.float32)

model = tfp.sts.LocalLinearTrend()

def build_variational_loss():
  (variational_loss, _) = tfp.sts.build_factored_variational_loss(
      model=model,
      observed_time_series=observed_time_series)
  print(str(variational_loss) + "\n")
  return variational_loss

optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.1)

if tf.executing_eagerly():
  for _ in range(100):  
    optimizer.minimize(build_variational_loss)
else:
  variational_loss = build_variational_loss()
  train_op = optimizer.minimize(variational_loss)
  sess = tf.Session()
  sess.run(tf.compat.v1.global_variables_initializer())
  for _ in range(100): 
    sess.run(train_op)
    loss = sess.run(variational_loss)
    print(str(loss) + "\n")
```

Output in static mode:

```
Tensor("build_factored_variational_loss/Neg_2:0", shape=(), dtype=float32)

214.40775

208.93944

207.45033
...
...
...

172.28859

172.84645

```

Output in eager mode:

```
tf.Tensor(221.03374, shape=(), dtype=float32)

tf.Tensor(242.22517, shape=(), dtype=float32)

...
...

tf.Tensor(231.78775, shape=(), dtype=float32)

tf.Tensor(226.86786, shape=(), dtype=float32)

tf.Tensor(242.59215, shape=(), dtype=float32)

```

Many thanks!

**Comment by davmre** [comment]
Thanks for reporting this; it definitely looks like a bug (in both the fitting code and the test).

My guess is that the underlying issue is that in eager mode the variables are getting rebuilt on each call -- `build_factored_variational_loss` both creates Variables and uses them to define a loss function, which is fine in graph mode but in Eager you want to separate those concerns (i.e., define Variables outside of a training loop but compute the loss and grads inside the loop). 

We're working on an updated API for VI fitting that will support this. I'd expect it might go out within the next couple of weeks (knock on wood). For now the recommended workaround is, unfortunately, to stick with graph mode.

**Comment by skeydan** [comment]
Hi Dave, thanks, then I'll stick with graph for now.
Can you link the fix here when it's merged?

**Comment by davmre** [comment]
We just committed a rewrite of STS fitting to better support eager idioms and integrate with the evolving set of `tfp.vi` utils. The main change is a shift from `build_factored_variational_loss` to `build_factored_surrogate_posterior`, which lets you build the surrogate posterior variables outside of a training loop, then fit them by optimizing a loss of your choice (or use `tfp.vi.fit_surrogate_posterior` to automate the loss construction and fitting):

  ```python
    surrogate_posterior = tfp.sts.build_factored_surrogate_posterior(
      model=model)
    loss_curve = tfp.vi.fit_surrogate_posterior(
      target_log_prob_fn=model.joint_log_prob(observed_time_series),
      surrogate_posterior=surrogate_posterior,
      num_steps=200)
    posterior_samples = surrogate_posterior.sample(50)
    # In graph mode, we would need to write:
    # with tf.control_dependencies([loss_curve]):
    #   posterior_samples = surrogate_posterior.sample(50)
  ```

(example from https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/sts/fitting.py#L144)

This will be in tfp-nightly as of tonight; feedback very welcome if you have a chance to try this out!

**Comment by skeydan** [comment]
Hi @damvre that's awesome!! I didn't get to test it today, but I definitely will tomorrow!

**Comment by skeydan** [comment]
@damvre sorry for the delay! I have to create a few wrappers first and sometimes there is some tricky stuff involved. May I ask you reg. a strange (to me, but it's probably not strange at all) thing?

Trying to use this (from https://github.com/tensorflow/probability/blob/210bff1979f62e5ba425c8d3030e6821f2dcc0c9/tensorflow_probability/python/vi/optimization.py#L129) as a test case 

```
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd
import tensorflow as tf
tf.enable_v2_behavior()

def log_prob(z, x): return tfd.Normal(0., 1.).log_prob(z) + tfd.Normal(z, 1.).log_prob(x)

conditioned_log_prob = lambda z: log_prob(z, x=5.)
# this does not work
#conditioned_log_prob = lambda z: z.log_prob(5)

q_z = tfd.Normal(loc=tf.Variable(0., name='q_z_loc'),
                   scale=tfp.util.DeferredTensor(
                     tf.nn.softplus,
                     tf.Variable(0., name='q_z_scale')), name='q_z')
                     
losses = tfp.vi.fit_surrogate_posterior(
      conditioned_log_prob,
      surrogate_posterior=q_z,
      optimizer=tf.train.AdamOptimizer(learning_rate=0.1),
      num_steps=100)
```
 I don't understand where the `x` comes from in `conditioned_log_prob = lambda z: log_prob(z, x=5.)` - shouldn't the argument be called `value`?

To port this to R, when I do

```
conditioned_log_prob <- function(z) tfp$distributions$Distribution$log_prob(z, x = 5)
```
I get

```
RuntimeError: Evaluation error: TypeError: log_prob() missing 1 required positional argument: 'value'.
```
But I cannot pass `value` in Python either.

BTW I've also tried the R equivalent of
```
conditioned_log_prob = lambda z: z.log_prob(5)
```
but evidently this is not possible in Python either.

Would you have an idea what I could do about the `x`?
Thanks!!

**Comment by davmre** [comment]
Hi Sigrid, just to clarify, does the Python code by itself work for you? It does for me, so I suspect the issue is on the R side somewhere.

Your ported `conditioned_log_prob <- function(z) tfp$distributions$Distribution$log_prob(z, x = 5)` doesn't look right to me. Following the Python code, it should be calling the custom `log_prob` we defined (which takes Tensor arguments `z` and `x`), not the log-prob for the base Distribution class. Probably we should name this function something more distinctive like `model_log_prob` or `target_log_prob`...

**Comment by skeydan** [comment]
Oops sorry Dave, that was really stupid of me!! I must have been in some pretty confused state...thanks :-)

**Comment by skeydan** [comment]
In eager mode this runs great for me now! One last (hopefully not that stupid) question if I may, is the above example supposed to work in graph mode?

For me that fails at 
```
losses = tfp.vi.fit_surrogate_posterior(
      conditioned_log_prob,
      surrogate_posterior=q_z,
      optimizer=tf.train.AdamOptimizer(learning_rate=0.1),
      num_steps=100)
```


with 

```
ValueError: No variables provided.
```

So I would assume `tf.control_dependencies` needs to be used with graph, but,  looking at the usage of `tf.control_dependencies` in the corresponding test https://github.com/tensorflow/probability/blob/d7aa69574e6a11ac9ac070db762c993b9af98c01/tensorflow_probability/python/vi/optimization_test.py#L69

```
loss_curve = tfp.vi.fit_surrogate_posterior(
        trainable_log_prob, q,
        num_steps=1000,
        sample_size=10,
        optimizer=tf.optimizers.Adam(0.1),
        seed=seed)
self.evaluate(tf1.global_variables_initializer())
with tf.control_dependencies([loss_curve]):
      final_q_loc = tf.identity(q.mean())
      final_q_scale = tf.identity(q.stddev())
      final_likelihood_scale = tf.identity(likelihood_scale)
```
I see that `tf.control_dependencies([loss_curve])` is used after the line that (in the shorter docstring version) fails for me...

Thanks again!

**Comment by davmre** [comment]
That example should run in graph mode, but it looks like it assumes the use of new-style 'resource' variables, which are default in TF2 but not TF1. You can get it working in TF1 by adding `tf.compat.v1.enable_resource_variables()` at the top of your program, or by passing `use_resource=True` to each of the Variable constructors.

Are you seeing the error with `tfp.sts.build_factored_surrogate_posterior`, or just that VI example code? If it's coming from STS code, it's a bug and we should fix it.

**Comment by skeydan** [comment]
No, it's not coming from STS :-)
I've now been able to test the STS-related code and it runs fine with eager as well as graph :-)

For the above ` tfp.vi.fit_surrogate_posterior` docstring code, adding 

`tf.compat.v1.enable_resource_variables()`

makes the error go away, but the result looks false (mean after fitting is 0).
I'm adding the code to reproduce in a second, but anyway I think for my current purpose (which right now is just the unit test for  `tfp.vi.fit_surrogate_posterior`) I will just skip the test when running in graph mode... Anyway I think that with the substantial differences between  TF1 and TF2, it will not make sense forever to test all new functionality with TF1...
So from my side feel free to close anytime, and thanks again - here in any case is the code to reproduce the "mean 0" behavior I mentioned above:

```
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd
import tensorflow as tf

tf.compat.v1.enable_resource_variables()

def log_prob(z, x): return tfd.Normal(0., 1.).log_prob(z) + tfd.Normal(z, 1.).log_prob(x)
conditioned_log_prob = lambda z: log_prob(z, x=5.)

q_z = tfd.Normal(loc=tf.Variable(0., name='q_z_loc'),
                 scale=tfp.util.DeferredTensor(tf.nn.softplus,
                 tf.Variable(0., name='q_z_scale')), name='q_z')
                     
losses = tfp.vi.fit_surrogate_posterior(
  conditioned_log_prob,
  surrogate_posterior=q_z,
  optimizer=tf.train.AdamOptimizer(learning_rate=0.1),
  num_steps=100)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(q_z.mean())
```

**Comment by davmre** [comment]
So the tricky thing about graph mode is that you need to add `control_dependencies` wrappers to ensure the optimization actually gets run. Calling `fit_surrogate_posterior` adds optimization ops to the graph, but since fetching a Tensor in graph mode only runs the ops prior to that Tensor in the dependency graph, just fetching `q_z.mean()` won't run the optimization unless you explicitly force a dependency. This should work:

```python
# ...

losses = tfp.vi.fit_surrogate_posterior(
  conditioned_log_prob,
  surrogate_posterior=q_z,
  optimizer=tf.train.AdamOptimizer(learning_rate=0.1),
  num_steps=100)

with tf.control_dependencies([losses]):
  # `tf.identity` ensures we create a new op to capture the dependency.
  optimized_mean = tf.identity(q_z.mean())

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(optimized_mean)
```

This is one of many ways in which Eager mode is more intuitive than graph mode. :-)

**Comment by skeydan** [comment]
Finally got it, thanks! :-)
(I had seen that in the unit test but evidently not put all pieces together ;-))

Now my test runs in both modes which is fine :-)

> This is one of many ways in which Eager mode is more intuitive than graph mode. :-)

Yeah, and it seems the direction is let the user write eager and wrap stuff in graph internally, right (like with the HMC fitting that had to be wrapped in `tf.function` until recently... or like it works with `tf.keras`...)? That is a lot more convenient then in fact :-)

Thanks again, closing!
