### ISSUE TITLE
Cannot run lstm_tfp example in jupyter notebooks

### ISSUE THREAD

**Issue by tungnt55** [tensorflow/probability#460]
I tried to run the example of lstm using tensorflow probability (in the link below): 
https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/LSTM_TFP.ipynb  
What I did is simply copy-paste the code into a python script file and then execute it. However, I couldn't make it run, it always hang at the line:  
```
[_, train_nll_] = evaluate([train_op, train_nll])
```
No error is shown on screen, the session just hang there.

**Comment by srvasude** [comment]
Hi,
  I don't believe this example exists anymore, so I am closing the issue. We do have an STS library that hopefully satisfies your usecase. Feel free to reopen this issue if you'd like to see autoregressive uses of TFP.
