### ISSUE TITLE
MultivariateNormalFullCovariance: Cholesky decomposition was not successful

### ISSUE THREAD

**Issue by 100376348** [tensorflow/probability#464]
Hi, I am working in GMM and I have a problem when I try to randomly generate MultivariateNormalFullCovariance.
```
k = 3
dim = 2
n_sample = tf.constant(np.random.randint(1, 5*k, size=k)*1000, dtype=tf.int32)
true_mu = tf.constant(np.random.rand(k,dim)*10, dtype=tf.float32)
sigma_aux = 0.5 * np.random.rand(k,dim,dim) + 0.1
sigma_aux = np.dot(sigma_aux, np.transpose(sigma_aux, (0,2,1))
true_sigma = tf.constant(sigma_aux, dtype=tf.float32)
true_dist_norm = tfd.MultivariateNormalFullCovariance(loc=true_mu, covariance_matrix=true_sigma)

def generate_samples(n_sample, norm):
    samplesA = norm.sample(sample_shape=n_sample[0])[:,0]
    samplesB = norm.sample(sample_shape=n_sample[1])[:,1]
    samplesC = norm.sample(sample_shape=n_sample[2])[:,2]

    samples = tf.concat([samplesA, samplesB, samplesC], 0)
    return samples

sess = tf.InteractiveSession()
samples = sess.run(generate_samples(n_sample, true_dist_norm))
sess.close()
```

The code from above it ending up with the following error:

> InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
	 [[{{node MultivariateNormalFullCovariance_10/init/Cholesky}}]]

This code works perfectly fine if I initialize the covariance matrix manually like this:
`true_sigma = tf.constant([[[0.1, 0.13],[0.13, 0.8]], [[0.2, 0.12],[0.12, 0.4]], [[0.1, 0.09],[0.09, 0.8]]], dtype=tf.float32)`

The covariance matrix is a symmetric positive definite matrix, and I have tried out typical solutions like the following one (proposed [here](https://github.com/GPflow/GPflow/issues/553)):
```
Kf = (Kf + tf.transpose(Kf,perm=[0,2,1]))/2.
e,v = tf.self_adjoint_eig(Kf)
e = tf.where(e > 1e-14, e, 1e-14*tf.ones_like(e))
Kf_pos_def = tf.matmul(tf.matmul(v,tf.matrix_diag(e),transpose_a=True),v) 
```

I think this may be a bug, but I don't know... Maybe is my mistake (I am pretty new at this statistic/algebra/... world). If anyone has any idea about this issue, I would be very glad.

Thank you so much in advance!

**Comment by skeydan** [comment]
Hi,

from the line 

```
sigma_aux = 0.5 * np.random.rand(k,dim,dim) + 0.1
```

one can get matrices  such as these, where the first is not positive semidefinite (not even symmetric, but that's ignored by `tfd.MultivariateNormalFullCovariance`):

```
array([[[0.11432126, 0.58535485],
        [0.55203346, 0.16035991]],

       [[0.57614413, 0.18314088],
        [0.5718848 , 0.54410207]],

       [[0.57588409, 0.32826305],
        [0.38662137, 0.42072244]]])
```

To generate positive semidefinite matrices, you could e.g. multiply a matrix by its transpose, as suggested in this SO thread: https://stackoverflow.com/questions/619335/a-simple-algorithm-for-generating-positive-semidefinite-matrices.

**Comment by 100376348** [comment]
@skeydan Thanks for your answer.

I forgot to copy one line. I was copying only some lines, because there is a lot of unrelated code (unrelated to this issue). I am going to add the line right now. Later I will check out the code to verify that the covariance matrix is correct, but I think it is.

**Comment by srvasude** [comment]
Please reopen if this is still an issue.
