### ISSUE TITLE
type object 'Module' has no attribute '_TF_MODULE_IGNORED_PROPERTIES'

### ISSUE THREAD

**Issue by KOLANICH** [tensorflow/probability#465]
```
***/tensorflow_probability/python/bijectors/bijector.py in Bijector()
    561   """
    562 
--> 563   _TF_MODULE_IGNORED_PROPERTIES = tf.Module._TF_MODULE_IGNORED_PROPERTIES.union(
    564       (
    565           '_graph_parents',

AttributeError: type object 'Module' has no attribute '_TF_MODULE_IGNORED_PROPERTIES'
```

TensorFlow version is nightly built 2019-06-14

**Comment by csuter** [comment]
I think that field was added back in April, so it seems odd that it's not there.

Can you confirm you don't have 2 parallel TF versions installed (e.g., `tensorflow` and `tf-nightly`)?

**Comment by KOLANICH** [comment]
>Can you confirm you don't have 2 parallel TF versions installed (e.g., tensorflow and tf-nightly)?

As far as I remember, I have installed tf only from nightly wheels.

**Comment by csuter** [comment]
can you do `pip list` to check what's there?

**Comment by KOLANICH** [comment]
You were right. I have mistakingly installed tf-nightly instead of tf-nightly-2.0-preview.
