### ISSUE TITLE
the tfp.mcmc.HamiltonianMonteCarlo can't be used in eager mode

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/probability#477]
The step_size parameter of __init__() expects a tensor or a list of tensor. when I run in eager mode. I get an error message that

> AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute `assign_add`

Therefore, I can only use it in graph mode.

**Comment by SiegeLordEx** [comment]
Would you mind showing us more code? What version of TFP are you using?
