### ISSUE TITLE
Docs: Default values not listed for hyperparameters in ExponentiatedQuadratic class

### ISSUE THREAD

**Issue by alinaselega** [tensorflow/probability#484]
## URL(s) with the issue:

https://www.tensorflow.org/probability/api_docs/python/tfp/positive_semidefinite_kernels/ExponentiatedQuadratic

## Description of issue (what needs changing):

List default values for hyperparameters `amplitude` and `length_scale` that are used when a kernel is created with default values, as suggested [here](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/GaussianProcess#examples):

```
tfd = tfp.distributions
psd_kernels = tfp.positive_semidefinite_kernels

# Define a kernel with default parameters.
kernel = psd_kernels.ExponentiatedQuadratic()
```

### Parameters defined

Default values for `amplitude` and `length_scale` are not listed (apart from a keyword 'None').

**Comment by trainorpj** [comment]
It looks like when `ExponentiatedQuadratic()` is intended to work when `amplitude` and `length_scale` are `None`. [This line shows](https://github.com/tensorflow/probability/blob/dd14e161d86d83fa71c58c70373763a259c660d2/tensorflow_probability/python/positive_semidefinite_kernels/exponentiated_quadratic.py#L113) that when `self._apply()` is called, it returns something (as seen in the example for `GaussianProcess`).

```py
# ExponentiatedQuadratic
def _apply(self, x1, x2, example_ndims=0):
    exponent = -0.5 * util.sum_rightmost_ndims_preserving_shape(
        tf.math.squared_difference(x1, x2), self.feature_ndims)
    
    # other stuff handling amplitude and length_scale is not None...
    # which doesn't get called, in our case

    return tf.exp(exponent)
```

I agree that it's confusing, and it could be improved. Which of these are you suggesting?

1. The `ExponentiatedQuadratic` [documentation](https://www.tensorflow.org/probability/api_docs/python/tfp/positive_semidefinite_kernels/ExponentiatedQuadratic) should be more clear about what's happening when those parameters are `None` (i.e. their defaults)
2. The `GaussianProcess` [examples](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/GaussianProcess#examples) should be more clear about what the kernel is doing without any parameters

Let me know if I missed something!

**Comment by csuter** [comment]
Sorry, I think this is just a documentation bug. When these params are `None`, the thing we compute is equivalent to if they were `1.`, but we use an `is None` check to avoid actually doing, e.g., a divide or multiply by `1.`. This will lead to a smaller graph (in graph mode) and a slightly more efficient computation in both graph and eager modes.

I think the docstrings should be made to articulate this (ie, that `None` acts like `1.` but slightly more efficient), PR's welcome :)

**Comment by alinaselega** [comment]
I agree that the changes to the documentation you mentioned would be very useful. Should I keep this issue open for now?

**Comment by trainorpj** [comment]
PR merged, this can be closed 🙂
