### ISSUE TITLE
Collab notebook error

### ISSUE THREAD

**Issue by jacor-** [tensorflow/probability#486]
Hello,
I am getting the following error when I  run this example (both locally and in Collab Notebooks):  https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Linear_Mixed_Effects_Models.ipynb

Any suggestion about how to fix it?

----------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-3af50542927d> in <module>()
     28 next_state, kernel_results = hmc.one_step(
     29       current_state=current_state,
---> 30       previous_kernel_results=hmc.bootstrap_results(current_state))
     31 
     32 expectation_update = tf.group(

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/internal/leapfrog_integrator.py in _one_step(self, half_next_momentum_parts, state_parts, target, target_grad_parts)
    328       next_target.set_shape(target.shape)
    329       for ng, g in zip(next_target_grad_parts, target_grad_parts):
--> 330         ng.set_shape(g.shape)
    331 
    332       next_half_next_momentum_parts = [

AttributeError: 'IndexedSlices' object has no attribute 'set_shape'

**Comment by csuter** [comment]
@SiegeLordEx who probably touched leapfrog code most recently.

Gradients of `tf.gather` return `IndexedSlices` (which are a `CompositeTensor`, not a plain ol' `Tensor`). So a gather op may be the source of this.

**Comment by twiecki** [comment]
Running into the same problem.

**Comment by csuter** [comment]
FYI -- this should be fixed in the latest tf-nightly-2.0-preview. Please reopen if you find it's not working for you!
