### ISSUE TITLE
Shape mismatch for tfd.QuantizedDistribution of tfd.Indepent.

### ISSUE THREAD

**Issue by krzysztofrusek** [tensorflow/probability#489]
Hi All

I am getting an error in `log_prob` when using `tfd.Independs` with `tfd.QuantizedDistribution` with low and high arguments.
When low and high arguments are removed everything works as expected.
Switching the order (QuntizedDistribution first, then `tfd,Independent`) also solves the problem

```python
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions

g=tf.Graph()

with g.as_default():
  
  n = tfd.Normal(
  loc=[1.0,2.0,3.0],
  scale = [[1.0],[2.0]])
  
  n=tfd.Independent(n, reinterpreted_batch_ndims=2)
  
  q = tfd.QuantizedDistribution(n, low=1.0, high=4.0 )
  
  #This works
  #q = tfd.QuantizedDistribution(n )
  
  x=q.sample()
  l=q.log_prob(x)
  
with tf.Session(graph=g) as ses:
  out = ses.run(l)
  print(out)
```
- Output: `InvalidArgumentError: Shapes must be equal rank, but are 0 and 2 for 'QuantizedDistribution/log_survival_function/Select' (op: 'Select') with input shapes: [2,3], [], [].`

- `tf.__version__, tfp.__version__ : ('1.14.0', '0.7.0')

**Comment by junpenglao** [comment]
I think Independent should be the outer most wrapper?
```
q = tfd.Independent(tfd.QuantizedDistribution(n, low=1.0, high=4.0), reinterpreted_batch_ndims=2)
```

**Comment by krzysztofrusek** [comment]
This exactly what works for me. I have checked the documentation before submitting the issue and there is no information whatsoever about the supported position of `tfd.Independent` in the distribution chain.

**Comment by brianwa84** [comment]
I suspect there's a bug in the way QuantizedDistribution handles
non-scalar-event underlying distributions. We should probably flesh out the
test coverage and see what it turns up.

Brian Patton | Software Engineer | bjp@google.com

**Comment by srvasude** [comment]
I believe this is fixed (I tried running with /without the commented block and everything works as expected). Closing this, but feel free to reopen if this is still an issue.
