### ISSUE TITLE
tfp-nightly Import error

### ISSUE THREAD

**Issue by nklarer** [tensorflow/probability#49]
Hi TFP Team,

I recently ran a Colab that functioned last week. It seems that the latest TFP nightly install has trouble importing the following function:

` ---> 22 from tensorflow.python.keras._impl.keras.backend import abs
     23 from tensorflow.python.keras._impl.keras.backend import all
     24 from tensorflow.python.keras._impl.keras.backend import any

ImportError: cannot import name 'abs' `

So, I reverted the tfp-nightly install to an earlier developer version based on the syntax available to me with pip show:

`!pip install tfp-nightly==0.0.1.dev20180512`

Unfortunately, I then ran into the following error:

`---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

ImportError: cannot import name pywrap_tensorflow`

Which supposedly has to do with running Tensorflow in the install directory. So, I tried to cd out of the install directory - but colab limits changing directories. I will attempt to run this program in a Jupyter notebook to see if this resolves and update you then.

**Comment by nklarer** [comment]
I have confirmed that the notebook runs locally using the following TFP version. It **does not run** in colab using this version.
`
Name: tfp-nightly
Version: 0.0.1.dev20180503
Summary: Probabilistic modeling and statistical inference in TensorFlow
Home-page: http://github.com/tensorflow/probability
`
Which means that I believe I've identified a compatibility problem with colab.

**Comment by srvasude** [comment]
Going to close, because I think this issue is fixed. Please reopen if otherwise.
