### ISSUE TITLE
Bijector forward memory leak

### ISSUE THREAD

**Issue by j-wilson** [tensorflow/probability#493]
#### Environment:
- macOS 10.14.5
- Python 3.6.7
- tensorflow==2.0.0b1 
- tfp-nightly==0.8.0.dev20190628

#### Problem:
The forward methods of some `<tfp.bijector.Bijector>`, such as `<tfp.bijector.Identity>` and `<tfp.bijector.Exp>`, seem to create memory leaks.

#### Demo:
The following demo uses the [memory_profiler](https://pypi.org/project/memory-profiler) package.
```python
from memory_profiler import profile
from tensorflow.random import uniform
from tensorflow_probability.python.bijectors import Exp, Identity

@profile
def foo(sample_shape):
    return uniform(sample_shape)

@profile
def bar(sample_shape, bijector):
    return bijector.forward(uniform(sample_shape))

bijector = Exp()
for step in range(1000):
    # foo(sample_shape=[2**20])
    bar(sample_shape=[2**20], bijector=bijector)
```
My expectation is that the memory footprints when using functions `foo()` and `bar()` will be comparable both to one another and between runs. Using `foo()`, the profiler consistently reports:
```
# At step=0:
Line #    Mem usage    Increment   Line Contents
================================================
     6    219.4 MiB    219.4 MiB   @profile
     7                             def foo(sample_shape):
     8    233.9 MiB     14.6 MiB       return uniform(sample_shape)

# At step=999:
Line #    Mem usage    Increment   Line Contents
================================================
     6    310.1 MiB    310.1 MiB   @profile
     7                             def foo(sample_shape):
     8    310.1 MiB      0.0 MiB       return uniform(sample_shape)
```
Using `bar()`, the memory usage is seemingly dictated at runtime. Behavior varies depending on the choice of bijector.  For `<tfp.bijector.Identity>`, the profile consistently looks like:
```
# At step=0:
Line #    Mem usage    Increment   Line Contents
================================================
     9    218.5 MiB    218.5 MiB   @profile
    10                             def bar(sample_shape, bijector):
    11    234.0 MiB     15.6 MiB       return bijector.forward(uniform(sample_shape))

# At step=999:
Line #    Mem usage    Increment   Line Contents
================================================
     9   4264.6 MiB   4264.6 MiB   @profile
    10                             def bar(sample_shape, bijector):
    11   4268.6 MiB      4.0 MiB       return bijector.forward(uniform(sample_shape))
```
For `<tfp.bijector.Exp>`, the demo's memory footprint sometimes converges reasonably; other times it looks like:
```
# At step=0:
Line #    Mem usage    Increment   Line Contents
================================================
     9    219.3 MiB    219.3 MiB   @profile
    10                             def bar(sample_shape, bijector):
    11    237.9 MiB     18.6 MiB       return bijector.forward(uniform(sample_shape))

# At step=998:
Line #    Mem usage    Increment   Line Contents
================================================
     9   4042.9 MiB   4042.9 MiB   @profile
    10                             def bar(sample_shape, bijector):
    11   4046.9 MiB      4.0 MiB       return bijector.forward(uniform(sample_shape))
```
In my actual use case, the memory footprint continues to grow when using `<tfp.bijector.Exp>` as the link function for a Gaussian Process.

**Comment by csuter** [comment]
Hi James, thanks for reaching out. This is in a sense a "feature", though I agree it's not ideal here. Bijectors cache input/output pairs, which in the graph world was low-cost, but in eager mode it means the tensor *values* are stored as well, which I think is what is biting you.  One potential workaround might be to decorate the function(s) that are applying Bijectors to large inputs with `@tf.function`, which creates a graph in the background. Can you give this a try?

**Comment by j-wilson** [comment]
I see; thanks for explaining. This makes more sense to me now as legacy behavior. Given how extensively bijectors are used in tfp, the choice to always cache seems questionable when executing in eager mode? If nothing else, I think it will qualify as unexpected behavior for many users. Perhaps a flag (instance-specific and/or package-wide) could be added to regulate caching?

Regarding `@tf.function`, I will have to give it another look to see whether I can effectively use this decorate without significant refactoring.

**Comment by brianwa84** [comment]
Does `@profile` retain references to the returned values? What happens if
you return None or return forward(..) + 0 from bar?
Eager mode caching is weak-keyed on the output precisely to avoid this kind
of leak.

Brian Patton | Software Engineer | bjp@google.com

**Comment by j-wilson** [comment]
I don't think it maintains any references. As per the package description, "[memory_profiler] gets the memory consumption by querying the operating system kernel about the amount of memory the current process has allocated". Similarly, modifying the function's return values as you suggested does not seem to impact the resulting profile.

**Comment by brianwa84** [comment]
Note that I found/fixed a leak in tfb.Identity a couple weeks back. Exp is puzzling. You still see this on nightly?

**Comment by j-wilson** [comment]
Just updated my `tfp-nighty` and tested several times. Happy to report that the previous memory issue no longer manifested (for either bijector)!

**Comment by brianwa84** [comment]
Glad to hear it, thanks for reporting this one!
