### ISSUE TITLE
Disable storing the states in every step of MCMC

### ISSUE THREAD

**Issue by rzu512** [tensorflow/probability#497]
How to disable storing the the states in every step in `tfp.mcmc.sample_chain`?

I am only interested in the state that give the lowest logp. Storing the state in every step would take too much memory.

[tfp.mcmc.sample_chain](https://github.com/tensorflow/probability/blob/645b8e2eae077187f7e998bd6f57a45fa61a2994/tensorflow_probability/python/mcmc/sample.py#L348) seems to first store the states in every steps as `all_states`. Then it applies the `trace_fn` to transform the `all_states`. 

```python
(_, final_kernel_results), (all_states, trace) = mcmc_util.trace_scan(
        loop_fn=_trace_scan_fn,
        initial_state=(current_state, previous_kernel_results),
        elems=tf.one_hot(
            indices=0,
            depth=num_results,
            on_value=1 + num_burnin_steps,
            off_value=1 + num_steps_between_results,
            dtype=tf.int32),
        # pylint: disable=g-long-lambda
        trace_fn=lambda state_and_results: (state_and_results[0],
                                            trace_fn(*state_and_results)),
        # pylint: enable=g-long-lambda
        parallel_iterations=parallel_iterations)

    if return_final_kernel_results:
      return CheckpointableStatesAndTrace(
          all_states=all_states,
          trace=trace,
          final_kernel_results=final_kernel_results)
    else:
      if no_trace:
        return all_states
      else:
        return StatesAndTrace(all_states=all_states, trace=trace)
```

**Comment by SiegeLordEx** [comment]
If you want just the final state of the chain, you can write a simple loop manually:
```python
initial_results = kernel.bootstrap_results(init_state)
final_state, final_results = tf.while_loop(
    lambda *args: True,
    kernel.one_step,
    (init_state, initial_results),
   maximum_iterations=num_steps)
```

Note that `final_state` is not at all related to the "state that give the lowest logp", aka the 'mode', as MCMC will typically generate samples from the "typical set" which will be very far from the mode. If you are only interested in the mode, then you can use TensorFlow's standard optimization toolkit to find it.

**Comment by brianwa84** [comment]
Closing, please reopen if you have another q.
