### ISSUE TITLE
Gathering and slicing ops for RandomVariable's

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#5]
https://discourse.edwardlib.org/t/variational-gaussian-process-gp-regression-tensor-object-has-no-attribute-log-prob/697

This ultimately bottoms out to getting such ops implemented in distributions, which we might then leverage in `tfp.edward2`.

**Comment by Joshuaalbert** [comment]
Any progress?

**Comment by dustinvtran** [comment]
No progress.

**Comment by srvasude** [comment]
FWIW @brianwa84 has implemented in quite a few distributions slicing operations, which should hopefully propagate to Edward2 Random variates.

**Comment by srvasude** [comment]
I'm going to close this bug. `tfp.distributions` support slicing on batches (and can support complicated slices). Edward2 is not part of the current repo, but I believe should inherit these slicing properties.
