### ISSUE TITLE
Inducing prior for Variational Gaussian Process should not include observational noise

### ISSUE THREAD

**Issue by mrksr** [tensorflow/probability#514]
Hello everyone!

I have been playing around with the VGP implementation and have found some rather strange behaviour. Reading through the code I noticed that the inducing prior includes observational noise:

https://github.com/tensorflow/probability/blob/43e2db148211349cfcafc5b839a8e62d87b8d222/tensorflow_probability/python/distributions/variational_gaussian_process.py#L752

To my understanding, as the inducing prior references latent function values, it should not contain noise. And indeed, setting `observation_noise_variance=0.` removes some unwanted artifacts. In the plots below, red is the training data, green is the GP posterior (mean +- 2 std, calculated from samples) and blue are the inducing points. I also drew a few samples from the posterior. I trained the GP using the optimal variational distribution.

Am I missing something?

## With observational noise in prior
![sgpr_noise_in_prior](https://user-images.githubusercontent.com/5184063/62373467-22e9f780-b53a-11e9-965d-e411bd80dfed.png)

## Without observational noise in prior
![sgpr_no_noise_in_prior](https://user-images.githubusercontent.com/5184063/62373492-2a110580-b53a-11e9-8722-e3bdf1451672.png)

Note that inducing points are placed where they should not be at about -0.25 (or, if they are there, they should have higher variance) and the "bump" in uncertainty just next to the data, which should not be there. Both effects go away without the noise in the prior.

**Comment by csuter** [comment]
Ah, great point! Thanks for filing this (with pictures!). I can fix today.
