### ISSUE TITLE
 Broken links in edward2.md

### ISSUE THREAD

**Issue by myoshimu** [tensorflow/probability#526]
We are not seeing the Overview or Upgrade guide linked in [edward2.md](https://github.com/tensorflow/probability/blob/d24e333cb2742dee0fad6a4aabf1484766aea17f/tensorflow_probability/g3doc/api_docs/python/tfp/edward2.md).

Those document can not be also open from the official [TFP website](https://www.tensorflow.org/probability/api_docs/python/tfp/edward2?hl=ja).

Would you put the correct URLs?

**Comment by jordanero** [comment]
Hi, 

The links still don't work for me. Is there somewhere I can access them?

**Comment by davmre** [comment]
Sorry about that -- the corrected links should appear in the online docs once they're regenerated, which should happen when the next TFP version (0.8.0) is released soon. For now you can read them directly from the source docstring:
https://github.com/tensorflow/probability/commit/12c57f6b785167c4f9e6427520360ce64d845e96
