### ISSUE TITLE
User-defined random variables in Edward2

### ISSUE THREAD

**Issue by davmre** [tensorflow/probability#53]
Currently Edward2 provides predefined random variables for each TF Distribution, e.g., `tfd.Normal` is wrapped as`ed.Normal`. In general, users should be able to extend Edward by defining their own custom random variables, just as they can define custom Distributions.

@dustinvtran and I discussed this briefly; there are at least three solutions we might consider:

1) Publicly expose the `make_random_variable(distribution_cls)` utility function. A user would implement their custom `CrazyDistribution(tf.Distribution)`, then write a probabilistic program as
```python
CrazyRV = ed.make_random_variable(CrazyDistribution)
def ed_model():
  a = ed.Normal(0., 1.)
  b = CrazyRV(scale = a)
  return some_fn(b)
```

2) Implement and expose `ed.CustomRV(distribution_instance)`. This is an RV whose only parameter is a Distribution instance. A user would write
```python
def ed_model():
  a = ed.Normal(0., 1.)
  b = ed.CustomRV(CrazyDistribution(scale = a))
  return some_fn(b)
```
or if desired, could use the sugar `CrazyRV = lambda *args, **kwargs : ed.CustomRV(CrazyDistribution(*args, **kwargs))` to recover the syntax above.

3) Publicly expose the `@interceptable` decorator. This is the lowest-level approach; the user could directly implement their own analogue of `make_random_variable`. 
```python

@interceptable
def CrazyRV(*args, sample_shape=(), value=None, **kwargs):
  return ed.RandomVariable(
              CrazyDistribution(*args, **kwargs), 
              sample_shape=sample_shape, value=value)

def ed_model():
  a = ed.Normal(0., 1.)
  b = CrazyRV(scale = a)
  return some_fn(b)
```

These solutions are not mutually exclusive; we could support any combination of them. 

My impulse to support a combination of (1) and (2), because:
- allowing `make_random_variable` externally matches the pattern we use for defining RVs inside of TFP, and hides the implementation details of `@interceptable`. 
- the CustomRV object is independently useful in allowing edward2 to serve as a backend for APIs that deal in Distribution objects on the frontend. E.g., the user specifies a prior distribution with a `Distribution` instance, and the API internally builds an Edward model by wrapping this distribution as a `CustomRV`.

But this is only a weak feeling. Are there other approaches? Or advantages/disadvantages of the ones I've listed?

**Comment by dustinvtran** [comment]
If I understand correctly, this is fixed as of

https://github.com/tensorflow/probability/commit/1fa060de86558ed84b40b0e93ba2111b218f7b1f#diff-883a7a8e0d1e1cc6ee8995754deb4b52
