### ISSUE TITLE
AttributeError: 'Normal' object has no attribute 'type'

### ISSUE THREAD

**Issue by LuisSaybe** [tensorflow/probability#538]
using the following versions

tensorflow==2.0.0-rc0
tensorflow_probability==0.8.0-rc0

any help appreciated, I get the below trace from this code

```python
import tensorflow as tf
import tensorflow_probability as tfp
import math

def game(action):
    if action < -4 or action > 2:
        return -1
    return math.sin(action)

def make_distribution_fn(t):
    return tfp.distributions.Normal(loc=t, scale=t, validate_args=True)

def convert_to_tensor_fn(s):
    return s.sample(5)

action_model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, input_dim=2),
  tfp.layers.DistributionLambda(
    make_distribution_fn=make_distribution_fn,
    convert_to_tensor_fn=convert_to_tensor_fn
  )
])

tensor = tf.constant([
  [1.0, 2.0]
], dtype='float32')

out = action_model.predict(tensor)

print(out)

```

then I get

```
2019-08-30 18:28:41.155045: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-30 18:28:41.160144: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2304000000 Hz
2019-08-30 18:28:41.160827: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3a84100 executing computations on platform Host. Devices:
2019-08-30 18:28:41.160877: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/tmp/tf-gridworld/src/index.py", line 28, in <module>
    out = action_model.predict(tensor)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 915, in predict
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 722, in predict
    callbacks=callbacks)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 565, in _make_execution_function
    return model._make_execution_function(mode)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2155, in _make_execution_function
    self._make_predict_function()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2145, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3658, in function
    return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3555, in __init__
    base_graph=source_graph)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/lift_to_graph.py", line 260, in lift_to_graph
    add_sources=add_sources))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/ops/op_selector.py", line 404, in map_subgraph
    elif op.type == "Placeholder":
AttributeError: 'Normal' object has no attribute 'type'
```

full repo and code here: `https://github.com/LuisSaybe/tf-gridworld/blob/master/src/index.py`

**Comment by zhulingchen** [comment]
You cannot use `model.predict(x_test)` to do the prediction when your output is a `tfp.distributions` Distribution. You have to use in the form of `model(x_test)`, i.e., `action_model(tensor)` for your case.

Meanwhile, another important difference is that `model.predict(x_test)` does the inference batch-by-batch while `model(x_test)` does not, so the latter one would exhaust your GPU RAM quickly. Try to implement your own batch-by-batch inference with `model(x_test)`.

See https://github.com/tensorflow/tensorflow/issues/31695#issuecomment-522640232

**Comment by LuisSaybe** [comment]
@zhulingchen 

There are some things that are different in my code than what you described.

- "You cannot use model.predict(x_test) to do the prediction when your output is a tfp.distributions Distribution"
The output of my model is not a `tfd.Distribution`, see the usage of `convert_to_tensor_fn`

- "and must with your TensorFlow eager execution enabled"
I'm using tensorflow 2, eager execution is enabled by default.

**Comment by beasteers** [comment]
@zhulingchen It seems like this would be a bug, right? 

Ideally, model.predict would return a distribution object, but even if it needs to return a tensor, shouldn't it call `convert_to_tensor_fn` before outputting?

I think the expected behavior would be `model.predict` returning `Distribution.sample()` by default instead of breaking keras predict.

I feel like this shouldn't be a closed issue 😬

**Comment by nbro** [comment]
@LuisSaybe Yes, I agree with @beasteers, you should re-open this issue.

**Comment by LuisSaybe** [comment]
I do not recall how I fixed this, but as a result of doing that, I closed this issue. I will go come back to this issue soon to see what the problem is and re-open or comment with the fix

**Comment by LuisSaybe** [comment]
@nbro @beasteers 

Copy and pasted from the docs [here](https://www.tensorflow.org/probability/api_docs/python/tfp/layers/DistributionLambda)

Here is a working example but the versions have been upgraded since my original bug report, current versions before

tensorflow==2.1.0-rc0
tensorflow_probability==0.8.0

```python
import tensorflow as tf
import tensorflow_probability as tfp
import math

def game(action):
    if action < -4 or action > 2:
        return -1
    return math.sin(action)

def convert_to_tensor_fn(s):
    return s.sample(5)

action_model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, input_dim=2),
  tfp.layers.DistributionLambda(
    make_distribution_fn=lambda t: tfp.distributions.Normal(
      loc=t[..., 0], scale=tf.exp(t[..., 1])
    ),
    convert_to_tensor_fn=lambda s: s.sample(1)
  )
])

tensor = tf.constant([
  [1.0, 2.0]
], dtype='float32')

out = action_model.predict(tensor)

print(out)

```

**Comment by nbro** [comment]
@LuisSaybe Your just provided example gives the same original error with TensorFlow 2.0. Can you explain a little bit how this exactly is different from your original one?

**Comment by LuisSaybe** [comment]
@nbro 

`Your just provided example gives the same original error with TensorFlow 2.0.`

The example I provided should works with

```
tensorflow==2.1.0-rc0
tensorflow_probability==0.8.0
```

`Furthermore, can you explain a little bit how this exactly is different from your original example?`

The example is a copy and paste form the [tensorflow-probability docs](https://www.tensorflow.org/probability/api_docs/python/tfp/layers/DistributionLambda), not directly related to my original code.

My original code (including some unrelated bug fixes), works now, you can run this code which works with the aforementioned versions of tensorflow and tensorflow_probability. I only changed adding a absolute value layer before the `DistributionLambda` layer and removed the `convert_to_tensor_fn` argument.

```python
import tensorflow as tf
import tensorflow_probability as tfp
import math

def game(action):
    return math.sin(action)

def make_distribution_fn(t):
    return tfp.distributions.Normal(loc=t, scale=t, validate_args=True)

action_model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, input_dim=2),
  tf.keras.layers.Lambda(tf.abs),
  tfp.layers.DistributionLambda(
    make_distribution_fn=make_distribution_fn
  )
])

tensor = tf.constant([
  [1.0, 2.0]
], dtype='float32')

out = action_model.predict(tensor)

print(out)
```

**Comment by nbro** [comment]
@LuisSaybe Your original code https://github.com/tensorflow/probability/issues/538#issue-487617982 (with a modification to `convert_to_tensor_fn`, i.e. `s.sample()` rather than `s.sample(5)`, otherwise, we get an output mismatch) and https://github.com/tensorflow/probability/issues/538#issuecomment-561113039 indeed work with TF 2.1 and TFP 0.9. without getting any error. I haven't tried your code with TF 2.0 and TFP 0.8 though.
