### ISSUE TITLE
MaskedAutoregressiveFlow and RealNVP using 2x unnecessary computation?

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#54]
[`tfd.TransformedDistribution`'s `log_prob`](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/distributions/transformed_distribution.py#L421) calls a `tfb.Bijector`'s `inverse` and `inverse_log_det_jacobian`. In [MAF](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/distributions/python/ops/bijectors/masked_autoregressive.py) and [RealNVP](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/distributions/python/ops/bijectors/real_nvp.py), `_inverse` and `_inverse_log_det_jacobian` duplicate calls to `_shift_and_log_scale_fn`. They could have shared this function call and therefore avoid an extra forward pass, which is the main bottleneck in these architectures.

If I'm not mistaken, this is doubly wasteful?

**Comment by jvdillon** [comment]
Common subexpression elimination will mean there's no duplication in graph mode. I suspect there would be waste in TFE, however that might be fixed once all functions are decorated with defun.

**Comment by srvasude** [comment]
I'm going to close this. When inspecting this with a graph visualizer / graph mode, you can see that the underlying NN is shared. That means the computation is done once. There is still a question of eager mode, but I would say that's a more general issue.
