### ISSUE TITLE
NUTS appears to be biased

### ISSUE THREAD

**Issue by goldingn** [tensorflow/probability#542]
Thanks for all your work with TF Probability! It's really awesome, and has made my work maintaining and extending greta so much easier - greta is increasingly just an R-ish higher-level interface to TFP.

The new NUTS sampler seems to be running fine with our set up now. However it's now tripping one of greta's tests of sampler validity. Sampling a bivariate normal seems to return biased estimates of the variance and correlation.

The test is [here](https://github.com/greta-dev/greta/blob/fd8bb770f5e94fd0948668a14286586a034e46d6/tests/testthat/helpers.R#L653-L722), and is based on the approach in [this Stan post](https://github.com/stan-dev/stan/issues/2178#issuecomment-268078910) from when the Stan default sampler was biased. The test calculates error in the parameter estimates, and divides this by the Monte Carlo standard error to remove the component of the error that's due to the Monte Carlo approximation.
 
I re-wrote the failing test in R below (sorry, my Python is not up to this task), alongside a passing test for the HMC sampler. It's mostly in R TensorFlow code, so shouldn't be too hard to translate to python. The only thing I couldn't do in TF/TFP was the estimate of Monte Carlo Standard Error.

```r
# MVN density
unnormalized_log_prob <- function (z) {
  dist <- tfp$distributions$MultivariateNormalTriL(
    loc = mu,
    scale_tril = L
  )
  dist$log_prob(z)
}

run_chain <- function (kernel) {

  tfp$mcmc$sample_chain(
    num_results = n_samples,
    current_state = z,
    kernel = kernel,
    num_burnin_steps = 1000L,
    trace_fn = function (current_state, kernel_results) {kernel_results}
  )

}

# given mcmc output, return components of the variance and correlation
# components
get_stats <- function (z) {

  # set up samples to get posterior estimates for mean, variances and correlation
  err <- z - mu
  var <- err ^ 2
  corr <- tf$reduce_prod(err, axis = 2L, keepdims = TRUE) /
    tf$reduce_prod(tf$sqrt(tf$diag_part(Sigma)))

  # return as 5-column matrix
  tf$concat(list(z, var, corr), axis = 2L)

}

summarise <- function (mcmc_output) {

  all_states <- mcmc_output$all_states

  # stats to summarise to get posterior estimates of distribution parameters
  stats <- get_stats(all_states)

  # their expectations
  expectations <- tf$reduce_mean(stats, axis = 0:1)

  # convergence diagnostics
  rhat <- tfp$mcmc$diagnostic$potential_scale_reduction(stats)
  neff <- tfp$mcmc$diagnostic$effective_sample_size(stats)

  list(
    stats = stats,
    expectations = expectations,
    rhat = rhat,
    neff = tf$reduce_sum(neff, 0L)
  )

}

# Monte Carlo standard error (using batch means) adapted form the mcmcse r
# package to work on matrices
mcse <- function(draws) {

  n <- nrow(draws)
  b <- floor(sqrt(n))
  a <- floor(n / b)

  group <- function(k) {
    idx <- ( (k - 1) * b + 1 ):(k * b)
    colMeans(draws[idx, , drop = FALSE])
  }

  bm <- vapply(seq_len(a),
               group,
               draws[1, ])

  if (is.null(dim(bm)))
    bm <- t(bm)

  mu_hat <- as.matrix(colMeans(draws))
  ss <- sweep(t(bm), 2, mu_hat, "-") ^ 2
  var_hat <- b * colSums(ss) / (a - 1)
  sqrt(var_hat / n)

}

# compute scaled error (summary must be R objects, as no TFP MCSE method)
scaled_error <- function (summary) {
  expected <- c(mu_val, diag(Sigma_val), cov2cor(Sigma_val)[1, 2])
  dim(summary$stats) <- c(n_chains * n_samples, 5)
  abs(summary$expectations - expected) / mcse(summary$stats)
}

library(tensorflow)
library(tfprobability)

# set up kernels
hmc <- tfp$mcmc$HamiltonianMonteCarlo(
  target_log_prob_fn = unnormalized_log_prob,
  num_leapfrog_steps = 3L,
  step_size = 1
)

nuts <- tfp$mcmc$NoUTurnSampler(
  target_log_prob_fn = unnormalized_log_prob,
  max_tree_depth = 6L,
  step_size = 1
)

# random MVN mean and covariance
set.seed(1)
mu_val <- rnorm(2, 0, 5)
Sigma_val <- rWishart(1, 3, diag(2))[, , 1]
mu <- tf$constant(mu_val, dtype = tf$float64)
Sigma <- tf$constant(Sigma_val, dtype = tf$float64)
L <- tf$linalg$cholesky(Sigma)

# do MCMC
n_chains <- 16L
n_samples <- 2000L
z <- tf$random_normal(shape(n_chains, 2), dtype = tf$float64)

hmc_output <- run_chain(hmc)
nuts_output <- run_chain(nuts)

# compute stats and convert to R objects
sess <- tf$compat$v1$Session()
hmc_summary <- sess$run(summarise(hmc_output))
nuts_summary <- sess$run(summarise(nuts_output))

hmc_summary[c("rhat", "neff")]
```
> ```
> $rhat
> [1] 1.002495 1.003442 1.002971 1.004497 1.004640
> 
> $neff
> [1] 4172.441 3648.792 4745.325 4319.222 4544.814
> ``` 
```r
nuts_summary[c("rhat", "neff")]
```
> ```
> $rhat
> [1] 1.006676 1.010129 1.004479 1.006589 1.006095
> 
> $neff
> [1] 3655.192 2573.992 6677.299 3734.599 4431.260
> ``` 
```r
# get the error in estimates of the means, variances, and correlation, scaled in
# terms of the number of Monte Carlo standard errors
hmc_rel_error <- scaled_error(hmc_summary)
nuts_rel_error <- scaled_error(nuts_summary)

# compute the probability of seeing an error this extreme
1 - pnorm(hmc_rel_error)
```
> ```
> [1] 0.3031953 0.0903269 0.3377994 0.2780941 0.4651906
> ```
```r
1 - pnorm(nuts_rel_error)
```
> ```
> [1] 0.3549072141 0.2223409725 0.0018964110 0.0001103708 0.0002332163
> ```

If my code is correct (and it may well not be), the probability of seeing an error this big (or bigger) in the NUTS variance and correlation estimates just due to Monte Carlo sampling error is very low. I use 0.01 as the threshold in the greta test.

**Comment by junpenglao** [comment]
Thanks for reporting! I will take a look.

**Comment by junpenglao** [comment]
Thanks again for the report, I can confirm the bug. The problem seems to be that the generalized U-turn is biased, as it is fine using the original u turn criteria. I am working on a PR to reverse back to the u turn criteria check as in the original paper, and a follow up cl to fix the bug in generalized U-turn.

**Comment by goldingn** [comment]
Awesome, thanks for fixing this so quickly!
