### ISSUE TITLE
Deep copy of bijectors

### ISSUE THREAD

**Issue by awav** [tensorflow/probability#547]
Hello all,

I found that `deepcopy` doesn't work on bijector classes. Actually, I was surprised that deepcopy *just* works in TF2.0 out of the box for variables and tensors, but this is a different story.

Here is a MWE:

```python
import tensorflow_probability as tfp
import tensorflow as tf
from copy import deepcopy

class A(tf.Module):
    def __init__(self):
        super().__init__()
        self.bijector = tfp.bijectors.Softplus()


a = A()
deepcopy(a)

x = tf.convert_to_tensor(-1.0)
y = a.bijector.forward(x)

try:
    deepcopy(a)
except:
    print(f'bijector._from_x is NOT empty: {a.bijector._from_x}')
```

After the first call, the `deepcopy` works fine, but once you do *forward* or *inverse* the `deepcopy` throws an error "_TypeError: can't pickle HashableWeakRef objects_".

The bijector class is adjusted to TF1.0, where tensors are not actual results of operations, but a computation nodes in the graph. The bijector class has the cache dictionary inside where a key is a tensor or a numpy object and a value is a result of the `forward` or `inverse` operations. Such a simple solution helps against graph over-growing, in other words it is a computation graph optimization technique. The key of the cache have `tensorflow_probability.python.bijectors.bijector.HashableWeakRef` type , which inherits from the `weakref`, which in turn is not compatible with `deepcopy`.

In TF2.0 this cache related code is redundant. **Moreover, it is a potential leak for TF2.0 case.** Whenever we compute *forward* or *inverse*, the bijector saves the input tensor and the result in the cache. Check example below:

```python
# ... continue from previous MWE
[a.bijector.forward(tf.random.normal((1,))) for _ in range(100)]
assert a.bijector._from_x >= 100
```

My opinion that this code should be just removed. There is no benefit from having it in TF2.0. It may stay because of backward compatibility, but in that case, the issue with `deepcopy` should be fixed and cache shouldn't grow linearly with number of calls to *forward* and *inverse*.

Thanks

**Comment by brianwa84** [comment]
The references in there are weak, so there *shouldn't* be a memory leak even in 2.0/eager land.
I agree it'd be nice if deepcopy would work, feel free to send a PR that just skips the _from_x/_from_y fields (create new ones for the copy).

**Comment by emilyfertig** [comment]
Closing since `deepcopy` now works for bijectors, following global caching changes.
