### ISSUE TITLE
SimpleStepSizeAdaptation target_accept_prob dtype issue

### ISSUE THREAD

**Issue by lionfish0** [tensorflow/probability#550]
Hello,
I'm not sure why this became an issue in the example code below, and not, say in the code provided [here](https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/SimpleStepSizeAdaptation). So it's probably a bug or mistake I'm making, but would be interested to know what I've done wrong [I'm new to coding in TF1&2 and TFP]. I've solved the 'bug' so this is purely for information, as I'm not really sure why it broke in the first place.

A minimal reproducible example: sampling from a GP prior using MCMC to sample observations (clearly this can be done quickly analytically, but it's just an example).
```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
psd_kernels = tfp.positive_semidefinite_kernels
f = lambda x: 3*np.sin(0.6*x[..., 0]) * np.exp(-0.04*x[..., 0]**2)
observation_index_points = np.sort(np.random.uniform(-1., 1., 200))[..., np.newaxis].astype(np.float64)
observations = np.random.normal(f(observation_index_points), .005).astype(np.float64)

def joint_log_prob(index_points, predictions):   
    gp_predictions = tfd.GaussianProcess(
        kernel=psd_kernels.ExponentiatedQuadratic(
            np.float64(10.0),np.float64(2.5)),index_points=index_points, observation_noise_variance=np.float64(0.001))
    logprob = gp_predictions.log_prob(predictions)
    return logprob

parallel = 10
init_preds = tf.zeros([parallel,200],dtype=tf.float64)
initial_chain_states = [
    init_preds,
]

def unnormalized_log_posterior(preds):
  return joint_log_prob(observation_index_points, preds)

num_results = 100
num_burnin_steps = 100
kernel = tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn=unnormalized_log_posterior,
            step_size=np.float64(0.01),
            num_leapfrog_steps=2)
kernel = tfp.mcmc.SimpleStepSizeAdaptation(inner_kernel=kernel, num_adaptation_steps=int(num_burnin_steps * 0.8), target_accept_prob=np.float64(0.75))

preds, kernel_results = tfp.mcmc.sample_chain(
    num_results=num_results,
    num_burnin_steps=num_burnin_steps,
    current_state=initial_chain_states,
    kernel=kernel)

print("Acceptance rate: {}".format(
  np.mean(kernel_results.inner_results.is_accepted)))
```
The above code works. But if you remove the  `target_accept_prob=np.float64(0.75))` parameter, then the `SimpleStepSizeAdaptation` constructor uses a `float32` instead, which later breaks with an:
`InvalidArgumentError: cannot compute Greater as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Greater]`

Most useful stack trace step:
```
~/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/simple_step_size_adaptation.py in one_step(self, current_state, previous_kernel_results)
    386 
    387         new_step_size_part = mcmc_util.choose(
--> 388             reduced_log_accept_prob > log_target_accept_prob,
```

In the constructor there's this code in [python/mcmc/simple_step_size_adaptation.py](https://github.com/tensorflow/probability/blob/0ff138fc7f0e3bfeb4bf9014452cbc8b7f592629/tensorflow_probability/python/mcmc/simple_step_size_adaptation.py#L263)] 
```
    with tf.compat.v1.name_scope(
        mcmc_util.make_name(name, 'simple_step_size_adaptation', '__init__'),
        values=[target_accept_prob, adaptation_rate,
                num_adaptation_steps]) as name:
      dtype = dtype_util.common_dtype([target_accept_prob, adaptation_rate],
                                      tf.float32)
```
The float32 seems to be maybe the issue? [Maybe the 'v1' is a bit of an issue too?? should I even be using this code?? Also my codebase is a week or two from the latest, so maybe should update].

So I don't know if this is a bug, or how I should avoid it properly in future.
Thanks for any advice.

**Comment by junpenglao** [comment]
sounds similar to https://github.com/tensorflow/probability/issues/543

**Comment by lionfish0** [comment]
Ah, yes, it does. Sorry didn't spot that issue (searched only last week!).

**Comment by junpenglao** [comment]
No worries! And thanks for reporting ;-) 
cc @csuter

**Comment by srvasude** [comment]
Closing this, because I believe the underlying issue is resolved. Feel free to reopen if this issue still persists.
