### ISSUE TITLE
tfp.bijectors.MatvecLU's log determinant is correct?

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/probability#554]
tensorflow-probability==0.8.0rc0
tensorflow==2.0.0rc0

in matveclu.py

```python
  def _forward_log_det_jacobian(self, unused_x):
        return tf.reduce_sum(tf.math.log(
            tf.abs(tf.linalg.diag_part(self.lower_upper))),
                             axis=-1)
```

in [the paper](https://arxiv.org/pdf/1807.03039.pdf), conv1x1's determinat is here.
``h x w x log(det|W|)``

example code
```python
def trainable_lu_factorization(event_size,
                               batch_shape=(),
                               seed=None,
                               dtype=tf.float32,
                               name=None):
    with tf.name_scope('trainable_lu_factorization'):
        event_size = tf.convert_to_tensor(event_size,
                                          dtype=tf.int32,
                                          name='event_size')
        batch_shape = tf.convert_to_tensor(batch_shape,
                                           dtype=event_size.dtype,
                                           name='batch_shape')
        random_matrix = tf.Variable(tf.random.uniform(
            shape=tf.concat([batch_shape, [event_size, event_size]], axis=0),
            dtype=dtype,
            seed=seed,
        ),
                                    name='conv1x1_weights')

        def lu_p(m):
            return tf.linalg.lu(tf.linalg.qr(m).q)

        # lower_upper = tfp.util.DeferredTensor(lambda m: lu_p(m)[0],
        #                                       random_matrix)
        # permutation = tfp.util.DeferredTensor(lambda m: lu_p(m)[1],
        #                                       random_matrix,
        #                                       # trainable=False,
        #                                       dtype=tf.int32,
        #                                       shape=random_matrix.shape[:-1])
        lower_upper = tf.Variable(lu_p(random_matrix)[0])
        # ref https://github.com/tensorflow/probability/issues/545
        permutation = tf.Variable(lu_p(random_matrix)[1], trainable=False)
        return lower_upper, permutation


t_lower_upper, t_permutation = trainable_lu_factorization(3)
conv1x1 = tfb.MatvecLU(t_lower_upper, t_permutation, name='MatvecLU')
lower_upper.shape # => 3 x 3
```

where is ``h x w`` ?

**Comment by SiegeLordEx** [comment]
It's right here: https://github.com/tensorflow/probability/blob/882291654ac7b5480753462f96d322802d03886f/tensorflow_probability/python/bijectors/bijector.py#L1354-L1356 :)

TFP bijectors support being applied to distributions whose event dimensions exceed the natural dimension of the bijector. E.g. you can apply a scalar scaling to a 0D, 1D, 2D etc distribution. This is easy enough for the forward/inverse transformations, we just use broadcasting. For the log-det jacobian, we sum out the excess dimensions.

So, for this bijector, it's designed to work with 1D and larger dimensional distributions. E.g. 1D event is just your regular vector distribution, like you could use in a VAE. 2D event might be useful for raw-waveform audio modeling. And 3D is obviously used for images. In case of 3D, the events have shape `[h, w, c]`, where `c` is the number of channels, so the extra two dimensions `h` and `w` get summed-out, resulting in the `h * w` factor when you compute the log-det jacobian.

**Comment by MokkeMeguru** [comment]
Thanks, but I think, however, the attribute seems a little dangerous. 

If it's not my mistake, Affine Coupling layer's log-determinant is simply, ``sum(log(|s|))`` (s means a neural network's output ref. [paper](https://arxiv.org/pdf/1807.03039.pdf) Table 1)

![image](https://user-images.githubusercontent.com/30849444/64586623-cb139b80-d3d7-11e9-868f-ae4d311bd940.png)

Is there a possibility of accidentally multiply ``h * w`` ?

**Comment by SiegeLordEx** [comment]
I don't think there's a possibility of a mistake unless you call the bijector's `forward/reverse_log_det_jacobian` manually and pass in the wrong number of the `event_ndims` argument. If you use TFP's `TransformedDistribution` that'll get set correctly automatically.

For that table entry, recall that there isn't an explicit `h * w` factor in TFP, we just have a sum just like they do in the table: if the coupling doesn't vary by position (like it doesn't for 1x1 convolution), it's exactly `h * w` times the log-det jacobian per-position; if the coupling does vary by posiiton, like it does for the affine coupling, then you won't be able to extract the `h * w` term, but the overall sum expression remains the same. They could also have written the log-determinants for actnorm and the invertible 1x1 convolution without the `h * w` factor, and just left that implicit in the `sum`.

**Comment by MokkeMeguru** [comment]
Thank you for the advice!
I read the source code of bijector and bijectors.chain, and I confirmed that it seems to work properly.

(Now I am implementing Glow.)
If this doesn't work, open this issue again.

**Comment by SiegeLordEx** [comment]
Nice! I'm excited to see what you come up with. I recently implemented Glow in TFP as well (it's not yet public); I can show it to you if you're interested, but I'm also curious what you'll come up without me biasing you one way or another :).

**Comment by MokkeMeguru** [comment]
I'm trying to implement this week (from a week ago). 
If you can't, you may rely on you.

Thanks!

**Comment by MokkeMeguru** [comment]
Thank you for the other day!
Thanks to you, my repository is probably complete!

RealNVP+MNIST https://github.com/MokkeMeguru/glow-realnvp-tutorial/blob/master/tips/RealNVP_mnist_en.ipynb

Glow+MNIST https://github.com/MokkeMeguru/glow-realnvp-tutorial/blob/master/tips/glow_mnist_en.ipynb

Please let me know if there are any problems in implementation. I welcome it.

**Comment by SiegeLordEx** [comment]
That implementation is great! I only gave it a short look-over, but from what I've seen it's similar to what I've done: I've also heavily used Blockwise for the multiscale architecture. The key difference is that you used nesting to implement it, while I opted to avoid it. Here was my architecture:

![glow](https://user-images.githubusercontent.com/43966695/64983129-a5bddc00-d874-11e9-9d6a-9f4f31ae031c.png)

The reason it's still valid is because the squeeze operation preserves the relative ordering of the channels, so I can avoid transforming an ever-decreasing fraction of the channels as I go down the multi-scale hierarchy. I don't necessarily think one way is more efficient than the other (I have fewer reshapes, but that's about it), although I think it's a little easier to extract the un-transformed values that correspond to different scales (e.g. I can extract the most general values by doing z[..., :16] on the [4, 4, 64] vector) in my version.

Other than that, I also believe you shouldn't need a custom Blockwise3D or RealNVP; the ones in TFP have been sufficient for me. The reason why is basically the same argument that I made for MatVecLU: even though both tfb.Blockwise and tfb.RealNVP are nominally defined on vectors, they still work on 3D event shapes fine if all you're interested is transforming along the final dimension.

If you ever feel like it, TFP could definitely use the Squeeze and ActNorm bijectors. I don't fully understand how you've implemented yours (I don't see where you update the scales/shifts post-initialization), but I'm sure we can work through that.

**Comment by brianwa84** [comment]
I had similar thoughts looking at this, esp around RealNVP. Also,
tf.datasets might eliminate some of the code around importing & munging
mnist.

On the whole, this is quite nice. I wonder if we could put it in the
jupyter_notebooks directory in TFP?

Brian Patton | Software Engineer | bjp@google.com

**Comment by MokkeMeguru** [comment]
@SiegeLordEx 
Thanks! 
1. Of course, I was thinking of using some of the TFP functions/classes. However, Blockwise and RealNVP were not used because I need to manipulate the dimensions 3D->vector. I want to the implementation of RealNVP(AffineCoupling)   to the original implementation (In other words I wanted to work in 3D).

2. Multi-Scale Architecture has one of the motivations which want to do efficient variable transformations, I think. So I thought it might be necessary to reduce the number of dimensions going through Flow-Step.

ref. https://arxiv.org/pdf/1605.08803.pdf 3.6 Multi-scale Architecture.

3. ActNorm is initialized by the first batch you inputs. When you input the first batch, Actnorm is called the function setStat. And in the following batch, it attributes default trainable parameter. 

see. https://colab.research.google.com/gist/MokkeMeguru/a1d67a5b0655a5bb962a2bd0de971e4f/untitled0.ipynb

**Comment by MokkeMeguru** [comment]
@brianwa84 
Willing to do it.
I will rewrite it so that it can be transferred to your https://github.com/tensorflow/probability/tree/master/tensorflow_probability/examples.

I have a few questions.

1. should I remove some statements need "checkpoints folder"?    
   To see the progress during learning, I'd used tensorboard. So my code needs "checkpoints folder".
  Should I "remove" these statements, or "comment out" them?

2. I am not very familiar with Git.
    Is the following process correct Pull Request?
    1. git clone [tensorflow probability]
    2. checkout new branch, such as 'add-example-glow-realnvp'
    3. add my code into example's folder
    4. commit to remote
    5. pull request via Github
