### ISSUE TITLE
Can someone explain the usage of ed2.make_log_joint_fn?

### ISSUE THREAD

**Issue by Char-Aznable** [tensorflow/probability#558]
Hi all, I am new to tf.probability and edward2. I am going through the Probabilistic_PCA.ipynb tutorial and I have trouble understanding the usage of make_log_joint_fn() in edward2. For reference, I copy and paste the relevant code here:
```python
def probabilistic_pca(data_dim, latent_dim, num_datapoints, stddv_datapoints): # (unmodeled) data
  w = ed.Normal(loc=tf.zeros([data_dim, latent_dim]),
                scale=2.0 * tf.ones([data_dim, latent_dim]),
                name="w")  # parameter
  z = ed.Normal(loc=tf.zeros([latent_dim, num_datapoints]),
                scale=tf.ones([latent_dim, num_datapoints]), 
                name="z")  # parameter
  x = ed.Normal(loc=tf.matmul(w, z),
                scale=stddv_datapoints * tf.ones([data_dim, num_datapoints]),
                name="x")  # (modeled) data
  return x, (w, z)

log_joint = ed.make_log_joint_fn(probabilistic_pca)

...

w = tf.Variable(np.ones([data_dim, latent_dim]), dtype=tf.float32)
z = tf.Variable(np.ones([latent_dim, num_datapoints]), dtype=tf.float32)

def target(w, z):
  """Unnormalized target density as a function of the parameters."""
  return log_joint(data_dim=data_dim,
                   latent_dim=latent_dim,
                   num_datapoints=num_datapoints,
                   stddv_datapoints=stddv_datapoints,
                   w=w, z=z, x=x_train)
energy = -target(w, z)
optimizer = tf.train.AdamOptimizer(learning_rate=0.05)
train = optimizer.minimize(energy)
```
Here are my questions:
1) What exactly is the return type of make_log_joint_fn()? The documentation says it's `A log-joint probability function.` but in the tutorial Probabilistic_PCA.ipynb it's a tuple of ed2.RandomVariable. In particular, what is the meaning of the parenthesis in `return x, (w, z)` from `probabilistic_pca()` in the above code?
2) What is the difference between the `ed.Normal` type of `w` and `z` in the data generation part of the code and those defined later as `tf.Variable`? If `ed.Normal` and `tf.Variable` serve different purpose, is there some reason that they have the same name?
3) In the `log_joint()` call in the `target()` function, x was never defined as placeholder -- was this done implicitly somewhere? Also, I thought input parameters such as `data_dim` and `latent_dim` to `probabilistic_pca()` are already wrapped into the definition of the random variables `w` and `z` -- why do they have to be provided again later in the `log_joint()` call in `target()`?

I appreciate it if you can at least point me to the right direction. I tried going through the edward2 arxiv paper but it only gets more confusing... Thanks in advance!

**Comment by davmre** [comment]
The return value of `make_log_joint_fn` is a Python callable -- `log_joint` in the code. This callable takes all of the same arguments as the model callable (`data_dim`, `latent_dim`, etc) as well as a keyword argument for each variable in the model.

You can ignore the return value of the `probabilistic_pca` model callable (`x, (w, z)`). It's written that way so that you can draw a sample from the model prior by just calling `x, (w, z) = probabilistic_pca(...)`, but it's not used in this example. 

Re the multiple definitions of model variables, the `w`, `z`, `x` values defined inside of `probabilistic_pca()` are random variable objects -- you can think of them as symbolically describing the probabilistic model. By default they'll be instantiated as samples from the model prior, but we can override their values by passing arguments to `log_joint`. Note that Edward2 `RandomVariable`s are very different from `tf.Variable`s -- an E2 RV encodes a probability distribution with an attached value, while a TF Variable defines mutable state. To optimize `w` and `z`, we create mutable representations of their values using `tf.Variable`s; passing those to `log_joint` evaluates the likelihood at those values. It's not important that the Variables and RVs have the same names -- we could have used `w_optimized_value` or similar as the name of the Variable, and then passed `log_joint(w=w_optimized_value, ...)` to compute the target loss.

**Comment by Char-Aznable** [comment]
@davmre Thanks for the explanation! That makes more sense now. Just one more thing, is whatever E2 RVs not assigned a `tf.Variable` in the `log_joint()` call assume a placeholder position? For example, if we have instead
```python
w = tf.Variable(np.ones([data_dim, latent_dim]), dtype=tf.float32)
# define z_train here
z_train = sess.run(...)
def target(w):
  """Unnormalized target density as a function of the parameters."""
  return log_joint(data_dim=data_dim,
                   latent_dim=latent_dim,
                   num_datapoints=num_datapoints,
                   stddv_datapoints=stddv_datapoints,
                   w=w, z=z_train, x=x_train)
```
this would optimize `p(w | z, x)` instead?

**Comment by davmre** [comment]
Yes -- the log joint is evaluated at the values you pass in, so if you pass in a fixed value for some RV, it'll set the RV to that fixed value.

**Comment by Char-Aznable** [comment]
@davmre Can you also help with my questions regarding the variational inference part of the same tutorial:
```python
tf.reset_default_graph()

def variational_model(qw_mean, qw_stddv, qz_mean, qz_stddv):
  qw = ed.Normal(loc=qw_mean, scale=qw_stddv, name="qw")
  qz = ed.Normal(loc=qz_mean, scale=qz_stddv, name="qz")
  return qw, qz


log_q = ed.make_log_joint_fn(variational_model)

def target_q(qw, qz):
  return log_q(qw_mean=qw_mean, qw_stddv=qw_stddv,
               qz_mean=qz_mean, qz_stddv=qz_stddv,
               qw=qw, qz=qz)


qw_mean = tf.Variable(np.ones([data_dim, latent_dim]), dtype=tf.float32)
qz_mean = tf.Variable(np.ones([latent_dim, num_datapoints]), dtype=tf.float32)
qw_stddv = tf.nn.softplus(tf.Variable(-4 * np.ones([data_dim, latent_dim]), dtype=tf.float32))
qz_stddv = tf.nn.softplus(tf.Variable(-4 * np.ones([latent_dim, num_datapoints]), dtype=tf.float32))

qw, qz = variational_model(qw_mean=qw_mean, qw_stddv=qw_stddv,
                           qz_mean=qz_mean, qz_stddv=qz_stddv)

energy = target(qw, qz)
entropy = -target_q(qw, qz)

elbo = energy + entropy
```
During the ELBO optimization, Is there a way to control the batch size of sampling from `z ~ q(z)` and `w ~ q(w)`? It seems how the tutorial was written assumes only one sample was drawn for each iteration? 

Thanks a lot!

**Comment by davmre** [comment]
Yup, drawing multiple samples from E2 models is a nontrivial problem in general -- since a model function can contain arbitrary code, drawing a vector of samples requires the ability to vectorize arbitrary TF/Python functions. The best solution now (which didn't exist when this tutorial was written) is to sample from the variational model by calling it using `tf.vectorized_map`, and then pass those samples to the log joint fn by also calling it using `tf.vectorized_map`. For example, I think this should work:

```python
num_samples = 10
qw, qz = tf.vectorized_map(
  lambda i: variational_model(
    qw_mean=qw_mean, qw_stddv=qw_stddv,
    qz_mean=qz_mean, qz_stddv=qz_stddv),
  np.arange(num_samples))
energy = tf.vectorized_map(target, qw, qz)
entropy = -tf.vectorized_map(target_q, qw, qz)

elbo = tf.reduce_sum(energy + entropy, axis=0)
```

**Comment by Char-Aznable** [comment]
@davmre I think I get the idea even though the code 
```python
qw, qz = tf.vectorized_map(
  lambda i: variational_model(
    qw_mean=qw_mean, qw_stddv=qw_stddv,
    qz_mean=qz_mean, qz_stddv=qz_stddv),
  np.arange(num_samples))
```
gives the error:
```python
AssertionError                            Traceback (most recent call last)                        
<ipython-input-10-67cfc8f9731c> in <module>                                                        
      4     qw_mean=qw_mean, qw_stddv=qw_stddv,                                                    
      5     qz_mean=qz_mean, qz_stddv=qz_stddv),                                                   
----> 6   np.arange(num_samples))                                                     
                                                                                                   
~/.linuxbrew/opt/python/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow
_ops.py in vectorized_map(fn, elems)                                                               
    336     return fn(gathered_elems)                                                              
    337   batch_size = array_ops.shape(nest.flatten(elems)[0])[0]                                  
--> 338   return pfor(loop_fn, batch_size)                                                         
                                                                                                   
~/.linuxbrew/opt/python/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow
_ops.py in pfor(loop_fn, iters, parallel_iterations)                                               
    162   if context.executing_eagerly():                                                          
    163     f = function.defun(f)                                                                  
--> 164   return f()                                                                               
    165
    166

~/.linuxbrew/opt/python/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py in f()
    159   """
    160   def f():
--> 161     return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
    162   if context.executing_eagerly():
    163     f = function.defun(f)

~/.linuxbrew/opt/python/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py in _pfor_impl(loop_fn, iters, parallel_iterations, pfor_config)                           
    212       outputs = []
    213       for loop_fn_output in nest.flatten(loop_fn_outputs):                                
--> 214         outputs.append(converter.convert(loop_fn_output))                                 
    215       return nest.pack_sequence_as(loop_fn_outputs, outputs)                              
    216   else:

~/.linuxbrew/opt/python/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/pfor.py in convert(self, y)
   1173     if isinstance(y, sparse_tensor.SparseTensor):                                         
   1174       return self._convert_sparse(y)
-> 1175     output = self._convert_helper(y)
   1176     if isinstance(output, WrappedTensor):
   1177       assert isinstance(y, ops.Tensor)

~/.linuxbrew/opt/python/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/pfor.py in _convert_helper(self, op_or_tensor)
   1206         y_op = y
   1207       else:
-> 1208         assert isinstance(y, ops.Tensor), y                                               
   1209         y_op = y.op
   1210

AssertionError: RandomVariable("loop_body_7/qw/", shape=(2, 1), dtype=float32)
```
Maybe we need to vectorize inside the `variational_model()`?

**Comment by davmre** [comment]
Oh right, `vectorized_map` works on functions that take/return `Tensor`s, so it might choke on functions that return E2 `RandomVariable`s.  This is probably fixable at a higher level, but as an immediate workaround, you can get around this by modifying `variational_model` to return explicit `Tensor`s, e.g., `return  qw.value, qz.value`.

**Comment by Char-Aznable** [comment]
@davmre I see. Also, `fn` in `vectorized_map` only takes a single argument. To summarize, I manage to get the following to work with drawing multiple samples in VI although it gives a warning (see below).
```python
def sampleFromVariationalModel(qw_mean, qw_stddv, qz_mean, qz_stddv):
    qw, qz = variational_model(qw_mean, qw_stddv, qz_mean, qz_stddv)
    return qw.value, qz.value

def targetOnTuple(qwqz):
    return target(qwqz[0], qwqz[1])

def targetQOnTuple(qwqz):
    return target_q(qwqz[0], qwqz[1])

num_samples = 10
qw, qz = tf.vectorized_map(
  lambda i: sampleFromVariationalModel(
    qw_mean=qw_mean, qw_stddv=qw_stddv,
    qz_mean=qz_mean, qz_stddv=qz_stddv),
  np.arange(num_samples))
energy = tf.vectorized_map(targetOnTuple, (qw, qz))
entropy = -tf.vectorized_map(targetQOnTuple, (qw, qz))
elbo = tf.reduce_sum(energy + entropy, axis=0)

```
with the warning:
```
W0916 16:15:13.050199 47798449800640 pfor.py:2408] Note that RandomStandardNormal inside pfor op ma
y not give same output as inside a sequential loop.                                                
W0916 16:15:13.101383 47798449800640 pfor.py:2408] Note that RandomStandardNormal inside pfor op ma
y not give same output as inside a sequential loop.
```
Are these warnings benign?

**Comment by davmre** [comment]
Yup. They're just saying that you (probably) won't get literally-identical
random samples from calling the variational model under `vectorized_map` as
you would have by manually calling it multiple times and stacking the
resulting samples (assuming the same random seed in both cases). But both
methods will draw independent samples from the same distribution, so
there's no difference for statistical purposes.

**Comment by Char-Aznable** [comment]
Great! Thank you again for the help! I'm closing this thread.

**Comment by dionman** [comment]
Hi! Can we simply do inference on `w` or should `z` be included in VI schemes for PPCA?
