### ISSUE TITLE
Error when adding a call to positive_semidefinite_kernels matrix in a tf.while loop

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/probability#563]
Using tensorflow-nightly-2.0 and tfp-nightly, if I attempt to add a call to a positive semidefinite kernel matrix inside the body of a tf.while_loop in graph mode, I get the following error (it works fine in eager execution).

Traceback (most recent call last):
  File "...\tensorflow_nightly\lib\site-packages\tensorflow_core\python\framework\ops.py", line 2370, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'sequential/learn_flow_layer_scaled/MaternOneHalf/IdentityN' has no attr named '_XlaCompile'.

....

ValueError: Attempting to capture tensor Tensor(".../MaternOneHalf/Sum:0", shape=(896, 100), dtype=float64) which is not in the forward graph but in sequential_learn_flow_layer_scaled_while_body_1170.

**Comment by axch** [comment]
I can guess at a few possible causes.  Are there gradient tapes involved?  If so it may (for the time being) be useful to construct the psd kernel under the gradient tape in question.  There's some chance that the same holds of any tf.function annotations.  But really, this is just guesswork right now.  Could you add a small complete reproducing example?  Then we could investigate more reliably.

**Comment by srvasude** [comment]
Closing this issue. Feel free to reopen with a code snippet for reproduction is this is still the case.
