### ISSUE TITLE
late-binding property in VariationalGaussianProcess layer still necessary with TF2?

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#566]
Hi,

regarding this requirement for `tfd.VariationalGaussianProcess`

> Parameterized by number of inducing points and a
  `kernel_provider`, which should be a `tf.keras.Layer` with an @property that
  late-binds variable parameters to a
  `tfp.positive_semidefinite_kernel.PositiveSemidefiniteKernel` instance (this
  requirement has to do with the way that variables must be created in a keras
  model).

I was wondering if the `@property` is still required with TF 2 (and its different `Variable`-related behavior).

The reason I'm asking is that if still required, this is not easily implementable from the R wrapper to TFP.

Many thanks!

**Comment by csuter** [comment]
Hey Sigrid, I'm afraid it is still necessary to do something like what's implemented in the TF2 world. TBH I'm not crazy about how this bit of the layers API shaped up. The really essential thing here is that the relevant trainable Variables be created by something that Keras knows about, in this case a `Layer` object's `build()` method. I think any other approach that satisfies that requirement would work. I had hoped to revisit this API after we put it together early this year, but haven't found the time.

**Comment by skeydan** [comment]
Hi Chris,

thanks for answering!! Do you think it would be possible to replace that by either a "standard" subclassed `tf.keras.layers.Layer` (putting 

```
self._amplitude = self.add_weight(...
```

inside `build()` and using `tfp.positive_semidefinite_kernels.ExponentiatedQuadratic` inside `call()`), or else by a subclassed `tf.keras.Model`?

Both should work fine from R...

**Comment by skeydan** [comment]
Closing this one; we found a way to create a layer with such a `property` from R :-)

**Comment by csuter** [comment]
Oh great! Sorry I wasn't more helpful 😬Glad you got past it!
