### ISSUE TITLE
Update VAE example to use Keras layers

### ISSUE THREAD

**Issue by davmre** [tensorflow/probability#57]
Currently our VAE example 
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/vae.py
uses `tf.layers`. Keras layers are the recommended best practice going forward in TF, but will require a different set of best practices. In particular, because they don't support variable reuse via `tf.variable_scope`, we need to pass around the Keras model object explicitly.

**Comment by dustinvtran** [comment]
fixed in https://github.com/tensorflow/probability/commit/8a4ab2e49b49438b2051920f77e4306654c96743
