### ISSUE TITLE
TF2: tfp.distributions.Normal in tf.keras.Model issue

### ISSUE THREAD

**Issue by BlueFisher** [tensorflow/probability#578]
I just found that if I returned a distribution in `call` not a tensor and called `self(tf.keras.Input())` in `__init__`, it would throw an exception `'Normal' object has no attribute 'shape'`

```python
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()

        self.l = tf.keras.layers.Dense(2)
        self(tf.keras.Input(shape=(3,)))

    def call(self, inputs):
        x = self.l(inputs)

        policy = tfp.distributions.Normal(loc=x, scale=x)
        return policy


model = MyModel()
```

**Comment by davmre** [comment]
Are you familiar with the DistributionLambda layer, and the TFP
distribution layers more generally? Keras requires some extra plumbing to
handle non-Tensor return values such as Distributions:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/layers/distribution_layer.py#L101

**Comment by BlueFisher** [comment]
@davmre Thanks a lot. That's just what I need.
