### ISSUE TITLE
AutoGraph bug

### ISSUE THREAD

**Issue by Ste29** [tensorflow/probability#581]
When i try to execute [this code](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/cifar10_bnn.py) on google colab i get the following warnings:

> WARNING:tensorflow:Warning: deleting old log directory at /tmp/bayesian_neural_network/
> W1001 11:08:43.077606 140480120850304 <ipython-input-10-d88de198c1a6>:6] Warning: deleting old log directory at /tmp/bayesian_neural_network/
> x_train shape:(50000, 32, 32, 3)
> 50000 train samples
> 10000 test samples
> WARNING:tensorflow:Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67d4b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67d4b70>>: AssertionError: Bad argument number for Name: 3, expecting 4
> W1001 11:08:52.908765 140480120850304 ag_logging.py:145] Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67d4b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67d4b70>>: AssertionError: Bad argument number for Name: 3, expecting 4
> WARNING: Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67d4b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67d4b70>>: AssertionError: Bad argument number for Name: 3, expecting 4
> WARNING:tensorflow:Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67300f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67300f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
> W1001 11:08:53.131333 140480120850304 ag_logging.py:145] Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67300f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67300f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
> WARNING: Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67300f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d67300f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
> WARNING:tensorflow:Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d6548b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d6548b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
> W1001 11:08:53.359856 140480120850304 ag_logging.py:145] Entity <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d6548b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _ConvVariational.call of <tensorflow_probability.python.layers.conv_variational.Conv2DFlipout object at 0x7fc3d6548b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
> 

I didn't modify anything, i just copy pasted the code in google colab and obviously i copy pasted also the code for the resnet architecture.
The first warning was printed by the code, as it should work, but after "10000 test samples" there are some unexpected warnings. Can i ignore them or are them a problem? I'm still a noob with tensorflow

**Comment by dynamicwebpaige** [comment]
Adding @mdanatg, for the AutoGraph mention, and making a note that this example should be updated to use TensorFlow 2.0.

**Comment by mdanatg** [comment]
The warning is due to #33799. Could you try downgrading gast to 0.2.2 (`pip install gast=0.2.2.`)? Let us know if that doesn't fix it.

**Comment by Ste29** [comment]
yes, it worked, thank you
