### ISSUE TITLE
Is there any c++ inference API in tfp? 

### ISSUE THREAD

**Issue by Capri2014** [tensorflow/probability#582]
Is there any c++ inference API in tfp? 

Thanks

**Comment by brianwa84** [comment]
For c++ I'd suggest using tf.saved_model to export a tf.Module with the
relevant inference inside a tf.function method thereof. You should then be
able to use the TF serving package.

**Comment by brianwa84** [comment]
Simplest possible thing:

```python
class Model(tf.Module):
  @tf.function(input_signature=(tf.TensorSpec(dtype=tf.float32, shape=[2])
  def f(self, loc):
    return tfd.Normal(loc, 1).sample(3)

tf.saved_model.save(Model(), '/tmp/model')
```
