### ISSUE TITLE
Is there any method to get conditional distribution?

### ISSUE THREAD

**Issue by hellocybernetics** [tensorflow/probability#583]
Hi. I will start to use TensorFlow Probability instead of Pyro with PyTorch, because of new release TF2.0 and TFP0.8.0.

Therefore, I looking forward to a method to get conditional distribution from existed probabilistic model (joint distribution). For example, in pyro, below code achieve it.

```python
def model(x):
    s = pyro.param("s", torch.tensor(0.5))
    z = pyro.sample("z", dist.Normal(x, s))
    return z ** 2

conditioned_model = pyro.poutine.condition(model, data={"z": 1.0})
```

In addition, pyro has some convenient handlers for distributions.

[pyro handlers](http://docs.pyro.ai/en/stable/poutine.html)

I think this Pyro APIs is similar to edward2 APIs, but there is a few examples (edward2 is not used for TFP users?).

If you have convenient method, please let me know.

**Comment by brianwa84** [comment]
Is your downstream use-case VI or MCMC? Often those interfaces take a
target_log_prob_fn which consumes the latents. Doing this conditioning is
fairly straightforward with all three flavors of tfd.JointDistribution. I'd
suggest looking here
https://colab.sandbox.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb
(you'll
see in here something like `lambda *latents: jd.log_prob(latents +
(conditioning,))`
The variants are JointDistributionSequential, JointDistributionNamed, and
JointDistributionCoroutine. The coro one is most like ed2, IMO.
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/JointDistributionCoroutine

Brian Patton | Software Engineer | bjp@google.com

**Comment by brianwa84** [comment]
Going to close for now, feel free to reopen if you have more questions. I like the idea of some sugar for conditioning, maybe a PR for something under tfp.experimental :-)

**Comment by hellocybernetics** [comment]
Thanks to reply.

I tried to use `tfd.JointDistribution.Coroutine`, therefore please check.

https://github.com/hellocybernetics/TensorFlow2.0_Eager_Execution_Tutorials/blob/master/tutorials/04_probability/probabilistic_model_by_tfp_layers.ipynb

After writing this notebook, I have new question.
As you say, conditional distribution is represented by using joint distribution module easily, but when I got bayes prediction distribution, especially with samples from posterior by MCMC, I had lost method.

So, as above notebook, I calculate with broadcast and reduce_mean. Is there any method for this purpose in tfp modules?

**Comment by hellocybernetics** [comment]
`tfp.distributions.JointDistribution` class is suit to my purpose !

https://github.com/hellocybernetics/TensorFlow2.0_Eager_Execution_Tutorials/blob/master/tutorials/04_probability/VariationalRegression_JointDistribution.ipynb
