### ISSUE TITLE
Deprecation warnings for Seedstream in sts/fitting.py

### ISSUE THREAD

**Issue by tarrou** [tensorflow/probability#591]
In three locations `sts/fitting.py`,  `tfp_util.SeedStream` needs to be updated to ` tfp.util.SeedStream`. The former has been deprecated.

The lines are 188, 343, and 566.

(I would love to do this myself, but I'm not sure how. Do I fork it, clone it, change it and then make a PR? Thanks.)

**Comment by brianwa84** [comment]
Yes, you can change it the normal git way, with a PR.

**Comment by tarrou** [comment]
Well, I tried with [PR 595](https://github.com/tensorflow/probability/pull/595), but it doesn't pass a check, and I have no idea why. Anyone else want to take a whack?

**Comment by axch** [comment]
So, I don't think `fitting.py` is actually importing `SeedStream` from the wrong place.  I just fixed a few other references (notably, sts/local_level.py) in https://github.com/tensorflow/probability/commit/7b2b2b831f8ea14d80af4b64b72f758433898bbf, but I'm not sure I got all of them.  Do you still see the warning if you update past that?

**Comment by tarrou** [comment]
I don't, but I'm not putting everything in, so I'm not sure.  Thanks!

**Comment by srvasude** [comment]
I believe this should be cleaned up everywhere. Closing this.
