### ISSUE TITLE
Sampling from a JointDistributionSequential produces unexpected shapes 

### ISSUE THREAD

**Issue by jefio** [tensorflow/probability#594]
- tensorflow                2.0.0
- tensorflow-probability    0.8.0

Let's define a joint distribution over 2 variables, each with an event shape equal to 2:

```python
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

jd = tfd.JointDistributionSequential([
    tfd.Independent(
        tfd.Normal(loc=tf.zeros([2]), scale=tf.ones([2])),
        1),
    lambda x: tfd.Independent(
        tfd.Normal(loc=x[0], scale=tf.ones([2])),
        1)
])
data = jd.sample(10)
print([x.shape for x in data]) 
```
Here I was expecting the output to be (10, 2), (10, 2). But I got this instead:

```python

[TensorShape([10, 2]), TensorShape([2])]
```

Is this the expected behavior of `sample`?

**Comment by brianwa84** [comment]
Or x[...,0]

**Comment by jefio** [comment]
Hi,

> In the second distribution you have `loc=x[0]`, I think it should be `loc=x` instead.

I did mean `loc=x[0]` in the second distribution. More generally I meant any mapping of x to a real number(`loc=x[0]`, `loc=tf.reduce_sum(x)`, etc). My point is that the second distribution event shape is 2 because of broadcasting, which is why I expected `jd.sample(10)` to return tensors with shapes `[TensorShape([10, 2]), TensorShape([10, 2])]`.

> Or x[...,0]

`loc=x[...,0]` causes an error:

```ValueError: Arguments `loc` and `scale` must have compatible shapes; loc.shape=(10,), scale.shape=(2,).```

**Comment by junpenglao** [comment]
I see what you mean, in the current implementation, JointDistribution* treats downstream variables that contains dependence a little be different to make sure broadcasting works for most case (most use case being that if you have something like y ~ Normal(X*beta, sigma), and you have beta and sigma being from `some_dist.sample(10)`, you want y to be shape (10) instead of (10, 10)).

However, there is an internal flag in JointDistribution you could overwrite to get the behavior you are expecting:
```
# after initialized your JointDistribution
jd = ...
jd._always_use_specified_sample_shape = True
```

**Comment by brianwa84** [comment]
Alternative: x[..., :1]

**Comment by brianwa84** [comment]
JointDistCoroutine lets you explicitly specify which distributions are
sampling roots.

**Comment by junpenglao** [comment]
Nice! I didnt know that you can use root to do that. 
For completeness:
```python
Root = tfd.JointDistributionCoroutine.Root  # Convenient alias.
def model():
  x = yield Root(tfd.Independent(
        tfd.Normal(loc=tf.zeros([2]), scale=tf.ones([2])),
        1))
  z = yield Root(tfd.Independent(
        tfd.Normal(loc=x[0], scale=tf.ones([2])),
        1))

jd = tfd.JointDistributionCoroutine(model)
```

**Comment by brianwa84** [comment]
I don't think z should be taken as a root. It will inherit sample shape
from x. Slicing should only be done within the event dimensions of an
upstream sample, so the axis will always need a leading ellipsis, [..., :n,
:].

**Comment by junpenglao** [comment]
But it seems that's the intention of @jefio:
> I did mean `loc=x[0]` in the second distribution. More generally I meant any mapping of x to a real number(`loc=x[0]`, `loc=tf.reduce_sum(x)`, etc).

**Comment by brianwa84** [comment]
That's the intention for a scalar sample. But for a vector shaped sample, the sample at position 1 may not depend on the sample at position 0, otherwise the samples are no longer independent. And since sample dimensions are the first dimensions, you must always index from the *right*.

**Comment by jefio** [comment]
Thanks, I understand my mistake. My goal is to model `P(X, Y)` defined as `X ~ N([0, 0], Id) Y ~ N([[X[0], X[0]], Id)`, which is why I used `loc=x[0]` in my first post.  But now I realize that this doesn't work with `jd.sample(10)`, as `x` refers to a (10, 2) sample matrix.
 
> ```
> # after initialized your JointDistribution
> jd = ...
> jd._always_use_specified_sample_shape = True
> ```

Thanks, indeed this results in the correct shape. However the resulting distribution is not the one I was trying to model (see the end of this post)

> Alternative: x[..., :1]

Yep this did it,  thank you 👍  Sample output (I multiplied the `scale` of Y by 0.01 for clarity)

```
tf.Tensor(
[[ 1.4184642   1.1758332 ]
 [-0.06547955  0.7487986 ]
 [ 0.18621838 -0.26628125]
 [ 1.0231884   0.47857696]
 [-1.0036682   3.2664437 ]
 [ 1.29737     2.1123233 ]
 [ 0.3810004   1.1663677 ]
 [ 0.8402362  -0.27824485]
 [ 0.34952566 -0.3909819 ]
 [-0.23838514  0.3902707 ]], shape=(10, 2), dtype=float32)
tf.Tensor(
[[ 1.4293468   1.4280617 ]
 [-0.06052362 -0.07319161]
 [ 0.20485571  0.1897709 ]
 [ 1.0351573   1.0152292 ]
 [-0.985974   -1.0146173 ]
 [ 1.2856497   1.3006475 ]
 [ 0.37117818  0.38192976]
 [ 0.83900887  0.84372246]
 [ 0.36456746  0.35179356]
 [-0.2437398  -0.23591079]], shape=(10, 2), dtype=float32)
```

> Nice! I didnt know that you can use root to do that.
> For completeness:
> 
> ```python
> Root = tfd.JointDistributionCoroutine.Root  # Convenient alias.
> def model():
>   x = yield Root(tfd.Independent(
>         tfd.Normal(loc=tf.zeros([2]), scale=tf.ones([2])),
>         1))
>   z = yield Root(tfd.Independent(
>         tfd.Normal(loc=x[0], scale=tf.ones([2])),
>         1))
> 
> jd = tfd.JointDistributionCoroutine(model)
> ```

Why specify `z` as a sampling root while `z` explicitly depends on `x`? Anyway it doesn't seem to work (I multiplied the `scale` of Y by 0.01 for clarity):

```
tf.Tensor(
[[ 0.56546384  1.4316167 ]
 [-0.99243283  1.7284156 ]
 [-0.24338096  0.9720364 ]
 [-0.16978513  1.1237727 ]
 [ 0.7826207   1.5686011 ]
 [-0.43699977 -1.1167209 ]
 [ 0.26112378  1.1449372 ]
 [ 0.17098914  1.0072612 ]
 [-0.07338718  1.95083   ]
 [-0.2707743   0.7465145 ]], shape=(10, 2), dtype=float32)
tf.Tensor(
[[0.56577575 1.433082  ]
 [0.5500376  1.4307244 ]
 [0.56398857 1.448282  ]
 [0.55995584 1.421304  ]
 [0.559967   1.4182094 ]
 [0.5637099  1.448543  ]
 [0.55873877 1.4300407 ]
 [0.565578   1.4257815 ]
 [0.57268995 1.424436  ]
 [0.5619036  1.4344039 ]], shape=(10, 2), dtype=float32)
```

As you can see, all samples of `Y` use both components of the first sample of `X` (same problem when setting `jd._always_use_specified_sample_shape = True`).

**Comment by junpenglao** [comment]
Thanks for the clarification, yeah Brian's recommendations are the right answers.
