### ISSUE TITLE
Boltzmann generators

### ISSUE THREAD

**Issue by janosh** [tensorflow/probability#597]
Feature suggestion: implement [Boltzmann generators](https://science.sciencemag.org/content/365/6457/eaaw1147) in TFP.

Admittedly, it might be a little too early to tell but I think they could provide a nice alternative/complement to HMC sampling.

**Comment by junpenglao** [comment]
I am likely missing a lot of details here but is this the same as Sequential Monte Carlo?

**Comment by janosh** [comment]
Missing the same details as I'm just reading into this atm, but yes, it sounds like learning the bijection using INNs is the crux and novelty here.
