### ISSUE TITLE
tfp.edward2.make_log_joint_fn for weighted datasets

### ISSUE THREAD

**Issue by dionman** [tensorflow/probability#603]
Is there a straightforward way to augment ```tfp.edward2.make_log_joint_fn``` functionality in order to seamlessly support weighted datasets, i.e. instead of doing inference on a model given data ```datapoints = [1,1,1,2,2]``` to use weighted dataset ```datapoints=[1,2], weights=[3,2] ``` with equivalent result?

**Comment by davmre** [comment]
Did you resolve this? If you have a working solution, posting it here could help future users with the same question.

**Comment by dionman** [comment]
Not exactly, I ended up writing explicitely the ```joint_log_prob``` function, e.g. as follows for logistic regression:

```
# Log joint for logistic regression on weighted datasets
def joint_log_prob(X0, Y0, theta0, weights=None):
        rv_theta = tfd.MultivariateNormalDiag(loc=[0., 0.], scale_diag=[1., 1.])
        logits_ = tf.tensordot(X0, theta0, 1)
        rv_Y = tfd.Bernoulli(logits=logits_)
        if weights is None:
            return (rv_theta.log_prob(theta0) + tf.reduce_sum(rv_Y.log_prob(Y0)))
        else:
            return (rv_theta.log_prob(theta0) + tf.reduce_sum(tf.multiply(weights, rv_Y.log_prob(Y0))))
```
