### ISSUE TITLE
tensorflow.contrib.learn.python.learn.datasets does not exist in TensorFlow 2

### ISSUE THREAD

**Issue by nbro** [tensorflow/probability#605]
The example https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py imports `mnist` from `tensorflow.contrib.learn.python.learn.datasets`. However, this is no more available in TensorFlow 2. I don't even know where the API of `tensorflow.contrib.learn.python.learn.datasets` is documented, so it is not clear how to port the code in https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py  to TensorFlow 2, where I should be using `tensorflow_datasets`.

**Comment by dynamicwebpaige** [comment]
`tf.contrib` was deprecated in TensorFlow 2.0, but you should be able to use MNIST from `tensorflow_datasets`. You can see an example of this [here](https://www.tensorflow.org/tutorials/quickstart/beginner), in the TensorFlow 2.0 beginners' tutorial.

**Comment by nbro** [comment]
@dynamicwebpaige I was actually able to do it, but I think you should update your examples to TF 2.0, ASAP.

**Comment by nbro** [comment]
Here's the same issue, but asked several months before https://github.com/tensorflow/probability/issues/438.

**Comment by nbro** [comment]
In the new version of the example of BNN (https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py), this problem doesn't occur anymore, so I will close this issue.
