### ISSUE TITLE
Unable to sample from MultivariateNormal likelihood

### ISSUE THREAD

**Issue by simonkamronn** [tensorflow/probability#609]
I'm trying to estimate the covariance in a multivariate normal, but has so far been unable the get the shapes right. I don't fully understand the sample, batch and event dimension, I'm afraid. 

```
Root = tfd.JointDistributionCoroutine.Root 
def model():
    chol_rho_a = yield Root(tfd.CholeskyLKJ(num_wards, 2))
    sigma_a = yield Root(tfd.Sample(tfd.LogNormal(0, 10), num_wards))

    aw = yield tfd.Independent(
        tfd.MultivariateNormalTriL(
            loc=tf.expand_dims(daily_obs, 1) * tf_arrival_dist,  # [num_obs, num_wards]
            scale_tril=tf.expand_dims(  # [1, num_wards, num_wards]
                tf.matmul(tf.linalg.LinearOperatorDiag(sigma_a), chol_rho_a), 
                1), 
        ),
        reinterpreted_batch_ndims=1)

model = tfd.JointDistributionCoroutine(model)
```

Here is a link to the example in colab: https://colab.research.google.com/drive/1vCM-BtQu48xFajOgkS0VO2ADQWWon6SS

**Comment by srvasude** [comment]
I took a look at the adjoining colab.

The main issue is the shape of the `Tensor` when you define `scale_tril`: `tf.expand_dims(tf.matmul(tf.linalg.LinearOperatorDiag(sigma_a), chol_rho_a), 1)`

I was able to fix the issue by replacing this with:
`tf.reshape(tf.matmul(tf.linalg.LinearOperatorDiag(sigma_a), chol_rho_a), [-1, 1, num_wards, num_wards])`

The difference between the two has to do with an empty sample shape. If the sample shape is empty (say if calling `.sample()`), then the scale_tril will have shape `[num_wards, num_wards]`. Using expand_dims will just make this `[num_wards, 1, num_wards]` which has the wrong shape. A reshape like the one above will always ensure the shape always look like at the right hand side as `[1, num_wards, num_wards]`.

There are a few other shape issues that surface from this as well later in the code, but should be easily debuggable from that fix.

Let me know if there are any additional questions / issues. I can try to whip up a colab with a fixed version of this.
