### ISSUE TITLE
When can probability support cloudpickle==1.2.2

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/probability#615]
I have to use both gym and tfp, but I get the following error message:

> ERROR: tensorflow-probability 0.8.0 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 1.2.2 which is incompatible.

I know the reason is that OpenAI's Gym has used cloudpickle==1.2.2, but tfp still uses cloudpickle==1.1.1, which makes it not compatible with gym. I'm wondering when tfp can be compatible with a higher version of cloudpickle?

**Comment by brianwa84** [comment]
I think it is only used in tfp.layers, so if you don't use that, you might
just try forcing the upgrade.

**Comment by dynamicwebpaige** [comment]
Am able to use `cloudpickle==1.2.2` with `tensorflow_probability=0.7.0`; would you be able to use an earlier version of TFP, @xlnwel? Or, alternately, were you able to force the upgrade?

**Comment by xlnwel** [comment]
Thanks for your concerns. I've forced the update as @brianwa84 suggests.

**Comment by srvasude** [comment]
Closing this, since I believe we support cloudpickle >=1.2.2

**Comment by samfux84** [comment]
No you don't support cloudpickle >= 1.2.2 for tensorflow_probabilty 0.8.0:

```
[sfux@eu-login-44 ~]$ pip install tensorflow_probability==0.8.0
Collecting tensorflow_probability==0.8.0
  Downloading https://files.pythonhosted.org/packages/f8/72/29ef1e5f386b65544d4e7002dfeca1e55b099ed182cd6d405c21a19ae259/tensorflow_probability-0.8.0-py2.py3-none-any.whl (2.5MB)
     |████████████████████████████████| 2.5MB 3.3MB/s
Requirement already satisfied: gast<0.3,>=0.2 in /cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages (from tensorflow_probability==0.8.0) (0.2.2)
Requirement already satisfied: numpy>=1.13.3 in /cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages (from tensorflow_probability==0.8.0) (1.19.1)
Collecting cloudpickle==1.1.1
  Downloading https://files.pythonhosted.org/packages/24/fb/4f92f8c0f40a0d728b4f3d5ec5ff84353e705d8ff5e3e447620ea98b06bd/cloudpickle-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in /cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages (from tensorflow_probability==0.8.0) (1.12.0)
Requirement already satisfied: decorator in /cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages (from tensorflow_probability==0.8.0) (4.4.1)
Installing collected packages: cloudpickle, tensorflow-probability
  Found existing installation: cloudpickle 1.2.2
    Uninstalling cloudpickle-1.2.2:
ERROR: Operation cancelled by user
[sfux@eu-login-44 ~]$
```

**Comment by fighting-zz** [comment]
@xlnwel hello, have you solved this issue?
