### ISSUE TITLE
why are my sampler returning only initial values

### ISSUE THREAD

**Issue by yaowang1111** [tensorflow/probability#616]
I found that when i want to sample from a peaked distribution, eg.(normal(0,0.01)), my samplers(hmc,nuts) only returns initial values.
Shouldn't they walking around prob space?

I know the proposed value might have very small probability, but according to the math of rejection rate, i believe this won't be a big problem, so where do i understand it wrong?

Thanks a lot!

**Comment by junpenglao** [comment]
Usually, it is because the step size is too large and all proposals are rejected.

**Comment by yaowang1111** [comment]
Solved my problem, thanks~
