### ISSUE TITLE
rejecting tfp.mcmc.sample_chain samples according to is_accepted

### ISSUE THREAD

**Issue by dionman** [tensorflow/probability#626]
Reading the tutorials on mcmc sampling in tensorflow probability (e.g. examples here https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/HamiltonianMonteCarlo), it remains unclear to me if it's recommended as a general practice to reject samples when computing our empirical estimate according to the corresponding returned values of ```is_accepted```.

**Comment by brianwa84** [comment]
The is_accepted state is simply a diagnostic, indicating whether the
transition proposal was accepted.

in the expression `samps, states = sample_chain(...)`, samps are samples
from your target distribution (assuming a reasonable acceptance rate).

Brian Patton | Software Engineer | bjp@google.com

**Comment by dionman** [comment]
Thanks - just to clarify: which range of acceptance rates is reasonable? is it around 0.65?

**Comment by davmre** [comment]
More generally, anything in the 0.4-0.9 range is often considered
'basically fine' (if not necessarily optimal).

An exception is if you're using step size adaptation
(`tfp.mcmc.SimpleStepSizeAdaptation` or
`tfp.mcmc.DualAveragingStepSizeAdaptation`) targeting a particular
acceptance rate (the default is 0.75), and you notice that the actual
acceptance rates you're getting are significantly (> 10-15%) off from that
target rate -- the acceptance rate might still be 'fine' in isolation, but
a failed step size adaptation indicates that the chain isn't really mixing
during the adaptation period, which can be a sign of pathological geometry
or other problems.
