### ISSUE TITLE
Executor failed to create kernel. Internal: No function library [[{{node loop_body/Tensordot/MatMul/pfor/cond}}]]

### ISSUE THREAD

**Issue by dionman** [tensorflow/probability#639]
Reproducible with the following script

```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

d = 2
N = int(1e2)

# hyperparameters for prior
mu0 = np.zeros(d+1).astype('float32')
Sig0 = np.eye(d+1).astype('float32')

mu = np.array([0, 0])
cov = np.eye(2)
th = np.array([3, 3, 0])
X = np.ones((N,d+1))
X[:,:-1] = np.random.multivariate_normal(mu, cov, N)
ps = 1.0/(1.0+np.exp(-(X*th).sum(axis=1)))
y = (np.random.rand(N) <= ps).astype(int)
y[y==0]=-1
z = y[:, np.newaxis]*X
X = tf.convert_to_tensor(X, dtype=tf.float32)
y = tf.convert_to_tensor(y, dtype=tf.float32)
z = tf.multiply(X, y[:,tf.newaxis])
w = np.ones(shape=N).astype('float32')


def test(z, thetas, weights=None):
    theta_prior = tfd.MultivariateNormalFullCovariance(
              loc=mu0, covariance_matrix=Sig0)
    return tf.vectorized_map( lambda th: theta_prior.log_prob(th) +
        tf.reduce_sum(tf.multiply(weights, -tf.math.log1p(tf.exp(-tf.tensordot(z, th, axes=1)))), axis=-1), thetas)


initial_state = tf.ones(d+1, dtype=np.float32)
test(z, tf.stack([initial_state, initial_state]), w)

```

**Comment by dionman** [comment]
this seems to be related with an implicit condition for the loop of ```vectorized_map``` and does not appear when writing an equivalent expression using a ```for ```loop

**Comment by dynamicwebpaige** [comment]
Unable to reproduce with TensorFlow 1.15.0 and TensorFlow Probability 0.7.0. 

Which versions of TF and TFP are you using, @dionman?

```python
import tensorflow as tf
import tensorflow_probability as tfp
tf.__version__
tfp.__version__
```

**Comment by dionman** [comment]
I'm using ```tf 2.0.0-rc1``` and ```tfp 0.8.0-rc0```, on CPU

**Comment by MaheedHatem** [comment]
Any updates on this? I got a similar error trying to simply run the ode example found here. https://www.tensorflow.org/probability/api_docs/python/tfp/math/ode/Solver

I am using tf 2.0.0 for gpu and tfp 0.8.0-rc0 in an anaconda environment.

**Comment by srvasude** [comment]
I tried running this example, and I do still see this issue on tf 2.1.0 and tfp 0.9.0.

However, I believe execution of the program still continues. I was, for example, able to print the output value. This seems to indicate an error is displayed, but the execution still continues, which means that you should be able to continue your code execution.

I will follow up with a TF bug, since we should figure out why that line is in the output in the first place.

**Comment by srvasude** [comment]
TF internal bug is fixed. I will close this (and as mentioned this isn't a blocker for execution. The code before the fix will run fine as is, with noisy logging).

**Comment by CeyaoZhang** [comment]
> TF internal bug is fixed. I will close this (and as mentioned this isn't a blocker for execution. The code before the fix will run fine as is, with noisy logging).

Hello, what do you mean this bug is fixed? Is it to say that it would not print the words in the higher version as it does not affect the excution of code.
