### ISSUE TITLE
incorrect behavior for tfp.layers.KLDivergenceRegularizer

### ISSUE THREAD

**Issue by jacobsn** [tensorflow/probability#644]
I think [this line](https://github.com/tensorflow/probability/blob/c76d55c42c7f70dd6d887c6aca71be21c2fe168a/tensorflow_probability/python/layers/distribution_layer.py#L1345) should be `if use_exact_kl is True:` not `if use_exact_kl is None:`.

This code works regardless of whether use_exact_kl is True, False, or None: 
```
prior = tfd.MultivariateNormalTriL(loc=[2.0],scale_tril=[[1.0]])
p1 = tfkl.Dense(tfpl.MultivariateNormalTriL(1).params_size(1))
p2 = tfpl.MultivariateNormalTriL(1, 
  activity_regularizer=tfpl.KLDivergenceRegularizer(prior, use_exact_kl=False))
p2(p1(tfk.Input((1,))))
```

This code only fails when use_exact_kl is None: 
```
prior = tfd.Normal(loc=[2.0],scale=[[1.0]])
p1 = tfkl.Dense(tfpl.MultivariateNormalTriL(1).params_size(1))
p2 = tfpl.MultivariateNormalTriL(1, 
  activity_regularizer=tfpl.KLDivergenceRegularizer(prior, use_exact_kl=None))
p2(p1(tfk.Input((1,))))
```

When it fails, the error message is as follows:
```
NotImplementedError: No KL(distribution_a || distribution_b) registered for distribution_a type MultivariateNormalTriL and distribution_b type Normal
```
According to the documentation, I would have expected it to fail with use_exact_kl is True.

**Comment by bloops** [comment]
Thanks for reporting. This is fixed in this commit:
https://github.com/tensorflow/probability/commit/d82e8459cd36a307c2e1d1117017f548d29efb57

I think we can close this issue.
