### ISSUE TITLE
Masked autoregressive flow with TF 2.0

### ISSUE THREAD

**Issue by sanket-kamthe** [tensorflow/probability#645]
I am trying to train  MAF bijector, however, it doesn't have any trainable variables.

Is this a known issue/ or expected behaviour ? [ or  am I using the module incorrectly ?]

Note: same is true for tfp version 0.8.0, I just tested it on tfp_nightly to check whether it is already fixed. 

```python
In [14]: tf.__version__                                                                                                                                                              
Out[14]: '2.0.0'

In [15]: tfp.__version__                                                                                                                                                             
Out[15]: '0.9.0-dev20191111'

In [16]: tfd = tfp.distributions 
    ...: tfb = tfp.bijectors          
       
In [17]: dims = 2 
    ...: bij = tfb.MaskedAutoregressiveFlow( 
    ...:         shift_and_log_scale_fn=tfb.masked_autoregressive_default_template( 
    ...:             hidden_layers=[32, 32])) 
    ...: maf = tfd.TransformedDistribution( 
    ...:     distribution=tfd.Normal(loc=0., scale=1.), 
    ...:     bijector=bij, 
    ...:     event_shape=[dims])                                                                                                                                                     

In [18]: maf.trainable_variables                                                                                                                                                     
Out[18]: ()

In [19]: bij.trainable_variables                                                                                                                                                     
Out[19]: ()

```
Are there any pointers to the fix ? I can create a pull request if this has a quick fix.

**Comment by junpenglao** [comment]
See also discussion here https://github.com/tensorflow/probability/issues/629#issuecomment-552078556, seems like it has not been upgrade to TF2 yet
For now, I suggest you to use instead https://github.com/tensorflow/probability/blob/c76d55c42c7f70dd6d887c6aca71be21c2fe168a/tensorflow_probability/python/bijectors/masked_autoregressive.py#L572

**Comment by junpenglao** [comment]
There are more example after https://github.com/tensorflow/probability/commit/b99d9647239b77159bb2d344570cc40c70e689ac thanks to @jburnim 

Below is a snippet:
```python
dims = 2
bij = tfb.MaskedAutoregressiveFlow(
    shift_and_log_scale_fn=made)
maf = tfd.TransformedDistribution(
    distribution=tfd.Normal(loc=0., scale=1.),
    bijector=bij,
    event_shape=[dims])
maf.sample()
maf.trainable_variables
```

There are also some very informative doc string in: https://github.com/tensorflow/probability/blob/2065e03df67a35d62145b527ef0f41d4d38e61b0/tensorflow_probability/python/bijectors/masked_autoregressive.py#L197
