### ISSUE TITLE
Memory leak caused by bijectors

### ISSUE THREAD

**Issue by awav** [tensorflow/probability#647]
Hello everyone,

cc: @kkimdev

The original issue is described here: https://github.com/tensorflow/tensorflow/issues/34379. Pls, check for details.

Here is a colab notebook showing that the leakage caused by a bijector:

https://colab.research.google.com/gist/kkimdev/f69960cb84d05a8d865eaadf44f47967/memory-leak-in-custom-tensor.ipynb#scrollTo=WbADsIv5atpQ

Related issues:
https://github.com/tensorflow/probability/issues/547, https://github.com/tensorflow/probability/issues/493

The #493 detected the memory growth in a forward mode. In my case the issue appears when `GradientTape` is involved.

**Comment by csuter** [comment]
Thanks for filing this, Artem. We have a fix in the works. Hope to have it out in tfp-nightly tomorrow.

**Comment by csuter** [comment]
Quick update -- this didn't make it in yesterday, but I'm checking it in presently; should be fixed in tomorrow's tfp-nightly build.

**Comment by csuter** [comment]
Ok, fix checked in. Please let us know if you are still seeing issues after this! I tested the provided repro code locally and it appears to have eliminated the leak.

**Comment by awav** [comment]
@csuter , It works! No memory leaks! Thanks a lot!

**Comment by csuter** [comment]
Woohoo! Thanks for confirming.
