### ISSUE TITLE
TF 2.X Notebook

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/probability#649]
When can we expect the [official TFP notebooks](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/) to be updated to use TF 2.X? (If at all)

**Comment by junpenglao** [comment]
The team is working on it, and many of the notebooks are already updated to TF 2.0. Meanwhile if you are looking at a notebook that is still TF1 and you need it urgently, we are happy to prioritized it :-)

**Comment by luischinchillagarcia** [comment]
Thanks for the quick response! Yes, I have been looking to update the [Linear_Mixed_Effects notebook](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Linear_Mixed_Effects_Models.ipynb) for about a week without much luck, so this would be incredibly helpful. Thanks Junpeng!

**Comment by junpenglao** [comment]
I will take a stab of updating it.

**Comment by junpenglao** [comment]
Just pushed https://github.com/tensorflow/probability/commit/c071e90b6b21d8587b04e761713adc86dcd821b7 so the notebook is TF2.0 now. Closing this for now but feel free follow up here ;-)
