### ISSUE TITLE
VAE tutorial

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#65]
Port current example into colab. Transfer text from 

+ http://edwardlib.org/tutorials/decoder
+ http://edwardlib.org/tutorials/inference-networks

**Comment by ChanchalKumarMaji** [comment]
I think I can do this. Can you please assign this to me ?

**Comment by Derek-Wds** [comment]
@dustinvtran Hi, I would love to help with this issue. I have a VAE tutorial on my personal website here: [VAE](https://wangdingsu.com/2019/04/10/VAE/). Could you please tell me what should I do?

Thanks,
Derek

**Comment by csuter** [comment]
Thanks, @Derek-Wds and @ChanchalKumarMaji -- I think we have pretty good coverage of VAE examples at this time (see `examples` and `examples/jupyter_notebooks` folders).
