### ISSUE TITLE
quantile is not implemented: Logistic

### ISSUE THREAD

**Issue by moonman925** [tensorflow/probability#656]
No inverse cdf (quantile) in Logisitc, does it mean that I have to write it myself?

**Comment by SiegeLordEx** [comment]
It's implemented, but hasn't made it into a stable release yet: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/logistic.py#L228. You can install the nightly package (which we recommend anyway) to get it: tfp-nightly
