### ISSUE TITLE
Sample documentation error

### ISSUE THREAD

**Issue by lucianopaz** [tensorflow/probability#661]
Example [2 in the docstring of `distributions.Sample`](https://github.com/tensorflow/probability/blob/r0.8/tensorflow_probability/python/distributions/sample.py#L92-L107) has the wrong `sample_n_shape`.

The example reads
```python
s = tfd.Sample(
    tfd.Independent(tfd.Normal(loc=tf.zeros([3, 2]), scale=1),
                    reinterpreted_batch_ndims=1),
    sample_shape=[5, 4])
x = s.sample([6, 1])
# ==> x.shape: [6, 1, 5, 4, 3, 2]
```

But actually `x.shape =(6, 1, 3, 5, 4, 2)`

The docstring currently seems to imply that the `sample_shape` given to `Sample` will be placed to the left of a batch dimension of the underlying `tfd.Normal`, which breaks the contract that any sample from a distribution will have a shape equal to `sample_shape + batch_shape + event_shape`

**Comment by junpenglao** [comment]
Sound like it is the karg being confusing, as the sample_shape actually add dimensions to the event shape. @jvdillon thoughts?

**Comment by jvdillon** [comment]
Thanks for raising this issue. I confirm that the docstring is broken but the code is not. The docstring 
should have said:

```python
# ==> x.shape: [6, 1, 3, 5, 4, 2]
```
since:

```python
sample_shape = [6, 1]
batch_shape = [3]
event_shape = [5, 4, 2]
```

**Comment by junpenglao** [comment]
```python
base_dist = tfd.MultivariateNormalDiag(loc=tf.zeros([3, 2, 5]),
                                       scale_diag=tf.ones([5]))
print(base_dist.batch_shape, base_dist.event_shape)
# ==> (3, 2) (5,)
# As batch_shape is inferred from loc
modified_dist = tfd.Independent(base_dist, reinterpreted_batch_ndims=1)
print(modified_dist.batch_shape, modified_dist.event_shape)
# ==> (3,) (2, 5)
# tfd.Independent move batch_shape[-reinterpreted_batch_ndims:] to event_shape,
# and stack at the left most.
s = tfd.Sample(modified_dist, sample_shape=[5, 4])
print(s.batch_shape, s.event_shape)
# ==> (3,) (5, 4, 2, 5)
# tfd.Sample stack additional sample_shape to the left most of event_shape.
x = s.sample([6, 1])
print(x.shape)
# ==> (6, 1, 3, 5, 4, 2, 5)
# which is (6, 1) + (3,) + (5, 4, 2, 5)
```

**Comment by jburnim** [comment]
The docstring for `tfd.Sample` has been updated.

Thanks for reporting, @lucianopaz  !
