### ISSUE TITLE
`bijectors.RealNVP` should allow `num_masked` to be defined as proportions

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#662]
It would be nice if the RealNVP template allowed the number of masked elements to be defined as proportions instead of just integers. Right now the `num_masked` should be an integer in `[-D+1, D-1]`.  It should be unambiguous if we allowed the user to specify `num_masked` as a float between `[-1, 1]`, and the implementation would be quite trivial.

I'll open a PR for this, and the details can be discussed there. I can't see any reason why this couldn't be allowed, but if anyone has objections to it, please let me know.

**Comment by SiegeLordEx** [comment]
Fixed by #663
