### ISSUE TITLE
gradients w.r.t. Wishart parameters are None

### ISSUE THREAD

**Issue by dwrtz** [tensorflow/probability#669]
I'm trying to make the parameters of a Wishart distribution trainable. I was able to do this successfully using a Normal distribution. It appears that there's something wrong with Wishart because the gradients are None. Code below reproduces the issue:

```
import tensorflow as tf
import tensorflow_probability as tfp
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

tfd = tfp.distributions


df = tf.Variable(4.0)
L = tf.Variable(2*tf.eye(4))

pX = tfd.Wishart(df=df, scale_tril=L)
X = pX.sample()

with tf.GradientTape() as tape:
    log_prob = pX.log_prob(X)
    
trainable_vars = [L, df]

grads = tape.gradient(log_prob, trainable_vars)

print(grads)
```

**Comment by dwrtz** [comment]
this was with tensorflow version 2.0.0 and tensorflow_probability version 0.8.0

**Comment by junpenglao** [comment]
This should be already fixed on master - could you try upgrade to TFP nightly?

**Comment by dwrtz** [comment]
I just tried this on TFP version 0.9.0-dev20191203 and the issue is fixed. 

Thanks!
