### ISSUE TITLE
Can observed_time_series passed to tfp.sts.forecast be different than the one used for model fitting?

### ISSUE THREAD

**Issue by boxu08** [tensorflow/probability#670]
Suppose that I have fit an Autoregressive model with order=5 using a time series. Now I want to test the model using a completely new time series. Particularly I want to make a prediction at every point of the new time series (except the first 5 since I need at least 5 points to make a prediction). Since order=5, I'll slide through the new time series with a window of size 5. For each slide of the window, I get a mini time series with length=5 and run tfp.sts.forecast with observed_time_series be set to this mini time series. My questions are: 

1. Can observed_time_series passed to tfp.sts.forecast be different than the one used for model fitting? In my case, I'm passing the mini time series which was not seen when the model was fit. Is this a viable approach? 
2. If the answer to question 1 is true, can the observed_time_series only include the past n observations where n is the order of the Autoregressive model? Or is it that the entire time series has to be passed to tfp.sts.forecast?

**Comment by davmre** [comment]
It's certainly valid to pass novel time series to `tfp.sts.forecast`, as
long as you think they're from the same model as the one you originally
fit. The forecast method will make a filtering pass over whatever series
you pass in, using the model parameters from the original fitting.

In general the fitted model will have some level of observation noise, so
it's likely beneficial to include more than the bare minimum amount of
history (i.e., more than five steps for an autoregressive model). It will
depend a bit on the parameters you've fit (for autoregressive, on the
relative magnitudes of the noise scale and the drift scale), but in general
it's useful to give the model a chance to average away the noise in the
inferred states. You could test this empirically by incrementally trying
histories of increasing length until your forecast stops changing. But yes,
at a programmatic level there's no fixed length required for the observed
time series.

Dave

**Comment by boxu08** [comment]
Thanks Dave. Your information is very helpful. If the training time series is fitted with a seasonal model and I want to test on a different time series from the same model, what is a reasonable length of the time series I should pass to tfp.sts.forecast? I cannot pass the entire test time series because the test time series comes as a data stream.

**Comment by davmre** [comment]
It'll depend on the data and the specific model you fit, but for a seasonal
model I think a few cycles of the seasonality is a reasonable rule of
thumb. E.g., if you're modeling day-of-week seasonality, you'd maybe want
3-4 weeks of history so that you get multiple observations of each effect.

**Comment by boxu08** [comment]
I see. Thanks Dave!
