### ISSUE TITLE
Varargs for JointDistributionSequential._get_required_args

### ISSUE THREAD

**Issue by tramchamploo** [tensorflow/probability#675]
Why does JointDistributionSequential doesn't support varargs in distribution functions?
This somehow limits abstraction for JointDistributionSequential style model definition.

**Comment by brianwa84** [comment]
I believe that as of https://github.com/tensorflow/probability/commit/3aeaef56a916622f6ecd0ec215002602abfeacdc it does! Please give tf-nightly a try and let us know if it's not working for you.

**Comment by brianwa84** [comment]
Or maybe you're referring to the model functions, i.e.
```python
tfd.JDSequential([
 tfd.Normal(0,1),
 lambda x: tfd.Normal(n, 1),
 lambda z, y: tfd.Normal(y+z, 1)])
```
The names of the lambda/function arguments are used to create a dependency graph, so they must be explicitly named.

**Comment by tramchamploo** [comment]
So if I want to seprate priors Frome likelihood, are there any good ways to
redefining priors without changing the long likelihood arg list?

Brian Patton <notifications@github.com> 于 2019年12月10日周二 上午1:41写道：

**Comment by brianwa84** [comment]
Maybe you could write a function?

def create_model_fn(prior_fn):
  return [prior_fn, lambda x: ...]
