### ISSUE TITLE
Add Johnson's SU-distribution

### ISSUE THREAD

**Issue by 0x0badc0de** [tensorflow/probability#678]
Hi guys, is it possible to have Johnson's SU-distribution added?
Details - https://en.wikipedia.org/wiki/Johnson%27s_SU-distribution
As stated on wiki:
Johnson's SU-distribution has been used successfully to model asset returns for portfolio management.

**Comment by brianwa84** [comment]
Looks quite feasible, we should already have all the stuff needed to get it
working. Would you be willing to send a PR?

**Comment by brianwa84** [comment]
It looks like the distribution has a tractable inversion sampler, so you
could use special_math.erfinv and tf.sinh plus some add/mul/div to go from
uniform samples to samples from this dist; such samples would have
gradients to parameters, which is nice.

Brian Patton | Software Engineer | bjp@google.com

**Comment by brianwa84** [comment]
Actually skip the erfinv, just use std normal for the underlying samples.

Brian Patton | Software Engineer | bjp@google.com

**Comment by 0x0badc0de** [comment]
Thanks for directions, Brian. I'll try to implement it later.
