### ISSUE TITLE
Run Session for one_step

### ISSUE THREAD

**Issue by tcholewik** [tensorflow/probability#686]
Sorry if this was already addressed elsewhere but I couldn't find any other issue close enough.

I am trying to debug my model and I wanted to run something along the lines of:
`
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
mcmc = tfp.mcmc

kernel = mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=model.log_prob,
    step_size=0.1,
    num_leapfrog_steps=3
)

previous_state = tf.placeholder(dtype=tf.dtypes.float32,name='PreviousState')
initiall_results = kernel.bootstrap_results(previous_state)
previous_results = tf.placeholder(dtype=tf.dtypes.float32,name="PreviousResults")

current_state, current_results = kernel.one_step(previous_state, previous_results)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    state = tf.constant(1)
    results = sess.run(initiall_results,{previous_state: state})
    
    for i in xrange(1000):
        state, results = sess.run([state, results],{previous_state:state, previous_results:results})
`

Code above will throw an error:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-85-8ccab8971902> in <module>
>      9 previous_results = tf.placeholder(dtype=tf.dtypes.float32,name="PreviousResults")
>     10 
>---> 11 current_state, current_results = kernel.one_step(previous_state, previous_results)
>      12 
>      13 results = tb.summary.scalar('mean',results)
> 
> ~\AppData\Local\Continuum\anaconda3\envs\mcmc\lib\site-packages\tensorflow_probability\python\mcmc\hmc.py in one_step(self, current_state, previous_kernel_results)
>     547     with tf.control_dependencies(previous_step_size_assign):
>     548       next_state, kernel_results = self._impl.one_step(
> --> 549           current_state, previous_kernel_results)
>     550       if self.step_size_update_fn is not None:
>     551         step_size_assign = self.step_size_update_fn(  # pylint: disable=not-callable
> 
> ~\AppData\Local\Continuum\anaconda3\envs\mcmc\lib\site-packages\tensorflow_probability\python\mcmc\metropolis_hastings.py in one_step(self, current_state, previous_kernel_results)
>     192       ] = self.inner_kernel.one_step(
>     193           current_state,
> --> 194           previous_kernel_results.accepted_results)
>     195 
>     196       if (not has_target_log_prob(proposed_results) or
> 
> AttributeError: 'Tensor' object has no attribute 'accepted_results'

Which does make makes sense to me `previous_state` is not a Tensor but a named tuple, but I am not sure how to write something similar that does not throw any error.
I chose to write this code like that is that I have another model there is a bug somewhere in it so with help of tensorboard I'd like to be able to inspect it as mcmc is drawing samples from it.

Thinking about how I could go around this I came up with couple workarounds:

1. I can execute my code in eager mode and inspect trace that comes out at the end, but that is not always feasible because some models will require that you sample very long chains and you will have to wait until all of sampling is done for you to even begin to look at the results.
2. Only feed state values and recycle results, pull out just the Tensors of interest from results, something like this :

```
 init_results = tf.placeholder(dtype=tf.dtypes.bool,name='InitializeResults')
 previous_results = tf.cond(
     init_results,
     lambda: kernel.bootstrap_results(previous_state), 
     lambda: current_results
 )
```
But this throws another error.

So my question is am I not using some feature that would make this code run correctly?
Is anyone facing similar issue?

In case it isn't obvious yet I am quite new to TF.

**Comment by SiegeLordEx** [comment]
I would definitely recommend using Eager (or rather, just learn TF 2.0, especially if you're new to this) and `tf.function` to make Eager fast after you debugged it. You don't need to run the entire chain to be able to inspect it, e.g. this code right here works fine in Eager:

```python
hmc = tfp.mcmc.HamiltonianMonteCarlo(
    lambda x: -x**2 / 2., num_leapfrog_steps=1, step_size=0.1)

state = tf.constant(0.)
kernel_results = hmc.bootstrap_results(state)

for i in range(10):
  state, kernel_results = hmc.one_step(state, kernel_results)
  print(state)
```

`tfp.mcmc.sample_chain` also has a callback called `trace_fn`, which you can also use to debug what's happening in the chain:

```python
def trace_fn(state, kernel_results):
  print(state)
  return state, kernel_results

state, results = tfp.mcmc.sample_chain(
    kernel=hmc, current_state=state, num_results=10, trace_fn=trace_fn)
```

And once you finished debugging, you can wrap the `sample_chain` call in a `tf.function` to make it run a lot faster:

```python
state, results = tf.function(lambda: tfp.mcmc.sample_chain(
    kernel=hmc, current_state=state, num_results=10, trace_fn=trace_fn))()
```

That said, if you for some reason don't want to or can't use Eager, here's how to accomplish your TF 1. The key step is to use the `tf.nest` library, which lets you operate on nested collections (namedtuples included). It's useful to know of it as it's very handy even in TF 2.0 world.

```python
hmc = tfp.mcmc.HamiltonianMonteCarlo(
    lambda x: -x**2 / 2., num_leapfrog_steps=1, step_size=0.1)

state = tf.constant(0.)
kernel_results = hmc.bootstrap_results(state)

state_ph, kernel_results_ph = tf.nest.map_structure(
    lambda tensor: tf.placeholder(tensor.dtype, tensor.shape),
    (state, kernel_results))
new_state, new_kernel_results = hmc.one_step(state_ph, kernel_results_ph)
all_ph = tf.nest.flatten((state_ph, kernel_results_ph))

with tf.Session() as sess:
  state_, kernel_results_ = sess.run([state, kernel_results])

  for i in range(10):
    state_, kernel_results_ = sess.run([new_state, new_kernel_results], {
        ph: v
        for ph, v in zip(all_ph, tf.nest.flatten((state_, kernel_results_)))
    })
    print(state_)
```

**Comment by tcholewik** [comment]
Thank you,

Code works like a charm now.
