### ISSUE TITLE
Broken tests?

### ISSUE THREAD

**Issue by linusmartensson** [tensorflow/probability#693]
Hi team TFP,

I've noticed I'm unable to run some of the examples, and found in c8f841c28c0341346d1db1831a79ba8712b49791 that they've been disabled in the automated test suite back in february as "tf2-kokoro-broken" - will this be fixed?

For example, running the bayesian neural network example, it seems to be pointing at now unavailable test sets:
Traceback (most recent call last):
  File "bayesian_neural_network.py", line 41, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import mnist
ImportError: No module named contrib.learn.python.learn.datasets

Any official word on these?

**Comment by srvasude** [comment]
Hi, I don't remember the full context for this, but we are in the midst of moving our examples to using TF2 (I think at the time the example was not TF2 compatible).

**Comment by srvasude** [comment]
Using #416 to track this.
