### ISSUE TITLE
watched_variable vs trainable_variable

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/probability#695]
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/FFJORD_Demo.ipynb
I watched your FFJORD example. It looks GREAT!!!

I wonder why you use `tape.watched_variables()` instead of `stacked_ffjord.trainable_variables`.

Questions

- should we use tape.watched_variables?
- how not-trainable variable will do if we use tape.watched_variables?

**Comment by srvasude** [comment]
Hi,
  In this case it really shouldn't matter. Both should return (and I've verified) the same set of variables. 

In general, the reasons to prefer watched_variables is you could potentially use this component as part of a larger model, that has also other trainable variables, and so watched_variables would subsume that set. Also, if you differentiate other things and use `tape.watch(...)` on them, `tape.watched_variables()` would have this, while `trainable_variables` won't.

Given these arguments, in some sense, `watched_variables` is a somewhat safer option than using `trainable_variables`.

Hopefully this answers your question. I will close this, but feel free to reopen if you have a follow up question / comment.

**Comment by MokkeMeguru** [comment]
Thanks your advice! 
I will use `watched_variables()`
