### ISSUE TITLE
tfp.bijectors.MatvecLU's batch_size?

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/probability#696]
Glow's original Implementation: https://github.com/openai/glow/blob/master/model.py#L438-L464
```
c=4
w_init = np.linalg.qr(np.random.randn(c,c))[0]
tf.compat.v1.get_variable("W", initializer=w_init)
```
```
<tf.Variable 'W:0' shape=(4, 4) dtype=float64, numpy=
array([[-0.1970753 , -0.73133301,  0.34299162, -0.55558086],
       [ 0.84265183, -0.10569677,  0.50553336,  0.15232236],
       [ 0.45773963, -0.37086514, -0.79147199, -0.16280531],
       [-0.20389617, -0.56252934, -0.01910118,  0.80101326]])>
```

this matrix does not include batch_shape

But in your implementation, its matrix include batch_shape.
https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/MatvecLU

I wonder why your matrix has batch_shape?

**Comment by brianwa84** [comment]
Almost much every class in TFP supports multi-dimensional batches.

The idea here would be that MatvecLU might be useful well beyond the single-variable case leveraged by GLOW, i.e. if you wanted to sample typical matrices using parallel MCMC chains.
