### ISSUE TITLE
Independent RelaxedBernoulli log_prob gives nan

### ISSUE THREAD

**Issue by uri-datorama** [tensorflow/probability#705]
RelaxedBernoulli with > 0 dimensions and sufficiently small temperature produces nan when log_prob is invoked on sampled values.
Reproduction below;

```
d = tfd.RelaxedBernoulli(0.01, probs=tf.ones(1)*.5)
iid = tfd.Independent(d, reinterpreted_batch_ndims=1)

iid.log_prob(iid.sample()) # <-- usually given nan

iid.log_prob(d.sample()) # always gives the right result
```

When inspecting d.sample() vs iid.sample() they appear to be similar by their __repr__().
The problem doesn't reproduce for scalar RelaxedBernoulli or if temperature is high enough.

On:
macOS High Sierra 10.13.6 
tensorflow 2.0.0               
tensorflow-probability 0.8.0

**Comment by srvasude** [comment]
This should be fixed in https://github.com/tensorflow/probability/commit/242731a9b2b42d4eb676539658a8d5e8267c0720.
