### ISSUE TITLE
TFP Covariance Estimation Example - Do we still use tf.Graphs and tf.Session with TF 2.0?

### ISSUE THREAD

**Issue by 00krishna** [tensorflow/probability#707]
Hello. I am reading over the TFP Guide in particular the ["Covariance Estimation"](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/TensorFlow_Probability_Case_Study_Covariance_Estimation.ipynb) example. At Step 3, I see the author creates the usual Tensorflow 1 `tf.Graph` and `tf.Session,` however, on the main TFP [website page](https://www.tensorflow.org/probability), the example does not use the Graph and Session code to run the model. Also in the "Distributions" and "Shapes" tutorials, there is no mention of Graphs and Sessions. 

Hence I was a bit confused about whether we still need to use Graphs and Sessions, or whether there is a different idiom or API for TF 2.0 ? I thought perhaps the documentation might not be up to date, but otherwise it might be that we still need to define Graphs and Sessions like in TF 1. Can you let me know what the current standard is for this, or where I might find the right examples. 

I checked in the Pull Requests, but some updates to the [documentation](https://github.com/tensorflow/probability/pull/698) seem to be failing on CI. 

Any help would be appreciated. Thanks.

**Comment by brianwa84** [comment]
Graph and Session are TF1 behavior, but we haven't yet updated all the examples to TF2.
