### ISSUE TITLE
Why do we need multi-dimensional batch_shape?

### ISSUE THREAD

**Issue by nbro** [tensorflow/probability#716]
In [this notebook](https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Understanding_TensorFlow_Distributions_Shapes.ipynb#scrollTo=usTT7v0trG7H), it is written

> **Batch shape** describes **independent, not identically distributed draws, aka a "batch" of distributions**.

> Sample shape describes independent, identically distributed draws of batches from the distribution family.

Now, consider the following program

```
import tensorflow_probability as tfp

d = tfp.distributions.Normal(loc=[0, 1], scale=[[0, 1], [2, 3]])
print(d)
```

that outputs the following

```
tfp.distributions.Normal("Normal", batch_shape=[2, 2], event_shape=[], dtype=float32)
```

What does `batch_shape=[2, 2]` actually mean? If I understood correctly, the `loc=[0, 1]` will be broadcast to the `scale=[[0, 1], [2, 3]]` parameter (or vice-versa), but how exactly? Does `d` represent 4 Gaussian distributions where the first two have mean 0 (one with standard deviation 0 and the other with standard deviation 1) and the second two have mean 1 (one with std 2 and the other with std 3)? 

The "not identically" part in the quoted sentence of the notebook should emphasize that the distributions can possibly have different mean and variance, but this is not explicitly stated.

Is there a way of debugging this broadcasting?

```
print(d.loc)
print(d.scale)
```

outputs

```
tf.Tensor([0. 1.], shape=(2,), dtype=float32)
tf.Tensor([[0. 1.] [2. 3.]], shape=(2, 2), dtype=float32)
```

which does not provide the information I am looking for.

In general, why do we need multi-dimensional `batch_shape`? Is it because we may, for example, have a neural network with an output layer of shape `NxM`, for `N, M > 1`, where we want an independent distribution for each of these outputs neurons? If that's the case `batch_shape` may not be the most appropriate name for this parameter, IMHO, even though that may still be considered a batch, it's just a little bit counter-intuitive, given the usage of the term "batch" in the context of neural networks, which usually only refers to one dimension of an array.

**Comment by brianwa84** [comment]
One way to better understand the semantics is to slice the distribution:
```python
d = tfd.Normal(
    loc=[0, 1],
    scale=[[1, 2], [3, 4]])
d10 = d[1, 0]
d10.loc  # => 0
d10.scale  # => 3
```

The batch axes index separately parameterized distributions. Broadcasting lines up axes by implicitly adding ones on the left/major end of the shape where necessary until ranks line up, then broadcasting the ones against any sizes that are >1. In some cases the broadcasting can save a fair amount of computation, assuming you have reasons for parameters to broadcast.

**Comment by csuter** [comment]
Thanks, @brianwa84! I'd just add a couple notes

You can also get a picture of what broadcasting is doing by looking at the mean() and stddev() function values, which will in the simple case of `Normal` just be the loc and scale parameters, but fully broadcast:

```
print(d.mean())
print(d.stddev())
```

gives

```
tf.Tensor(
[[1. 0.]
 [1. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
```

As to why we support higher-rank batching, one not-actually-too-cheeky answer is "why not??" :). Almost all TF ops (similar to NumPy and other array programming systems) support (in principle) batching of arbitrary rank. We would actually have to go somewhat out of our way *not* to support it in TFP :)

One interesting use case is in generative models of images like a VAE, where the final distribution is over N x N images (see [this blog post](https://medium.com/tensorflow/variational-autoencoders-with-tensorflow-probability-layers-d06c658931b7) and [accompanying notebook](https://colab.sandbox.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_VAE.ipynb#scrollTo=MM7wW4S2OrBt). Sure, we could flatten and unflatten but why bother when we can simply express the distribution as a "square" of independent pixel distributions?

As for naming, I think for bettor worse that that ship has sailed...Agreed that batch probably has its etymological roots in minibatch SGD. It has evolved, however, at least in the TF and TFP (and, e.g., [PyTorch distributions](https://pytorch.org/docs/stable/distributions.html)), to refer generically to the notion of independent, vectorized parallel computations.

**Comment by nbro** [comment]
@brianwa84 I didn't know we could slice distribution objects so that to obtain the single distributions. Yes, in order to debug the distribution objects, combined with the suggestion by @csuter of calling `d.mean()` and `d.stddev()`, this was more or less what I was looking for.

I had actually read that article, but I may have skipped that part or, at the time, I didn't have this question yet.

> Sure, we could flatten and unflatten but why bother when we can simply express the distribution as a "square" of independent pixel distributions?

Yes, I agree with you. _However_, this behaviour is not consistent across all functions of TF. For example, even though a little bit unrelated, recently, I wanted to have a `NxM` output layer `O` and compute the binary-cross-entropy between `O[i, j]` and `T[i, j]`, for all `i, j`, where `T` is the `NxM` target array, but, to do that, I had to flatten both `O` and `T` to be `(N*M)x1`, otherwise the `tf.losses.binary_crossentropy` would compute the cross-entropy between the row `O[i]` and `T[i]`, for all `i`, and we would have only `N` cross-entropy losses, rather than `NxM`.

**Comment by srvasude** [comment]
@nbro This is definitely true in TF, but the hope is that vmap / some of these functions will start to support batching in the future (definitely for some of the numeric functions we've used, we've supported general batching.

Going to close this issue since I think the general question is resolved, but feel free to reopen.
