### ISSUE TITLE
Is TFP's distribution's probability correct?

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/probability#720]
Hello, I'm learning a normal distribution and multi variate normal distribution with tfd.Normal and tfd.MultivariateNormalDiag.

I write a code here. https://colab.research.google.com/gist/MokkeMeguru/91cfd83151738e8cdbc2d3f0ac8ba537/distribution_test.ipynb

```python
target_dist = tfd.MultivariateNormalDiag(
    loc=tf.cast(tf.zeros([32 * 32 * 1]), tf.float32),
    scale_diag=tf.cast(tf.ones([32 * 32 * 1]), tf.float32)
)
target_dist2 = tfd.Normal(loc=0., scale=1.)

samples = target_dist.sample(256)
print('td log_prob : {}'.format(tf.reduce_mean(target_dist.log_prob(samples))))
print('td2 log_prob : {}'.format(tf.reduce_mean(tf.reduce_sum(target_dist2.log_prob(samples), axis=[-1]))))

# td log_prob : -1454.9139404296875
# td2 log_prob : -1454.9139404296875

prob = target_dist.prob(samples) # 0
prob = target_dist2.prob(samples) # 0
```

And I found two unsure points.

1. MultivariateNormal Distribution has a Covariance matrix. It is different from Normal Distribution. But log_probability of some sampled vectors are the same.

2. the sampled vector form the MultivariateNormal Distribution has the 0 probability between its distribution. 

Is this the correct behavior?

**Comment by brianwa84** [comment]
You are using MVNDiag, a diagonal MVN. This is equivalent to
Independent(Normal(zeros((32*32)), 1), reinterpreted_baych_ndims=1).
Normal.log_prob will broadcast when given samples having a batch shape
bigger than the distribution.

What would be instructive would be to note that the MVN log prob has shape
(256,) whereas the Normal log prob has shape (256, 32*32). The independent
events are aggregated for you by the MVN.

If you want non diagonal covariance, use MVNTriL.

**Comment by MokkeMeguru** [comment]
Thanks!  So if we want to use diagonal coveriance, 

```python
target_dist3 = tfd.MultivariateNormalTriL(loc=tf.zeros([32 * 32 * 1]), scale_tril=tf.eye(32 * 32 * 1))
print('td3 log_prob: {}'.format(tf.reduce_mean(target_dist3.log_prob(samples))))
# td3 log_prob: -1454.8526611328125
```
※ det(I) = 1, so td3's log_prob is same as td or td2's log_prob, I think
