### ISSUE TITLE
Indexing a normal distribution with multi-dimensional batch_shape produces an EagerTensor object rather than a distribution object

### ISSUE THREAD

**Issue by nbro** [tensorflow/probability#722]
We can create a [`Normal`](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Normal) object `d` with a multi-dimensional `batch_shape=(N, M)`, for `N, M > 1`, where [`d[i, j]` corresponds to a single scalar normal distribution](https://github.com/tensorflow/probability/issues/716#issuecomment-572333153). For example, consider the following code

```
import tensorflow_probability as tfp

tfd = tfp.distributions

d = tfp.distributions.Normal(loc=[0, 1], scale=[[0, 4],
                                                [2, 3]])
print("d.batch_shape =", d.batch_shape)
print("type(d[0, 0]) =", type(d[0, 0]))
```

whose output is

```
d.batch_shape = (2, 2)
type(d[0, 0]) = <class 'tensorflow_probability.python.distributions.normal.Normal'>
```

Now, consider this program

```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions


def get_model():
    inp = tf.keras.layers.Input(shape=(1,))

    x = tfp.layers.DenseFlipout(4)(inp)

    locations = tfp.layers.DenseFlipout(2)(x)
    rhos = tfp.layers.DenseFlipout(2)(x)

    out = tfp.layers.DistributionLambda(lambda t: tfd.Normal(loc=t[0], scale=tf.math.softplus(t[1])))([locations, rhos])

    model = tf.keras.Model(inp, out)
    return model


def main():
    model = get_model()
    data = np.array([[1.], [3.]])

    d = model(data)
    print("d.batch_shape =", d.batch_shape)
    print("type(d[0, 0]) =", type(d[0, 0]))


if __name__ == '__main__':
    main()
```
whose output is

```
d.batch_shape = (2, 2)
type(d[0, 0]) = <class 'tensorflow.python.framework.ops.EagerTensor'>
```

Why isn't `d[0, 0]` a [`Normal`](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Normal) object in this case? These different outputs are, _at least_, unintuitive.

In the second program,  I wanted to have an output layer with `M` univariate (normal) distributions, where each of these distributions should have a learnable mean and variance. In the example above, for simplicity, `N = M = 2`, where `N` is the batch size. If you have a better suggestion to achieve that, I'd be glad to hear it. 

In both cases, I am using TF 2.0 and TFP 0.8.0.

**Comment by brianwa84** [comment]
Ah the issue is that distribution lambda converts to a tensor (by sampling)
upon use of any overloaded operator. The object is actually a
DistributionTensorCoercible iirc. It should have an attr for the underlying
distribution.

**Comment by csuter** [comment]
slightly more precisely, "DistributionLambda returns an object that is a mixin of Distribution and DistributionTensorCoercible...etc etc"

**Comment by nbro** [comment]
@brianwa84, @csuter  Note that, in the second example, `type(d)` is a `Normal` object and not `DistributionLambda` or `DistributionTensorCoercible` object. 

Moreover, why would the use of the indexing operator convert the `Normal` object to a tensor in the second example? What's the rationale behind this?

**Comment by csuter** [comment]
@nbro there's some funky metaclass stuff going on with how these mixins are generated. The relevant code is here: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/util/deferred_tensor.py#L81

If you print the "__bases__" of `d`'s __class__, you'll see the mixed in subclasses:

print(d.__class__.__bases__)
(<class 'tensorflow_probability.python.layers.internal.distribution_tensor_coercible._TensorCoercible'>, <class 'tensorflow_probability.python.distributions.normal.Normal'>)

**Comment by csuter** [comment]
I'm still not quite sure where/why it's getting converted to tensor. @brianwa84 would know more about the slicing internals.

**Comment by brianwa84** [comment]
Presumably it's because `__getitem__` is in tf.Tensor.OVERLODABLE_OPERATORS

**Comment by csuter** [comment]
Ah, right of course...

**Comment by brianwa84** [comment]
Going to close as working-as-intended.

**Comment by nbro** [comment]
@brianwa84 Why is this the intended behavior? Isn't this behaviour unintuitive?

**Comment by brianwa84** [comment]
Most centrally: because we can't have it both ways. If we 'fixed' this
issue, we could break this use-case:

tf.keras.Sequential([
  tf.keras.layers.Dense(12),
  tfp.layers.IndependentNormal(6),
  tf.keras.layers.Lambda(lambda x: x[:2])  # Or even a further
IndependentNormal(3), which will slice its input assuming it is Tensor-like.
])

In some sense, we already chose the acts-like-a-Tensor way for smoother
Keras integration.

Brian Patton | Software Engineer | bjp@google.com
