### ISSUE TITLE
error when import tensorflow_probability as tfp

### ISSUE THREAD

**Issue by amitca71** [tensorflow/probability#724]
I tried all combinations on  Google Colab
the only combination I found working was: 
pip install tensorflow==2.1.0
pip install tensorflow_probability==0.9.0

(https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Structural_Time_Series_Modeling_Case_Studies_Atmospheric_CO2_and_Electricity_Demand.ipynb#scrollTo=c5oL4Cc9lwHR)

same results on local environment (using CPU only)

**Comment by srvasude** [comment]
Hi, thanks for pointing this out! I'm going to close this in favor of #416 being a tracking bug for us updating our example code to TF2 / making it usable in a TF2 related world. I believe a lot of these colabs just used a fixed TF version, and we should actually let these install the latest nightlies. I'll try to follow up soon by removing the restrictions on these colabs.
