### ISSUE TITLE
Updating `TensorFlow_Probability_Case_Study_Covariance_Estimation` notebook for TF 2.0 -- Is it still critical?

### ISSUE THREAD

**Issue by 00krishna** [tensorflow/probability#729]
Hello Tensorflow Probability. 

I just had a question. I know that you all have been updating the notebooks to reflect Tensorflow 2.0, and that some key notebooks have already been updated. I noticed that the `Tensorflow Case Study Covariance Estimation` notebook had not been updated yet, even though it is the third notebook in the
Tensorflow Probability Guide. So I was trying to understand how important this notebook was in terms of how TF Probability works under TF 2.0?

In other words, my assumption is that you have probably updated the minimal critical set of notebooks to help users understand how TF Probability works under TF 2.0. For example, you have updated the `Linear Mixed Effects` notebook, already, as well as others. However, since the Covariance Estimation notebook is the 3rd one in the Guide, it seems like it would have been a critical notebook to update--but then again it might not be. 

The reason I was interested in the Covariance Estimation notebook is because it indicates some very specific numerical issues in how to handle say Cholesky decomposition of the precision matrix and how to best handle that in TF Probability. BUT, it might be that under the new Tensorflow Probability, these issues might be resolved; and if they are resolved, then this Covariance Estimation notebook is not so critical anymore. 

Haha, so a very complicated and convoluted issue, but hopefully you guys get what I am asking. Thanks.

**Comment by srvasude** [comment]
Hi,
  This notebook should have been upgraded in https://github.com/tensorflow/probability/commit/9af0aba1944787ee48f145d386dd348c67444df3.

**Comment by 00krishna** [comment]
@srvasude Okay interesting. So I noticed in other notebooks that were upgraded to TF2, the code was like:
```
#@title Install { display-mode: "form" }
TF_Installation = 'TF2 Nightly (GPU)' #@param ['TF2 Nightly (GPU)', 'TF2 Stable (GPU)', 'TF1 Nightly (GPU)', 'TF1 Stable (GPU)','System']

if TF_Installation == 'TF2 Nightly (GPU)':
  !pip install -q --upgrade tf-nightly-gpu-2.0-preview
  print('Installation of `tf-nightly-gpu-2.0-preview` complete.')
elif TF_Installation == 'TF2 Stable (GPU)':
  !pip install -q --upgrade tensorflow-gpu==2.0.0-alpha0
  print('Installation of `tensorflow-gpu==2.0.0-alpha0` complete.')
elif TF_Installation == 'TF1 Nightly (GPU)':
  !pip install -q --upgrade tf-nightly-gpu
  print('Installation of `tf-nightly-gpu` complete.')
elif TF_Installation == 'TF1 Stable (GPU)':
  !pip install -q --upgrade tensorflow-gpu
  print('Installation of `tensorflow-gpu` complete.')
elif TF_Installation == 'System':
  pass
else:
  raise ValueError('Selection Error: Please select a valid '
                   'installation option.')
```

But in the Covariance Estimation notebook the import code is:
```

import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()
import tensorflow_probability as tfp
```

So should I just assume that the Convariance Estimation notebook is using TF 2.0. I thought the `tensorflow.compat.v2` syntax was for TF 1.0? But please correct me if I am wrong. 

Thanks for getting back to me.

**Comment by srvasude** [comment]
The underlying code is TF2-based syntax. So this would work in TF2, and in later versions of TF1 since you can import compat.v2 in both cases. 

Regarding the import, I'll need to check if we should use these imports in all our colabs (the examples have inconsistent behavior here).

**Comment by 00krishna** [comment]
Excellent. That clarifies what I was confused about. Thanks for your help @srvasude .

**Comment by 00krishna** [comment]
This issue can be closed. It was resolved.
