### ISSUE TITLE
tfp.util.DeferredTensor should allow access to the value of the tensor through .numpy()

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#731]
Hey,

I think it'd be useful if `tfp.util.DeferredTensor` values could be accessed in the same way as the non-deferred variable values. For example, it would be useful if the following was possible:
```python
import tensorflow as tf
import tensorflow_probability as tfp


def main():
    x = tf.Variable(0.5)
    y = tfp.util.DeferredTensor(x, tf.exp)
    print(y.numpy())  # y.transform_fn(y.variables).numpy() works.


if __name__ == '__main__':
    main()
```

However, the example currently fails with `AttributeError: 'DeferredTensor' object has no attribute 'numpy'`.

Is this intentional and there's a fundamental reason for not allowing this for `DeferredTensor`s or is this a feature that could exist? I'd be happy to contribute a fix for this if needed.

**Comment by brianwa84** [comment]
This feature could exist, feel free to send a PR.

**Comment by csuter** [comment]
Thanks, @hartikainen! You can also do tf.convert_to_tensor(y).numpy() (in eager mode), though that's not much shorter than the commented code you wrote :).

Also, check out TransformedVariable for an example like the one you've written. It let's you simply write

```
y = tfp.util.TransformedVariable(np.exp(.5), tf.exp)
```

This class creates the tf.Variable in the backgroundm and support assignments, which "do the right thing" w.r.t. the transformation. Note that it's initialized with the *post-transform* value.
