### ISSUE TITLE
0.9 and 0.10 not support tf 2.0

### ISSUE THREAD

**Issue by moonman925** [tensorflow/probability#758]
so upcoming version of tfp will not support tf 2.0 no more ?

**Comment by mayou36** [comment]
Just wondering: where did you get this information from? Is there a comfortable way to stay up-to-date on this things?

**Comment by moonman925** [comment]
> Just wondering: where did you get this information from? Is there a comfortable way to stay up-to-date on this things?

from error

**Comment by mayou36** [comment]
Sorry, which error? Could you point me to it?

**Comment by moonman925** [comment]
in tf 2.0 and tfp>=0.9 case, import tensorflow then import tfp will throw such kind of error.

**Comment by mayou36** [comment]
Can you maybe post the error here? Doesn't it say that it needs 2.1 or higher?

as here: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/__init__.py#L56

**Comment by davmre** [comment]
TFP is developed against TF head; our current practice is that every time TF cuts a new release, we cut a new TFP release. So in general every TFP version is compatible with the most recent TF version at the time of its release: TFP 0.9 was released in sync with TF 2.1, and TFP 0.10 will (most likely) be released shortly after TF 2.2.

We don't in general have the resources to backport TFP to older TF versions, though of course we're happy to accept patches if there's an incompatibility that's easily fixable.

**Comment by brianwa84** [comment]
Also, we aim to keep `tfp-nightly` compatible with `tf-nightly` and `tf-nightly-cpu`.
