### ISSUE TITLE
are `tfb.Ordered.forward` and `tfb.Ordered.inverse` the wrong way round?

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#765]
Hi,

Please forgive me if I am being a bit slow with this.

The current behaviour is well documented in the library, but given the behaviour of other bijectors (e.g. `tfb.Exp().forward(x)` calculates `exp(x)`) I really expected `tfb.Ordered().forward(x)` to "order" x - but that is not the case. Is there a way of thinking that I am missing or is this inconsistent?

Currently (I think) this would mean to do e.g. MCMC with parameters that were constrained to be ordered we would need to use:

``` python
tfp.mcmc.TransformedTransitionKernel(..., bijector=[tfb.Invert(tfb.Ordered())])
```

Which is no big deal but feels odd to me...

This would be needed in https://github.com/tensorflow/probability/pull/753.

Thanks

**Comment by junpenglao** [comment]
I think that makes sense, also that tfb forward map something in an unconstrained space to a constrained space - I probably made a mistake coding up the Ordered transformation.

**Comment by jeffpollock9** [comment]
hi @junpenglao - thanks for getting back to me. Perhaps then it would be good to flip the functions around - I am happy to send you a PR if that would be useful? It is a breaking change for anyone already using the `Ordered` class though, so I am not sure the best way to deal with that.

**Comment by junpenglao** [comment]
Me neither in this case - @jburnim what is the best path for deprecation is this case?

**Comment by davmre** [comment]
My feeling is it's a bit sketchy to change the behavior of the class in-place, since not everyone checks deprecation warnings and swapping directions of a bijector could lead to silently incorrect results.

My suggestion would be to check in a new bijector under a different name (`Increasing`, `Sorted`, ...?), and add a deprecation notice to Ordered (and update the docstring) advising people to use the new thing. That way eventually deleting the existing `Ordered` bijector will at least raise a loud error for anyone still using it.

**Comment by SiegeLordEx** [comment]
+1 on Dave's comment. A variation of 'Increasing' or 'Ascending' is arguably a better name than 'Ordered' anyway. 'Sorted' is good too, as that typically implies the ascending order (cf Python, C++ etc).

**Comment by jeffpollock9** [comment]
also +1 that sounds like the right course here. FWIW, personally I prefer `Increasing` over `Sorted` - to me `Sorted` implies that the forward operation is doing some kind of sort, which is not really the case here.

**Comment by csuter** [comment]
New `Increasing` bijector and deprecating `Ordered` sgtm. Agree that `Sorted` implies something this is not.

**Comment by jeffpollock9** [comment]
Cool, feel free to assign this to me if you would like me to attempt to contribute it (I will probably have time in the next few weeks).

**Comment by st--** [comment]
+1, I'd love to see an `Ascending`/`Increasing` bijector - I just spotted an issue in a project that relied on an ordered parameter and we hadn't realised we needed to use Invert(Ordered()) to actually achieve that (until just now)! If you'd still be happy to review a corresponding PR, and @jeffpollock9 isn't keen on it anymore, I'd be happy to contribute the change.

**Comment by jeffpollock9** [comment]
Hi @st-- if you'd like to make the contribution then please go ahead, perhaps I could try to do an initial review if you would like.

**Comment by brianwa84** [comment]
Please send the PR, this sounds like a great fix!

**Comment by st--** [comment]
By the way, the docstring currently claims (see https://github.com/tensorflow/probability/blob/cfeae22d71766041d2b4108f5b7675e9e7175e34/tensorflow_probability/python/bijectors/ordered.py#L37) that mapping samples from a Normal(0, 1) distribution through the `Ordered` bijector results in ordered samples from a Normal(0, 1) distribution:
> The inverse of the bijector applied to a normal random vector `y ~ N(0, 1)`
  gives back a sorted random vector with the same distribution `x ~ N(0, 1)`
  where `x = sort(y)`
I don't know where this claim comes from. For sure, it does not hold out empirically:
```python
import tensorflow_probability as tfp
d = tfp.distributions.Normal(0.0, 1.0)
s = d.sample(100000)
o = tfp.bijectors.Ordered()
ss = o.inverse(s)
s.numpy().mean()  # ~ 0.0
s.numpy().std()  # ~ 1.0
ss.numpy().mean()  # ~ 8.3e4
ss.numpy().std()  # ~ 4.7e4
```
If I don't hear any objections, I'll simply remove that section of the docstring.

**Comment by brianwa84** [comment]
Looks like it originated here: https://github.com/tensorflow/tensorflow/pull/18647
 @junpenglao do you know about the N(0,1)->N(0,1) claim?
