### ISSUE TITLE
layers.VariationalGaussianProcess skips layer's 'name' property

### ISSUE THREAD

**Issue by alexander-e1off** [tensorflow/probability#769]
Hello,

it seems `layers.VariationalGaussianProcess` does not pass `name` property to the base class initializer.
It is accepted [here](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/layers/distribution_layer.py#L1814) but not passed to the base class initializer [here](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/layers/distribution_layer.py#L1854)

As a result layer's name remains default.

**Comment by brianwa84** [comment]
Sounds like an easy fix, feel free to send a PR.

**Comment by alexander-e1off** [comment]
Fixed in #772
