### ISSUE TITLE
 tfp.util.TransformedVariable should allow access to the value of the tensor through .numpy()

### ISSUE THREAD

**Issue by ottofabian** [tensorflow/probability#789]
Hi, 

currently the tfp.util.TransformedVariable does not allow to access the variable values by calling `numpy()`. 
Example: 

```python
import tensorflow as tf
import tensorflow_probability as tfp

def main():´
    init_cov = tf.eye(3)
    scale_tril = tfp.util.TransformedVariable(init_cov, bijector=tfp.bijectors.FillScaleTriL())
    print(scale_tril.numpy())

if __name__ == '__main__':
    main()
```
This is highly related to #731.

**Comment by brianwa84** [comment]
I just ran `tfp.util.TransformedVariable(10., tfb.Exp()).numpy()` against tfp-nightly and it worked.

**Comment by ltiao** [comment]
If you don't want to use the bleeding-edge version (i.e. `tfp-nightly`), you can also just call:
```
tf.convert_to_tensor(transformed_variable).numpy()
```
This will work with the 0.9.0 release.
