### ISSUE TITLE
`one_step` function does not run a full step of the NuTS!

### ISSUE THREAD

**Issue by MedAbdelkaderAbba** [tensorflow/probability#797]
I was experimenting with the NuTS method in tfp, and realised that the one_step function only runs one leapfrog step instead of a full iteration of NuTS. 
Is there a way to actually run a full iteration of the algorithm without calling mcmc.sample_shain ?

**Comment by junpenglao** [comment]
It does run a full iteration of NUTS - it will run k leapfrog until it hit a U-turn or a divergence. 
Most likely is that in your code the step size is too large, thus after from your chosen initial position after one leapfrog it got a divergence.

**Comment by MedAbdelkaderAbba** [comment]
Thanks for the helpful reply. I double checked and you are right.
