### ISSUE TITLE
Conditional Distribution as custom distribution

### ISSUE THREAD

**Issue by kasakh** [tensorflow/probability#802]
Hi, I am trying to figure out if there is a way to implement conditional distribution as user-defined distribution, once the joint distribution is known as `tfp.distribution`. Here is a small example (copied from the Gaussian Copula notebook) of what I am trying to do:

```
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()

import tensorflow_probability as tfp
tfd = tfp.distributions
tfb = tfp.bijectors

class GaussianCopulaTriL(tfd.TransformedDistribution):
  """Takes a location, and lower triangular matrix for the Cholesky factor."""
  def __init__(self, loc, scale_tril):
    super(GaussianCopulaTriL, self).__init__(
        distribution=tfd.MultivariateNormalTriL(
            loc=loc,
            scale_tril=scale_tril),
        bijector=tfb.NormalCDF(),
        validate_args=False,
        name="GaussianCopulaTriLUniform")
class WarpedGaussianCopula(tfd.TransformedDistribution):
  def __init__(self, loc, scale_tril, marginal_bijectors, block_sizes=None):
    super(WarpedGaussianCopula, self).__init__(
        distribution=GaussianCopulaTriL(loc=loc, scale_tril=scale_tril),
        bijector=tfb.Blockwise(bijectors=marginal_bijectors,
                               block_sizes=block_sizes),
        validate_args=False,
        name="GaussianCopula")
def create_gaussian_copula(correlation):
  # Use Gaussian Copula to add dependence.
  return WarpedGaussianCopula(
      loc=[0.,  0.],
      scale_tril=[[1., 0.], [correlation, tf.sqrt(1. - correlation ** 2)]],
      # These encode the marginals we want. In this case we want X_0 has
      # Kumaraswamy marginal, and X_1 has Gumbel marginal.

      marginal_bijectors=[
          tfb.Invert(tfb.KumaraswamyCDF(a, b)),
          tfb.Invert(tfb.GumbelCDF(loc=0., scale=1.))])
## The above code is copied from the Gaussian Copula notebook. 
```

I can run `copula = create_gaussian_copula(0.5)` to create a Gaussian copula joint distribution with a correlation 0.5 and use `copula.log_prob([2,1])` to find the log of the density function at the point `(2,1)`

However, this approach is a bit limiting. E.g. when I want to compute the MC expectation $E[X^2|Y = 1]$ under this copula joint distribution, I am stuck with the following code

```
## This code does not run
num_draws = int(1e5)
p = copula.prob([ , 1]) # not sure how to condition  
## Ideally, it should be a tensorflow distribution

squared expectation = tfp.monte_carlo.expectation(
    f=lambda x: x**2,
    samples=p.sample(num_draws, seed=42),
    log_prob=p.log_prob,
    use_reparameterization=(p.reparameterization_type
                           == tfp.distributions.FULLY_REPARAMETERIZED))

```
Once the joint distribution $P(X,Y)$ is stored as `tfp.distirbution`, I was wondering if there is a simple way to define the following $P(X|Y=y)$ , $P(X,Y=y)$, etc. as customized tfp.distributions so that we call `log_prob` and other functions. I am not sure if bijectors help here. Any working example is appreciated. 
Thanks in advance!

**Comment by srvasude** [comment]
Conditional distributions are supported in TFP! You can do this by providing kwargs to the corresponding methods. We do this in the Gaussian Process class for instance:
https://cs.opensource.google/tensorflow/probability/+/master:tensorflow_probability/python/distributions/gaussian_process.py;drc=5b3eae41363d5fc5ef6390a62c6f75f326372939;l=436

Given that for Gaussian Copulas, the conditionals are tractable, you could implement _log_prob(x, indices=None, values=None). This would specify what indices of variables you want to condition on and what values (and similarly for the .sample(...) method, etc.).

**Comment by srvasude** [comment]
Closing this as I believe the above answers the question. Feel free to reopen if this is not the case.
