### ISSUE TITLE
TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: float16, float32, float64, complex64, complex128

### ISSUE THREAD

**Issue by nbro** [tensorflow/probability#803]
The following program 

```
def example():
    import tensorflow as tf
    import tensorflow_probability as tfp
    from tensorflow_probability import distributions as tfd

    def get_model(input_shape=(1,)):
        inp = tf.keras.layers.Input(shape=input_shape)
        x = tfp.layers.DenseFlipout(8, activation="relu")(inp)
        x = tfp.layers.DenseFlipout(16, activation="relu")(x)
        logits = tfp.layers.DenseFlipout(1)(x)
        bernoulli = tfp.layers.DistributionLambda(lambda t: tfd.Bernoulli(logits=t))(logits)
        model = tf.keras.models.Model(inputs=inp, outputs=bernoulli)
        return model

    model = get_model()

    # Error is produced here, probably because of "mse", but the error message is quite mysterious.
    # If you comment this, you won't get an error.
    model.compile(loss="mse")

    # This does NOT produce any error.
    import numpy as np
    x = np.array([[1.0]])
    print(model(x))


if __name__ == '__main__':
    example()
```

produces a strange error message

> TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: float16, float32, float64, complex64, complex128

The problem is probably due to the usage of "mse" as the loss function. In any case, this error message is very cryptic, so I think this is an issue (i.e. the error message should at least be more descriptive of the actual problem).

I am using TF 2.1 and TFP 0.9.

**Comment by csuter** [comment]
Bernoulli produces int-valued samples by default. Try specifying `dtype=tf.float32` in the Bernoulli constructor.

**Comment by nbro** [comment]
@csuter Yes, that solves the problem. Actually, I didn't want to use the MSE loss function, but I thought this was a bug. Why wouldn't the MSE also expect integers?

**Comment by csuter** [comment]
Just guessing at the source of the error, mse needs to divide by the number of terms to compute the average, which will need to be a floating point computation. TF is generally strict about not promoting dtypes, so this yields an error.

I'll close this, but feel free to continue discussion or reopen if there are further issues.

**Comment by abbasabaei** [comment]
you can use this link:
https://stackoverflow.com/a/63300437/13181871

**Comment by pavanbodas** [comment]
> Just guessing at the source of the error, mse needs to divide by the number of terms to compute the average, which will need to be a floating point computation. TF is generally strict about not promoting dtypes, so this yields an error.
> 
> I'll close this, but feel free to continue discussion or reopen if there are further issues.

TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64, int32. 
can you solve this problem

**Comment by pavanbodas** [comment]
> @csuter Yes, that solves the problem. Actually, I didn't want to use the MSE loss function, but I thought this was a bug. Why wouldn't the MSE also expect integers, or what's exactly causing the issue then?

can you send me your code

**Comment by vaibhavshah1234** [comment]
TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64, int32.
can you solve this problem i am aso getting same error
please do solve it

**Comment by vaibhavshah1234** [comment]
https://colab.research.google.com/drive/1g_gYCQ3dMZx245Ks8LJOARkGqtrkO-ES?usp=sharing
Here is my code
