### ISSUE TITLE
Error occurs when import

### ISSUE THREAD

**Issue by kuanzi** [tensorflow/probability#83]
I cloned the repository and installed it according to the command "pip install --user --upgrade tfp-nightly-gpu # depends on tensorflow-gpu (GPU enabled)". But when I run a basic script, I get the following error:
Command:
`python tensorflow_probability/examples/logistic_regression.py`
Result:
`Traceback (most recent call last):
  File "tensorflow_probability/examples/logistic_regression.py", line 30, in <module>
    import tensorflow_probability as tfp
  File "/path/to/tf-probability/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/path/to/tf-probability/tensorflow_probability/python/__init__.py", line 21, in <module>
    from tensorflow_probability.python import distributions
  File "/path/to/tf-probability/tensorflow_probability/python/distributions/__init__.py", line 38, in <module>
    from tensorflow_probability.python.distributions.internal.distribution_util import fill_triangular_inverse
ImportError: cannot import name fill_triangular_inverse
`
It seems that there is no "fill_triangular_inverse" in the file
[probability/tensorflow_probability/python/distributions/internal/distribution_util.py](https://github.com/tensorflow/probability/blob/80366a51ae5fe7521f4697654e32a89ee76593d6/tensorflow_probability/python/distributions/internal/distribution_util.py)

Is this due to my operating mistakes? Or did you update your code recently?
I am looking forward to your reply, thank you very much!

**Comment by neighthan** [comment]
I just installed the nightly today (6/22) and I'm getting the same error.

**Comment by acriptis** [comment]
I have the same issue. Seems tere are only references for `fill_triangular_inverse`, but no declaration anywhere: https://github.com/tensorflow/probability/search?q=fill_triangular_inverse&unscoped_q=fill_triangular_inverse

**Comment by acriptis** [comment]
Finally, I've fixed this error by hacky trick in the code:
1. i've commented out the line:
https://github.com/tensorflow/probability/blob/67a55b2ef5e94da203991ed102c9e41d085a840a/tensorflow_probability/python/distributions/__init__.py#L78
(my code does not need this method)

2. then i've launched my script and catched another error for this import:
https://github.com/tensorflow/probability/blob/67a55b2ef5e94da203991ed102c9e41d085a840a/tensorflow_probability/python/layers/util.py#L26
So... I've tried to comment out that line in hope of having no dependencies for the commented import and ... magic have occured! It works somehow!

**Comment by srvasude** [comment]
I'm going to close this issue. From the looks of it, the underlying issue was that fill_triangular_inverse was implemented in TF, and the symbol was not exposed later (so using a later version of tensorflow works as well as tf-nightly). 

The recommended behavior is if using tfp-nightly, ensure that you are also using tf-nightly. Otherwise, for tfp version 0.3, ensure that tensorflow 1.10 is installed.

Please reopen if this is persistent
