### ISSUE TITLE
doc string error in weibull_cdf.py

### ISSUE THREAD

**Issue by bourov** [tensorflow/probability#834]
in class [tensorflow_probability/python/bijectors/weibull_cdf.py](https://github.com/tensorflow/probability/blob/425395da0472b91400655ba3aec8f69cf0249673/tensorflow_probability/python/bijectors/weibull_cdf.py)

doc text is
```python 
"""Compute `Y = g(X) = 1 - exp((-X / scale) ** concentration), X >= 0`.
```

while actual calculation is (note `(-x)**power` vs `-(x**power)`)
```python
  def _forward(self, x):
    with tf.control_dependencies(self._maybe_assert_valid_x(x)):
      return -tf.math.expm1(-((x / self.scale) ** self.concentration))
```

if no-one objects, I can try to fix the doc string in several places in `weibull_cdf.py `

**Comment by srvasude** [comment]
Hi, 
   Feel free to send a PR for this! Thanks for the catch!

**Comment by bourov** [comment]
> Hi,
> Feel free to send a PR for this! Thanks for the catch!

Will do!
