### ISSUE TITLE
Multiple chains in Edward2

### ISSUE THREAD

**Issue by davmre** [tensorflow/probability#85]
TFP's MCMC methods support multiple parallel chains, represented via batch dimensions in the arguments and return value of the `target_log_prob_fn`. But the functions built by Edward2's `make_log_joint_fn` don't support batch dimensions: they return only a scalar `tf.Tensor`. So it's not straightforward to run multiple inference chains on Edward models. 

A workaround is to create a wrapper function that unstacks its inputs along their batch dimension, calls `log_joint_fn` separately for each chain, and stacks the the resulting log probs, but this loses the potential benefits of vectorization within the log joint computation. It would be better to implement `log_joint_fn` so that batch dimensions are preserved throughout the computation.

**Comment by dustinvtran** [comment]
also related: https://github.com/tensorflow/probability/issues/26

Batching should definitely be thought about carefully. And it has high value.

**Comment by davmre** [comment]
Ah, thanks for the pointer! I'll close this issue for now since I agree a general-purpose solution for batch semantics is the right way to address this problem.
