### ISSUE TITLE
Problems with HMM inside tfd.JointDistributionCoroutine

### ISSUE THREAD

**Issue by Char-Aznable** [tensorflow/probability#853]
I want to define a Hidden Markov Model with 2 states and a NegativeBinomial emission of vector-of-two data (nDimData = 2):
```python
Root = tfd.JointDistributionCoroutine.Root
def HMMBeta(nStates, nSteps, nDimData):
    #Initial state distribution
    pInit = yield Root(
        tfd.Categorical(probs=np.ones(nStates)/nStates))
    #State transition distribution
    pSwitch = 0.05
    pt = pSwitch / (nStates-1) * np.ones(
        [nStates, nStates], dtype=np.float32)
    np.fill_diagonal(pt, 1-pSwitch)
    pTrans =  yield Root(tfd.Categorical(probs=pt))
    #emission distribution with Beta prior on the NB probability
    ppNB = yield Root(tfd.Independent(tfd.Beta(
        tf.ones((nStates, nDimData)) * 2,
        tf.ones((nStates, nDimData)) * 5), 2))
    pEmission = yield tfd.Independent(
        tfd.NegativeBinomial(1, probs=ppNB),
        reinterpreted_batch_ndims=2)
    hmm = yield tfd.HiddenMarkovModel(
        initial_distribution=pInit,
        transition_distribution=pTrans,
        observation_distribution=pEmission,
        num_steps=nSteps)
nStates = 2
concreteHMMBeta = functools.partial(HMMBeta,
    nStates=nStates, nSteps=data.shape[0],
    nDimData=data.shape[1])
model = tfd.JointDistributionCoroutine(concreteHMMBeta)
```
Running `model` gives the error:
```
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'event_shape'
```
What am I missing here?

**Comment by brianwa84** [comment]
tfd.HMM is expecting tfd.Distribution instances for the
initial_distribution,  transition_distribution, and
observation_distribution parameters, but the result stored in `somevar`
from the expression `somevar = yield Root(SomeDist(..)))` in JDCoroutine is
a *sample* from that distribution, not the distribution itself.

It seems like in this case you can just do `ppNB = yield ...; hmm = yield
HMM(initial_distribution=tfd.Categorical(probs=np.ones(nStates)/nStates),
transition_distribution=tfd.Categorical(probs=pt),
observation_distribution=tfd.Independent(tfd.NegativeBinomial(1,
probs=ppNB), reinterpreted_batch_ndims=2)))`

Brian Patton | Software Engineer | bjp@google.com

**Comment by Char-Aznable** [comment]
@brianwa84 That works! However, I am now hitting https://github.com/tensorflow/probability/issues/854 How do I represent the data dimension in HMM?

**Comment by brianwa84** [comment]
Resolving; note #854 is also resolved now.
