### ISSUE TITLE
HiddenMarkovModel of multiple sequences

### ISSUE THREAD

**Issue by Char-Aznable** [tensorflow/probability#854]
Say my observed `data` is (100, 2) with 100 steps and a vector-of-two observation each step. What is the best way to represent the vector-of-two observation? I am currently trying to represent it as event dimension in `tfp.distributions.HiddenMarkovModel` but that doesn't seem to work. Here is my code:
```python
# HMM parameters
nStates = 4
pInit = tfd.Categorical(probs=np.ones(nStates)/nStates)
pSwitch = 0.05
pt = pSwitch / (nStates-1) * np.ones(
    [nStates, nStates], dtype=np.float32)
np.fill_diagonal(pt, 1-pSwitch)
pTrans = tfd.Categorical(probs=pt)
# piror on the NB probability
priorPNB = tfd.Beta(2, 5)
pNB = tf.Variable(priorPNB.sample((nStates, data.shape[1])).numpy(), name='pNB')
pEmission = tfd.Independent(tfd.NegativeBinomial(1, probs=pNB), reinterpreted_batch_ndims=1)
hmm = tfd.HiddenMarkovModel(
    initial_distribution=pInit,
    transition_distribution=pTrans,
    observation_distribution=pEmission,
    num_steps=data.shape[0])

```
Running `hmm.log_prob(data)` gives the error:
```
InvalidArgumentError: Incompatible shapes: [100,2,1] vs. [4,2] [Op:Mul] name: HiddenMarkovModel/log_prob/IndependentNegativeBinomial/log_prob/NegativeBinomial/log_prob/mul/
```

**Comment by jfrancis71** [comment]
I think I have run into the same issue:

I have an example model with 2 hidden states, and at each time step the observation output is a vector
of 5 Bernoulli variables, and I am assuming that the observation sequence length is 3.

    initial_distribution = tfd.Categorical(probs=[0.8, 0.2])
    transition_distribution = tfd.Categorical(probs=[[0.7, 0.3],
                                                 [0.2, 0.8]])
    observation_distribution =\
        tfd.Independent(
            tfd.Bernoulli(logits=0.5*np.ones( [2,5] ) ),
            reinterpreted_batch_ndims=1)
    model = tfd.HiddenMarkovModel(
        initial_distribution=initial_distribution,
        transition_distribution=transition_distribution,
        observation_distribution=observation_distribution,
        num_steps=3)
    model.log_prob( np.ones( shape = [ 3, 5 ] ) )

The above (log_prob) fails with

     InvalidArgumentError:  Incompatible shapes: [3,5,1] vs. [2,5] [Op:Mul] name: HiddenMarkovModel/log_prob/IndependentBernoulli/log_prob/Bernoulli/log_prob/mul/

**Comment by brianwa84** [comment]
I agree this looks like a bug. Does sampling work as you expect? Only
log_prob is an issue?

Brian Patton | Software Engineer | bjp@google.com
