### ISSUE TITLE
installation errors in anaconda

### ISSUE THREAD

**Issue by kmario23** [tensorflow/probability#86]
I'm trying to install `tfp-nightly-gpu` but it fails with this message:

```
$ pip install --user --upgrade tfp-nightly-gpu
Collecting tfp-nightly-gpu
Requirement not upgraded as not directly required: six>=1.10.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tfp-nightly-gpu) (1.11.0)
Requirement not upgraded as not directly required: tf-nightly in /home/mario/.local/lib/python3.6/site-packages (from tfp-nightly-gpu) (1.10.0.dev20180622)
Requirement not upgraded as not directly required: numpy>=1.11.1 in /home/mario/anaconda3/lib/python3.6/site-packages (from tfp-nightly-gpu) (1.14.5)
Requirement not upgraded as not directly required: gast>=0.2.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (0.2.0)
Requirement not upgraded as not directly required: setuptools<=39.1.0 in /home/mario/.local/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (39.1.0)
Requirement not upgraded as not directly required: protobuf>=3.4.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (3.5.2)
Requirement not upgraded as not directly required: wheel>=0.26 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (0.31.1)
Requirement not upgraded as not directly required: grpcio>=1.8.6 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (1.12.1)
Requirement not upgraded as not directly required: astor>=0.6.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (0.6.2)
Requirement not upgraded as not directly required: termcolor>=1.1.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (1.1.0)
Requirement not upgraded as not directly required: absl-py>=0.1.6 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (0.2.2)
Requirement not upgraded as not directly required: tb-nightly<1.11.0a0,>=1.10.0a0 in /home/mario/.local/lib/python3.6/site-packages (from tf-nightly->tfp-nightly-gpu) (1.10.0a20180622)
Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /home/mario/anaconda3/lib/python3.6/site-packages (from tb-nightly<1.11.0a0,>=1.10.0a0->tf-nightly->tfp-nightly-gpu) (0.14.1)
Requirement not upgraded as not directly required: markdown>=2.6.8 in /home/mario/anaconda3/lib/python3.6/site-packages (from tb-nightly<1.11.0a0,>=1.10.0a0->tf-nightly->tfp-nightly-gpu) (2.6.11)
Installing collected packages: tfp-nightly-gpu
Exception:
Traceback (most recent call last):
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/wheel.py", line 323, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tfp-nightly-gpu .dist-info directory not found

```

Any help regarding how to fix this?

**Comment by csuter** [comment]
Hi Mario, I just successfully installed tfp-nightly-gpu in a clean, empty virtualenv, so I think the package is fine.

One possible issue is that it looks like you have tf-nightly, not tf-nightly-gpu. You might try uninstalling tf-nightly and then installing tf-nightly-gpu. However, I'm not familiar with anaconda so I'm not sure the appropriate commands to run.

**Comment by kmario23** [comment]
Hi Christopher, thanks for your response! I'm trying to install this in my base conda environment, where I also have my `tensorflow-gpu` installed. The issue is same as the one raised in #80 

I also tried uninstalling `tf-nightly` by `pip uninstall tf-nightly` and then installed `tf-nightly-gpu` but with no luck.

**Comment by acriptis** [comment]
@kmario23 have you tried something like this:
```pip install tf-nightly-gpu --upgrade --no-cache-dir --isolated```
?
it helped me to resolve the similar issue with tensorflow_probability

**Comment by kmario23** [comment]
Hi @acriptis , I tried your suggestion and now I get a different error:

```
❯ pip install tf-nightly-gpu --upgrade --no-cache-dir --isolated
Collecting tf-nightly-gpu
  Downloading https://files.pythonhosted.org/packages/f5/88/33ad2509cdf68185db7ef2702ef848fe2b0a8ed5523f9404fc411e7cebbb/tf_nightly_gpu-1.10.0.dev20180620-cp36-cp36m-manylinux1_x86_64.whl (226.6MB)
    100% |████████████████████████████████| 226.7MB 27.2MB/s 
Requirement not upgraded as not directly required: setuptools<=39.1.0 in /home/mario/.local/lib/python3.6/site-packages (from tf-nightly-gpu) (39.1.0)
Requirement not upgraded as not directly required: protobuf>=3.4.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (3.5.2)
Requirement not upgraded as not directly required: grpcio>=1.8.6 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.12.1)
Requirement not upgraded as not directly required: wheel>=0.26 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.31.1)
Requirement not upgraded as not directly required: numpy>=1.13.3 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.14.5)
Requirement not upgraded as not directly required: gast>=0.2.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.2.0)
Requirement not upgraded as not directly required: six>=1.10.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.11.0)
Requirement not upgraded as not directly required: absl-py>=0.1.6 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.2.2)
Requirement not upgraded as not directly required: astor>=0.6.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.6.2)
Collecting tb-nightly<1.11.0a0,>=1.10.0a0 (from tf-nightly-gpu)
  Downloading https://files.pythonhosted.org/packages/5d/dc/15e0a2e37daaf969c45e3e7e9201876b77edffecf613e7d1961a1757c126/tb_nightly-1.10.0a20180622-py3-none-any.whl (3.3MB)
    100% |████████████████████████████████| 3.3MB 30.9MB/s 
Requirement not upgraded as not directly required: termcolor>=1.1.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.1.0)
Requirement not upgraded as not directly required: markdown>=2.6.8 in /home/mario/anaconda3/lib/python3.6/site-packages (from tb-nightly<1.11.0a0,>=1.10.0a0->tf-nightly-gpu) (2.6.11)
Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /home/mario/anaconda3/lib/python3.6/site-packages (from tb-nightly<1.11.0a0,>=1.10.0a0->tf-nightly-gpu) (0.14.1)
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/mario/.local/lib/python3.6/site-packages/tfp_nightly-0.1.0rc1.dev20180623.dist-info/METADATA'

```

Any suggestions to fix this?

**Comment by kmario23** [comment]
I managed to fix this issue by removing the offending directory and the did a fresh install.

```
$ cd /home/mario/.local/lib/python3.6/site-packages/
$ rm -rf tfp_nightly-0.1.0rc1.dev20180623.dist-info
$ pip install tf-nightly-gpu --upgrade --no-cache-dir --isolated
```

The above steps fixes the issue.

-------------

However, still I cannot install `tfp-nightly-gpu` because it fails with the issue:

```
Installing collected packages: tfp-nightly-gpu
Exception:
Traceback (most recent call last):
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/mario/anaconda3/lib/python3.6/site-packages/pip/_internal/wheel.py", line 323, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tfp-nightly-gpu .dist-info directory not found

```

Any suggestions to fix this, please?

**Comment by csuter** [comment]
Hi, apologies for the confusion here. We have not been uploading python3-compatible packages to PyPI in the nightly releases. We will work to fix this quickly. Sorry for the confusion and inconvenience!

**Comment by srvasude** [comment]
@cgs I believe this is fixed since you added wheel file generation for python3. Closing, but please re-open if this is an issue.

**Comment by sudarshanpsl** [comment]
$ pip install tf-nightly
Collecting tf-nightly
  Could not find a version that satisfies the requirement tf-nightly (from versions: )
No matching distribution found for tf-nightly
$ pip install tf-nightly-gpu
Collecting tf-nightly-gpu
  Could not find a version that satisfies the requirement tf-nightly-gpu (from versions: )
No matching distribution found for tf-nightly-gpu
$

**Comment by huainanhaoyuelengqianshan** [comment]
> Hi @acriptis , I tried your suggestion and now I get a different error:
> 
> ```
> ❯ pip install tf-nightly-gpu --upgrade --no-cache-dir --isolated
> Collecting tf-nightly-gpu
>   Downloading https://files.pythonhosted.org/packages/f5/88/33ad2509cdf68185db7ef2702ef848fe2b0a8ed5523f9404fc411e7cebbb/tf_nightly_gpu-1.10.0.dev20180620-cp36-cp36m-manylinux1_x86_64.whl (226.6MB)
>     100% |████████████████████████████████| 226.7MB 27.2MB/s 
> Requirement not upgraded as not directly required: setuptools<=39.1.0 in /home/mario/.local/lib/python3.6/site-packages (from tf-nightly-gpu) (39.1.0)
> Requirement not upgraded as not directly required: protobuf>=3.4.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (3.5.2)
> Requirement not upgraded as not directly required: grpcio>=1.8.6 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.12.1)
> Requirement not upgraded as not directly required: wheel>=0.26 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.31.1)
> Requirement not upgraded as not directly required: numpy>=1.13.3 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.14.5)
> Requirement not upgraded as not directly required: gast>=0.2.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.2.0)
> Requirement not upgraded as not directly required: six>=1.10.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.11.0)
> Requirement not upgraded as not directly required: absl-py>=0.1.6 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.2.2)
> Requirement not upgraded as not directly required: astor>=0.6.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (0.6.2)
> Collecting tb-nightly<1.11.0a0,>=1.10.0a0 (from tf-nightly-gpu)
>   Downloading https://files.pythonhosted.org/packages/5d/dc/15e0a2e37daaf969c45e3e7e9201876b77edffecf613e7d1961a1757c126/tb_nightly-1.10.0a20180622-py3-none-any.whl (3.3MB)
>     100% |████████████████████████████████| 3.3MB 30.9MB/s 
> Requirement not upgraded as not directly required: termcolor>=1.1.0 in /home/mario/anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu) (1.1.0)
> Requirement not upgraded as not directly required: markdown>=2.6.8 in /home/mario/anaconda3/lib/python3.6/site-packages (from tb-nightly<1.11.0a0,>=1.10.0a0->tf-nightly-gpu) (2.6.11)
> Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /home/mario/anaconda3/lib/python3.6/site-packages (from tb-nightly<1.11.0a0,>=1.10.0a0->tf-nightly-gpu) (0.14.1)
> Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/mario/.local/lib/python3.6/site-packages/tfp_nightly-0.1.0rc1.dev20180623.dist-info/METADATA'
> ```
> Any suggestions to fix this?

The same to you.And I don't know how to fix.
