### ISSUE TITLE
Cannot import TensorFlow Probability

### ISSUE THREAD

**Issue by AarshApple** [tensorflow/probability#860]
I am a beginner with using Tensorflow and tried to use the TensorFlow probability for Hidden Markov Model. I was getting some incompatibility error after googling it and implementing all possible solutions from StackOverflow. It seemed to work. But now I have a new error

`ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' (/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/core/__init__.py)
`

Can anyone please help me 

Tensorflow versions:

tb-nightly: 2.3.0a20200401     
tblib: 1.4.0              
tensorboard: 2.1.1              
tensorboard-plugin-wit: 1.6.0.post2        
tensorflow: 2.1.0              
tensorflow-estimator: 2.1.0              
tensorflow-probability: 0.9.0              
tf-estimator-nightly: 2.3.0.dev2020040101
tf-nightly: 2.2.0.dev20200401  
tfp-nightly: 0.10.0.dev20200401

**Comment by csuter** [comment]
Looks like you have a combination of stable and nightly versions of TF and TFP side by side. Depending on the order in which these were all installed, your code might be reading an incompatible combination. You should make sure you only have stable versions TF and TFP (pip packages `tensorflow` and `tensorflow-probability`) or nightlies (`tf-nightly`, `tfp-nightly`), but not both.

**Comment by sahil161** [comment]
any solution to the issue mentioned above?

**Comment by ColCarroll** [comment]
You would probably want to recreate your virtual environment and install **only** `tensorflow` and `tensorflow-probability` **or** `tf-nightly` and `tfp-nightly` (depending on if you value stability or latest features, respectively).

You could try to "fix" an existing environment by `pip uninstall tensorflow tensorflow-probability tf-nightly tfp-nightly`, and then `pip install tf-nightly tfp-nightly` (assuming you want nightly installs).
