### ISSUE TITLE
None gradient in ODE solve when combining initial state and ode_fn parameters

### ISSUE THREAD

**Issue by mrksr** [tensorflow/probability#866]
# Combining gradients yields `None`
Usually, `Solver.solve` yields gradients just fine, both for `DormandPrince` and `BDF` implementations. Gradients can be evaluated both for `initial_state` and `ode_fn`-parameters. However, when combining those gradients, `ode_fn` parameter gradients evaluate to `None`.

# Example
This code has been run with `tensorflow==2.2.0-rc2` and `tfp-nightly==0.10.0.dev20200408`.
```python
import tensorflow as tf
import tensorflow_probability as tfp

scalar = tf.constant(2.)
initial_state = tf.constant(1.)

def ode_fn(time, state):
    return scalar

# Same for BDF
solver = tfp.math.ode.DormandPrince()

with tf.GradientTape() as tape:
    tape.watch([scalar, initial_state])
    result = solver.solve(
        ode_fn=ode_fn,
        initial_time=0.,
        initial_state=initial_state,
        solution_times=[1.],
    )
    
tape.gradient(result.states, [scalar, initial_state])
# [None, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>]
```
The gradient with respect to `scalar` should not be `None`.

# Things that work
We can evaluate gradients separately.
```python
with tf.GradientTape() as tape:
    tape.watch(scalar)
    result = solver.solve(
        ode_fn=ode_fn,
        initial_time=0.,
        initial_state=initial_state,
        solution_times=[1.],
    )
    
tape.gradient(result.states, scalar)
# <tf.Tensor: shape=(), dtype=float32, numpy=0.9999995>
```
```python
with tf.GradientTape() as tape:
    tape.watch(initial_state)
    result = solver.solve(
        ode_fn=ode_fn,
        initial_time=0.,
        initial_state=initial_state,
        solution_times=[1.],
    )
    
tape.gradient(result.states, initial_state)
# <tf.Tensor: shape=(), dtype=float32, numpy=1.0>
```
We can also evaluate gradients "separately jointly" using two tapes.
```python
with tf.GradientTape() as tape:
    tape.watch(scalar)
    with tf.GradientTape() as tape_2:
        tape_2.watch(initial_state)
        result = solver.solve(
            ode_fn=ode_fn,
            initial_time=0.,
            initial_state=initial_state,
            solution_times=[1.],
        )
    
[
    tape.gradient(result.states, scalar),
    tape_2.gradient(result.states, initial_state)
]
# [<tf.Tensor: shape=(), dtype=float32, numpy=0.9999995>,
#  <tf.Tensor: shape=(), dtype=float32, numpy=1.0>]
```

# Reason
My best guess is that the `tf.custom_gradient` implementation of the ODE solver gives rise to this behaviour: 
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/math/ode/base.py#L218

This code has been touched recently and the docs read like this should work: `"""Restricts gradient to initial state components and constants."""`. Am I doing something wrong?

**Comment by junpenglao** [comment]
@SiegeLordEx recently fixed it, you should define your ode function with additional kwargs that you need gradients, and pass those kwargs as a dictionary to `constants`. Your example will be translate into something like:

```python
import tensorflow as tf
import tensorflow_probability as tfp

scalar = tf.constant(2.)
initial_state = tf.constant(1.)

def ode_fn(time, state, scalar):
    return scalar

# Same for BDF
solver = tfp.math.ode.DormandPrince()

with tf.GradientTape() as tape:
    tape.watch([scalar, initial_state])
    result = solver.solve(
        ode_fn=ode_fn,
        initial_time=0.,
        initial_state=initial_state,
        solution_times=[1.],
        constants={'scalar': scalar}
    )
    
tape.gradient(result.states, [scalar, initial_state])
```

**Comment by mrksr** [comment]
Indeed, your proposed solution works, thank you :).
Thanks @SiegeLordEx for the fix!

**Comment by morgatron** [comment]
In the docs for [Solver](https://www.tensorflow.org/probability/api_docs/python/tfp/math/ode/Solver) that there are two options noted to get gradients for values closed over by the propagated function:

> There are two options to get the gradients flowing through these values:
> 1. Use tf.Variable for these values.
> 2. Pass the values in explicitly using the constants argument:

Please forgive me for showing how new I am to tensorflow, but is it possible to get an example or brief explanation for using tf.Variables?  

Number 2, as described above does work, but it seems very clunky for my purposes. Thanks for any help you can give. Happy to provide details if that'll help

**Comment by SiegeLordEx** [comment]
There's an example of case 1 in the tests: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/math/ode/ode_test.py#L521-L548.

**Comment by morgatron** [comment]
Great, I'll take a look...

...and course, now that I've seen that I feel a little silly and it is
probably quite obvious to most folks without the example.. You pretty much
just use variables. for those parameters. Not sure why I failed on my first
attempts.

In any case, thanks Pavel for taking the time to reply.
