### ISSUE TITLE
tfd.Multinomial.log_prob returns nan if an entry of probs is 0

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/probability#867]
## Minimal working example (tfp-nightly 2020-03-29):
```python
import tensorflow_probability as tfp
tfd = tfp.distributions

rv = tfd.Multinomial(1000, probs=[0.7, 0.0, 0.3])
x = [489, 0, 511]
logp = rv.logp(x)
```
__Expected result__: `logp` is  `0.01980746`
__Actual result__: `logp`  is `nan`

## Suspected cause
The implementation of `tfp.Multinomial.log_prob` calculates 
$$\log \pi(x, p) \propto x_1 \log p_1 + ... + x_m \log p_m$$
It needs to trap conditions where $x_i = 0$ and $p_i = 0$ such that $x_i \log (p_i)$ returns 0 rather than `nan`.

**Comment by csuter** [comment]
@axch I think [tf.math.multiply_no_nan](https://www.tensorflow.org/api_docs/python/tf/math/multiply_no_nan) should do the trick here?

**Comment by axch** [comment]
@csuter Yep.  Doing that.

@chrism0dwk Are you sure about your expected result?  The log prob ought to be negative for this discrete distribution, and I'm pretty consistently getting logp ~= -100.4.

**Comment by chrism0dwk** [comment]
@axch my bad, indeed should be -100.4.
