### ISSUE TITLE
TruncatedNormal mean() returns inf

### ISSUE THREAD

**Issue by hardianlawi** [tensorflow/probability#871]
Hi,

For some reason, running the code below gives me `inf`.

```
import tensorflow_probability as tfp
tfd = tfp.distributions
tfd.TruncatedNormal(-2.8216267, 0.6991148, 1.0, 4.0).mean()
```

I would expect the answer to be close to 1.12 which I got by taking the average of `sample`.

**Comment by ColCarroll** [comment]
Hi! I can't reproduce this running on `tfp-nightly`: are you on an older version? Also, looks like your empirical mean was a pretty good estimate!

![image](https://user-images.githubusercontent.com/2295568/79154049-e941df80-7d9c-11ea-985c-5d4bb960c6fa.png)

**Comment by hardianlawi** [comment]
Thank you for your reply and indeed upgrading it does work for me! My bad, I should have tried that before posting here. I was using version `0.8.0rc` and I think I upgraded not too long ago.

But anyway, thanks!
