### ISSUE TITLE
Generalized extreme value distribution

### ISSUE THREAD

**Issue by jedisom** [tensorflow/probability#874]
I see that the Gumbel distribution has been created based on this link: https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Gumbel
This is the xi =0 case per https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution

I would like to use a more generalized version of the extreme value distrubutions allowing xi to be non-zero; Gumbel xi =0, Frechet xi > 0, and/or Weibull xi < 0.

**Comment by brianwa84** [comment]
Does the FrechetCDF bijector help here?
tfb.Invert(tfb.FrechetCDF(...))(tfd.Uniform(0,1))

**Comment by jedisom** [comment]
@brianwa84, That appears to be a way to get a random variable from a Frechet distribution.  The application I'm looking for is implementing these distributions within a Neural Network output layer allowing the network to learn the location, scale _AND_ shape parameters.  Something like:

`tfp.layers.DistributionLambda(lambda t: tfd.GeneralizedExtremeDistribution(loc=t[..., 0], scale=tf.nn.softplus(t[..., 1]), shape=t[..., 2]))`

The above obviously doesn't exist yet, but there might be a clever way to create the same effect with bijectors as you've suggested in your response above.

**Comment by srvasude** [comment]
There might be a way of chaining a `PowerTransform` bijector here, since essentially the difference between GEV and Gumbel is replacing the exponential in the exponent with a power transform.

Probably something like this would work (the forward of this would give you the CDF of a GEV):
`Exp(Reciprocal(PowerTransform(power=xi)(Scale(1/sigma)(Shift(-mu)))))`
but I'd probably recommend implementing from scratch (since I think the numerics of the above might not be so great). Contributions welcome here.

**Comment by jedisom** [comment]
I may take a stab at building the GeneralizedExtremeValue distribution class.  This would be my first contribution to the repo.  My initial thought was that I should be able to use the Gumbel class as a template and then just augment it with the shape/concentration parameter the generalized version needs, and then re-use the existing gumbel, frechet and weibull bijectors.  Thoughts or feedback on this approach?

**Comment by blacksde** [comment]
Hi @srvasude @brianwa84 @jedisom I am raising a pr of Generalized extreme value distribution cdf bijector. It could be a partial solution of this issue. A future gev distribution could be added based on this. Could you help review the code?

**Comment by jedisom** [comment]
@blacksde, thanks for offering to help out.  I'd love to help review your PR when it's ready.  That would definitely make the class PR simpler to implement.

**Comment by blacksde** [comment]
Hi @jedisom , I am starting writing the gev distribution based on the gev cdf from my pr #901 . Here is the code: https://github.com/blacksde/probability/blob/8ba1d6f60f3c68b859b3411f3989942c01143dea/tensorflow_probability/python/distributions/gev.py

Let me know whether you have any comments or you need some more features to be added in this distribution.

**Comment by hudson-ai** [comment]
@blacksde are you planning on opening a PR to resolve this issue?

**Comment by blacksde** [comment]
> @blacksde are you planning on opening a PR to resolve this issue?
> 
> Thanks for your great work!

Hi @hudson-ai I prepared my code but didn't have time to fix some minor issues and raise pr in the last few months. I think I can find some time this week to raise a pr.
