### ISSUE TITLE
Sample hidden states in HiddenMarkovModel

### ISSUE THREAD

**Issue by lucianopaz** [tensorflow/probability#876]
This is more a question than an issue so feel free to close this and tell me if there is a more appropriate place to ask tfp questions.

I am interested in sampling the hidden states of a `HiddenMarkovModel` conditioned on some observed emissions. From what I've been reading, I need to use some kind of particle filter algorithm to get samples from the posterior probability distribution of hidden states given the observations. However, it looks like the `HiddenMarkovModel` is not the right entity to work with because there doesn't seem to be a way to tap into the hidden state values. Am I forced to write a new distribution class or use a `JointDistribution` with `tf.scan` and some `Categorical` distributions that represent the hidden and observed states explicitly?

**Comment by ColCarroll** [comment]
Hey Luciano! The [example in the particle_filter](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/experimental/mcmc/particle_filter.py#L324) is pretty helpful in terms of organizing code. Here's a slightly modified example (I used a deterministic position as a function of velocity). Let me know if this is helpful!

```python
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd

import matplotlib.pyplot as plt

initial_state_prior = tfd.JointDistributionNamed({
    'position': tfd.Normal(loc=0., scale=1.),
    'velocity': tfd.Normal(loc=0., scale=0.1)})


def transition_fn(_, previous_state):
  return tfd.JointDistributionNamed({
      'position': tfd.Deterministic(previous_state['position'] + 
                                    previous_state['velocity']),
      'velocity': tfd.Normal(loc=previous_state['velocity'], scale=0.01)})


def observation_fn(_, state):
  return tfd.Normal(loc=state['position'], scale=0.1)

# Simulate data
true_positions = tf.linspace(0.4, 0.8, 40)
observed_positions = tfd.Normal(loc=true_positions,
                                scale=0.1).sample()

# Run particle filtering to sample plausible trajectories.
trajectories, lps = tfp.experimental.mcmc.infer_trajectories(
          observations=observed_positions,
          initial_state_prior=initial_state_prior,
          transition_fn=transition_fn,
          observation_fn=observation_fn,
          num_particles=1000)
```

These can be plotted as so:

```python
plt.plot(trajectories['position'][:, ::20], 'k-', alpha=0.1)
plt.plot(observed_positions,'o')
plt.plot(true_positions, '-');
```

![image](https://user-images.githubusercontent.com/2295568/79391484-a8ce9700-7f3f-11ea-879a-bf59953dee54.png)

**Comment by lucianopaz** [comment]
Thanks Colin! This is great! It seems that I was looking at an older commit of tfp experimental and didn't see `infer_trajectories`. With your example, I can modify the transition and observation functions to match my use case (both are `Categorical`) and get the estimate of the hidden states path. From a first glimpse it looks like I'll have to use the raw `particle_filter` to also assess the path degeneracy.

**Comment by lucianopaz** [comment]
@ColCarroll, just to be clear, was I right in thinking that I couldn't get a trajectory estimate from the `HiddenMarkovModel` distribution? In a sense, is it like the `Mixture` distribution, where the component membership is marginalized out of the model? I imagine this is desired because it helps sampling from the the prior, transition and emission probability distribution parameters, right?

**Comment by davmre** [comment]
You can get some picture of latent trajectories from the
`HiddenMarkovModel` distribution using the `posterior_marginals` and
`posterior_mode` methods, which return the distributions over latent states
at each step, and the highest-probability latent trajectory, respectively.

An analogous `posterior_sample` method to return exact samples of latent
trajectories is technically feasible using similar dynamic programming
algorithms (you'd do the same forward filtering pass as
`posterior_marginals`, then draw the samples on the backwards pass), but
it's not currently implemented. We'd of course happily accept a PR. :-)

Dave

**Comment by lucianopaz** [comment]
Thanks @davmre, i had seen the `posterior_marginals`, but I wanted sample paths in the hidden space. The marginals didn't hold the information of the path that lead to each state at a given step. The `posterior_mode` does work well but I wanted to try to quantify the uncertainty in the predicted path.
I liked your idea on `posterior_sample` using the backward pass. I may try to implement it and, if I do, I'll send a PR.
