### ISSUE TITLE
Nesting JointDistribution objects

### ISSUE THREAD

**Issue by OliverCobb** [tensorflow/probability#880]
I am trying to create a model defined as a sequence of nested ```JointDistributionSequential``` objects. The "Composition of Joint Distributions" in the recent "Joint Distributions for TensorFlow Probability" whitepaper (arxiv.org/pdf/2001.11819.pdf) suggests this should be possible. However I believe there might be bug preventing such an implementation.

Suppose I define low level models for variables ```y_1``` and ```y_2```:

```python
import tensorflow_probability as tfp
tfd = tfp.distributions

y_1_model = tfd.JointDistributionSequential(
    [
        tfd.Normal(0, 1, name='x_1'),
        lambda x_1: tfd.Normal(x_1, 1, name='y_1')
    ]
)
y_2_model = tfd.JointDistributionSequential(
    [
        tfd.Normal(0, 1, name='x_2'),
        lambda x_2: tfd.Normal(x_2, 1, name='y_2')
    ], 
)
```

I then try to define a model for a new variable ```z``` which is probabilistically related to the model for ```y_1``` and ```y_2``` as:

```python

z_model = tfd.JointDistributionSequential(
    [
        y_1_model,
        y_2_model,
        lambda y_2, y_1: tfd.Normal(y_1[1]-y_2[1], 1, name='z')
    ]
)
```

This works to some extent in that ```z_model.sample()``` returns a nested list of tensors of the expected structure. However there are problems with ```z_model```. For example ```print(z_model)``` returns the following error:
```
*** TypeError: 'generator' object does not support item assignment
```

However the real problem is that the variables within ```z_model``` can't seem to be referenced when defining further models. Whereas ```z_model.sample()[0][0]``` returns samples from ```x_1``` as expected, we can't reference ```x_1``` in the same way in the following:

```python
further_model = tfd.JointDistributionSequential(
    [
        z_model,
        lambda z: z[0][0]
    ]
)
```
The resultant ```further_model``` is not an object we can sample, or do anything with, as far as I can tell. If we try to sample it we get:

```
*** AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'sample'
```

**Comment by junpenglao** [comment]
I think the lambda function in JointDistributionSequential need to return a distribution, this seems to work:

```
further_model = tfd.JointDistributionSequential(
    [
        z_model,
        lambda z: tfd.Normal(z[0][0], .0001)
    ]
)
```

**Comment by OliverCobb** [comment]
Defining ```z_model``` in that way indeed results in an object we can sample - thanks @junpenglao!

However there still appears to be issues concerning a loss of functionality with each subsequent call to JDSequential. For example ```print(y_1_model)``` is fine but ```print(z_model)``` is not and ```z_model.sample_distributions()``` is fine but ```further_model.sample_distributions()``` is not.

**Comment by junpenglao** [comment]
yeah I dont think all method are well tested for nested, although `further_model.sample_distributions()` seems to work?
You can also try `JointDistributionCoroutine`, the yield method might be more robust for nested. For example, the model above would be translate to:
```python
root = tfd.JointDistributionCoroutine.Root
def y_1_model():
  x_1 = yield root(tfd.Normal(0, 1, name='x_1'))
  y_1 = yield tfd.Normal(x_1, 1, name='y_1')

def y_2_model():
  x_2 = yield root(tfd.Normal(0, 1, name='x_2'))
  y_2 = yield tfd.Normal(x_2, 1, name='y_2')

y_1_jd = tfd.JointDistributionCoroutine(y_1_model)
y_2_jd = tfd.JointDistributionCoroutine(y_2_model)
print(y_1_jd)
print(y_2_jd)

def z_model():
  y_1 = yield root(y_1_jd)
  y_2 = yield root(y_2_jd)
  z = yield tfd.Normal(y_1[1] - y_2[1], 1, name='z')

z_jd = tfd.JointDistributionCoroutine(z_model)
z_jd.sample()
print(z_jd)

def further_model():
  z = yield root(z_jd)
  final = yield tfd.Normal(z[0][0], .0001)

final_jd = tfd.JointDistributionCoroutine(further_model)
final_jd.sample()
```

**Comment by OliverCobb** [comment]
Thanks @junpenglao that's really useful. I'll look further into the coroutine approach.

(I checked again and ```further_model.sample_distributions()``` doesn't work for me although I don't think that it's particularly problematic in the scheme of things).
