### ISSUE TITLE
Beta distribution non-nan gradient for undefined `log_prob` input.

### ISSUE THREAD

**Issue by rwolst** [tensorflow/probability#884]
The Beta distribution is defined on the interval `x in [0, 1]`, hence I would expect the pdf, log pdf and their gradients to be `nan` for values outside this range.

This is the case in the standard pdf (`.prob`) case, however the gradient of the log pdf (`.log_prob`) isn't `nan` for values outside this range. For example

    x = tf.Variable(-1.0)

    print(tfp.distributions.Beta(10, 1000).log_prob(x))

    with tf.GradientTape() as t:
        z = tfp.distributions.Beta(10, 1000).log_prob(x)

    dx = t.gradient(z, x)
    print(dx)

Shouldn't these gradients also be `nan`?

**Comment by brianwa84** [comment]
I'd expect values outside a distribution's support have log_prob(x)==-inf
and prob(x)==0. I wouldn't be surprised if the gradients were zero.

As a quick workaround, you could use validate_args=True, which should
verify that x is in the distribution's support.

**Comment by rwolst** [comment]
I agree, that would also be a fine convention. I wouldn't be surprised by either (although would personally lean toward `nan`).

**Comment by rwolst** [comment]
By the way, if it wasn't clear in the question the gradients you get running the code snippet aren't 0, they are some negative real numbers.

**Comment by axch** [comment]
Most of our distributions actually implement analytic extensions of their density functions outside the support.  Partly that's because it's the simplest, partly because we save a few `tf.where` ops that way, and partly because there are some distributions (e.g., Bernoulli) where people seem to want them.  But I agree that this can be surprising, and maybe we should revisit.

**Comment by rwolst** [comment]
Ok, now I am aware of it its perfectly fine. Was surprising at first as it was causing an optimisation error that only after investigation did I find out this was the cause.
