### ISSUE TITLE
Binomial distribution nan gradient for exact integer `total_count`.

### ISSUE THREAD

**Issue by rwolst** [tensorflow/probability#897]
I am trying to perform an optimisation where the `total_count` parameter for a `Binomial` distribution is a function of one of the variables I am trying to optimise.

For coding purposes (happy to go into more detail) I am often finding the probability from the distribution for values outside its support. In most case this happily evaluates to 0 along with the gradient.

However if my variable transformation to `total_count` happens to be an exact integer (its type is still `float32`), then my gradient now evaluates to `nan`.

I've managed to pull a minimum example out of my code:

    # The gradient in this case is nan.
    x = tf.constant([120.])
    # The gradient in this case is ok!
    # x = tf.constant([120.1])

    with tf.GradientTape() as t:
        t.watch(x)
    
        N_dist = tfp.distributions.Binomial(
            total_count = x,
            probs = 0.5
        )  
        
        # Set a value to evaluate the pmf at outside of the support.
        N_range = 125.0

        # Evaluate pmf.
        z = N_dist.prob(N_range)
    
    dx = t.gradient(z, [x])
    print(dx[0])

**Comment by rwolst** [comment]
I think this isn't a bug, I've done some investigating and the pmf in the Binomial case has a term relying on the gamma function:

https://github.com/tensorflow/probability/blob/v0.9.0/tensorflow_probability/python/distributions/binomial.py#L224

https://github.com/tensorflow/probability/blob/v0.9.0/tensorflow_probability/python/distributions/binomial.py#L336

This is `-inf` for all non-positive integers as I recall (I now remember it being a classic function for analytic continuation examples).

Obviously the term `1. + total_count - counts`, in the case that `counts` is greater than `total_count` with both being integers, is a non-positive integer. Hence the non-differentiability.

In the alternative case, the pmf is extended outside the support of the distribution and is then in fact differentiable.

P.S.

This is unfortunate as I was using the values outside the support in order to keep consistent sizes for my tensors allowing efficient tensor operations. I really don't care about what they evaluate to outside the support and in fact just want these gradients ignored.

**Comment by axch** [comment]
Can you just mask out the problematic values?  To get good gradients you might need to use the "[double-where trick](https://stackoverflow.com/questions/33712178/tensorflow-nan-bug/42497444#42497444)"

```
good_inputs_mask = tf.where(x < total_count, 1, 0)  # Up to shape and dtype
safe_x = tf.where(good_inputs_mask, x, 0)  # Pick any sentinel that will give a finite gradient
raw_probs = binom.prob(safe_x)
result = tf.where(good_inputs_mask, raw_probs, 0)
```

Post back if you'd like a walk-through of what's going on here -- thinking about how gradients work can be confusing.

**Comment by rwolst** [comment]
That works! The double-where trick is a nice idiom to be aware of, thanks.
