### ISSUE TITLE
Multinomial sampling slower than numpy

### ISSUE THREAD

**Issue by yoavram** [tensorflow/probability#898]
Since tfp's multinomial can take a multidimensional probability array and sample from it, I thought it would be faster then looping over the probability array first dimension and using numpy, but that is NOT THE CASE:
```
N = 100000
m = 20
n = 100

p = np.random.exponential(size=(n, m))
p /= p.sum(axis=1, keepdims=True)

%timeit np.array([np.random.multinomial(n, p_) for p_ in p]) // **1.88 ms** ± 378 µs per loop
dist = tfp.distributions.Multinomial(total_count=N, probs=p)
%timeit dist.sample() // **786 ms** ± 5.84 ms per loop
```

Am I missing something?

I'm using a MacBook Pro 2016, no GPU, numpy 1.18.1, tfp 0.9.0, tf 2.1.0.

**Comment by axch** [comment]
Which TFP version are you using?  We recently sped up the multinomial sampler substantially.  The tfp-nightly package should have the improvement, as well as 0.10.0rc0, but the 0.9 release does not.

You also seem to benchmarking TensorFlow in Eager mode, which has considerable overhead (the price for debuggability, given TF's internal architecture).

Something like this
```
@tf.function
def try_me():
  return dist.sample()

# Warm the compilation cache
try_me()

%timeit try_me()
```
should do much better.  When I tried that on my machine, I got 1.14 ms per loop.

**Comment by csuter** [comment]
OP says they have 0.9, so no multinomial update

NB -- I don't think it made the cut for 0.10, which had to be branched before the recent tensor seed updates, due to missing support in TF 2.2

**Comment by yoavram** [comment]
@axch thanks I’ll try that.
@csuter so which version should I try? Master branch? Which tf version would I need then?

**Comment by csuter** [comment]
We and the TF team produce nightly builds from the latest state of the
code. You can pip install tf-nightly and tfp-nightly to get the latest of
each. We test tfp-nightly against the TF nightly builds before releasing it
so they should generally work together without any major issues.

**Comment by yoavram** [comment]
I installed the nightly of tf and tfp and re-run the test, and indeed tfp is a bit **faster** then numpy, although not by much - roughly 1.5-fold faster for the use case I imagine.

For reference, this is the [test notebook file](https://github.com/yoavram/ipython-notebooks/blob/60a7f5530ea2f99c6a8a03e040ebf043ef9878d3/tfp_multinomial.ipynb).
