### ISSUE TITLE
Mention that tf-nightly is recommended dependency to install tfp from source

### ISSUE THREAD

**Issue by matthewfeickert** [tensorflow/probability#910]
# Description

At the moment (2020-05-01) the [instructions on installing from source](https://github.com/tensorflow/probability/blob/34703541f15160aaf5c003e6b718807374b57545/README.md#installing-from-source) don't mention what version of TensorFlow is required to build TensorFlow Probability. However, if I setup a clean virtual environment

```
$ python3 -m venv "${HOME}/.venvs/tfp-dev"
$ . "${HOME}/.venvs/tfp-dev/bin/activate"
(tfp-dev) $ python -m pip install --upgrade pip setuptools wheel
```

and then clone TFP and setup a `build.sh` script for myself

```
(tfp-dev) $ git clone https://github.com/tensorflow/probability.git
(tfp-dev) $ cd probability
(tfp-dev) $ cat build.sh
#!/usr/bin/env bash

bazel clean --expunge
bazel build --copt=-O3 --copt=-march=native :pip_pkg
PKGDIR=$(mktemp -d)
./bazel-bin/pip_pkg $PKGDIR
python -m pip install --upgrade $PKGDIR/*.whl
```
then if I install just `tensorflow`

```
(tfp-dev) $ python -m pip install tensorflow
```

the build (`(tfp-dev) $ bash build.sh`) will fail. However, if I install `tf-nightly` _instead_ (here I clean out the venv and start fresh)

```
(tfp-dev) $ python -m pip install --upgrade tf-nightly
(tfp-dev) $ bash build.sh
...
Build complete. Wheel files are in /tmp/tmp.VNEDwf88Vi
Processing /tmp/tmp.VNEDwf88Vi/tfp_nightly-0.11.0.dev20200501-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /home/feickert/.venvs/tfp-dev/lib/python3.7/site-packages (from tfp-nightly==0.11.0.dev20200501) (1.18.3)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /home/feickert/.venvs/tfp-dev/lib/python3.7/site-packages (from tfp-nightly==0.11.0.dev20200501) (1.14.0)
Requirement already satisfied, skipping upgrade: gast>=0.3.2 in /home/feickert/.venvs/tfp-dev/lib/python3.7/site-packages (from tfp-nightly==0.11.0.dev20200501) (0.3.3)
Collecting cloudpickle==1.3
  Using cached cloudpickle-1.3.0-py2.py3-none-any.whl (26 kB)
Installing collected packages: decorator, cloudpickle, tfp-nightly
Successfully installed cloudpickle-1.3.0 decorator-4.4.2 tfp-nightly-0.11.0.dev20200501
```

Given this, it would be helpful if it was recommended that `tf-nightly` was installed in the docs.

# Proposed Change

In the `README` note that while not a hard requirement it is highly recommended that `tf-nightly` be installed before trying to build `TensorFlow Probability` from source.

**Comment by matthewfeickert** [comment]
Btw, if the TFP agrees with this I'm happy to open a PR for it.

**Comment by brianwa84** [comment]
If installing/building TFP from source, I guess we might also recommend
doing the same for TF, technically speaking. That's what we do.

That said, tf-nightly is almost always good enough and we are always
testing against tf-nightly internally (though occasionally it breaks us &
we blacklist the current nightly for a ~day).

**Comment by matthewfeickert** [comment]
> If installing/building TFP from source, I guess we might also recommend doing the same for TF, technically speaking.

That seems totally reasonable. I guess I should say that I'd just advocate for more explicit instructions on what is the recommended way to get dependencies to test TFP. @brianwa84, if you're happy with suggesting to install TF from source I can open a PR for this.

**Comment by brianwa84** [comment]
I think it's a pretty tall order to ask a contributor to build TF from source. @csuter thoughts?

Your proposal to use tf-nightly sounds pretty reasonable to me. Feel free to send a PR, maybe wait for Chris to weight in.

**Comment by csuter** [comment]
As Brian mentions, our presubmits for pushing code out to github are gated on passing with the latest tf-nightly, so the HEAD state of the repo should almost always work in tf-nightly (if not today's, yesterday's). Compiling TF should not be necessary. We *don't* test the HEAD state of the repo against the most recent stable `tensorflow` release, and it will typically diverge between releases as we come to rely on new TF API elements.

I think clarifying this in the public source build instructions would be a nice improvement.
