### ISSUE TITLE
QuantizedDistribution  does not recognize inherited log_cdf

### ISSUE THREAD

**Issue by krzysztofrusek** [tensorflow/probability#915]
log_prob in `tfdQuantizedDistribution` of `tfd.Exponential`  does not work and throws exception:
`log_prob` not implemented unless the base distribution implements `log_cdf`, however `tfd.Exponential` implements log_cdf

Here is minimal code reproducing this issue

```python
import tensorflow_probability as tfp
qe = tfp.distributions.QuantizedDistribution(
    tfp.distributions.Exponential(0.01)
)
s=qe.sample(10)
qe.log_prob(s)
```
A workaround is to implement `_log_prob()`, 

[Colab](https://colab.research.google.com/drive/1FzsfOvCpOHibI89mtGYo7E9Gsllfo8zW?usp=sharing)

**Comment by srvasude** [comment]
Closing as this should be fixed now.
