### ISSUE TITLE
TF/TFP-nightly pip related problem

### ISSUE THREAD

**Issue by adamhaber** [tensorflow/probability#936]
I'm trying to finish a small project I've been working on - a small pythonic wrapper around the stan2tfp compiler - and ran into a TF/TFP-nightly pip related problem. This might be a "pip only" issue, and not a TF/TFP issue - I'm not sure; I just thought someone here might've encountered this already, or similar issues.

[Here's](https://github.com/adamhaber/stan2tfp) the package; it has both tf-nightly and tfp-nightly as dependencies (in [setup.py](https://github.com/adamhaber/stan2tfp/blob/963c7435e54cecdeac4cf335e1616665bd140b46/setup.py#L11)). I set up [CI](https://github.com/adamhaber/stan2tfp/blob/master/.github/workflows/pythonpackage.yml) using GitHub Action, in which I use `pip install -e .` to install tf-nightly and tfp-nightly, and everything seems OK. 

I then uploaded it to TestPyPi, created a new local conda environment, and tried to install it using `pip install --index-url https://test.pypi.org/simple/ stan2tfp`; this gives:
```
Looking in indexes: https://test.pypi.org/simple/
Collecting stan2tfp
  Downloading https://test-files.pythonhosted.org/packages/ca/14/8b4cf32fc231fb7abb40d1139515999be0b3061609a51cbd9794d95d567c/stan2tfp-0.1.0-py3-none-any.whl (5.7 kB)
Requirement already satisfied: pip in /Users/adamhaber/miniconda3/envs/tmp_stan2tfp/lib/python3.7/site-packages (from stan2tfp) (20.1)
Requirement already satisfied: numpy in /Users/adamhaber/miniconda3/envs/tmp_stan2tfp/lib/python3.7/site-packages (from stan2tfp) (1.18.4)
Collecting tfp-nightly
  Downloading https://test-files.pythonhosted.org/packages/71/29/00f4aed8ce6848922fab7ae7b79440175a5d2a205885bda95c3012b86f14/tfp-nightly-0.0.1.dev20180309.tar.gz (60 kB)
     |████████████████████████████████| 60 kB 363 kB/s 
ERROR: Could not find a version that satisfies the requirement tf-nightly (from stan2tfp) (from versions: none)
ERROR: No matching distribution found for tf-nightly (from stan2tfp)
```
For some reason pip is downloading `tfp-nightly-0.0.1.dev20180309.`; indeed, when I do:
```
pip install tf-nightly tfp-nightly
pip install --index-url https://test.pypi.org/simple/ stan2tfp
```
everything works. I tried changing the requirements in setup.py to `tf-nightly>=2.3.0,tfp-nightly>=0.11.0` but that didn't help, either. Is there a better way to make pip install the latest nightly versions? 

Any relevant feedback would be much appreciated!

**Comment by csuter** [comment]
I think it's trying to download tfp from test pypi and the last time we
uploaded to it was in 2018 when we first created the pip pkg. When you
switch to the main package repository you should get the latest version.
There may be some other way to tell it to get the dependencies from the
main repo. Not sure.

**Comment by adamhaber** [comment]
Switching to the main repo indeed solved the problem, thanks!
