### ISSUE TITLE
Sampling tfd.Uniform with integer dtype fails

### ISSUE THREAD

**Issue by odel4y** [tensorflow/probability#939]
Hi all,
I am trying to sample a `tfd.Uniform` distribution with low and high defined as integers but it fails. The following code
```python3
from tensorflow_probability import distributions as tfd
import numpy as np

highs = np.random.randint(1, 4, size=(10, 4))
uniform_int = tfd.Uniform(0, highs)
print(uniform_int.sample())
```
produces an error:
`ValueError: Must specify maxval for integer dtype tf.int64`

It will sample correctly if I convert `highs` to float but then the result is of course a float. Is that a bug or do you not intend to support uniform integer distributions? Thank you!

**Comment by csuter** [comment]
Hi, while it might be possible to get Uniform to output integers in `.sample`, I think it's counter to the definition of this distribution, which assumes a continuous support. For example, `log_prob` will be wrong -- it'll still be a density value, not a probability mass localized to the integer points.

For a single range of ints you could use `tfd.FiniteDiscrete(outcomes=np.range(0, high), logits=np.zeros(high))` but for a batch multiple ranges, as you wrote, you effectively have supports with different length ranges, which starts to get tricky. No easy solution comes to mind for that...

**Comment by csuter** [comment]
Of course if you just want integer samples and don't care about a "proper" `Distribution`, you can just do what you did, with float ranges, and then use `tf.floor` on the samples.

**Comment by odel4y** [comment]
Thank you for the clarification!
