### ISSUE TITLE
Feature request: JointDistributionSequential name resolution for generated components

### ISSUE THREAD

**Issue by wilecoyote2015** [tensorflow/probability#942]
Hello,

I am working on the problem described here: 
https://stackoverflow.com/questions/61598240/continuous-state-markov-chain-with-time-dependent-kernel-with-tenstorflow-probab

What I try to implement in a nutshell:
My model's joint PDF corresponds to a chain of transition kernel functions `g_i`, conditioned on their predecessor `g_{i-1}`.
`g_i` is a distribution generated by a function if no datapoint exists at time `t_i`, and else it is a Deterministic representing the measurement.
I assume this would be a use case for the JointDistributionSequential, where a list of `g_i`s is generated by a loop, according to the number of time steps, and used as components.

However, with the current name resolution, one is forced to use the argument names in distribution-making functions in order to refer to the previous distributions in the sequence. 
Hence, at least as far as I understand, it is not possible to generate the list of distribution-making functions by a function.

Maybe, it could be useful if the names of the distribution-making functions' arguments would not be considered at all, so that the resolution of referred components would work with argument order (and optionally names in case of keyword arguments)?

**Comment by ColCarroll** [comment]
Sorry for the late reply -- I am not sure I understand the suggestion completely, but it might be simpler to use `JointDistributionCoroutine` or `JointDistributionNamed` instead. Here is an implementation of a model that sounds like what you're describing using `JointDistributionCoroutine` let me know if this helps!

```python
root = tfd.JointDistributionCoroutine.Root

@tfd.JointDistributionCoroutine
def model():
  params = {}
  for j in range(10):
    name = f"param_{j}"
    if j % 2 == 0:
      params[name] = yield root(tfd.Normal(j, 1.))
    else:
      params[name] = yield tfd.Normal(params[f"param_{j - 1}"], 1.)

model.sample()
```
which gives something like

```pythontb
(<tf.Tensor: shape=(), dtype=float32, numpy=-0.46617696>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4320046>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.7000911>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.115792>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.1658926>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.6507006>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.3191533>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.746093>,
 <tf.Tensor: shape=(), dtype=float32, numpy=8.11293>,
 <tf.Tensor: shape=(), dtype=float32, numpy=8.696498>)
```
