### ISSUE TITLE
Numerical stability of tfb.Sigmoid

### ISSUE THREAD

**Issue by adamhaber** [tensorflow/probability#950]
Following a recent [comment](https://github.com/stan-dev/stanc3/issues/372#issuecomment-633252558) on the stanc3 repo, I'm trying to understand [this](https://github.com/tensorflow/probability/blob/c833ee5cd9f60f3257366b25447b9e50210b0590/tensorflow_probability/python/bijectors/sigmoid.py#L72-L76) part from tfb.sigmoid. Why is `high * g(X) + low * g(-X)`more numerically stable? For comparison, Stan implements the bijector as `low + (high - low) * g(X)` (see Bob's comment at the first link).

**Comment by axch** [comment]
We were having problems where `low + (high - low) * g(X)` would evaluate to slightly greater than `high` for large `X`, triggering asserts elsewhere.  The adopted implementation doesn't do that.
