### ISSUE TITLE
Minor error in fit_sparse and _fit_sparse_exact_hessian with maximum_iterations default value

### ISSUE THREAD

**Issue by arkhanna** [tensorflow/probability#961]
I think there is a minor error in `fit_sparse()` and `_fit_sparse_exact_hessian()`. Default value for `maximum_iterations` is `None`, but this throws:

```
_FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.
...
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
```

This is fixed by changing default value for `maximum_iterations` to `1`, which is the intended default behavior.

**Comment by ursk** [comment]
Hi, thanks for reporting this. I just submitted a patch which should be included in tonight's `tfp-nightly` package.
