### ISSUE TITLE
count_integers may fail when minlength is not given

### ISSUE THREAD

**Issue by javidcf** [tensorflow/probability#962]
According to the documentation of [`tfp.stats.count_integers`](https://www.tensorflow.org/probability/api_docs/python/tfp/stats/count_integers), when `minlength` or `maxlength` are not given, they are assumed to be `tf.reduce_max(arr) + 1`. However, in some cases that is not the case, and the function fails:

```python
import tensorflow as tf
import tensorflow_probability as tfp

x = tf.constant([[1, 3, 0, 0, 3],
                 [1, 3, 1, 0, 2],
                 [1, 3, 1, 2, 2]])

# This works as expected
tf.print(tfp.stats.count_integers(x, axis=1))
# [[2 1 0]
#  [1 2 2]
#  [0 1 2]
#  [2 1 1]]

# This fails unexpectedly
tf.print(tfp.stats.count_integers(x, axis=0))
# ValueError: Incompatible shape for value ((4,)), expected ((2,))

# When a minlength equivalent to what should be the default value is given it works
tf.print(tfp.stats.count_integers(x, axis=0, minlength=tf.math.reduce_max(x) + 1))
# [[0 0 1 2 0]
#  [3 0 2 0 0]
#  [0 0 0 1 2]
#  [0 3 0 0 1]]
```

Environment:
Python 3.7.6, TensorFlow 2.2.0, TensorFlow Probability 0.10.0, Win 10 x64, no CUDA/GPU.

**Comment by ursk** [comment]
Hi Javier, thanks for bringing this to our attention. We have a fix that we'll roll out with our next nightly release.
