### ISSUE TITLE
TypeError Python 3.8.1

### ISSUE THREAD

**Issue by MattyJP200** [tensorflow/probability#970]
Hi everyone, I am experiencing an issue when i run my code, in which this error comes up: TypeError: __init__() got an unexpected keyword argument 'parent'. Does any one have any suggestions?
This is the full program:

# Tell Python to use the tkinter library
import tkinter as tk
import arcade
from tkinter import *

# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "The Tale of the Rogue Knight"

# Constants used to scale our sprites from their original size
CHARACTER_SCALING = 1
TILE_SCALING = 0.5
COIN_SCALING = 0.5

# Movement speed of player, in pixels per frame
PLAYER_MOVEMENT_SPEED = 5
GRAVITY = 1
PLAYER_JUMP_SPEED = 20

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 200
TOP_VIEWPORT_MARGIN = 85

# Create a Python class to serve as a blueprint
class SampleApp(tk.Tk):

    def __init__(self, *args, **kwargs):
        tk.Tk.__init__(self, *args, **kwargs)

        # The container is where we'll stack a bunch of frames
        # on top of each other, then the one we want visible
        # will be raised above the others
        container = tk.Frame(self)
        container.pack(side="top", fill="both", expand=True)
        container.grid_rowconfigure(0, weight=1)
        container.grid_columnconfigure(0, weight=1)

        # Set the window size and the X and Y offset
        self.geometry("1200x800")

        # Set the title that will dispaly in the top caption bar of the window
        self.title("The Tale of The Rogue Knight")

        # Display a specific icon to display on the window
        self.iconbitmap('racecar.png')
       
        self.frames = {}
        for F in (StartPage, MyGame, Page2):
            page_name = F.__name__
            frame = F(parent=container, controller=self)
            self.frames[page_name] = frame

            # Put all of the pages in the same loction;
            # The one on the top of the stacking order
            # will be the one that is visible

            frame.grid(row=0, column=0, sticky="nsew")

        self.show_frame("StartPage")

    def show_frame(self, page_name):
        '''Show a frame for the given page name'''
        frame = self.frames[page_name]
        frame.tkraise()

# Create the StartPage class
class StartPage(tk.Frame):
   
    def __init__(self, parents, controller):
        tk.Frame.__init__(self, parents)

        # Change background colour to black
        self.configure(background="Black")

        # Upload a background
        Main_pic = PhotoImage (file="background_01.png")
        img=tk.Label (self, image=Main_pic)
        img.image = Main_pic
        img.place (x=0,y=0)

        # Create a button labelled button1, the command=lambda is what to do
        button1 = tk.Button(self, text="Single player",
                            command=lambda: controller.show_frame("MyGame"))
       
        button2 = tk.Button(self, text="How to play",
                            command=lambda: controller.show_frame("Page2"))

        # Create an exit button to quit the program
        exit_button = tk.Button(self, text="Quit",
                                command=lambda: controller.destroy())

        # Place the exit button at 100 pixels across from left and 600 pixels from the top
        # Place button1 at 100 pixels across from left and 200 pixels from the top
        # Place button2 at 100 pixels across fron the left and 400 pixels from the top
        # Also adjust the size of each button
        button1.place(x=100, y=200, height=100, width=150)
        button2.place(x=100, y=400, height=100, width=150)
        exit_button.place(x=100, y=600, height=100, width=150)

# Create the Page 1 class that runs when from a button on the StartPage class

class MyGame(arcade.Window):

    def __init__(self):

        # Call the parent class and set up the window
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)

        # These are 'lists' that keep track of our sprites. Each sprite should
        # go into a list.
        self.coin_list = None
        self.wall_list = None
        self.player_list = None

        # Separate variable that holds the player sprite
        self.player_sprite = None

        #our Physics Engine
        self.physics_engine = None
        
        #USED TO KEEP TRACK OF OUR SCROLING
        self.view_bottom = 0
        self.view_left = 0

        #keep track of the score
        self.score = 0

        #load sounds
        self.collect_coin_sound = arcade.load_sound(":resources:sounds/coin3.wav")
        self.jump_sound = arcade.load_sound(":resources:sounds/jump3.wav")
        
        arcade.set_background_color(arcade.csscolor.CORNFLOWER_BLUE)

    def setup(self):
        """ Set up the game here. Call this function to restart the game. """
        # Create the Sprite lists
        self.player_list = arcade.SpriteList()
        self.wall_list = arcade.SpriteList(use_spatial_hash=True)
        self.coin_list = arcade.SpriteList(use_spatial_hash=True)

        #keep track of the score
        self.score = 0

       # Set up the player, specifically placing it at these coordinates.
        image_source = ":resources:images/animated_characters/robot/robot_idle.png"
        self.player_sprite = arcade.Sprite(image_source, CHARACTER_SCALING)
        self.player_sprite.center_x = 64
        self.player_sprite.center_y = 128
        self.player_list.append(self.player_sprite)

        #create the ground
        #This shows using a loop to place multiple sprites horizontally
        for x in range(0, 4800, 64):
            wall = arcade.Sprite(":resources:images/tiles/grassMid.png", TILE_SCALING)
            wall.center_x = x
            wall.center_y = 32
            self.wall_list.append(wall)

        #put some crates on the ground
        #this shows using a coordinate list to place sprites
        coordinate_list = [[512,96],
                           [256,96],
                           [768,96],
                           [320,260],
                           [400,360],
                           [464,360],
                           [528,360],
                           [592,442],
                           [656,442]]

        for coordinate in coordinate_list:
            # Add a crate on the ground
            wall = arcade.Sprite(":resources:images/tiles/boxCrate_double.png", TILE_SCALING)
            wall.position = coordinate
            self.wall_list.append(wall)

            #use a loop to place some coins for our character to pick up
            for x in range (128, 1250, 256):
                coin = arcade.Sprite(":resources:images/items/coinGold.png", COIN_SCALING)
                coin.center_x = x
                coin.center_y = 96
                self.coin_list.append(coin)

        # Create the 'physics engine'
        self.physics_engine = arcade.PhysicsEnginePlatformer(self.player_sprite,
                                                             self.wall_list,
                                                             GRAVITY)

    def on_draw(self):
        """ Render the screen. """

        # Clear the screen to the background color
        arcade.start_render()

        # Draw our sprites
        self.wall_list.draw()
        self.coin_list.draw()
        self.player_list.draw()

        #draw our score on the screen, scrolling it with the viewport
        score_text = f"score: {self.score}"
        arcade.draw_text(score_text, 900 + self.view_left, 620 + self.view_bottom,
                         arcade.csscolor.WHITE, 18)

    def on_key_press(self, key, modifiers):
        """Called whenever a key is pressed. """
        #What happens to the character when a key is pressed
        if key == arcade.key.UP or key == arcade.key.W or key == arcade.key.SPACE or key == arcade.key.BACKSPACE:
            if self.physics_engine.can_jump():
                self.player_sprite.change_y = PLAYER_JUMP_SPEED
                arcade.play_sound(self.jump_sound)
        elif key == arcade.key.LEFT or key == arcade.key.A:
            self.player_sprite.change_x = -PLAYER_MOVEMENT_SPEED
        elif key == arcade.key.RIGHT or key == arcade.key.D:
            self.player_sprite.change_x = PLAYER_MOVEMENT_SPEED

    def on_key_release(self, key, modifiers):
        """Called when the user releases a key. """
        #What happens when a key is released
        if key == arcade.key.LEFT or key == arcade.key.A:
            self.player_sprite.change_x = 0
        elif key == arcade.key.RIGHT or key == arcade.key.D:
            self.player_sprite.change_x = 0

    def on_update(self, delta_time):
        """ Movement and game logic """

        # Move the player with the physics engine
        self.physics_engine.update()

        #see if we hit any coins
        coin_hit_list = arcade.check_for_collision_with_list(self.player_sprite,
                                                             self.coin_list)

        #loop through each coin we hit (if any) and remove it
        for coin in coin_hit_list:
            #remove the coin
            coin.remove_from_sprite_lists()
            #play a sound
            arcade.play_sound(self.collect_coin_sound)
            #add one to the score
            self.score += 1

        # --- Manage Scrolling ---

        # Track if we need to change the viewport

        changed = False

        # Scroll left
        left_boundary = self.view_left + LEFT_VIEWPORT_MARGIN
        if self.player_sprite.left < left_boundary:
            self.view_left -= left_boundary - self.player_sprite.left
            changed = True

        # Scroll right
        right_boundary = self.view_left + SCREEN_WIDTH - RIGHT_VIEWPORT_MARGIN
        if self.player_sprite.right > right_boundary:
            self.view_left += self.player_sprite.right - right_boundary
            changed = True

        # Scroll up
        top_boundary = self.view_bottom + SCREEN_HEIGHT - TOP_VIEWPORT_MARGIN
        if self.player_sprite.top > top_boundary:
            self.view_bottom += self.player_sprite.top - top_boundary
            changed = True

        # Scroll down
        bottom_boundary = self.view_bottom + BOTTOM_VIEWPORT_MARGIN
        if self.player_sprite.bottom < bottom_boundary:
            self.view_bottom -= bottom_boundary - self.player_sprite.bottom
            changed = True

        if changed:
            # Only scroll to integers. Otherwise we end up with pixels that
            # don't line up on the screen
            self.view_bottom = int(self.view_bottom)
            self.view_left = int(self.view_left)

            # Do the scrolling
            arcade.set_viewport(self.view_left,
                                SCREEN_WIDTH + self.view_left,
                                self.view_bottom,
                                SCREEN_HEIGHT + self.view_bottom)

# Create Pg 2
class Page2(tk.Frame):

    def __init__(self, parents2, controller):
        tk.Frame.__init__(self, parents2)

        # Change background colour to black
        self.configure(background="Black")

        self.controller = controller

        # Change the background colour of the frame
        self.configure(background="Light Blue")

        # Add a heading for the frame and set its foreground
        # and background colour scheme
        label = tk.Label(self, text="Controls",
                         bg = "Light Blue",
                         fg = "Black")  
        label.pack(side="top", fill="x", pady=10)

        # Add the main body text for the page
        explanation = """Basic movement keys"""
        main_text = tk.Label(self,
                             text = explanation,
                             fg = "Black",
                             bg = "Light Blue",
                             font = "Trebuchet 30 bold").place(x=575, y=75)
        # Basic Movement description
        explanation = """
Up arrow/space bar is to jump
Left arrow is to move to the left
Right arrow is to move to the right"""
        main_text = tk.Label(self,
                             text = explanation,
                             fg = "Black",
                             bg = "Light Blue",
                             font = "Trebuchet 18 italic").place(x=585, y=115)
       
                # Action keys
        explanation = """Action keys"""
        main_text = tk.Label(self,
                             text = explanation,
                             fg = "Black",
                             bg = "Light Blue",
                             font = "Trebuchet 30 bold").place(x=575, y=75)
        # Action keys description
        explanation = """
Tab is to
"""
        main_text = tk.Label(self,
                             text = explanation,
                             fg = "Black",
                             bg = "Light Blue",
                             font = "Trebuchet 18 italic").place(x=585, y=115)

        button = tk.Button(self, text="Back to main",
                           command=lambda: controller.show_frame("StartPage"))
        button.pack()

if __name__ == "__main__":
    app = SampleApp()
    app.mainloop()

**Comment by MattyJP200** [comment]
The full issue when attempting to run is : Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Programs\Python\Python38-32\SDD\Arcade academy code\Main menu.py", line 351, in <module>
    app = SampleApp()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python38-32\SDD\Arcade academy code\Main menu.py", line 54, in __init__
    frame = F(parent=container, controller=self)
TypeError: __init__() got an unexpected keyword argument 'parent'

**Comment by csuter** [comment]
Hi, I think you are posting on the wrong repo -- this does not seem related to TensorFlow Probability.

That said, I believe you have a typo -- `parent` should be `parents`. Good luck~
