### ISSUE TITLE
Mixture shapes do not fit

### ISSUE THREAD

**Issue by dirmeier** [tensorflow/probability#989]
Hi, I have a problem getting the following model to work:

```python
model = tfd.JointDistributionNamed(dict(
    m1=tfd.Normal(loc=0.0, scale=1.0),    
    m2=tfd.Normal(loc=0.0, scale=1.0),    
    x= lambda m1, m2: tfd.Mixture(
        cat=tfd.Categorical(probs=tf.constant([0.5, 0.5])),
        components=[tfd.Normal(loc=m1, scale=1.0),
                    tfd.Normal(loc=m2, scale=1.0)]
    )
))

samples = model.sample(10)
```

since it throws:

```python
ValueError: components[0] batch shape must be compatible with cat shape and other component batch shapes
```

If i dont use constant categorical probs, but a Dirichlet prior it works though:

```python
model = tfd.JointDistributionNamed(dict(
    m1=tfd.Normal(loc=0.0, scale=1.0),    
    m2=tfd.Normal(loc=0.0, scale=1.0),    
    d=tfd.Dirichlet([1.0, 1.0]),
    x= lambda m1, m2, d: tfd.Mixture(
        cat=tfd.Categorical(probs=d),
        components=[tfd.Normal(loc=m1, scale=1.0),
                    tfd.Normal(loc=m2, scale=1.0)]
    )
))
```

Am I doing anything wrong here or is this a bug? Help would be appreciated. A colab is [here](https://colab.research.google.com/drive/1jBrd5o8rie_p4pchy5Q63gwndLlqfzYQ?usp=sharing).

Cheers,
S

**Comment by brianwa84** [comment]
Try JointDistributionNamedAutoBatched?

The batch shape of the categorical must match the batch shape of the
components, but here cat has batch shape [] and the components have batch
shape [10].

You could use tf.ones_like(tf.stack([m1, m1], axis=-1)) * .5 as the probs
param.

**Comment by dirmeier** [comment]
Hey, thank you for the help! That did it.
