### ISSUE TITLE
Cannot import name 'CloudPickler' from 'cloudpickle.cloudpickle' in tensorflow_probability\python\layers\distribution_layer.py

### ISSUE THREAD

**Issue by stevenmailca** [tensorflow/probability#992]
Hi, I got the error message from Julia Shell "The Python package tensorflow_probability could not be found by pyimport." due to "<class 'ImportError'>
ImportError("cannot import name 'CloudPickler' from 'cloudpickle.cloudpickle' (D:\\Users\\WinUser\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\cloudpickle\\cloudpickle.py)")" 
File "D:\Users\WinUser\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow_probability\python\layers\distribution_layer.py", line 28, in <module>
    from cloudpickle.cloudpickle import CloudPickler
----------------------
I checked the local folders and confirmed cloudpickle.py is right with the following path
D:\Users\WinUser\AppData\Local\Programs\Python\Python38\Lib\site-packages\cloudpickle\cloudpickle.py ,
but why still import error caused by "from cloudpickle.cloudpickle import CloudPickler" in file distribution_layer.py  which locates D:\Users\WinUser\AppData\Local\Programs\Python\Python38\Lib\site-packages\tensorflow_probability\python\layers\distribution_layer.py ?

**Comment by matthewfeickert** [comment]
This is the same issue as Issue #991. I'm not part of TFP, but it might be more helpful if you closed this and went to discuss on the original issue.

**Comment by stevenmailca** [comment]
@matthewfeickert Thank you very much for your kind info. I'll just close this issue and turn to the original issue #991.
