### ISSUE TITLE
Add the (implicit) reparameterization gradient for inverse Gaussian distribution 

### ISSUE THREAD

**Issue by yorkerlin** [tensorflow/probability#996]
The `autograd` implementation including some test cases is available at https://github.com/yorkerlin/iBayesLRule/blob/master/inverse_gauss/inv_gauss_sampler.py

The writeup can be found at
Appendix H.1 (page 27) of https://arxiv.org/pdf/2002.10060v8.pdf (to appear at ICML 2020)

**Comment by srvasude** [comment]
This is fixed by https://github.com/tensorflow/probability/commit/a91efeb17a6f6fdae97d3465878f5fc7fba12d30
